import type { SkillPack } from '../schema';

/** neutral instruction for correction items (the given sentence may already be correct) */
const FIX_INSTR = 'אם יש טעות — גע במילה או ברווח ובחר תיקון. אם המשפט תקין, בחר "אין צורך בתיקון".';

/**
 * S01 BE_PROGRESSIVE — am / is / are + -ing.
 * Item S01-01 belongs to the scripted first segment: keep it unchanged.
 */
export const S01: SkillPack = {
  skill: 'S01',
  lessons: [
    {
      unit: 'S01',
      title: 'מה קורה עכשיו: `am / is / are + ing`',
      short:
        'פעולה שקורה עכשיו, או מצב זמני סביב עכשיו: `am / is / are` + פועל עם ing. בעברית אין מילה שמקבילה ל-`am`, ולכן קל להשמיט אותה — `I am still working`, ולא `I still working`.',
      chain: ['am / is / are', 'V-ing'],
      examples: [
        { en: 'She is talking to the supplier right now.', he: 'היא מדברת עכשיו עם הספק.' },
        { en: "We aren't using the old forms anymore.", he: 'אנחנו כבר לא משתמשים בטפסים הישנים.' },
        { en: 'Is anyone sitting here?', he: 'מישהו יושב כאן?' },
      ],
      contrast: {
        a: { en: 'I still work there.', he: 'אני עדיין עובד שם (זה עדיין מקום העבודה שלי).' },
        b: { en: "I'm still working on it.", he: 'אני עדיין עובד על זה (באמצע, עכשיו).' },
        note: 'שני המשפטים תקינים ואומרים דברים שונים: `I still work` — עובדה קבועה או הרגל; `I am still working on it` — פעולה שבאמצע, עכשיו. `I still working`, בלי `am`, אינו תקין בשום משמעות.',
      },
      deep:
        '• `am / is / are` לפי הנושא: `I am`; `he / she / it is`; `you / we / they are`. גם שם עצם ברבים מקבל `are`: `My colleagues are…`.\n' +
        "• שלילה: `I'm not`, `isn't`, `aren't` + פועל עם ing. שאלה: `am / is / are` עובר לפני הנושא — `Is anyone using this room?` — בלי `do`.\n" +
        "• מתי: מה שקורה עכשיו (`She is talking to the supplier`), וגם מצב זמני סביב עכשיו — השבוע, בתקופה הזאת (`I'm staying at a hotel this week`).\n" +
        '• הרגל או עובדה קבועה — בהווה פשוט, בלי `am`: `I still work there`, `I usually drive to work`.\n' +
        '• פעלי מצב — `know`, `need`, `want`, `belong`, `own` — בדרך כלל בלי ing, גם כשמדובר בעכשיו: `I know`, `This desk belongs to Maya`. `I am knowing` אינו תקין.\n' +
        '• זו גם החוליה הראשונה של `have been working`: אותו פועל עם ing, רק שלפניו בא `have been` במקום `am`.',
      pitfalls: [
        '`I still working…` — חסר `am`.',
        '`The printers is…` / `She are…` — `am / is / are` לפי הנושא.',
        '`Do you still using…?` — לפני ing השאלה נפתחת ב-`am / is / are`, לא ב-`do`.',
        '`I am knowing…` — `know` הוא פועל מצב: `I know`.',
      ],
    },
  ],
  examples: {
    S01: [
      { en: "The printer on the second floor isn't working again.", he: 'המדפסת בקומה השנייה שוב לא עובדת.' },
      {
        en: "They're painting the stairs this week, so we're using the back door.",
        he: 'השבוע צובעים את חדר המדרגות, אז אנחנו נכנסים מהדלת האחורית.',
      },
      { en: 'Are you waiting for someone?', he: 'אתה מחכה למישהו?' },
      {
        en: 'I need a few more minutes — I am still checking the numbers.',
        he: 'אני צריך עוד כמה דקות — אני עדיין בודק את המספרים.',
        note: '`need` הוא פועל מצב, ולכן בלי ing; `checking` — פעולה שקורה עכשיו.',
      },
    ],
  },
  items: [
    {
      id: 'S01-01',
      v: 2,
      skill: 'S01',
      unit: 'S01',
      sub: 'affirmative',
      type: 'correct',
      role: 'practice',
      stage: 1,
      ctx: 'work.report',
      fam: 'S01.still-working-report',
      goal: 'לומר שאתה באמצע העבודה על הדוח ממש עכשיו',
      instr: 'בדוק את המשפט. אם יש טעות — גע במילה או ברווח ובחר תיקון; אם הוא תקין, בחר "אין צורך בתיקון".',
      sitHe: 'עמית שואל אם סיימת את הדוח. עוד לא — אתה עובד עליו ממש עכשיו.',
      scaffold: ['am / is / are', 'V-ing'],
      hint: 'חסרה מילה אחת לפני `still`.',
      explain:
        'פעולה שקורה עכשיו נבנית מ-`am / is / are` + פועל עם ing. `still` נכנס אחרי `am`: `I am still working`.',
      deep: 'בעברית "אני עדיין עובד" — בלי מילה נוספת. באנגלית המבנה המתמשך צריך שני חלקים: `am` וגם `working`. `I still work on the report` הוא משפט תקין, אבל הוא מתאר הרגל או תפקיד קבוע — לא את מה שקורה עכשיו.',
      source: [
        { id: 's1', t: 'I' },
        { id: 's2', t: 'still' },
        { id: 's3', t: 'working' },
        { id: 's4', t: 'on the report' },
      ],
      tokens: [
        { id: 't1', t: 'am' },
        { id: 't2', t: 'is', why: 'עם `I` משתמשים ב-`am`, לא ב-`is`.', err: 'be_agreement' },
        {
          id: 't3',
          t: 'have',
          why: '`have` לבד לפני `working` אינו מבנה תקין. למה שקורה עכשיו: `I am still working`.',
          err: 'have_without_been',
        },
        {
          id: 't4',
          t: 'work',
          why: '`work` בלי ing מתאר הרגל או תפקיד קבוע, לא פעולה שקורה עכשיו.',
          err: 'simple_for_now',
          as: 'meaning_mismatch',
        },
      ],
      accept: [
        { a: 'I am still working on the report', o: 'correct_target' },
        {
          a: 'I still am working on the report',
          o: 'valid_alternative',
          note: 'תקין, עם הדגשה. הסדר הרגיל: `I am still working`.',
        },
        {
          a: 'I am working on the report',
          o: 'valid_alternative',
          note: 'נכון. `still` מוסיף את ה"עדיין": `I am still working on the report`.',
        },
      ],
      wrong: [
        {
          a: 'I still working on the report',
          as: 'form_error',
          err: 'missing_be',
          fb: 'חסר פועל העזר `am`: לפני פועל עם ing צריך `am / is / are`. כאן: `I am still working on the report`.',
        },
        {
          a: 'I still work on the report',
          as: 'meaning_mismatch',
          err: 'simple_for_now',
          fb: '`I still work on the report` הוא משפט תקין, אבל הוא מתאר הרגל או תפקיד קבוע — לא פעולה שקורה עכשיו. לעכשיו: `I am still working on the report`.',
        },
        {
          a: 'I still have work on the report',
          as: 'meaning_mismatch',
          err: 'have_work',
          fb: 'המשפט תקין, אבל הוא אומר משהו אחר: שנשארה לך עוד עבודה על הדוח — לא שאתה עובד עליו עכשיו. במשפט המקורי חסר רק `am`: `I am still working on the report`.',
        },
        {
          a: 'I have work on the report',
          as: 'meaning_mismatch',
          err: 'have_work',
          fb: 'המשפט אומר משהו אחר: שיש לך עבודה על הדוח — לא שאתה עובד עליו עכשיו. במשפט המקורי חסר רק `am`: `I am still working on the report`.',
        },
      ],
      rules: [
        {
          has: ['am', 'work'],
          lacks: ['working'],
          as: 'form_error',
          err: 'be_base',
          fb: 'אחרי `am` בא פועל עם ing: `am working`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S01-02',
      v: 1,
      skill: 'S01',
      unit: 'S01',
      sub: 'affirmative',
      type: 'assemble',
      role: 'practice',
      stage: 1,
      ctx: 'work.project',
      fam: 'S01.developers-testing',
      goal: 'לומר מה המפתחים עושים ברגע זה',
      instr: 'בנה את המשפט באנגלית. לא חייבים להשתמש בכל המילים.',
      sitHe: 'שואלים אותך בפגישה איפה המפתחים. הם בחדר השני, באמצע בדיקה של הגרסה החדשה.',
      promptHe: 'המפתחים בודקים את הגרסה החדשה.',
      scaffold: ['am / is / are', 'V-ing'],
      hint: 'הנושא ברבים. איזו צורה של `am / is / are` מתאימה לו?',
      explain: 'פעולה שקורה עכשיו: `are` + פועל עם ing. `the developers` ברבים, ולכן `are`, לא `is`.',
      deep: 'הצורה נקבעת לפי הנושא: `I am`, `he / she / it is`, `we / you / they are`. גם שם עצם ברבים (`the developers`, `my colleagues`) מקבל `are`. `The developers test the new version` הוא משפט תקין, אבל הוא מתאר את התפקיד הקבוע שלהם — לא את מה שקורה עכשיו.',
      tokens: [
        { id: 't1', t: 'the developers' },
        { id: 't2', t: 'are' },
        { id: 't3', t: 'testing' },
        { id: 't4', t: 'the new version' },
        { id: 't5', t: 'is', why: '`the developers` ברבים, ולכן `are`, לא `is`.', err: 'be_agreement' },
        {
          id: 't6',
          t: 'test',
          why: '`test` בלי ing מתאר הרגל — מה שהם עושים בדרך כלל. למה שקורה עכשיו: `are testing`.',
          err: 'simple_for_now',
          as: 'meaning_mismatch',
        },
        {
          id: 't7',
          t: 'have',
          why: '`have` לא מתאים כאן. לפעולה שקורה עכשיו צריך `are` + פועל עם ing: `are testing`.',
          err: 'have_without_been',
        },
      ],
      accept: [{ a: 'The developers are testing the new version', o: 'correct_target' }],
      rules: [
        {
          has: ['developers testing'],
          lacks: ['are', 'is', 'have'],
          as: 'form_error',
          err: 'missing_be',
          fb: 'חסר `are`: לפני פועל עם ing צריך `am / is / are`. כאן: `The developers are testing the new version`.',
        },
        {
          has: ['are test'],
          as: 'form_error',
          err: 'be_base',
          fb: 'אחרי `are` בא פועל עם ing: `are testing`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S01-03',
      v: 2,
      skill: 'S01',
      unit: 'S01',
      sub: 'question',
      type: 'assemble',
      role: 'practice',
      stage: 1,
      ctx: 'work.software',
      fam: 'S01.old-system-question',
      goal: 'לשאול עמית אם הם עדיין עובדים עם המערכת הישנה',
      instr: 'בנה את השאלה באנגלית. לא חייבים להשתמש בכל המילים.',
      sitHe: 'הארגון עובר בהדרגה למערכת חדשה. אתה שואל עמית ממחלקה אחרת אם אצלם עדיין עובדים עם הישנה.',
      promptHe: 'אתם עדיין משתמשים במערכת הישנה?',
      target: 'שאלה רגילה: `am / is / are` לפני הנושא, ואחריו פועל עם ing',
      scaffold: ['am / is / are', 'you', 'V-ing'],
      hint: 'בשאלה `are` עובר לפני `you`. `still` בא אחרי הנושא.',
      explain: 'שאלה על מה שקורה בתקופה הזאת: `Are you still using…?` — `are` לפני הנושא, והפועל עם ing אחריו.',
      deep: 'השאלה בנויה כמו המשפט `You are still using the old system`, רק ש-`are` קופץ לפני `you`. `do` מתאים לשאלה עם פועל בסיס (`Do you still use it?` — גם שאלה תקינה, על הרגל), אבל לא לפני ing.',
      tokens: [
        { id: 't1', t: 'are' },
        { id: 't2', t: 'you' },
        { id: 't3', t: 'still' },
        { id: 't4', t: 'using' },
        { id: 't5', t: 'the old system' },
        { id: 't6', t: 'is', why: 'עם `you` משתמשים ב-`are`, לא ב-`is`.', err: 'be_agreement' },
        {
          id: 't7',
          t: 'do',
          why: '`do` בא לפני פועל בסיס (`Do you use…?`), לא לפני ing. עם `using` השאלה נפתחת ב-`are`: `Are you still using…?`',
          err: 'do_with_ing',
        },
      ],
      accept: [
        { a: 'Are you still using the old system', o: 'correct_target' },
        {
          a: 'Are you using the old system',
          o: 'valid_alternative',
          note: 'נכון. `still` מוסיף את ה"עדיין".',
        },
        {
          a: 'You are still using the old system',
          o: 'target_not_used',
          note: 'בדיבור זה אפשרי — שאלה של הפתעה, עם אינטונציה עולה. שאלה רגילה פותחת ב-`are`: `Are you still using the old system?`',
        },
        {
          a: 'You are using the old system',
          o: 'target_not_used',
          note: 'בדיבור זה אפשרי — שאלה של הפתעה, עם אינטונציה עולה. שאלה רגילה פותחת ב-`are`: `Are you still using the old system?`',
        },
      ],
      rules: [
        {
          has: ['you still using'],
          lacks: ['are', 'is', 'do'],
          as: 'form_error',
          err: 'missing_be',
          fb: 'חסר `are`: לפני פועל עם ing צריך `am / is / are`, ובשאלה הוא בא לפני הנושא: `Are you still using…?`',
        },
      ],
      end: '?',
    },
    {
      id: 'S01-04',
      v: 1,
      skill: 'S01',
      unit: 'S01',
      sub: 'negative',
      type: 'assemble',
      role: 'practice',
      stage: 2,
      ctx: 'work.project',
      fam: 'S01.not-answering',
      goal: 'לומר שמישהו לא עונה לטלפון כרגע',
      instr: 'קרא את הסיטואציה ובנה משפט אחד באנגלית.',
      sitEn:
        "You need an answer from Dan today. You've called him three times in the last ten minutes, and there's no answer. Tell your manager.",
      trHe: 'אתה צריך תשובה מדן היום. התקשרת אליו שלוש פעמים בעשר הדקות האחרונות, ואין מענה. ספר למנהלת.',
      hint: 'מה שלא קורה ממש עכשיו: `isn\'t` + פועל עם ing.',
      explain: "ברגע זה אין מענה: `Dan isn't answering his phone` — `isn't` (= `is not`) + פועל עם ing.",
      deep: "`Dan doesn't answer his phone` הוא משפט תקין, אבל הוא אומר משהו אחר: שזה ההרגל שלו — הוא אף פעם לא עונה. על מה שקורה עכשיו: `isn't answering`.",
      tokens: [
        { id: 't1', t: 'Dan' },
        { id: 't2', t: "isn't" },
        { id: 't3', t: 'answering' },
        { id: 't4', t: 'his phone' },
        { id: 't5', t: "aren't", why: "עם `Dan` (אדם אחד) משתמשים ב-`isn't`, לא ב-`aren't`.", err: 'be_agreement' },
        {
          id: 't6',
          t: "doesn't",
          why: "`doesn't` בא לפני פועל בסיס (`doesn't answer` — הרגל: הוא אף פעם לא עונה). לפני ing השלילה היא `isn't`: `Dan isn't answering`.",
          err: 'do_with_ing',
        },
        {
          id: 't7',
          t: 'not',
          why: "`not` לבד לא יוצר שלילה לפני פועל עם ing — צריך גם `is`. `isn't` כבר כולל את שניהם: `Dan isn't answering`.",
          err: 'missing_be',
        },
      ],
      accept: [
        { a: "Dan isn't answering his phone", o: 'correct_target' },
        { a: "Dan isn't answering", o: 'valid_alternative', note: 'גם נכון: אפשר גם בלי `his phone`.' },
      ],
      rules: [
        {
          has: ['Dan answering'],
          lacks: ["isn't"],
          as: 'form_error',
          err: 'missing_be',
          fb: "חסר פועל העזר לפני `answering`, וגם השלילה: `Dan isn't answering his phone`.",
        },
      ],
      end: '.',
    },
    {
      id: 'S01-05',
      v: 1,
      skill: 'S01',
      unit: 'S01',
      sub: 'temporary',
      type: 'assemble',
      role: 'practice',
      stage: 1,
      ctx: 'daily.travel',
      fam: 'S01.train-this-week',
      goal: 'לספר על מצב זמני, רק לשבוע הזה',
      instr: 'בנה את המשפט באנגלית. לא חייבים להשתמש בכל המילים.',
      sitHe: 'בדרך כלל אתה נוסע לעבודה ברכב. השבוע הרכב במוסך, ולכן אתה נוסע ברכבת.',
      promptHe: 'השבוע אני נוסע ברכבת.',
      target: 'מצב זמני: `am / is / are + V-ing`',
      scaffold: ['am / is / are', 'V-ing'],
      hint: 'זה רק לשבוע הזה, לא הסדר קבוע.',
      explain: 'מצב זמני, סביב עכשיו: `I am taking the train this week`. `I take the train` נשמע כמו הרגל קבוע.',
      deep: "המבנה המתמשך מתאר לא רק את הרגע הזה, אלא גם מצב זמני סביב עכשיו — השבוע, החודש, בתקופה הזאת: `I'm working from home this week`. להרגל קבוע משתמשים בהווה פשוט: `I usually drive to work`.",
      tokens: [
        { id: 't1', t: 'I' },
        { id: 't2', t: 'am' },
        { id: 't3', t: 'taking' },
        { id: 't4', t: 'the train' },
        { id: 't5', t: 'this week' },
        { id: 't6', t: 'take' },
        { id: 't7', t: 'is', why: 'עם `I` משתמשים ב-`am`, לא ב-`is`.', err: 'be_agreement' },
        {
          id: 't8',
          t: 'have',
          why: '`have` לא מתאים כאן. למצב זמני צריך `am` + פועל עם ing: `I am taking`.',
          err: 'have_without_been',
        },
      ],
      accept: [
        { a: 'I am taking the train this week', o: 'correct_target' },
        { a: 'This week I am taking the train', o: 'valid_alternative', note: 'גם נכון: `this week` בתחילת המשפט.' },
        {
          a: 'I take the train this week',
          o: 'target_not_used',
          note: 'אפשרי כשמתארים סידור קבוע מראש, כמו לוח זמנים. למצב זמני הצורה הטבעית היא `I am taking the train this week`.',
        },
        {
          a: 'This week I take the train',
          o: 'target_not_used',
          note: 'אפשרי כשמתארים סידור קבוע מראש, כמו לוח זמנים. למצב זמני הצורה הטבעית היא `This week I am taking the train`.',
        },
      ],
      rules: [
        {
          has: ['I taking'],
          lacks: ['am', 'is', 'have'],
          as: 'form_error',
          err: 'missing_be',
          fb: 'חסר `am`: לפני פועל עם ing צריך `am / is / are`. כאן: `I am taking the train this week`.',
        },
        {
          has: ['am take'],
          as: 'form_error',
          err: 'be_base',
          fb: 'אחרי `am` בא פועל עם ing: `am taking`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S01-06',
      v: 1,
      skill: 'S01',
      unit: 'S01',
      sub: 'contrast',
      type: 'correct',
      role: 'practice',
      stage: 3,
      ctx: 'work.municipality',
      fam: 'S01.still-work-there',
      goal: 'לומר שאתה עדיין עובד באותו מקום',
      instr: FIX_INSTR,
      sitHe: 'חבר ותיק שואל אם עזבת את העירייה. לא עזבת — אתה עובד שם כבר שנים, וזה עדיין מקום העבודה שלך.',
      hint: 'האם מדובר במשהו שקורה ברגע זה, או בעובדה קבועה?',
      explain:
        'עובדה קבועה — זה עדיין מקום העבודה שלך: `I still work at the municipality` תקין. גם `I am still working at the municipality` נכון כאן.',
      deep: '`I still work at the municipality` — עדיין מקום העבודה שלי: עובדה, הרגל. `I am still working at the municipality` — גם נכון, ומדגיש שזה נמשך בינתיים. שגוי רק `I still working`, בלי `am`. ועל פעולה שקורה ברגע זה (`I am still working on the report`) מתאים רק המבנה המתמשך.',
      diff: '`I still work there` — עובדה קבועה: שם אני עובד. `I am still working on it` — פעולה שבאמצע, עכשיו. על מקום עבודה אפשר את שניהם; על מה שקורה ברגע זה — רק את השני.',
      source: [
        { id: 's1', t: 'I' },
        { id: 's2', t: 'still' },
        { id: 's3', t: 'work' },
        { id: 's4', t: 'at the municipality' },
      ],
      tokens: [
        { id: 't1', t: 'am' },
        { id: 't2', t: 'working' },
        { id: 't3', t: 'is', why: 'עם `I` משתמשים ב-`am`, לא ב-`is`.', err: 'be_agreement' },
      ],
      accept: [
        { a: 'I still work at the municipality', o: 'correct_target' },
        {
          a: 'I am still working at the municipality',
          o: 'valid_alternative',
          note: 'גם נכון: המבנה המתמשך מדגיש שזה נמשך בינתיים. לעובדה קבועה הצורה הטבעית ביותר: `I still work at the municipality` — לכן לא היה צורך בתיקון.',
        },
        {
          a: 'I still am working at the municipality',
          o: 'valid_alternative',
          note: 'תקין, עם הדגשה. אבל לא היה צורך בתיקון: `I still work at the municipality` תקין.',
        },
      ],
      wrong: [
        {
          a: 'I still working at the municipality',
          as: 'form_error',
          err: 'missing_be',
          fb: 'חסר `am`: `I still working` אינו תקין. המשפט המקורי היה תקין: `I still work at the municipality` (או `I am still working…`).',
        },
      ],
      rules: [
        {
          has: ['am', 'work'],
          lacks: ['working'],
          as: 'form_error',
          err: 'be_base',
          fb: 'אחרי `am` בא פועל עם ing. אבל כאן לא היה צורך בתיקון: `I still work at the municipality` תקין.',
        },
      ],
      end: '.',
    },
    {
      id: 'S01-07',
      v: 1,
      skill: 'S01',
      unit: 'S01',
      sub: 'contrast',
      type: 'discriminate',
      role: 'practice',
      stage: 3,
      ctx: 'daily.food',
      fam: 'S01.still-cooking',
      goal: 'לענות שאתה באמצע משהו, ממש עכשיו',
      instr: 'בחר את התשובה שמתאימה למצב.',
      sitHe: 'אורחים אמורים להגיע בעוד שעה. חבר מתקשר ושואל אם האוכל מוכן. עוד לא — אתה באמצע הבישול.',
      hint: 'מה קורה ברגע זה? ומה חסר או מיותר בכל משפט?',
      explain:
        "באמצע הבישול, עכשיו: `I'm still cooking`. `I still cook` תקין אבל מתאר הרגל, ו-`I still cooking` חסר `am`.",
      deep: '`still` מתאים לשני המבנים, והמשמעות משתנה: `I still cook` — עדיין מבשל באופן כללי, לא הפסקתי לבשל; `I\'m still cooking` — עדיין באמצע הבישול, עכשיו.',
      multi: false,
      options: [
        {
          id: 'a',
          en: "Not yet — I'm still cooking.",
          v: 'fits',
          why: 'מתאים: אתה באמצע הבישול, עכשיו — `am` (`I\'m`) + פועל עם ing.',
        },
        {
          id: 'b',
          en: 'Not yet — I still cook.',
          v: 'other_meaning',
          why: 'תקין דקדוקית, אבל `I still cook` אומר שאתה עדיין מבשל באופן כללי (לא הפסקת לבשל) — לא שאתה באמצע הבישול עכשיו.',
          err: 'simple_for_now',
        },
        {
          id: 'c',
          en: 'Not yet — I still cooking.',
          v: 'ungrammatical',
          why: 'חסר `am`: לפני פועל עם ing צריך `am / is / are` — `I\'m still cooking`.',
          err: 'missing_be',
        },
        {
          id: 'd',
          en: "Not yet — I'm still cook.",
          v: 'ungrammatical',
          why: 'אחרי `am` (`I\'m`) בא פועל עם ing: `I\'m still cooking`.',
          err: 'be_base',
        },
      ],
    },
    {
      id: 'S01-08',
      v: 1,
      skill: 'S01',
      unit: 'S01',
      sub: 'stative',
      type: 'correct',
      role: 'practice',
      stage: 3,
      ctx: 'work.software',
      fam: 'S01.know-how-it-works',
      goal: 'לומר שאתה כבר יודע איך משהו עובד',
      instr: FIX_INSTR,
      sitHe: 'עמית מתחיל להסביר לך איך נכנסים למערכת החדשה. אתה כבר יודע — עשית את ההדרכה בשבוע שעבר.',
      hint: 'האם `know` מתאר פעולה שמתרחשת, או מצב?',
      explain: '`know` הוא פועל מצב, ולכן בלי `am` ובלי ing: `I know how it works`.',
      deep: "פעלים שמתארים מצב — ידיעה, צורך, רצון, שייכות: `know`, `need`, `want`, `belong`, `own` — בדרך כלל לא באים עם ing, גם כשמדובר בעכשיו: `I know`, `I need more time`. באנגלית מדוברת שומעים חריגים כמו `I'm loving it`, אבל `I am knowing` אינו תקין.",
      source: [
        { id: 's1', t: 'I' },
        {
          id: 's2',
          t: 'am',
          why: '`know` מתאר מצב — ידיעה — ולא פעולה שמתרחשת, ולכן בלי `am` ובלי ing: `I know how it works`.',
          err: 'stative_progressive',
        },
        {
          id: 's3',
          t: 'knowing',
          why: 'פעלי מצב כמו `know` בדרך כלל לא באים עם ing, גם כשמדובר בעכשיו: `I know how it works`.',
          err: 'stative_progressive',
        },
        { id: 's4', t: 'how it works' },
      ],
      tokens: [
        { id: 't1', t: 'know' },
        { id: 't2', t: 'already' },
      ],
      accept: [
        { a: 'I know how it works', o: 'correct_target' },
        { a: 'I already know how it works', o: 'correct_target' },
      ],
      wrong: [
        {
          a: 'I am knowing how it works',
          as: 'form_error',
          err: 'stative_progressive',
          fb: '`know` הוא פועל מצב: הוא מתאר ידיעה, לא פעולה, ולכן לא בא עם `am` ו-ing — גם כשמדובר בעכשיו. הנכון: `I know how it works`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S01-09',
      v: 1,
      skill: 'S01',
      unit: 'S01',
      sub: 'stative',
      type: 'correct',
      role: 'practice',
      stage: 2,
      ctx: 'work.clinic',
      fam: 'S01.laptop-belongs',
      goal: 'להסביר למי שייך משהו',
      instr: FIX_INSTR,
      sitHe: 'עובדת חדשה במרפאה שואלת אם מותר לה לקחת הביתה את המחשב הנייד שעל השולחן. אתה מסביר שהוא שייך למרפאה.',
      hint: 'האם `belong` מתאר פעולה שקורה עכשיו, או מצב?',
      explain: 'המשפט תקין. `belong` הוא פועל מצב, ולכן `belongs`, לא `is belonging` — גם כשמדובר בעכשיו.',
      deep: 'שייכות היא מצב, לא פעולה שמתרחשת, ולכן `belong` כמעט אף פעם לא בא עם ing. כך גם `own`, `know`, `need`: `This laptop belongs to the clinic`, `The clinic owns three laptops`.',
      source: [
        { id: 's1', t: 'this laptop' },
        { id: 's2', t: 'belongs' },
        { id: 's3', t: 'to the clinic' },
      ],
      tokens: [
        {
          id: 't1',
          t: 'is',
          why: '`belong` מתאר מצב (שייכות), לא פעולה שמתרחשת, ולכן בלי `is` ובלי ing. המשפט המקורי תקין: `This laptop belongs to the clinic`.',
          err: 'stative_progressive',
        },
        {
          id: 't2',
          t: 'belonging',
          why: '`belong` הוא פועל מצב, ולכן בלי ing: `belongs`. המשפט המקורי תקין.',
          err: 'stative_progressive',
        },
        {
          id: 't3',
          t: 'belong',
          why: 'עם נושא ביחיד (`this laptop`) הפועל מקבל s: `belongs`. המשפט המקורי תקין.',
          err: 'agreement_s',
        },
      ],
      accept: [{ a: 'This laptop belongs to the clinic', o: 'correct_target' }],
      rules: [
        {
          has: ['is belonging'],
          as: 'form_error',
          err: 'stative_progressive',
          fb: '`belong` הוא פועל מצב, ולכן לא `is belonging`. המשפט המקורי היה תקין: `This laptop belongs to the clinic`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S01-D1',
      v: 2,
      skill: 'S01',
      unit: 'S01',
      sub: 'dialogue',
      type: 'dialogue',
      role: 'practice',
      stage: 2,
      ctx: 'work.schedule',
      fam: 'S01.dialogue-home-this-week',
      goal: 'לענות למנהלת איפה אתה עובד השבוע ובמה אתה עובד היום',
      instr: 'ענה לדנה בכל תור.',
      partnerName: 'Dana',
      setupHe: 'דנה, המנהלת שלך, מתקשרת בבוקר. השבוע משפצים את הקומה שלכם, ולכן אתה עובד מהבית.',
      hint: 'בתור הראשון — מצב זמני, השבוע. בתור השני — מה אתה עושה היום.',
      explain: 'מצב זמני: `I am working from home this week`. מה שאתה עושה היום: `I am preparing the presentation for Thursday`.',
      turns: [
        {
          partner: { en: 'Hi! Are you in the office today?', he: 'היי! אתה במשרד היום?' },
          sub: 'temporary',
          instr: 'ענה שלא — השבוע אתה עובד מהבית.',
          hint: 'מצב זמני: `am` + פועל עם ing.',
          explain: 'רק השבוע, לא הסדר קבוע: `No, I am working from home this week`.',
          build: {
            tokens: [
              { id: 't1', t: 'no' },
              { id: 't2', t: 'I' },
              { id: 't3', t: 'am' },
              { id: 't4', t: 'working' },
              { id: 't5', t: 'from home' },
              { id: 't6', t: 'this week' },
              { id: 't7', t: 'is', why: 'עם `I` משתמשים ב-`am`, לא ב-`is`.', err: 'be_agreement' },
              {
                id: 't8',
                t: 'have',
                why: '`have` לא מתאים כאן. למצב זמני צריך `am` + פועל עם ing: `I am working`.',
                err: 'have_without_been',
              },
            ],
            accept: [
              { a: 'No, I am working from home this week', o: 'correct_target' },
              {
                a: 'No, this week I am working from home',
                o: 'valid_alternative',
                note: 'גם נכון: `this week` בתחילת החלק השני.',
              },
              { a: 'I am working from home this week', o: 'valid_alternative', note: 'גם נכון, בלי `no`.' },
              {
                a: 'This week I am working from home',
                o: 'valid_alternative',
                note: 'גם נכון: בלי `no`, ועם `this week` בתחילת המשפט.',
              },
            ],
            rules: [
              {
                has: ['I working'],
                lacks: ['am', 'is', 'have'],
                as: 'form_error',
                err: 'missing_be',
                fb: 'חסר `am`: לפני פועל עם ing צריך `am / is / are`. כאן: `I am working from home this week`.',
              },
            ],
            end: '.',
          },
        },
        {
          partner: { en: 'OK, no problem. What are you working on today?', he: 'בסדר, אין בעיה. על מה אתה עובד היום?' },
          sub: 'affirmative',
          instr: 'ספר לה שאתה מכין את המצגת ליום חמישי.',
          hint: 'מה שאתה עושה היום: `am` + פועל עם ing.',
          explain: 'פעולה שנמשכת היום, סביב עכשיו: `I am preparing the presentation for Thursday`.',
          build: {
            tokens: [
              { id: 't1', t: 'I' },
              { id: 't2', t: 'am' },
              { id: 't3', t: 'preparing' },
              { id: 't4', t: 'the presentation' },
              { id: 't5', t: 'for Thursday' },
              {
                id: 't6',
                t: 'prepare',
                why: '`prepare` בלי ing מתאר הרגל — משהו שאתה עושה בדרך כלל. על מה שאתה עושה היום: `I am preparing`.',
                err: 'simple_for_now',
                as: 'meaning_mismatch',
              },
              { id: 't7', t: 'are', why: 'עם `I` משתמשים ב-`am`, לא ב-`are`.', err: 'be_agreement' },
            ],
            accept: [{ a: 'I am preparing the presentation for Thursday', o: 'correct_target' }],
            rules: [
              {
                has: ['am prepare'],
                as: 'form_error',
                err: 'be_base',
                fb: 'אחרי `am` בא פועל עם ing: `am preparing`.',
              },
              {
                has: ['I preparing'],
                lacks: ['am', 'are'],
                as: 'form_error',
                err: 'missing_be',
                fb: 'חסר `am`: לפני פועל עם ing צריך `am / is / are`. כאן: `I am preparing…`.',
              },
            ],
            end: '.',
          },
        },
      ],
      closing: { en: "Great. Send it to me when it's ready.", he: 'מצוין. שלח לי כשזה מוכן.' },
    },
    {
      id: 'S01-C1',
      v: 1,
      skill: 'S01',
      unit: 'S01',
      sub: 'negative',
      type: 'assemble',
      role: 'check',
      stage: 2,
      ctx: 'daily.shopping',
      fam: 'S01.cards-today',
      goal: 'לומר מה לא קורה היום, באופן זמני',
      instr: 'קרא את הסיטואציה ובנה משפט אחד באנגלית.',
      sitEn:
        'At the supermarket, the card machines are down today, so the cashiers only take cash. Warn the friend who is shopping with you.',
      trHe: 'בסופרמרקט מכשירי האשראי לא עובדים היום, והקופאים מקבלים רק מזומן. הזהר את החבר שקונה איתך.',
      hint: 'מצב זמני — רק היום — בשלילה. הנושא: `they`.',
      explain: "מצב זמני, רק היום: `They aren't accepting cards today` — `aren't` + פועל עם ing.",
      deep: "`They don't accept cards` הוא משפט תקין אבל מתאר מדיניות קבועה של החנות. כשזה רק היום: `They aren't accepting cards today`.",
      tokens: [
        { id: 't1', t: 'they' },
        { id: 't2', t: "aren't" },
        { id: 't3', t: 'accepting' },
        { id: 't4', t: 'cards' },
        { id: 't5', t: 'today' },
        { id: 't6', t: "isn't", why: "עם `they` משתמשים ב-`aren't`, לא ב-`isn't`.", err: 'be_agreement' },
        {
          id: 't7',
          t: "don't",
          why: "`don't` בא לפני פועל בסיס (`don't accept`), לא לפני ing. עם `accepting` השלילה היא `aren't`.",
          err: 'do_with_ing',
        },
        {
          id: 't8',
          t: 'not',
          why: "`not` לבד לא מספיק לפני פועל עם ing — צריך גם `are`. `aren't` כבר כולל את שניהם.",
          err: 'missing_be',
        },
      ],
      accept: [
        { a: "They aren't accepting cards today", o: 'correct_target' },
        { a: "Today they aren't accepting cards", o: 'valid_alternative', note: 'גם נכון: `today` בתחילת המשפט.' },
        {
          a: "They aren't accepting cards",
          o: 'valid_alternative',
          note: 'נכון. `today` מבהיר שזה רק היום.',
        },
      ],
      rules: [
        {
          has: ['they accepting'],
          lacks: ["aren't", "isn't"],
          as: 'form_error',
          err: 'missing_be',
          fb: "חסר פועל העזר לפני `accepting`, וגם השלילה: `They aren't accepting cards today`.",
        },
      ],
      end: '.',
    },
    {
      id: 'S01-C2',
      v: 1,
      skill: 'S01',
      unit: 'S01',
      sub: 'question',
      type: 'assemble',
      role: 'check',
      stage: 2,
      ctx: 'work.meeting',
      fam: 'S01.meeting-still-going',
      goal: 'לשאול אם משהו עדיין נמשך ברגע זה',
      instr: 'בנה את השאלה באנגלית.',
      sitHe: 'הזמנת את חדר הישיבות לאחת-עשרה. עכשיו אחת-עשרה וחמש, הדלת סגורה ושומעים קולות. אתה שואל את המזכירה אם הפגישה שבפנים עדיין נמשכת.',
      hint: 'שאלה על מה שקורה עכשיו: `is` לפני הנושא, ואחריו פועל עם ing.',
      explain: 'שאלה על מה שקורה ברגע זה: `Is the meeting still going on?` — `is` לפני הנושא, והפועל עם ing אחריו.',
      tokens: [
        { id: 't1', t: 'is' },
        { id: 't2', t: 'the meeting' },
        { id: 't3', t: 'still' },
        { id: 't4', t: 'going on' },
        { id: 't5', t: 'are', why: '`the meeting` ביחיד, ולכן `is`, לא `are`.', err: 'be_agreement' },
        {
          id: 't6',
          t: 'does',
          why: '`does` בא לפני פועל בסיס (`Does it go on…?`), לא לפני ing. עם `going` השאלה נפתחת ב-`is`.',
          err: 'do_with_ing',
        },
      ],
      accept: [
        { a: 'Is the meeting still going on', o: 'correct_target' },
        { a: 'Is the meeting going on', o: 'valid_alternative', note: 'נכון. `still` מוסיף את ה"עדיין".' },
      ],
      rules: [
        {
          has: ['meeting still going'],
          lacks: ['is', 'are', 'does'],
          as: 'form_error',
          err: 'missing_be',
          fb: 'חסר `is`: לפני פועל עם ing צריך `am / is / are`, ובשאלה הוא בא לפני הנושא: `Is the meeting still going on?`',
        },
      ],
      end: '?',
    },
    {
      id: 'S01-C3',
      v: 2,
      skill: 'S01',
      unit: 'S01',
      sub: 'affirmative',
      type: 'correct',
      role: 'check',
      stage: 2,
      ctx: 'work.email',
      fam: 'S01.writing-to-ask',
      goal: 'לפתוח מייל בניסוח מקובל',
      instr: FIX_INSTR,
      sitHe: 'אתה כותב מייל לספק כדי לשאול על לוח הזמנים החדש של המשלוחים. זו השורה הראשונה.',
      hint: 'מה אתה עושה ברגע זה? בדוק שהמבנה שלם.',
      explain: 'מה שאתה עושה ברגע זה, כשאתה כותב: `I am writing to ask about…` — `am` + פועל עם ing.',
      deep: '`I am writing to…` היא פתיחה מקובלת מאוד במייל ובמכתב: היא מתארת את מה שאתה עושה ברגע הכתיבה.',
      source: [
        { id: 's1', t: 'I' },
        { id: 's2', t: 'writing' },
        { id: 's3', t: 'to ask about' },
        { id: 's4', t: 'the new delivery schedule' },
      ],
      tokens: [
        { id: 't1', t: 'am' },
        {
          id: 't2',
          t: 'have',
          why: '`have` לבד לפני `writing` אינו מבנה תקין. מה שאתה עושה ברגע זה: `I am writing`.',
          err: 'have_without_been',
        },
        { id: 't3', t: 'is', why: 'עם `I` משתמשים ב-`am`, לא ב-`is`.', err: 'be_agreement' },
      ],
      accept: [{ a: 'I am writing to ask about the new delivery schedule', o: 'correct_target' }],
      wrong: [
        {
          a: 'I writing to ask about the new delivery schedule',
          as: 'form_error',
          err: 'missing_be',
          fb: 'חסר `am`: לפני פועל עם ing צריך `am / is / are`. הפתיחה המקובלת: `I am writing to ask about…`.',
        },
        {
          a: 'I have to ask about the new delivery schedule',
          as: 'meaning_mismatch',
          err: 'have_to_for_progressive',
          fb: 'המשפט תקין, אבל הוא אומר משהו אחר: `I have to ask` = "אני צריך לשאול". במשפט המקורי חסר רק `am`: `I am writing to ask about…` — הפתיחה המקובלת במייל.',
        },
      ],
      end: '.',
    },
  ],
};
