import type { SkillPack } from '../schema';

const CHAIN = ['have / has', 'V3'];
const PP_TARGET = 'המבנה `have / has` + V3 (present perfect)';
/** neutral instruction for correction items (the given sentence may already be correct) */
const FIX_INSTR = 'אם יש טעות — גע במילה או ברווח ובחר תיקון. אם המשפט תקין, בחר "אין צורך בתיקון".';

/**
 * S02 PERFECT_CHAIN — have / has + past participle (V3).
 * Bridge unit: short, focused items. Finished time vs up to now belongs to S06.
 */
export const S02: SkillPack = {
  skill: 'S02',
  lessons: [
    {
      unit: 'S02',
      title: 'עד עכשיו: `have / has + V3`',
      short:
        '`I have sent the report` — שלחתי, והתוצאה נכונה עכשיו: הדוח אצלך. אחרי `have / has` בא תמיד V3, הצורה השלישית של הפועל: `sent`, `written`, `gone`.',
      chain: CHAIN,
      examples: [
        { en: 'She has written the first draft.', he: 'היא כתבה את הטיוטה הראשונה (והיא מוכנה).' },
        { en: "We haven't decided yet.", he: 'עוד לא החלטנו.' },
        { en: 'Has anyone seen my keys?', he: 'מישהו ראה את המפתחות שלי?' },
      ],
      contrast: {
        a: { en: 'She has gone to the bank.', he: 'היא הלכה לבנק (והיא עדיין שם).' },
        b: { en: 'She has been to the bank.', he: 'היא הייתה בבנק (הלכה וחזרה).' },
        note: 'שני המשפטים תקינים ואומרים דברים שונים: `gone` — הלכה ועוד לא חזרה; `been` — הלכה וחזרה, או ביקרה שם.',
      },
      deep:
        "• `have` עם `I / you / we / they`; `has` עם `he / she / it` ועם שם עצם ביחיד (`the manager has`, `someone has`). שלילה: `haven't / hasn't`. שאלה: `have / has` לפני הנושא — `Have you sent it?`\n" +
        '• V3: בפעלים רגילים הוא זהה לצורת העבר (`finished`, `arrived`), וכך גם בחלק מהחריגים (`sent`, `left`). בחריגים רבים יש צורה נפרדת: `write – wrote – written`, `take – took – taken`, `go – went – gone`, `see – saw – seen`, `do – did – done`, `choose – chose – chosen`, `forget – forgot – forgotten`.\n' +
        '• `already` — כבר: בעיקר במשפט חיובי, בין `have` ל-V3 או בסוף. `yet` — עד עכשיו: בשלילה ובשאלה, בסוף המשפט. `just` — לפני רגע: בין `have` ל-V3.\n' +
        '• `been` / `gone`: `She has gone to the bank` — היא שם עכשיו; `She has been to the bank` — הלכה וחזרה. `Have you ever been to Eilat?` — ביקור, חוויה.\n' +
        '• באנגלית אמריקאית אומרים גם `I already sent it`, `Did you send it yet?` — זה לא שגוי. בתרגיל שמבקש `have` + V3, תשובה כזאת מסומנת "לא המבנה שהתבקש", לא טעות.\n' +
        '• זה הבסיס של מבנים נוספים: `have been working` (`been` הוא ה-V3 של `be`), וגם `has been approved`.',
      pitfalls: [
        '`I have send…` — אחרי `have` בא V3: `sent`.',
        '`She has wrote…` — `wrote` הוא עבר פשוט; ה-V3: `written`.',
        '`They have went…` — ה-V3 של `go` הוא `gone`.',
        '`She have…` — עם `he / she / it`: `has`.',
        '`I have sent it yet` — `yet` בא בשלילה ובשאלה; במשפט חיובי: `already`.',
      ],
    },
  ],
  examples: {
    S02: [
      { en: 'The new manager has just arrived.', he: 'המנהלת החדשה הגיעה הרגע.' },
      { en: "I haven't read the new contract yet.", he: 'עוד לא קראתי את החוזה החדש.' },
      { en: 'Have you ever been to Eilat?', he: 'היית פעם באילת?', note: '`been` — ביקור, חוויה: היית שם וחזרת.' },
      { en: 'Someone has left an umbrella in the waiting room.', he: 'מישהו השאיר מטרייה בחדר ההמתנה.' },
    ],
  },
  items: [
    {
      id: 'S02-01',
      v: 1,
      skill: 'S02',
      unit: 'S02',
      sub: 'affirmative',
      type: 'assemble',
      role: 'practice',
      stage: 1,
      ctx: 'work.report',
      fam: 'S02.already-sent-report',
      goal: 'לומר שכבר שלחת את הדוח',
      instr: 'בנה את המשפט באנגלית. לא חייבים להשתמש בכל המילים.',
      sitHe: 'המנהלת שואלת מתי תשלח את הדוח. הוא כבר אצלה בתיבת הדואר.',
      promptHe: 'כבר שלחתי את הדוח.',
      target: PP_TARGET,
      scaffold: ['have / has', 'already', 'V3'],
      hint: '`already` נכנס בין `have` לבין V3.',
      explain: 'כבר קרה, והתוצאה נכונה עכשיו: `I have already sent the report`. אחרי `have` בא V3 — `sent`.',
      deep: '`send – sent – sent`: בפועל הזה צורת העבר וצורת ה-V3 זהות. `already` בא בדרך כלל בין `have` ל-V3, ואפשר גם בסוף: `I have sent the report already`. באנגלית אמריקאית אומרים גם `I already sent the report` — זה תקין, אבל זה לא המבנה שמתרגלים כאן.',
      tokens: [
        { id: 't1', t: 'I' },
        { id: 't2', t: 'have' },
        { id: 't3', t: 'already' },
        { id: 't4', t: 'sent' },
        { id: 't5', t: 'the report' },
        { id: 't6', t: 'has', why: 'עם `I` משתמשים ב-`have`, לא ב-`has`.', err: 'have_agreement' },
        { id: 't7', t: 'send', why: '`send` היא צורת הבסיס. אחרי `have` בא V3: `sent`.', err: 'have_base' },
        {
          id: 't8',
          t: 'yet',
          why: '`yet` בא בשאלות ובמשפטי שלילה. במשפט חיובי, "כבר" הוא `already`.',
          err: 'yet_affirmative',
        },
      ],
      accept: [
        { a: 'I have already sent the report', o: 'correct_target' },
        {
          a: 'I have sent the report already',
          o: 'valid_alternative',
          note: 'גם נכון: `already` יכול לבוא גם בסוף המשפט.',
        },
        { a: 'I have sent the report', o: 'valid_alternative', note: 'נכון. `already` מוסיף את ה"כבר".' },
        {
          a: 'I already sent the report',
          o: 'target_not_used',
          note: 'תקין, ונפוץ מאוד באנגלית אמריקאית. התרגיל ביקש `have` + V3: `I have already sent the report`.',
        },
        {
          a: 'I sent the report already',
          o: 'target_not_used',
          note: 'תקין, ונפוץ באנגלית אמריקאית. התרגיל ביקש `have` + V3: `I have already sent the report`.',
        },
        {
          a: 'I sent the report',
          o: 'target_not_used',
          note: 'תקין — עבר פשוט. התרגיל ביקש `have` + V3, עם "כבר": `I have already sent the report`.',
        },
      ],
      rules: [
        {
          has: ['have send'],
          as: 'form_error',
          err: 'have_base',
          fb: 'אחרי `have` בא V3: `have sent`, לא `have send`.',
        },
        {
          has: ['have already send'],
          as: 'form_error',
          err: 'have_base',
          fb: 'אחרי `have` בא V3: `have already sent`, לא `send`.',
        },
        {
          has: ['send'],
          lacks: ['have', 'has'],
          as: 'meaning_mismatch',
          err: 'present_for_past',
          fb: '`send` בהווה מתאר הרגל — משהו שאתה עושה בדרך כלל. כאן זה כבר קרה: `I have already sent the report`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S02-02',
      v: 1,
      skill: 'S02',
      unit: 'S02',
      sub: 'negative',
      type: 'assemble',
      role: 'practice',
      stage: 1,
      ctx: 'work.meeting',
      fam: 'S02.not-chosen-date',
      goal: 'לומר שמשהו עוד לא קרה עד עכשיו',
      instr: 'בנה את המשפט באנגלית. לא חייבים להשתמש בכל המילים.',
      sitHe: 'שואלים אותך מתי הפגישה הבאה. המנהל עוד לא קבע.',
      promptHe: 'הוא עוד לא בחר תאריך לפגישה.',
      scaffold: ["haven't / hasn't", 'V3', '… yet'],
      hint: 'עד עכשיו זה לא קרה: `hasn\'t` + V3, ו-`yet` בסוף.',
      explain: "עד עכשיו זה לא קרה: `He hasn't chosen a date … yet`. אחרי `hasn't` בא V3: `chosen`, לא `chose`.",
      deep: "`choose – chose – chosen`. `chose` הוא עבר פשוט (`He chose a date` — הוא כבר בחר), ו-`chosen` בא אחרי `have / has`. `yet` בא בדרך כלל בסוף משפט שלילה או שאלה; `He hasn't yet chosen…` אפשרי בסגנון רשמי.",
      tokens: [
        { id: 't1', t: 'he' },
        { id: 't2', t: "hasn't" },
        { id: 't3', t: 'chosen' },
        { id: 't4', t: 'a date for the meeting' },
        { id: 't5', t: 'yet' },
        { id: 't6', t: "haven't", why: "עם `he` משתמשים ב-`hasn't`, לא ב-`haven't`.", err: 'have_agreement' },
        { id: 't7', t: 'chose', why: "`chose` הוא עבר פשוט. אחרי `hasn't` בא V3: `chosen`.", err: 'have_v2' },
      ],
      accept: [
        { a: "He hasn't chosen a date for the meeting yet", o: 'correct_target' },
        {
          a: "He hasn't yet chosen a date for the meeting",
          o: 'valid_alternative',
          note: 'גם נכון, בסגנון רשמי יותר.',
        },
        {
          a: "He hasn't chosen a date for the meeting",
          o: 'valid_alternative',
          note: 'נכון. `yet` בסוף מוסיף את ה"עוד".',
        },
        {
          a: "He hasn't chosen yet",
          o: 'valid_alternative',
          note: 'נכון — "הוא עוד לא בחר". עם המושא: `He hasn\'t chosen a date for the meeting yet`.',
        },
      ],
      rules: [
        {
          has: ['he chose'],
          as: 'meaning_mismatch',
          err: 'opposite_meaning',
          fb: "`He chose…` אומר שהוא כבר בחר. כאן הוא עוד לא בחר: `He hasn't chosen a date for the meeting yet`.",
        },
        {
          has: ['yet a date'],
          as: 'form_error',
          err: 'word_order',
          fb: "`yet` בא בסוף המשפט: `He hasn't chosen a date for the meeting yet`.",
        },
      ],
      end: '.',
    },
    {
      id: 'S02-03',
      v: 2,
      skill: 'S02',
      unit: 'S02',
      sub: 'question',
      type: 'assemble',
      role: 'practice',
      stage: 1,
      ctx: 'work.email',
      fam: 'S02.seen-email-yet',
      goal: 'לשאול אם מישהו כבר ראה את המייל ששלחת',
      instr: 'בנה את השאלה באנגלית. לא חייבים להשתמש בכל המילים.',
      sitHe: 'שלחת לעמית מייל חשוב, והוא עוד לא הגיב. אתה פוגש אותו במסדרון.',
      promptHe: 'ראית כבר את המייל שלי?',
      target: 'שאלה במבנה `have / has` + V3 (present perfect)',
      scaffold: ['have / has', 'you', 'V3', '… yet'],
      hint: '`have` לפני `you`, ו-`yet` בסוף השאלה.',
      explain: 'שאלה על מה שקרה (או לא) עד עכשיו: `Have you seen my email yet?` — `have` לפני הנושא, V3 אחריו, `yet` בסוף.',
      deep: 'בעברית "ראית כבר?" — ובאנגלית, בשאלה ניטרלית, "כבר" הוא `yet` בסוף השאלה. `Have you already seen it?` מתאים כשאתה מופתע שזה קרה כל כך מהר. באנגלית אמריקאית מדוברת שומעים גם `Did you see my email yet?`.',
      tokens: [
        { id: 't1', t: 'have' },
        { id: 't2', t: 'you' },
        { id: 't3', t: 'seen' },
        { id: 't4', t: 'my email' },
        { id: 't5', t: 'yet' },
        { id: 't6', t: 'has', why: 'עם `you` משתמשים ב-`have`: `Have you…?`', err: 'have_agreement' },
        { id: 't7', t: 'saw' },
      ],
      accept: [
        { a: 'Have you seen my email yet', o: 'correct_target' },
        { a: 'Have you seen my email', o: 'valid_alternative', note: 'נכון. `yet` בסוף מוסיף "כבר / עד עכשיו".' },
        {
          a: 'You have seen my email',
          o: 'target_not_used',
          note: 'בדיבור זו שאלת אישור (עם אינטונציה עולה). שאלה רגילה פותחת ב-`have`: `Have you seen my email yet?`',
        },
        {
          a: 'You saw my email',
          o: 'target_not_used',
          note: 'בדיבור זו שאלת אישור אפשרית. התרגיל ביקש שאלה רגילה ב-`have` + V3: `Have you seen my email yet?`',
        },
      ],
      wrong: [
        {
          a: 'You saw my email yet',
          as: 'form_error',
          err: 'no_inversion',
          fb: '`yet` לא בא במשפט חיובי רגיל, גם כשהוא נאמר כשאלה. שאלה עם `yet` נפתחת בפועל העזר: `Have you seen my email yet?` (באנגלית אמריקאית מדוברת גם `Did you see my email yet?`).',
        },
      ],
      rules: [
        {
          has: ['you seen'],
          lacks: ['have', 'has'],
          as: 'form_error',
          err: 'missing_have',
          fb: 'חסר `have`. בדיבור מהיר לפעמים "בולעים" אותו (`You seen…?`), אבל בשאלה מלאה `have` בא לפני הנושא: `Have you seen my email yet?`',
        },
        {
          has: ['have', 'saw'],
          as: 'form_error',
          err: 'have_v2',
          fb: '`saw` הוא עבר פשוט. אחרי `have` בא V3: `Have you seen…?`',
        },
        {
          has: ['you have', 'yet'],
          as: 'form_error',
          err: 'no_inversion',
          fb: 'בשאלה `have` בא לפני הנושא: `Have you seen my email yet?`',
        },
        {
          has: ['yet my email'],
          as: 'form_error',
          err: 'word_order',
          fb: '`yet` בא בסוף השאלה: `Have you seen my email yet?`',
        },
      ],
      end: '?',
    },
    {
      id: 'S02-04',
      v: 1,
      skill: 'S02',
      unit: 'S02',
      sub: 'affirmative',
      type: 'correct',
      role: 'practice',
      stage: 2,
      ctx: 'work.email',
      fam: 'S02.written-to-supplier',
      goal: 'לומר שמישהי כבר פנתה לספק',
      instr: FIX_INSTR,
      sitHe: 'שואלים אם מישהו כבר פנה לספק בעניין העיכוב במשלוח. דנה כתבה לו, והיא מחכה לתשובה.',
      target: PP_TARGET,
      hint: 'בדוק את צורת הפועל אחרי `has`.',
      explain: 'אחרי `has` בא V3: `written`, לא `wrote` (עבר פשוט). `Dana has written to the supplier`.',
      deep: '`write – wrote – written`. בפעלים חריגים רבים צורת העבר וצורת ה-V3 שונות: `take – took – taken`, `go – went – gone`, `see – saw – seen`. אחרי `have / has` תמיד V3.',
      source: [
        { id: 's1', t: 'Dana' },
        { id: 's2', t: 'has' },
        { id: 's3', t: 'wrote' },
        { id: 's4', t: 'to the supplier' },
      ],
      tokens: [
        { id: 't1', t: 'written' },
        { id: 't2', t: 'already' },
        { id: 't3', t: 'write', why: '`write` היא צורת הבסיס. אחרי `has` בא V3: `written`.', err: 'have_base' },
        {
          id: 't4',
          t: 'have',
          why: 'עם `Dana` (אדם אחד) משתמשים ב-`has`, לא ב-`have`.',
          err: 'have_agreement',
        },
      ],
      accept: [
        { a: 'Dana has written to the supplier', o: 'correct_target' },
        { a: 'Dana has already written to the supplier', o: 'correct_target' },
        {
          a: 'Dana has written to the supplier already',
          o: 'valid_alternative',
          note: 'גם נכון: `already` יכול לבוא גם בסוף.',
        },
        {
          a: 'Dana wrote to the supplier',
          o: 'target_not_used',
          note: 'תקין — עבר פשוט. התרגיל ביקש `has` + V3: `Dana has written to the supplier`.',
        },
        {
          a: 'Dana already wrote to the supplier',
          o: 'target_not_used',
          note: 'תקין, ונפוץ באנגלית אמריקאית. התרגיל ביקש `has` + V3: `Dana has already written to the supplier`.',
        },
      ],
      wrong: [
        {
          a: 'Dana has wrote to the supplier',
          as: 'form_error',
          err: 'have_v2',
          fb: '`wrote` הוא עבר פשוט. אחרי `has` בא V3: `written` — `Dana has written to the supplier`.',
        },
      ],
      rules: [
        {
          has: ['written'],
          lacks: ['has', 'have'],
          as: 'form_error',
          err: 'missing_have',
          fb: 'חסר `has`: צורת V3 (`written`) לא עומדת לבד. `Dana has written to the supplier`.',
        },
        {
          has: ['has', 'wrote'],
          as: 'form_error',
          err: 'have_v2',
          fb: '`wrote` הוא עבר פשוט. אחרי `has` בא V3: `written`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S02-05',
      v: 1,
      skill: 'S02',
      unit: 'S02',
      sub: 'affirmative',
      type: 'correct',
      role: 'practice',
      stage: 2,
      ctx: 'daily.home',
      fam: 'S02.done-dishes',
      goal: 'לומר שכבר עשית משהו',
      instr: FIX_INSTR,
      sitHe: 'מזכירים לך לשטוף את הכלים. כבר שטפת אותם — הכיור ריק.',
      target: PP_TARGET,
      hint: 'בדוק את צורת הפועל אחרי `have`. אם הכול תקין, אין צורך לתקן.',
      explain: 'המשפט תקין: `have` + `already` + V3 (`done`). `did` הוא עבר פשוט ולא בא אחרי `have`.',
      deep: '`do – did – done`. באנגלית אמריקאית אומרים גם `I already did the dishes` — גם זה תקין, אבל זה לא המבנה שמתרגלים כאן.',
      source: [
        { id: 's1', t: 'I' },
        { id: 's2', t: 'have' },
        { id: 's3', t: 'already' },
        { id: 's4', t: 'done' },
        { id: 's5', t: 'the dishes' },
      ],
      tokens: [
        { id: 't1', t: 'did' },
        { id: 't2', t: 'has', why: 'עם `I` משתמשים ב-`have`, לא ב-`has`. המשפט המקורי היה תקין.', err: 'have_agreement' },
      ],
      accept: [
        { a: 'I have already done the dishes', o: 'correct_target' },
        { a: 'I have done the dishes already', o: 'valid_alternative', note: 'גם נכון: `already` יכול לבוא גם בסוף.' },
        { a: 'I have done the dishes', o: 'valid_alternative', note: 'נכון. `already` מוסיף את ה"כבר".' },
        {
          a: 'I already did the dishes',
          o: 'target_not_used',
          note: 'תקין, ונפוץ באנגלית אמריקאית. אבל לא היה צורך בתיקון: `I have already done the dishes` תקין.',
        },
        {
          a: 'I did the dishes already',
          o: 'target_not_used',
          note: 'תקין, ונפוץ באנגלית אמריקאית. אבל לא היה צורך בתיקון: `I have already done the dishes` תקין.',
        },
        {
          a: 'I did the dishes',
          o: 'target_not_used',
          note: 'תקין — עבר פשוט. אבל לא היה צורך בתיקון: `I have already done the dishes` תקין.',
        },
      ],
      wrong: [
        {
          a: 'I have already did the dishes',
          as: 'form_error',
          err: 'have_v2',
          fb: '`did` הוא עבר פשוט. אחרי `have` בא V3: `done`. המשפט המקורי היה תקין.',
        },
      ],
      rules: [
        {
          has: ['done'],
          lacks: ['have', 'has'],
          as: 'form_error',
          err: 'missing_have',
          fb: 'חסר `have`: צורת V3 (`done`) לא עומדת לבד. המשפט המקורי היה תקין: `I have already done the dishes`.',
        },
        {
          has: ['have', 'did'],
          as: 'form_error',
          err: 'have_v2',
          fb: '`did` הוא עבר פשוט. אחרי `have` בא V3: `done`. המשפט המקורי היה תקין.',
        },
      ],
      end: '.',
    },
    {
      id: 'S02-06',
      v: 2,
      skill: 'S02',
      unit: 'S02',
      sub: 'contrast',
      type: 'correct',
      role: 'practice',
      stage: 3,
      ctx: 'work.job',
      fam: 'S02.gone-home',
      goal: 'להסביר שאנשים כבר יצאו ואינם כאן',
      instr: FIX_INSTR,
      sitHe: 'שש בערב. מבקר נכנס למשרד ושואל איפה כולם. העובדים יצאו הביתה, והמשרד ריק.',
      target: PP_TARGET,
      hint: 'מה ה-V3 של `go`? ומה ההבדל בין `gone` ל-`been`?',
      explain: '`go – went – gone`: אחרי `have` בא `gone`. `They have gone home` — הם יצאו ועדיין לא כאן.',
      deep: '`been` משמש גם הוא כ-V3 של `go`, במשמעות אחרת: `They have been to Paris` — היו שם וחזרו. `gone` — הלכו ועדיין שם, או בדרך. לכן כשהמשרד ריק: `They have gone home`.',
      diff: '`They have gone home` — יצאו ועדיין לא כאן. `They have been home` — היו בבית (או הלכו וחזרו).',
      source: [
        { id: 's1', t: 'they' },
        { id: 's2', t: 'have' },
        { id: 's3', t: 'went' },
        { id: 's4', t: 'home' },
      ],
      tokens: [
        { id: 't1', t: 'gone' },
        {
          id: 't2',
          t: 'been',
          why: '`have been` אומר שהם היו שם, או הלכו וחזרו — לא שיצאו ועדיין לא כאן. כאן: `They have gone home`.',
          err: 'been_for_gone',
          as: 'meaning_mismatch',
        },
        { id: 't3', t: 'go', why: '`go` היא צורת הבסיס. אחרי `have` בא V3: `gone`.', err: 'have_base' },
      ],
      accept: [
        { a: 'They have gone home', o: 'correct_target' },
        {
          a: 'They went home',
          o: 'target_not_used',
          note: 'תקין — עבר פשוט. התרגיל ביקש `have` + V3, וה-V3 של `go` הוא `gone`: `They have gone home`.',
        },
      ],
      wrong: [
        {
          a: 'They have went home',
          as: 'form_error',
          err: 'have_v2',
          fb: '`went` הוא עבר פשוט. אחרי `have` בא V3: `gone` — `They have gone home`.',
        },
        {
          a: 'They have been home',
          as: 'meaning_mismatch',
          err: 'been_for_gone',
          fb: 'המשפט תקין, אבל `have been home` אומר שהם היו בבית — לא שיצאו ועדיין לא כאן. כאן: `They have gone home`.',
        },
      ],
      rules: [
        {
          has: ['gone'],
          lacks: ['have', 'has', 'been'],
          as: 'form_error',
          err: 'missing_have',
          fb: 'חסר `have`: צורת V3 (`gone`) לא עומדת לבד. `They have gone home`.',
        },
        {
          has: ['have went'],
          as: 'form_error',
          err: 'have_v2',
          fb: '`went` הוא עבר פשוט. אחרי `have` בא V3: `gone`.',
        },
        {
          has: ['they been'],
          as: 'form_error',
          err: 'missing_have',
          fb: 'חסר `have` לפני `been`. וגם `They have been home` אומר שהם היו בבית — לא שיצאו ועדיין לא כאן. כאן: `They have gone home`.',
        },
        {
          has: ['been gone'],
          as: 'meaning_mismatch',
          err: 'been_gone',
          fb: '`They have been gone` אומר שהם כבר זמן מה לא כאן, אבל לא לאן הלכו. כדי לומר שיצאו הביתה: `They have gone home`.',
        },
        {
          has: ['they go'],
          as: 'meaning_mismatch',
          err: 'present_for_past',
          fb: '`They go home` מתאר הרגל. כאן הם כבר יצאו: `They have gone home`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S02-07',
      v: 1,
      skill: 'S02',
      unit: 'S02',
      sub: 'contrast',
      type: 'discriminate',
      role: 'practice',
      stage: 3,
      ctx: 'work.clinic',
      fam: 'S02.gone-post-office',
      goal: 'להבחין בין `has gone` ל-`has been`',
      instr: 'בחר את המשפט שמתאים למצב.',
      sitHe: 'מישהו ניגש לדלפק הקבלה במרפאה ושואל איפה רינה. היא יצאה לדואר לפני עשר דקות ועוד לא חזרה.',
      hint: 'היא כבר חזרה, או שהיא עדיין שם?',
      explain: '`She has gone to the post office` — היא שם עכשיו. `She has been to the post office` — הלכה וכבר חזרה.',
      deep: 'לפועל `go` יש שתי צורות V3: `gone` — הלך ועדיין לא חזר; `been` — הלך וחזר, או ביקר שם פעם (`Have you ever been to Eilat?`).',
      multi: false,
      options: [
        {
          id: 'a',
          en: 'She has gone to the post office.',
          v: 'fits',
          why: 'מתאים: `has gone` — היא יצאה ועדיין שם, עוד לא חזרה.',
        },
        {
          id: 'b',
          en: 'She has been to the post office.',
          v: 'other_meaning',
          why: 'תקין דקדוקית, אבל `has been` אומר שהיא הלכה וכבר חזרה — ואז היא הייתה כאן.',
          err: 'been_for_gone',
        },
        {
          id: 'c',
          en: 'She has went to the post office.',
          v: 'ungrammatical',
          why: '`went` הוא עבר פשוט. אחרי `has` בא V3: `gone`.',
          err: 'have_v2',
        },
        {
          id: 'd',
          en: 'She have gone to the post office.',
          v: 'ungrammatical',
          why: 'עם `she` משתמשים ב-`has`, לא ב-`have`.',
          err: 'have_agreement',
        },
      ],
    },
    {
      id: 'S02-08',
      v: 1,
      skill: 'S02',
      unit: 'S02',
      sub: 'affirmative',
      type: 'assemble',
      role: 'practice',
      stage: 2,
      ctx: 'work.software',
      fam: 'S02.forgotten-password',
      goal: 'להסביר לתמיכה שאתה לא זוכר את הסיסמה',
      instr: 'קרא את הסיטואציה ובנה משפט אחד באנגלית.',
      sitEn: "You're trying to log in to the new system, but you can't remember your password. Call IT and explain.",
      trHe: 'אתה מנסה להיכנס למערכת החדשה, אבל אתה לא זוכר את הסיסמה. התקשר לתמיכה והסבר.',
      target: PP_TARGET,
      hint: 'מה ה-V3 של `forget`?',
      explain: 'שכחת, והתוצאה עכשיו — אתה לא יכול להיכנס: `I have forgotten my password`. `forget – forgot – forgotten`.',
      deep: 'present perfect מתאים כשהתוצאה של מה שקרה חשובה עכשיו. `I forgot my password` נפוץ מאוד ותקין לגמרי — זה עבר פשוט. אחרי `have` בא `forgotten`, לא `forgot`.',
      tokens: [
        { id: 't1', t: 'I' },
        { id: 't2', t: 'have' },
        { id: 't3', t: 'forgotten' },
        { id: 't4', t: 'my password' },
        { id: 't5', t: 'forgot' },
        { id: 't6', t: 'has', why: 'עם `I` משתמשים ב-`have`, לא ב-`has`.', err: 'have_agreement' },
        { id: 't7', t: 'forget' },
      ],
      accept: [
        { a: 'I have forgotten my password', o: 'correct_target' },
        {
          a: 'I forgot my password',
          o: 'target_not_used',
          note: 'תקין לגמרי וטבעי מאוד — עבר פשוט. התרגיל ביקש `have` + V3: `I have forgotten my password`.',
        },
        {
          a: 'I forget my password',
          o: 'target_not_used',
          note: 'בדיבור `I forget` יכול לומר "אני לא זוכר כרגע" (כמו `I forget his name`), אבל לרוב זה נשמע כמו הרגל. כאן הניסוח הטבעי: `I have forgotten my password` (או `I forgot…`).',
        },
      ],
      rules: [
        {
          has: ['forgotten'],
          lacks: ['have', 'has'],
          as: 'form_error',
          err: 'missing_have',
          fb: 'חסר `have`: צורת V3 (`forgotten`) לא עומדת לבד. `I have forgotten my password`.',
        },
        {
          has: ['have forgot'],
          as: 'form_error',
          err: 'have_v2',
          fb: '`forgot` הוא עבר פשוט. אחרי `have` בא V3: `forgotten`.',
        },
        {
          has: ['have forget'],
          as: 'form_error',
          err: 'have_base',
          fb: '`forget` היא צורת הבסיס. אחרי `have` בא V3: `forgotten`.',
        },
        {
          has: ['has forget'],
          as: 'form_error',
          err: 'have_base',
          fb: 'עם `I` משתמשים ב-`have`, ואחריו V3: `I have forgotten`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S02-09',
      v: 1,
      skill: 'S02',
      unit: 'S02',
      sub: 'affirmative',
      type: 'assemble',
      role: 'practice',
      stage: 2,
      ctx: 'work.meeting',
      fam: 'S02.just-spoken-manager',
      goal: 'לומר שעשית משהו לפני רגע',
      instr: 'בנה משפט אחד באנגלית שמתאר את המצב.',
      sitHe: 'עמית שואל אם מישהו כבר סיפר למנהלת על התקלה. סיימת לדבר איתה לפני דקה.',
      target: PP_TARGET,
      hint: 'לפני רגע: `just` בין `have` ל-V3.',
      explain: 'לפני רגע, והתוצאה נכונה עכשיו: `I have just spoken to the manager`. `just` נכנס בין `have` ל-V3.',
      deep: '`speak – spoke – spoken`. `just` = לפני רגע. באנגלית אמריקאית אומרים גם `I just spoke to the manager` — תקין, אבל זה לא המבנה שמתרגלים כאן.',
      tokens: [
        { id: 't1', t: 'I' },
        { id: 't2', t: 'have' },
        { id: 't3', t: 'just' },
        { id: 't4', t: 'spoken' },
        { id: 't5', t: 'to the manager' },
        { id: 't6', t: 'spoke' },
        { id: 't7', t: 'has', why: 'עם `I` משתמשים ב-`have`, לא ב-`has`.', err: 'have_agreement' },
        {
          id: 't8',
          t: 'yet',
          why: '`yet` בא בשאלות ובמשפטי שלילה. כאן, "לפני רגע": `just`.',
          err: 'yet_affirmative',
        },
      ],
      accept: [
        { a: 'I have just spoken to the manager', o: 'correct_target' },
        { a: 'I have spoken to the manager', o: 'valid_alternative', note: 'נכון. `just` מוסיף "לפני רגע".' },
        {
          a: 'I just spoke to the manager',
          o: 'target_not_used',
          note: 'תקין, ונפוץ מאוד באנגלית אמריקאית. התרגיל ביקש `have` + V3: `I have just spoken to the manager`.',
        },
        {
          a: 'I spoke to the manager',
          o: 'target_not_used',
          note: 'תקין — עבר פשוט. התרגיל ביקש `have` + V3, ו-`just` מוסיף "לפני רגע".',
        },
      ],
      rules: [
        {
          has: ['spoken'],
          lacks: ['have', 'has'],
          as: 'form_error',
          err: 'missing_have',
          fb: 'חסר `have`: צורת V3 (`spoken`) לא עומדת לבד. `I have just spoken to the manager`.',
        },
        {
          has: ['have', 'spoke'],
          as: 'form_error',
          err: 'have_v2',
          fb: '`spoke` הוא עבר פשוט. אחרי `have` בא V3: `spoken`.',
        },
        {
          has: ['just have'],
          as: 'form_error',
          err: 'word_order',
          fb: '`just` בא אחרי `have`, לפני V3: `I have just spoken to the manager`.',
        },
        {
          ends: 'just',
          as: 'form_error',
          err: 'word_order',
          fb: '`just` בא בין `have` ל-V3: `I have just spoken to the manager`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S02-10',
      v: 1,
      skill: 'S02',
      unit: 'S02',
      sub: 'question',
      type: 'discriminate',
      role: 'practice',
      stage: 3,
      ctx: 'daily.food',
      fam: 'S02.eaten-yet',
      goal: 'לשאול אם מישהו כבר אכל',
      instr: 'בחר את כל המשפטים שמתאימים למצב.',
      sitHe: 'אחת וחצי בצהריים. אתה רוצה להציע לעמית לרדת איתך לאכול, אבל אולי הוא כבר אכל.',
      hint: 'יכול להיות שיותר ממשפט אחד מתאים. בדוק את צורת הפועל ואת `have / has`.',
      explain: '`Have you eaten yet?` ו-`Have you already eaten?` מתאימים שניהם. `ate` הוא עבר פשוט ולא בא אחרי `have`.',
      deep: '`yet` בשאלה — שאלה פתוחה: זה קרה או לא? `already` בשאלה — כשנראה לך שאולי זה כבר קרה, או כשאתה מופתע שזה קרה מהר. באנגלית אמריקאית מדוברת שומעים גם `Did you eat yet?`.',
      multi: true,
      options: [
        { id: 'a', en: 'Have you eaten yet?', v: 'fits', why: 'מתאים: שאלה פתוחה — `yet` בסוף השאלה.' },
        {
          id: 'b',
          en: 'Have you already eaten?',
          v: 'fits',
          why: 'מתאים: `already` בשאלה — כשנראה לך שאולי הוא כבר אכל.',
        },
        {
          id: 'c',
          en: 'Have you ate yet?',
          v: 'ungrammatical',
          why: '`ate` הוא עבר פשוט. אחרי `have` בא V3: `eaten`.',
          err: 'have_v2',
        },
        {
          id: 'd',
          en: 'Has you eaten yet?',
          v: 'ungrammatical',
          why: 'עם `you` משתמשים ב-`have`: `Have you…?`',
          err: 'have_agreement',
        },
      ],
    },
    {
      id: 'S02-D1',
      v: 2,
      skill: 'S02',
      unit: 'S02',
      sub: 'dialogue',
      type: 'dialogue',
      role: 'practice',
      stage: 2,
      ctx: 'work.project',
      fam: 'S02.dialogue-tests',
      goal: 'לעדכן את מנהלת הפרויקט מה כבר נעשה ומה עוד לא',
      instr: 'ענה לנועה בכל תור.',
      partnerName: 'Noa',
      setupHe: 'נועה, מנהלת הפרויקט, בודקת איפה עומדות הבדיקות לפני ההשקה ביום שני. חצי מהבדיקות כבר עשית; את בדיקות האבטחה עוד לא התחלת.',
      hint: 'בתור הראשון — מה כבר נעשה עד עכשיו. בתור השני — מה עוד לא.',
      explain: "מה כבר נעשה: `I have already done half of them`. מה עוד לא: `I haven't started them yet`.",
      turns: [
        {
          partner: { en: 'The launch is on Monday. How are the tests going?', he: 'ההשקה ביום שני. איך מתקדמות הבדיקות?' },
          sub: 'affirmative',
          instr: 'ספר לה שכבר עשית חצי מהבדיקות.',
          target: PP_TARGET,
          hint: 'כבר קרה, עד עכשיו: `have` + `already` + V3 של `do`.',
          explain: 'עד עכשיו: `I have already done half of them`. `do – did – done`: אחרי `have` בא `done`.',
          build: {
            tokens: [
              { id: 't1', t: 'I' },
              { id: 't2', t: 'have' },
              { id: 't3', t: 'already' },
              { id: 't4', t: 'done' },
              { id: 't5', t: 'half of them' },
              { id: 't6', t: 'did' },
              { id: 't7', t: 'has', why: 'עם `I` משתמשים ב-`have`, לא ב-`has`.', err: 'have_agreement' },
            ],
            accept: [
              { a: 'I have already done half of them', o: 'correct_target' },
              {
                a: 'I have done half of them already',
                o: 'valid_alternative',
                note: 'גם נכון: `already` יכול לבוא גם בסוף.',
              },
              { a: 'I have done half of them', o: 'valid_alternative', note: 'נכון. `already` מוסיף את ה"כבר".' },
              {
                a: 'I already did half of them',
                o: 'target_not_used',
                note: 'תקין, ונפוץ באנגלית אמריקאית. התרגיל ביקש `have` + V3: `I have already done half of them`.',
              },
              {
                a: 'I did half of them already',
                o: 'target_not_used',
                note: 'תקין, ונפוץ באנגלית אמריקאית. התרגיל ביקש `have` + V3: `I have already done half of them`.',
              },
              {
                a: 'I did half of them',
                o: 'target_not_used',
                note: 'תקין — עבר פשוט. התרגיל ביקש `have` + V3: `I have already done half of them`.',
              },
            ],
            rules: [
              {
                has: ['done'],
                lacks: ['have', 'has'],
                as: 'form_error',
                err: 'missing_have',
                fb: 'חסר `have`: צורת V3 (`done`) לא עומדת לבד. `I have already done half of them`.',
              },
              {
                has: ['have', 'did'],
                as: 'form_error',
                err: 'have_v2',
                fb: '`did` הוא עבר פשוט. אחרי `have` בא V3: `done`.',
              },
            ],
            end: '.',
          },
        },
        {
          partner: { en: 'Good. And the security tests?', he: 'יופי. ובדיקות האבטחה?' },
          sub: 'negative',
          instr: 'ענה שעוד לא התחלת אותן.',
          target: "המבנה `haven't` + V3 (present perfect)",
          hint: "עד עכשיו זה לא קרה: `haven't` + V3, ו-`yet` בסוף.",
          explain: "עד עכשיו לא התחלת: `I haven't started them yet` — `haven't` + V3, ו-`yet` בסוף.",
          build: {
            tokens: [
              { id: 't1', t: 'I' },
              { id: 't2', t: "haven't" },
              { id: 't3', t: 'started' },
              { id: 't4', t: 'them' },
              { id: 't5', t: 'yet' },
              { id: 't6', t: "didn't" },
              { id: 't7', t: 'start' },
              { id: 't8', t: "hasn't", why: "עם `I` משתמשים ב-`haven't`, לא ב-`hasn't`.", err: 'have_agreement' },
            ],
            accept: [
              { a: "I haven't started them yet", o: 'correct_target' },
              { a: "I haven't yet started them", o: 'valid_alternative', note: 'גם נכון, בסגנון רשמי יותר.' },
              { a: "I haven't started them", o: 'valid_alternative', note: 'נכון. `yet` בסוף מוסיף את ה"עוד".' },
              {
                a: "I haven't started yet",
                o: 'valid_alternative',
                note: 'נכון — "עוד לא התחלתי". עם `them` ברור שמדובר בבדיקות: `I haven\'t started them yet`.',
              },
              {
                a: "I didn't start yet",
                o: 'target_not_used',
                note: "נפוץ באנגלית אמריקאית מדוברת. התרגיל ביקש `haven't` + V3: `I haven't started them yet`.",
              },
              {
                a: "I didn't start them yet",
                o: 'target_not_used',
                note: "נפוץ באנגלית אמריקאית מדוברת. התרגיל ביקש `haven't` + V3: `I haven't started them yet`.",
              },
              {
                a: "I didn't start them",
                o: 'target_not_used',
                note: "תקין — עבר פשוט. התרגיל ביקש `haven't` + V3: `I haven't started them yet`.",
              },
            ],
            rules: [
              {
                has: ["haven't start"],
                as: 'form_error',
                err: 'have_base',
                fb: "אחרי `haven't` בא V3: `haven't started`.",
              },
              {
                has: ["didn't started"],
                as: 'form_error',
                err: 'did_v2',
                fb: "אחרי `didn't` בא פועל בסיס: `didn't start`. ובמבנה שהתבקש: `I haven't started them yet`.",
              },
              {
                has: ['started yet them'],
                as: 'form_error',
                err: 'word_order',
                fb: "`yet` בא בסוף המשפט: `I haven't started them yet`.",
              },
            ],
            end: '.',
          },
        },
      ],
      closing: { en: 'OK. Let me know when you start them.', he: 'בסדר. תעדכן אותי כשתתחיל.' },
    },
    {
      id: 'S02-C1',
      v: 1,
      skill: 'S02',
      unit: 'S02',
      sub: 'affirmative',
      type: 'assemble',
      role: 'check',
      stage: 2,
      ctx: 'daily.home',
      fam: 'S02.parking-spot',
      goal: 'לתאר תוצאה של משהו שקרה, כשהיא נראית עכשיו',
      instr: 'קרא את הסיטואציה ובנה משפט אחד באנגלית.',
      sitEn: "You come home, and there's a car you don't know in your parking spot. Tell your neighbor what the problem is.",
      trHe: 'אתה מגיע הביתה, ובחניה שלך עומד רכב שאתה לא מכיר. ספר לשכן מה הבעיה.',
      target: PP_TARGET,
      hint: 'התוצאה נראית עכשיו: `has` + V3 של `take`.',
      explain: 'מישהו לקח, והתוצאה — החניה תפוסה עכשיו: `Someone has taken my parking spot`. `take – took – taken`.',
      tokens: [
        { id: 't1', t: 'someone' },
        { id: 't2', t: 'has' },
        { id: 't3', t: 'taken' },
        { id: 't4', t: 'my parking spot' },
        { id: 't5', t: 'took' },
        { id: 't6', t: 'have', why: '`someone` מתנהג כמו יחיד, ולכן `has`, לא `have`.', err: 'have_agreement' },
        { id: 't7', t: 'take', why: '`take` היא צורת הבסיס. אחרי `has` בא V3: `taken`.', err: 'have_base' },
      ],
      accept: [
        { a: 'Someone has taken my parking spot', o: 'correct_target' },
        {
          a: 'Someone took my parking spot',
          o: 'target_not_used',
          note: 'תקין — עבר פשוט. התרגיל ביקש `has` + V3; ה-V3 של `take` הוא `taken`.',
        },
      ],
      rules: [
        {
          has: ['taken'],
          lacks: ['has', 'have'],
          as: 'form_error',
          err: 'missing_have',
          fb: 'חסר `has`: צורת V3 (`taken`) לא עומדת לבד. `Someone has taken my parking spot`.',
        },
        {
          has: ['has took'],
          as: 'form_error',
          err: 'have_v2',
          fb: '`took` הוא עבר פשוט. אחרי `has` בא V3: `taken`.',
        },
        {
          has: ['someone take'],
          as: 'form_error',
          err: 'have_base',
          fb: 'כאן צריך `has` + V3: `Someone has taken my parking spot`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S02-C2',
      v: 2,
      skill: 'S02',
      unit: 'S02',
      sub: 'contrast',
      type: 'correct',
      role: 'check',
      stage: 3,
      ctx: 'daily.travel',
      fam: 'S02.gone-airport',
      goal: 'לומר שמישהו יצא למקום אחר ועדיין לא חזר',
      instr: FIX_INSTR,
      sitEn: 'Your colleague Omer is flying to Berlin today. He left for the airport an hour ago. His manager comes by and asks where he is.',
      trHe: 'עומר, עמית שלך, טס היום לברלין. הוא יצא לשדה התעופה לפני שעה. המנהל שלו עובר ושואל איפה הוא.',
      target: PP_TARGET,
      hint: 'הוא חזר מהשדה, או שהוא עדיין שם?',
      explain: '`has gone` — יצא ועדיין לא חזר; `has been` — היה שם וחזר. כאן: `He has gone to the airport`.',
      source: [
        { id: 's1', t: 'he' },
        { id: 's2', t: 'has' },
        {
          id: 's3',
          t: 'been',
          why: '`has been to the airport` אומר שהוא היה שם וכבר חזר. הוא יצא ועדיין לא חזר: `has gone`.',
          err: 'been_for_gone',
          as: 'meaning_mismatch',
        },
        { id: 's4', t: 'to the airport' },
      ],
      tokens: [
        { id: 't1', t: 'gone' },
        { id: 't2', t: 'went' },
        { id: 't3', t: 'have', why: 'עם `he` משתמשים ב-`has`, לא ב-`have`.', err: 'have_agreement' },
      ],
      accept: [
        { a: 'He has gone to the airport', o: 'correct_target' },
        {
          a: 'He went to the airport',
          o: 'target_not_used',
          note: 'תקין — עבר פשוט. התרגיל ביקש `has` + V3, וכאן זה `gone`: `He has gone to the airport`.',
        },
      ],
      wrong: [
        {
          a: 'He has been to the airport',
          as: 'meaning_mismatch',
          err: 'been_for_gone',
          fb: 'המשפט תקין דקדוקית, אבל `has been to the airport` אומר שהוא היה שם וכבר חזר. הוא יצא ועדיין שם, או בדרך: `He has gone to the airport`.',
        },
      ],
      rules: [
        {
          has: ['gone'],
          lacks: ['has', 'have', 'been'],
          as: 'form_error',
          err: 'missing_have',
          fb: 'חסר `has`: צורת V3 (`gone`) לא עומדת לבד. `He has gone to the airport`.',
        },
        {
          has: ['has went'],
          as: 'form_error',
          err: 'have_v2',
          fb: '`went` הוא עבר פשוט. אחרי `has` בא V3: `gone`.',
        },
        {
          has: ['he been'],
          as: 'form_error',
          err: 'missing_have',
          fb: 'חסר `has` לפני `been`. וגם `He has been to the airport` אומר שהוא היה שם וכבר חזר. כאן: `He has gone to the airport`.',
        },
        {
          has: ['been gone'],
          as: 'meaning_mismatch',
          err: 'been_gone',
          fb: '`He has been gone` אומר שהוא כבר זמן מה לא כאן, אבל לא לאן הלך. כאן: `He has gone to the airport`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S02-C3',
      v: 1,
      skill: 'S02',
      unit: 'S02',
      sub: 'question',
      type: 'assemble',
      role: 'check',
      stage: 2,
      ctx: 'daily.shopping',
      fam: 'S02.order-arrived',
      goal: 'לשאול אם משהו כבר הגיע',
      instr: 'בנה את השאלה באנגלית. לא חייבים להשתמש בכל המילים.',
      sitHe: 'הזמנת טלפון חדש מחנות לפני שבוע, ואמרו לך שיגיע תוך כמה ימים. אתה מתקשר לחנות לבדוק.',
      target: 'שאלה במבנה `have / has` + V3 (present perfect)',
      hint: 'שאלה על מה שקרה (או לא) עד עכשיו: `has` לפני הנושא, ו-`yet` בסוף.',
      explain: 'עד עכשיו — הגיע או לא: `Has my order arrived yet?` — `has` לפני הנושא, V3 אחריו, `yet` בסוף.',
      deep: 'באנגלית אמריקאית מדוברת שואלים גם `Did my order arrive yet?` — זה לא שגוי, אבל התרגיל ביקש `has` + V3.',
      tokens: [
        { id: 't1', t: 'has' },
        { id: 't2', t: 'my order' },
        { id: 't3', t: 'arrived' },
        { id: 't4', t: 'yet' },
        { id: 't5', t: 'did' },
        { id: 't6', t: 'arrive' },
        { id: 't7', t: 'have', why: '`my order` ביחיד, ולכן `has`, לא `have`.', err: 'have_agreement' },
      ],
      accept: [
        { a: 'Has my order arrived yet', o: 'correct_target' },
        { a: 'Has my order arrived', o: 'valid_alternative', note: 'נכון. `yet` בסוף מוסיף "כבר / עד עכשיו".' },
        {
          a: 'Did my order arrive yet',
          o: 'target_not_used',
          note: 'נפוץ באנגלית אמריקאית מדוברת. התרגיל ביקש `has` + V3: `Has my order arrived yet?`',
        },
        {
          a: 'Did my order arrive',
          o: 'target_not_used',
          note: 'תקין — שאלה בעבר פשוט. התרגיל ביקש `has` + V3: `Has my order arrived yet?`',
        },
      ],
      rules: [
        {
          has: ['has my order arrive'],
          as: 'form_error',
          err: 'have_base',
          fb: 'אחרי `has` בא V3: `Has my order arrived…?`',
        },
        {
          has: ['did my order arrived'],
          as: 'form_error',
          err: 'did_v2',
          fb: 'אחרי `did` בא פועל בסיס: `Did my order arrive…?` ובמבנה שהתבקש: `Has my order arrived yet?`',
        },
        {
          has: ['my order has', 'yet'],
          as: 'form_error',
          err: 'no_inversion',
          fb: 'בשאלה `has` בא לפני הנושא: `Has my order arrived yet?`',
        },
      ],
      end: '?',
    },
  ],
};
