import type { SkillPack } from '../schema';

const CHAIN = ['have / has', 'been', 'V-ing'];

export const S03: SkillPack = {
  skill: 'S03',
  lessons: [
    {
      unit: 'S03',
      title: 'כבר זמן מה: `have been + ing`',
      short:
        '`I am working on it` — אני עובד עליו עכשיו. `I have been working on it for two hours` — אני עובד עליו כבר שעתיים: זה התחיל בעבר ועדיין נמשך.',
      chain: CHAIN,
      examples: [
        { en: 'I have been working on the report for two hours.', he: 'אני עובד על הדוח כבר שעתיים.' },
        { en: 'She has been waiting since nine.', he: 'היא מחכה מתשע.' },
        { en: 'How long have you been using this software?', he: 'כמה זמן אתה כבר משתמש בתוכנה הזאת?' },
      ],
      contrast: {
        a: { en: 'I am working on the report.', he: 'אני עובד על הדוח (עכשיו).' },
        b: { en: 'I have been working on the report for two hours.', he: 'אני עובד על הדוח כבר שעתיים.' },
        note: 'בעברית אומרים "אני עובד" בשני המקרים. באנגלית, ברגע שמוסיפים כמה זמן זה נמשך עד עכשיו (`for`, `since`, `how long`), עוברים ל-present perfect — בדרך כלל `have been + ing`.',
      },
      deep:
        '• שלוש חוליות, ואף אחת לא נשמטת: `have / has` (לפי הנושא: `I / you / we / they have`, `he / she / it has`) ← `been` ← פועל עם ing.\n' +
        '• המבנה מתאר פעולה שהתחילה בעבר ונמשכת עד עכשיו — או שהסתיימה ממש עכשיו ורואים את התוצאה: `I\'m tired — I\'ve been running.`\n' +
        '• עם פעלי מצב כמו `know`, `believe`, `own` בדרך כלל לא משתמשים ב-ing: `I have known her for years`, ולא `have been knowing`.\n' +
        '• עם `work`, `live`, `teach` שתי הצורות טבעיות למשהו שנמשך עד היום: `I have worked here for three years` תקין בדיוק כמו `I have been working here for three years`.\n' +
        '• `has been approved` נראה דומה אבל הוא מבנה אחר — סביל (מה קיבל את הפעולה). אחרי `been` לא תמיד בא ing; נלמד את זה בנפרד.',
      pitfalls: [
        '`I have working…` — חסר `been`.',
        '`I am working here for three years` — למשך עד עכשיו: `have been working` (או `have worked`).',
        '`I have been work…` — במבנה המתמשך אחרי `been` בא פועל עם ing.',
      ],
    },
  ],
  examples: {
    S03: [
      { en: 'We have been talking about this plan all week.', he: 'אנחנו מדברים על התוכנית הזאת כל השבוע.' },
      { en: 'He has been teaching English since 2019.', he: 'הוא מלמד אנגלית מ-2019.' },
      { en: 'It has been raining since this morning.', he: 'יורד גשם מהבוקר.' },
      { en: "I'm tired because I've been cleaning the house.", he: 'אני עייף כי ניקיתי את הבית (עד לפני רגע).' },
    ],
  },
  items: [
    {
      id: 'S03-01',
      v: 1,
      skill: 'S03',
      unit: 'S03',
      sub: 'affirmative',
      type: 'correct',
      role: 'practice',
      stage: 1,
      ctx: 'work.report',
      fam: 'S03.report-two-hours',
      goal: 'לומר שאתה עובד על הדוח כבר שעתיים',
      instr: 'בדוק את המשפט. אם יש טעות — גע במילה או ברווח ובחר תיקון; אם הוא תקין, בחר "אין צורך בתיקון".',
      sitHe: 'התחלת לעבוד על הדוח לפני שעתיים, ואתה עדיין עובד עליו.',
      target: 'המבנה המתמשך `have been + V-ing`',
      scaffold: CHAIN,
      hint: 'חסרה מילה אחת בין `have` ל-`working`.',
      explain:
        'פעולה שהתחילה בעבר ועדיין נמשכת: `have / has` + `been` + פועל עם ing. בלי `been` המבנה אינו תקין.',
      deep: 'שלוש החוליות תמיד מופיעות יחד: `have` מסמן "עד עכשיו", `been` מחבר, ו-`working` מראה שהפעולה נמשכת. השמטה של `been` היא הטעות הנפוצה ביותר במבנה הזה.',
      source: [
        { id: 's1', t: 'I' },
        { id: 's2', t: 'have' },
        { id: 's3', t: 'working' },
        { id: 's4', t: 'on the report' },
        { id: 's5', t: 'for two hours' },
      ],
      tokens: [
        { id: 't1', t: 'been' },
        {
          id: 't2',
          t: 'am',
          why: '`am` לא מתחבר ל-`have`, ו-`am working` מתאר רק את עכשיו. למשך עד עכשיו: `have been working`.',
          err: 'present_for_duration',
        },
        {
          id: 't3',
          t: 'being',
          why: '`being` לא מתאים כאן. במבנה המתמשך של present perfect משתמשים ב-`been`: `have been working`.',
          err: 'being_for_been',
        },
        { id: 't4', t: 'worked' },
      ],
      accept: [
        { a: 'I have been working on the report for two hours', o: 'correct_target' },
        {
          a: 'I have worked on the report for two hours',
          o: 'target_not_used',
          note: 'תקין — `have worked` הוא present perfect. התרגיל ביקש את המבנה המתמשך, שמדגיש שהעבודה עדיין נמשכת.',
        },
      ],
      wrong: [
        {
          a: 'I have working on the report for two hours',
          as: 'form_error',
          err: 'missing_been',
          fb: 'בין `have` ל-`working` חסרה המילה `been`. המבנה המלא: `have been working`.',
        },
        {
          a: 'I am working on the report for two hours',
          as: 'meaning_mismatch',
          err: 'present_for_duration',
          fb: '`I am working on the report for two hours` אפשרי רק כתוכנית ("אעבוד עליו שעתיים"). כדי לומר שזה כבר נמשך שעתיים עד עכשיו: `have been working`.',
        },
      ],
      rules: [
        {
          has: ['been worked'],
          as: 'form_error',
          err: 'been_v3',
          fb: 'אחרי `been` במבנה המתמשך בא פועל עם ing: `been working`. (`been worked` הוא מבנה סביל — לא מה שצריך כאן.)',
        },
      ],
      end: '.',
    },
    {
      id: 'S03-02',
      v: 2,
      skill: 'S03',
      unit: 'S03',
      sub: 'affirmative',
      type: 'assemble',
      role: 'practice',
      stage: 1,
      ctx: 'work.clinic',
      fam: 'S03.waiting-twenty',
      goal: 'לומר כמה זמן מישהי כבר מחכה',
      instr: 'בנה את המשפט באנגלית. לא חייבים להשתמש בכל המילים.',
      promptHe: 'היא מחכה כבר עשרים דקות.',
      sitHe: 'בחדר ההמתנה של המרפאה. מישהי התחילה לחכות לפני עשרים דקות ועדיין מחכה.',
      target: 'המבנה המתמשך `has been + V-ing`',
      scaffold: CHAIN,
      hint: 'שלוש חוליות לפני הזמן: `has` ← `been` ← פועל עם ing.',
      explain: 'התחילה לחכות לפני עשרים דקות ועדיין מחכה: `has been waiting`. עם `she` בא `has`.',
      tokens: [
        { id: 't1', t: 'she' },
        { id: 't2', t: 'has' },
        { id: 't3', t: 'been' },
        { id: 't4', t: 'waiting' },
        { id: 't5', t: 'for' },
        { id: 't6', t: 'twenty minutes' },
        { id: 't7', t: 'have', why: 'עם `she` משתמשים ב-`has`, לא ב-`have`.', err: 'have_agreement' },
        {
          id: 't8',
          t: 'since',
          why: '`since` בא לפני נקודת התחלה (`since nine`). לפרק זמן כמו עשרים דקות: `for`.',
          err: 'since_period',
        },
        {
          id: 't9',
          t: 'is',
          why: '`is waiting` מתאר רק את מה שקורה עכשיו. כדי לומר "כבר עשרים דקות" צריך `has been waiting`.',
          err: 'present_for_duration',
        },
        { id: 't10', t: 'waited' },
      ],
      accept: [
        { a: 'She has been waiting for twenty minutes', o: 'correct_target' },
        {
          a: 'She has waited for twenty minutes',
          o: 'target_not_used',
          note: 'תקין — present perfect. התרגיל ביקש את המבנה המתמשך, שמדגיש שההמתנה עדיין נמשכת.',
        },
        {
          a: 'She has been waiting twenty minutes',
          o: 'valid_alternative',
          note: 'גם נכון: בדיבור אפשר להשמיט את `for` לפני פרק זמן. הצורה המלאה: `for twenty minutes`.',
        },
      ],
      wrong: [
        {
          a: 'She is waiting for twenty minutes',
          as: 'meaning_mismatch',
          err: 'present_for_duration',
          fb: '`She is waiting for twenty minutes` אפשרי רק כתוכנית ("היא תחכה עשרים דקות"). כדי לומר שהיא מחכה כבר עשרים דקות: `She has been waiting for twenty minutes`.',
        },
      ],
      rules: [
        {
          has: ['is', 'been'],
          as: 'form_error',
          err: 'double_aux',
          fb: '`is` ו-`has been` לא הולכים יחד: `She has been waiting`.',
        },
        {
          has: ['has waiting'],
          lacks: ['been'],
          as: 'form_error',
          err: 'missing_been',
          fb: 'בין `has` ל-`waiting` חסרה המילה `been`: `has been waiting`.',
        },
        {
          has: ['been waited'],
          as: 'form_error',
          err: 'been_v3',
          fb: 'אחרי `been` במבנה המתמשך בא פועל עם ing: `been waiting`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S03-03',
      v: 2,
      skill: 'S03',
      unit: 'S03',
      sub: 'affirmative',
      type: 'assemble',
      role: 'practice',
      stage: 2,
      ctx: 'work.software',
      fam: 'S03.fixing-morning',
      goal: 'לספר שהצוות עובד על התקלה כל הבוקר',
      instr: 'בנה משפט אחד באנגלית שמתאר את המצב.',
      sitHe: 'אנשי המחשוב התחילו לתקן את המערכת בבוקר. עכשיו צהריים, והם עדיין עובדים על זה.',
      hint: 'הפעולה התחילה בבוקר ועדיין נמשכת.',
      explain: 'התחילו בבוקר ועדיין עובדים: `have been fixing`. `all morning` מדגיש את משך הפעולה — מהבוקר ועד עכשיו.',
      deep: '`all morning`, `all day`, `all week` מתאימים מאוד למבנה המתמשך: הם מדגישים את משך הפעולה עד הרגע הזה.',
      tokens: [
        { id: 't1', t: 'they' },
        { id: 't2', t: 'have' },
        { id: 't3', t: 'been' },
        { id: 't4', t: 'fixing' },
        { id: 't5', t: 'the system' },
        { id: 't6', t: 'all morning' },
        { id: 't7', t: 'has', why: 'עם `they` משתמשים ב-`have`, לא ב-`has`.', err: 'have_agreement' },
        {
          id: 't8',
          t: 'are',
          why: '`are fixing` מתאר רק את מה שקורה עכשיו. `all morning` — מהבוקר ועד עכשיו — מחייב `have been fixing`.',
          err: 'present_for_duration',
        },
        {
          id: 't9',
          t: 'fixed',
          why: '`fixed` אומר שהתיקון הושלם (או, אחרי `been`, שהמערכת תוקנה — סביל). כשהם עדיין עובדים על זה: `have been fixing`.',
          err: 'v3_for_ongoing',
          as: 'meaning_mismatch',
        },
      ],
      accept: [{ a: 'They have been fixing the system all morning', o: 'correct_target' }],
      wrong: [
        {
          a: 'They are fixing the system all morning',
          as: 'meaning_mismatch',
          err: 'present_for_duration',
          fb: 'המשפט נשמע כמו תוכנית ("הם יתקנו את המערכת כל הבוקר"). כשהם התחילו בבוקר ועדיין עובדים: `They have been fixing the system all morning`.',
        },
      ],
      rules: [
        {
          has: ['have fixing'],
          lacks: ['been'],
          as: 'form_error',
          err: 'missing_been',
          fb: 'בין `have` ל-`fixing` חסרה המילה `been`: `have been fixing`.',
        },
        {
          has: ['been fixed the system'],
          as: 'form_error',
          err: 'been_v3',
          fb: 'אחרי `been` במבנה המתמשך בא פועל עם ing: `have been fixing the system`. (`been fixed` הוא סביל — מה תוקן — ואחריו לא בא מושא.)',
        },
        {
          has: ['been fixed'],
          as: 'meaning_mismatch',
          err: 'passive_for_active',
          fb: '`has been fixed` הוא סביל: משהו תוקן — כלומר התיקון הסתיים. הם עדיין עובדים על זה: `They have been fixing the system all morning`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S03-04',
      v: 1,
      skill: 'S03',
      unit: 'S03',
      sub: 'contrast',
      type: 'correct',
      role: 'practice',
      stage: 3,
      ctx: 'work.job',
      fam: 'S03.working-here-years',
      goal: 'לומר כמה שנים אתה עובד במקום',
      instr: 'בדוק את המשפט. אם יש טעות — תקן; אם הוא תקין, בחר "אין צורך בתיקון".',
      sitHe: 'התחלת לעבוד במקום לפני שלוש שנים ואתה עדיין עובד שם.',
      hint: 'כמה זמן זה נמשך עד עכשיו? `am` מתאר רק את עכשיו.',
      explain:
        '"שלוש שנים עד היום" דורש present perfect: `I have been working here for three years` או `I have worked here for three years`.',
      deep: 'זו אחת ההעברות הנפוצות מעברית: "אני עובד כאן שלוש שנים" נאמר בהווה. באנגלית ההווה (`I am working`) לא יכול לשאת "כבר שלוש שנים". עם `work` ו-`live` שתי צורות ה-perfect מתאימות.',
      source: [
        { id: 's1', t: 'I' },
        {
          id: 's2',
          t: 'am',
          why: '`am working` מתאר מה קורה עכשיו. למשך עד עכשיו צריך `have been working` (או `have worked`).',
          err: 'present_for_duration',
        },
        { id: 's3', t: 'working' },
        { id: 's4', t: 'here' },
        { id: 's5', t: 'for three years' },
      ],
      tokens: [
        { id: 't1', t: 'have' },
        { id: 't2', t: 'been' },
        { id: 't3', t: 'worked' },
        {
          id: 't4',
          t: 'since',
          why: '`since` בא לפני נקודת התחלה (`since 2023`). לפרק זמן: `for three years`.',
          err: 'since_period',
        },
      ],
      accept: [
        { a: 'I have been working here for three years', o: 'correct_target' },
        {
          a: 'I have worked here for three years',
          o: 'valid_alternative',
          note: 'גם נכון. עם `work` ו-`live` שתי הצורות מתאימות למשהו שנמשך עד היום.',
        },
      ],
      wrong: [
        {
          a: 'I am working here for three years',
          as: 'meaning_mismatch',
          err: 'present_for_duration',
          fb: 'בעברית אומרים "אני עובד כאן שלוש שנים" בהווה. באנגלית `I am working here for three years` אפשרי רק כתוכנית לתקופה (חוזה לשלוש שנים). כדי לומר שזה כבר נמשך שלוש שנים: `I have been working here for three years` (או `I have worked…`).',
        },
      ],
      rules: [
        {
          has: ['am', 'been'],
          as: 'form_error',
          err: 'double_aux',
          fb: '`am` ו-`been` לא הולכים יחד כאן. הסר את `am` ובנה `I have been working`.',
        },
        {
          has: ['am', 'have'],
          as: 'form_error',
          err: 'double_aux',
          fb: '`am` ו-`have` לא הולכים יחד. המבנה: `I have been working`.',
        },
        {
          has: ['have working'],
          lacks: ['been'],
          as: 'form_error',
          err: 'missing_been',
          fb: 'בין `have` ל-`working` חסרה המילה `been`: `have been working`.',
        },
        {
          has: ['been worked'],
          as: 'form_error',
          err: 'been_v3',
          fb: 'אחרי `been` במבנה המתמשך בא פועל עם ing: `been working`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S03-D1',
      v: 2,
      skill: 'S03',
      unit: 'S03',
      sub: 'dialogue',
      type: 'dialogue',
      role: 'practice',
      stage: 2,
      ctx: 'work.report',
      fam: 'S03.dialogue-quarterly',
      goal: 'לענות לעמיתה על הדוח שעדיין לא גמרת',
      instr: 'ענה למאיה בכל תור.',
      partnerName: 'Maya',
      setupHe: 'מאיה, עמיתה לעבודה, עוברת ליד השולחן שלך. אתה באמצע העבודה על הדוח הרבעוני.',
      hint: 'בתור הראשון — מה קורה עכשיו. בתור השני — כמה זמן זה נמשך עד עכשיו.',
      explain: 'עכשיו: `I am still working on it`. כמה זמן עד עכשיו: `I have been working on it for three hours`.',
      turns: [
        {
          partner: { en: 'Hi! Are you done with the quarterly report?', he: 'היי! סיימת את הדוח הרבעוני?' },
          unit: 'S01',
          sub: 'affirmative',
          instr: 'ענה שלא — אתה עדיין עובד עליו.',
          hint: 'מה שקורה עכשיו: `am` + פועל עם ing.',
          explain: 'עכשיו, ברגע זה: `I am still working on it`.',
          build: {
            tokens: [
              { id: 't1', t: 'I' },
              { id: 't2', t: 'am' },
              { id: 't3', t: 'still' },
              { id: 't4', t: 'working' },
              { id: 't5', t: 'on it' },
              {
                id: 't6',
                t: 'work',
                why: '`work` בלי ing מתאר הרגל או תפקיד קבוע, לא פעולה שקורה ממש עכשיו. כאן: `I am still working on it`.',
                err: 'simple_for_now',
                as: 'meaning_mismatch',
              },
              {
                id: 't7',
                t: 'have',
                why: '`have` לבד לפני `working` אינו מבנה תקין. למה שקורה עכשיו: `I am still working`.',
                err: 'have_without_been',
              },
            ],
            accept: [
              { a: 'I am still working on it', o: 'correct_target' },
              {
                a: 'I still am working on it',
                o: 'valid_alternative',
                note: 'תקין, עם הדגשה. הסדר הרגיל: `I am still working on it`.',
              },
              {
                a: 'I am working on it',
                o: 'valid_alternative',
                note: 'גם נכון. `still` מוסיף "עדיין" — שזה עוד לא נגמר: `I am still working on it`.',
              },
            ],
            rules: [
              {
                has: ['still working'],
                lacks: ['am'],
                as: 'form_error',
                err: 'missing_be',
                fb: 'חסר `am`: לפני פועל עם ing צריך `am / is / are`. כאן: `I am still working on it`.',
              },
              {
                has: ['am', 'work'],
                as: 'form_error',
                err: 'be_base',
                fb: 'אחרי `am` בא פועל עם ing, לא צורת הבסיס: `I am still working on it`.',
              },
            ],
            end: '.',
          },
        },
        {
          partner: { en: 'Still? You look tired.', he: 'עדיין? אתה נראה עייף.' },
          instr: 'ספר לה שאתה עובד עליו כבר שלוש שעות (התחלת בשמונה).',
          hint: 'כמה זמן עד עכשיו: `have` ← `been` ← ing, ואחר כך `for` או `since`.',
          explain:
            'התחלת בשמונה ואתה עדיין עובד: `I have been working on it for three hours` — או `since eight`.',
          build: {
            tokens: [
              { id: 't1', t: 'I' },
              { id: 't2', t: 'have' },
              { id: 't3', t: 'been' },
              { id: 't4', t: 'working' },
              { id: 't5', t: 'on it' },
              { id: 't6', t: 'for' },
              { id: 't7', t: 'since' },
              { id: 't8', t: 'three hours' },
              { id: 't9', t: 'eight' },
              {
                id: 't10',
                t: 'am',
                why: '`am working` מתאר רק את עכשיו. כדי לומר כמה זמן זה נמשך עד עכשיו: `have been working`.',
                err: 'present_for_duration',
              },
            ],
            accept: [
              { a: 'I have been working on it for three hours', o: 'correct_target' },
              { a: 'I have been working on it since eight', o: 'correct_target' },
              {
                a: 'I have been working for three hours',
                o: 'valid_alternative',
                note: 'גם נכון: מההקשר ברור שמדובר בדוח, גם בלי `on it`.',
              },
              {
                a: 'I have been working since eight',
                o: 'valid_alternative',
                note: 'גם נכון: מההקשר ברור שמדובר בדוח, גם בלי `on it`.',
              },
              {
                a: 'I have been working on it three hours',
                o: 'valid_alternative',
                note: 'גם נכון: בדיבור אפשר להשמיט את `for` לפני פרק זמן. הצורה המלאה: `for three hours`.',
              },
            ],
            wrong: [
              {
                a: 'I am working on it for three hours',
                as: 'meaning_mismatch',
                err: 'present_for_duration',
                fb: '`I am working on it for three hours` נשמע כמו תוכנית ("אעבוד עליו שלוש שעות"). כדי לומר שזה כבר נמשך שלוש שעות עד עכשיו: `I have been working on it for three hours`.',
              },
            ],
            rules: [
              {
                has: ['for eight'],
                as: 'form_error',
                err: 'for_point',
                fb: '`for` בא לפני פרק זמן (`for three hours`). לפני שעת התחלה (`eight`) משתמשים ב-`since`.',
              },
              {
                has: ['since three hours'],
                as: 'form_error',
                err: 'since_period',
                fb: '`since` בא לפני נקודת התחלה (`since eight`). לפרק זמן: `for three hours`.',
              },
              {
                has: ['have working'],
                lacks: ['been'],
                as: 'form_error',
                err: 'missing_been',
                fb: 'בין `have` ל-`working` חסרה המילה `been`: `have been working`.',
              },
            ],
            end: '.',
          },
        },
      ],
      closing: { en: 'Take a short break. You still have until tomorrow.', he: 'קח הפסקה קצרה. יש לך עוד זמן עד מחר.' },
    },
    {
      id: 'S03-C1',
      v: 2,
      skill: 'S03',
      unit: 'S03',
      sub: 'affirmative',
      type: 'assemble',
      role: 'check',
      stage: 2,
      ctx: 'daily.home',
      fam: 'S03.neighbors-kitchen',
      goal: 'לספר על שיפוץ שעדיין נמשך',
      instr: 'בנה משפט אחד באנגלית.',
      sitHe: 'השכנים התחילו לשפץ את המטבח שלהם ביוני, והשיפוץ עדיין לא נגמר.',
      hint: 'התחיל ביוני ועדיין נמשך — `have been` + ing, ואחר כך נקודת ההתחלה.',
      explain: 'התחילו ביוני ועדיין משפצים: `The neighbors have been renovating their kitchen since June`.',
      tokens: [
        { id: 't1', t: 'the neighbors' },
        { id: 't2', t: 'have' },
        { id: 't3', t: 'been' },
        { id: 't4', t: 'renovating' },
        { id: 't5', t: 'their kitchen' },
        { id: 't6', t: 'since' },
        { id: 't7', t: 'June' },
        {
          id: 't8',
          t: 'has',
          why: '`the neighbors` ברבים, ולכן `have`, לא `has`.',
          err: 'have_agreement',
        },
        {
          id: 't9',
          t: 'for',
          why: '`for` בא לפני פרק זמן (`for three months`). לפני נקודת התחלה כמו `June`: `since`.',
          err: 'for_point',
        },
        {
          id: 't10',
          t: 'are',
          why: '`are renovating` מתאר רק את עכשיו. "מיוני ועד היום" מחייב `have been renovating`.',
          err: 'present_for_duration',
        },
        {
          id: 't11',
          t: 'renovated',
          why: '`renovated` נשמע כאילו השיפוץ הסתיים. כשהוא עדיין נמשך: `have been renovating`.',
          err: 'v3_for_ongoing',
          as: 'meaning_mismatch',
        },
      ],
      accept: [{ a: 'The neighbors have been renovating their kitchen since June', o: 'correct_target' }],
      rules: [
        {
          has: ['their kitchen has been'],
          as: 'meaning_mismatch',
          err: 'passive_for_active',
          fb: 'כאן הנושא הוא `their kitchen`, והמשפט מספר מה קרה למטבח — לא מה שהשכנים עושים. השיפוץ עדיין נמשך, והשכנים הם שמשפצים: `The neighbors have been renovating their kitchen since June`.',
        },
        {
          has: ['been renovated their kitchen'],
          as: 'form_error',
          err: 'been_v3',
          fb: 'אחרי `been` במבנה המתמשך בא פועל עם ing: `have been renovating their kitchen`. (`been renovated` הוא סביל, ואחריו לא בא מושא.)',
        },
        {
          has: ['have renovating'],
          lacks: ['been'],
          as: 'form_error',
          err: 'missing_been',
          fb: 'בין `have` ל-`renovating` חסרה המילה `been`: `have been renovating`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S03-C2',
      v: 1,
      skill: 'S03',
      unit: 'S03',
      sub: 'affirmative',
      type: 'assemble',
      role: 'check',
      stage: 2,
      ctx: 'daily.health',
      fam: 'S03.gym-january',
      goal: 'לספר על הרגל שהתחיל בינואר ועדיין נמשך',
      instr: 'קרא את הסיטואציה ובנה משפט אחד באנגלית.',
      sitEn: 'You started going to the gym in January. You still go every week. Tell a friend.',
      trHe: 'התחלת ללכת לחדר כושר בינואר ואתה עדיין הולך כל שבוע. ספר לחבר.',
      hint: 'ממתי ועד עכשיו: `have been` + ing, ואחר כך `since`.',
      explain: 'הרגל שהתחיל בינואר ועדיין נמשך: `I have been going to the gym since January`.',
      tokens: [
        { id: 't1', t: 'I' },
        { id: 't2', t: 'have' },
        { id: 't3', t: 'been' },
        { id: 't4', t: 'going' },
        { id: 't5', t: 'to the gym' },
        { id: 't6', t: 'since' },
        { id: 't7', t: 'January' },
        {
          id: 't8',
          t: 'for',
          why: '`for` בא לפני פרק זמן (`for eight months`). לפני נקודת התחלה כמו `January`: `since`.',
          err: 'for_point',
        },
        {
          id: 't9',
          t: 'went',
          why: '`went` הוא עבר פשוט — משהו שהסתיים. `since January` (עד היום) מחייב `have been going`.',
          err: 'past_for_duration',
        },
        {
          id: 't10',
          t: 'am',
          why: '`am going` מתאר רק את עכשיו (או תוכנית). "מינואר ועד היום" מחייב `have been going`.',
          err: 'present_for_duration',
        },
      ],
      accept: [{ a: 'I have been going to the gym since January', o: 'correct_target' }],
      rules: [
        {
          has: ['have going'],
          lacks: ['been'],
          as: 'form_error',
          err: 'missing_been',
          fb: 'בין `have` ל-`going` חסרה המילה `been`: `have been going`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S03-05',
      v: 2,
      skill: 'S03',
      unit: 'S03',
      sub: 'affirmative',
      type: 'assemble',
      role: 'practice',
      stage: 1,
      ctx: 'work.municipality',
      fam: 'S03.city-road',
      goal: 'לומר ממתי העירייה עובדת על הכביש',
      instr: 'בנה את המשפט באנגלית. לא חייבים להשתמש בכל המילים.',
      promptHe: 'העירייה מתקנת את הכביש מאז מאי.',
      target: 'המבנה המתמשך `has been + V-ing`',
      scaffold: CHAIN,
      hint: '`the city` הוא נושא ביחיד, ולכן `has`. אחרי `been` — פועל עם ing, ואחר כך ממתי.',
      explain: 'התחילו במאי ועדיין מתקנים: `The city has been repairing the road since May`.',
      deep: 'שים לב: `The road has been repaired` אומר שהכביש תוקן — זה מבנה סביל, והוא מספר שהעבודה הסתיימה. כאן העירייה עושה את הפעולה והיא עדיין נמשכת, ולכן `has been repairing`.',
      tokens: [
        { id: 't1', t: 'the city' },
        { id: 't2', t: 'has' },
        { id: 't3', t: 'been' },
        { id: 't4', t: 'repairing' },
        { id: 't5', t: 'the road' },
        { id: 't6', t: 'since' },
        { id: 't7', t: 'May' },
        { id: 't8', t: 'have', why: '`the city` הוא נושא ביחיד, ולכן `has`, לא `have`.', err: 'have_agreement' },
        {
          id: 't9',
          t: 'for',
          why: '`for` בא לפני פרק זמן (`for three months`). לפני נקודת התחלה כמו `May`: `since`.',
          err: 'for_point',
        },
        {
          id: 't10',
          t: 'repaired',
          why: '`repaired` מסמן פעולה שהושלמה. העבודה על הכביש עדיין נמשכת: `has been repairing`.',
          err: 'v3_for_ongoing',
          as: 'meaning_mismatch',
        },
      ],
      accept: [{ a: 'The city has been repairing the road since May', o: 'correct_target' }],
      rules: [
        {
          has: ['has repairing'],
          lacks: ['been'],
          as: 'form_error',
          err: 'missing_been',
          fb: 'בין `has` ל-`repairing` חסרה המילה `been`: `has been repairing`.',
        },
        {
          has: ['been repaired the road'],
          as: 'form_error',
          err: 'been_v3',
          fb: 'אחרי `been` במבנה המתמשך בא פועל עם ing: `has been repairing the road`. (`been repaired` הוא סביל — משהו תוקן — ואחריו לא בא מושא כמו `the road`.)',
        },
        {
          has: ['been repaired'],
          as: 'meaning_mismatch',
          err: 'passive_for_active',
          fb: '`has been repaired` הוא סביל: משהו תוקן — כלומר העבודה הסתיימה. העירייה עדיין עובדת, ולכן `has been repairing`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S03-06',
      v: 1,
      skill: 'S03',
      unit: 'S03',
      sub: 'negative',
      type: 'transform',
      role: 'practice',
      stage: 2,
      ctx: 'daily.health',
      fam: 'S03.sleeping-well',
      goal: 'לומר שבזמן האחרון אתה לא ישן טוב',
      instr: 'הפוך את המשפט לשלילה.',
      target: 'שלילה במבנה `have been + V-ing`',
      fromLabel: 'חיוב',
      toLabel: 'שלילה',
      hint: 'השלילה נצמדת לחוליה הראשונה: `have` ← `haven\'t`.',
      explain: 'בשלילה, `not` בא אחרי `have`: `I haven\'t been sleeping well lately`.',
      deep: 'כשיש כמה פעלי עזר, השלילה תמיד באה אחרי הראשון: `I haven\'t been sleeping`, `She hasn\'t been working`. אין צורך ב-`don\'t`: כבר יש פועל עזר.',
      source: [
        { id: 's1', t: 'I' },
        { id: 's2', t: 'have' },
        { id: 's3', t: 'been' },
        { id: 's4', t: 'sleeping' },
        { id: 's5', t: 'well' },
        { id: 's6', t: 'lately' },
      ],
      sourceEnd: '.',
      tokens: [
        { id: 't1', t: "haven't" },
        { id: 't2', t: 'not' },
        {
          id: 't3',
          t: "don't",
          why: '`don\'t` לא מתאים כאן: יש כבר פועל עזר (`have`), והשלילה נצמדת אליו: `I haven\'t been sleeping`.',
          err: 'do_with_perfect',
        },
        {
          id: 't4',
          t: "didn't",
          why: '`didn\'t` שייך לעבר פשוט. כאן השלילה נצמדת ל-`have`: `I haven\'t been sleeping`.',
          err: 'do_with_perfect',
        },
      ],
      accept: [
        { a: "I haven't been sleeping well lately", o: 'correct_target' },
        { a: 'I have not been sleeping well lately', o: 'correct_target' },
      ],
      wrong: [
        {
          a: 'I have been sleeping well lately',
          as: 'target_not_used',
          err: 'not_transformed',
          fb: 'המשפט תקין, אבל הוא עדיין בחיוב. התבקשת להפוך אותו לשלילה.',
        },
      ],
      rules: [
        {
          has: ['been not'],
          as: 'form_error',
          err: 'not_position',
          fb: 'השלילה באה אחרי פועל העזר הראשון: `I have not been sleeping` או `I haven\'t been sleeping`.',
        },
        {
          has: ["haven't", 'have'],
          as: 'form_error',
          err: 'double_aux',
          fb: '`haven\'t` מחליף את `have` — אל תשאיר את שניהם: `I haven\'t been sleeping`.',
        },
        {
          has: ['sleeping'],
          lacks: ['been'],
          as: 'form_error',
          err: 'missing_been',
          fb: 'אל תוריד את `been`: `I haven\'t been sleeping`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S03-07',
      v: 1,
      skill: 'S03',
      unit: 'S03',
      sub: 'stative',
      type: 'discriminate',
      role: 'practice',
      stage: 3,
      ctx: 'daily.family',
      fam: 'S03.know-dana',
      goal: 'לומר כמה זמן אתה מכיר מישהי',
      instr: 'איזה משפט מתאים לסיטואציה?',
      sitHe: 'הכרת את דנה לפני עשר שנים, ואתם עדיין חברים.',
      multi: false,
      hint: '`know` הוא פועל מצב: בדרך כלל לא מוסיפים לו ing.',
      explain: 'עם פועל מצב כמו `know` משתמשים ב-present perfect הרגיל: `I have known Dana for ten years`.',
      deep: 'פעלי מצב (`know`, `believe`, `own`, `need`) מתארים מצב ולא פעולה, ולכן בדרך כלל לא באים עם ing — גם לא במבנה `have been + ing`. למשך עד עכשיו: `have` + V3.',
      options: [
        { id: 'a', en: 'I have known Dana for ten years.', v: 'fits', why: 'נכון: פועל מצב, ומשך עד עכשיו — `have known`.' },
        {
          id: 'b',
          en: 'I have been knowing Dana for ten years.',
          v: 'ungrammatical',
          why: '`know` הוא פועל מצב, ולכן לא `been knowing`.',
          err: 'stative_ing',
        },
        {
          id: 'c',
          en: 'I know Dana for ten years.',
          v: 'ungrammatical',
          why: 'כמו בעברית ("אני מכיר אותה עשר שנים") — אבל באנגלית משך עד עכשיו דורש `have known`.',
          err: 'present_for_duration',
        },
        {
          id: 'd',
          en: 'I knew Dana for ten years.',
          v: 'other_meaning',
          why: 'תקין, אבל `knew` בעבר פשוט רומז שהקשר נגמר — ואתם עדיין חברים.',
          err: 'past_for_duration',
        },
      ],
    },
    {
      id: 'S03-08',
      v: 1,
      skill: 'S03',
      unit: 'S03',
      sub: 'just_stopped',
      type: 'assemble',
      role: 'practice',
      stage: 2,
      ctx: 'daily.travel',
      fam: 'S03.street-wet',
      goal: 'להסביר למה הרחוב רטוב',
      instr: 'קרא את הסיטואציה ובנה משפט אחד.',
      sitEn: 'You look outside. The street is wet, but it is not raining now.',
      trHe: 'אתה מסתכל החוצה. הרחוב רטוב, אבל עכשיו לא יורד גשם.',
      target: 'המבנה המתמשך `has been + V-ing`',
      hint: 'פעולה שנמשכה עד לפני רגע, ורואים את התוצאה שלה.',
      explain: '`It has been raining` — הגשם נמשך עד לא מזמן, ורואים את התוצאה: הרחוב רטוב.',
      deep: 'המבנה המתמשך לא חייב לתאר משהו שקורה ממש עכשיו. הוא מתאים גם לפעולה שנמשכה והסתיימה זה עתה, כשרואים את התוצאה שלה: `I\'m tired — I\'ve been running`.',
      tokens: [
        { id: 't1', t: 'it' },
        { id: 't2', t: 'has' },
        { id: 't3', t: 'been' },
        { id: 't4', t: 'raining' },
        {
          id: 't5',
          t: 'is',
          why: '`is` + ing אומר שזה קורה עכשיו — אבל הגשם כבר הפסיק. למה שנמשך עד לפני רגע: `has been raining`.',
          err: 'present_for_now',
          as: 'meaning_mismatch',
        },
        { id: 't6', t: 'have', why: 'עם `it` משתמשים ב-`has`, לא ב-`have`.', err: 'have_agreement' },
        { id: 't7', t: 'rained' },
      ],
      accept: [
        { a: 'It has been raining', o: 'correct_target' },
        {
          a: 'It has rained',
          o: 'target_not_used',
          note: 'תקין — present perfect. התרגיל ביקש את המבנה המתמשך, שמדגיש שהגשם נמשך זמן מה עד לפני רגע.',
        },
        {
          a: 'It rained',
          o: 'target_not_used',
          note: 'תקין — עבר פשוט. המבנה המתמשך מחבר את הגשם לתוצאה שרואים עכשיו.',
        },
      ],
      wrong: [
        {
          a: 'It is raining',
          as: 'meaning_mismatch',
          err: 'present_for_now',
          fb: '`It is raining` אומר שיורד גשם עכשיו — אבל הגשם כבר הפסיק. למה שנמשך עד לפני רגע: `It has been raining`.',
        },
      ],
      rules: [
        {
          has: ['has raining'],
          lacks: ['been'],
          as: 'form_error',
          err: 'missing_been',
          fb: 'בין `has` ל-`raining` חסרה המילה `been`: `has been raining`.',
        },
        {
          has: ['is', 'been'],
          as: 'form_error',
          err: 'double_aux',
          fb: '`is` ו-`has been` לא הולכים יחד: `It has been raining`.',
        },
        {
          has: ['is rained'],
          as: 'form_error',
          err: 'wrong_aux',
          fb: '`is rained` אינו מבנה תקין כאן. למה שנמשך עד לפני רגע: `It has been raining`.',
        },
        {
          has: ['been rained'],
          as: 'form_error',
          err: 'been_v3',
          fb: 'אחרי `been` במבנה המתמשך בא פועל עם ing: `been raining`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S03-09',
      v: 2,
      skill: 'S03',
      unit: 'S03',
      sub: 'affirmative',
      type: 'assemble',
      role: 'practice',
      stage: 2,
      ctx: 'work.clinic',
      fam: 'S03.phone-ringing',
      goal: 'לתאר משהו שנמשך כל הבוקר',
      instr: 'בנה משפט אחד באנגלית.',
      sitHe: 'במרפאה הטלפון מצלצל בלי הפסקה מהבוקר, והוא עדיין לא נרגע.',
      hint: 'התחיל בבוקר ועדיין נמשך. מה באנגלית מחליף את "מהבוקר"?',
      explain: 'מהבוקר ועד עכשיו: `The phone has been ringing all morning`.',
      tokens: [
        { id: 't1', t: 'the phone' },
        { id: 't2', t: 'has' },
        { id: 't3', t: 'been' },
        { id: 't4', t: 'ringing' },
        { id: 't5', t: 'all morning' },
        {
          id: 't6',
          t: 'is',
          why: '`is ringing` מתאר רק את עכשיו. "כל הבוקר" — עד עכשיו — מחייב `has been ringing`.',
          err: 'present_for_duration',
        },
        { id: 't7', t: 'have', why: '`the phone` ביחיד, ולכן `has`.', err: 'have_agreement' },
        {
          id: 't8',
          t: 'rang',
          why: '`rang` הוא עבר פשוט — משהו שהסתיים. הטלפון עדיין מצלצל: `has been ringing`.',
          err: 'past_for_duration',
          as: 'meaning_mismatch',
        },
      ],
      accept: [{ a: 'The phone has been ringing all morning', o: 'correct_target' }],
      rules: [
        {
          has: ['has ringing'],
          lacks: ['been'],
          as: 'form_error',
          err: 'missing_been',
          fb: 'בין `has` ל-`ringing` חסרה המילה `been`: `has been ringing`.',
        },
        {
          has: ['has', 'rang'],
          as: 'form_error',
          err: 'have_v2',
          fb: '`rang` הוא עבר פשוט, והוא לא בא אחרי `has` או `been`. הטלפון עדיין מצלצל: `has been ringing`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S03-10',
      v: 1,
      skill: 'S03',
      unit: 'S03',
      sub: 'affirmative',
      type: 'correct',
      role: 'practice',
      stage: 2,
      ctx: 'daily.home',
      fam: 'S03.living-2023',
      goal: 'לספר ממתי אתם גרים בדירה',
      instr: 'בדוק את המשפט. אם יש טעות — תקן; אם הוא תקין, בחר "אין צורך בתיקון".',
      sitHe: 'עברתם לדירה ב-2023 ואתם עדיין גרים בה.',
      hint: 'בדוק כל חוליה: `have` ← `been` ← ing, ואחר כך `since` + נקודת התחלה.',
      explain: 'המשפט תקין: `We have been living here since 2023`. גם `We have lived here since 2023` נכון.',
      deep: 'עם `live` ו-`work` שתי צורות ה-perfect מתאימות למשהו שנמשך עד היום. ולא כל משפט שמוצג כאן שגוי — לפעמים אין מה לתקן.',
      source: [
        { id: 's1', t: 'we' },
        { id: 's2', t: 'have' },
        { id: 's3', t: 'been' },
        { id: 's4', t: 'living' },
        { id: 's5', t: 'here' },
        { id: 's6', t: 'since 2023' },
      ],
      tokens: [
        {
          id: 't1',
          t: 'are',
          why: '`are living` מתאר רק את עכשיו; "מ-2023 ועד היום" מחייב `have been living` (או `have lived`).',
          err: 'present_for_duration',
        },
        { id: 't2', t: 'lived' },
        { id: 't3', t: 'has', why: 'עם `we` משתמשים ב-`have`.', err: 'have_agreement' },
      ],
      accept: [
        { a: 'We have been living here since 2023', o: 'correct_target' },
        {
          a: 'We have lived here since 2023',
          o: 'valid_alternative',
          note: 'גם נכון. אבל המשפט המקורי כבר היה תקין — לא היה צורך לשנות אותו.',
        },
      ],
      rules: [
        {
          has: ['have living'],
          lacks: ['been'],
          as: 'form_error',
          err: 'missing_been',
          fb: 'בין `have` ל-`living` חסרה המילה `been`: `have been living`.',
        },
        {
          has: ['been lived'],
          as: 'form_error',
          err: 'been_v3',
          fb: 'אחרי `been` במבנה המתמשך בא פועל עם ing: `been living` — או בלי `been`: `have lived`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S03-11',
      v: 2,
      skill: 'S03',
      unit: 'S03',
      sub: 'affirmative',
      type: 'correct',
      role: 'practice',
      stage: 2,
      ctx: 'work.software',
      fam: 'S03.new-system-monday',
      goal: 'לספר על עבודה שהתחילה ביום שני ועדיין נמשכת',
      instr: 'בדוק את המשפט. אם יש טעות — תקן; אם הוא תקין, בחר "אין צורך בתיקון".',
      sitHe: 'עמית התחיל לעבוד על המערכת החדשה ביום שני, והוא עדיין עובד עליה.',
      hint: 'בדוק את צורת הפועל שאחרי `been`.',
      explain: 'אחרי `been` במבנה המתמשך בא פועל עם ing: `He has been working on the new system since Monday`.',
      source: [
        { id: 's1', t: 'he' },
        { id: 's2', t: 'has' },
        { id: 's3', t: 'been' },
        {
          id: 's4',
          t: 'work',
          why: '`work` היא צורת הבסיס. במבנה המתמשך בא פועל עם ing: `has been working`.',
          err: 'been_base',
        },
        { id: 's5', t: 'on the new system' },
        { id: 's6', t: 'since Monday' },
      ],
      tokens: [
        { id: 't1', t: 'working' },
        { id: 't2', t: 'worked' },
        {
          id: 't3',
          t: 'is',
          why: '`is working` מתאר רק את עכשיו; "מאז יום שני" מחייב present perfect: `has been working` (או `has worked`).',
          err: 'present_for_duration',
        },
      ],
      accept: [
        { a: 'He has been working on the new system since Monday', o: 'correct_target' },
        {
          a: 'He has worked on the new system since Monday',
          o: 'valid_alternative',
          note: 'גם נכון: present perfect. המבנה המתמשך מדגיש שהעבודה עדיין בעיצומה.',
        },
      ],
      wrong: [
        {
          a: 'He has been work on the new system since Monday',
          as: 'form_error',
          err: 'been_base',
          fb: 'אחרי `been` במבנה המתמשך בא פועל עם ing: `has been working`.',
        },
      ],
      rules: [
        {
          has: ['has working'],
          lacks: ['been'],
          as: 'form_error',
          err: 'missing_been',
          fb: 'בין `has` ל-`working` חסרה המילה `been`: `has been working`.',
        },
        {
          has: ['been worked'],
          as: 'form_error',
          err: 'been_v3',
          fb: '`been worked` אינו המבנה הנכון כאן. במבנה המתמשך: `been working`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S03-12',
      v: 2,
      skill: 'S03',
      unit: 'S03',
      sub: 'contrast',
      type: 'transform',
      role: 'practice',
      stage: 3,
      ctx: 'work.job',
      fam: 'S03.teaching-ten-years',
      goal: 'להוסיף כמה זמן זה כבר נמשך',
      instr: 'הוסף למשפט "כבר עשר שנים" ושנה את מה שצריך.',
      target: 'משך עד עכשיו: `has been + V-ing` ו-`for`',
      fromLabel: 'מה קורה עכשיו',
      toLabel: 'כמה זמן זה נמשך עד עכשיו',
      hint: 'ברגע שמוסיפים משך עד עכשיו, `is teaching` כבר לא מספיק.',
      explain: 'עם משך עד עכשיו עוברים מ-`is teaching` ל-`has been teaching … for ten years`.',
      deep: 'זו בדיוק ההעברה מעברית: "היא מלמדת כאן עשר שנים" — אותו פועל בהווה. באנגלית, תוספת של משך עד עכשיו מחייבת לשנות את מבנה הפועל.',
      source: [
        { id: 's1', t: 'she' },
        {
          id: 's2',
          t: 'is',
          why: 'עם משך עד עכשיו (`for ten years`) לא משתמשים ב-`is teaching`: `has been teaching`.',
          err: 'present_for_duration',
        },
        { id: 's3', t: 'teaching' },
        { id: 's4', t: 'at this school' },
      ],
      sourceEnd: '.',
      tokens: [
        { id: 't1', t: 'has' },
        { id: 't2', t: 'been' },
        { id: 't3', t: 'for ten years' },
        {
          id: 't4',
          t: 'since ten years',
          why: '`since` בא לפני נקודת התחלה (`since 2016`). לפרק זמן: `for ten years`.',
          err: 'since_period',
        },
        { id: 't5', t: 'have', why: 'עם `she` משתמשים ב-`has`.', err: 'have_agreement' },
      ],
      accept: [
        { a: 'She has been teaching at this school for ten years', o: 'correct_target' },
        {
          a: 'She has been teaching for ten years at this school',
          o: 'valid_alternative',
          note: 'גם הסדר הזה אפשרי, אם כי הסדר הרגיל הוא קודם המקום ואחריו הזמן.',
        },
      ],
      wrong: [
        {
          a: 'She is teaching at this school',
          as: 'target_not_used',
          err: 'not_transformed',
          fb: 'המשפט תקין, אבל עוד לא הוספת כמה זמן זה נמשך.',
        },
        {
          a: 'She is teaching at this school for ten years',
          as: 'meaning_mismatch',
          err: 'present_for_duration',
          fb: 'בעברית "היא מלמדת כאן עשר שנים" — בהווה. באנגלית `is teaching … for ten years` נשמע כמו תוכנית לעתיד. למשך עד עכשיו: `She has been teaching at this school for ten years`.',
        },
      ],
      rules: [
        {
          has: ['has teaching'],
          lacks: ['been'],
          as: 'form_error',
          err: 'missing_been',
          fb: 'בין `has` ל-`teaching` חסרה המילה `been`: `has been teaching`.',
        },
        {
          has: ['is', 'been'],
          as: 'form_error',
          err: 'double_aux',
          fb: 'אין צורך ב-`is`: `She has been teaching…`.',
        },
        {
          has: ['is', 'has'],
          as: 'form_error',
          err: 'double_aux',
          fb: 'אין צורך ב-`is`: `She has been teaching…`.',
        },
        {
          has: ['is teaching', 'for ten years'],
          as: 'meaning_mismatch',
          err: 'present_for_duration',
          fb: 'בעברית "היא מלמדת כאן עשר שנים" — בהווה. באנגלית `is teaching … for ten years` נשמע כמו תוכנית לעתיד. למשך עד עכשיו: `She has been teaching at this school for ten years`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S03-C3',
      v: 2,
      skill: 'S03',
      unit: 'S03',
      sub: 'affirmative',
      type: 'assemble',
      role: 'check',
      stage: 2,
      ctx: 'daily.learning',
      fam: 'S03.guitar-march',
      goal: 'לספר על משהו שאתה לומד מאז מרץ',
      instr: 'קרא את הסיטואציה ובנה משפט אחד באנגלית.',
      sitEn: 'You started learning the guitar in March, and you are still learning.',
      trHe: 'התחלת ללמוד גיטרה במרץ, ואתה עדיין לומד.',
      hint: 'ממתי ועד עכשיו: `have been` + ing, ואחר כך נקודת ההתחלה.',
      explain: 'התחלת במרץ ועדיין לומד: `I have been learning the guitar since March`.',
      tokens: [
        { id: 't1', t: 'I' },
        { id: 't2', t: 'have' },
        { id: 't3', t: 'been' },
        { id: 't4', t: 'learning' },
        { id: 't5', t: 'the guitar' },
        { id: 't6', t: 'since' },
        { id: 't7', t: 'March' },
        {
          id: 't8',
          t: 'for',
          why: '`for` בא לפני פרק זמן (`for six months`). לפני נקודת התחלה כמו `March`: `since`.',
          err: 'for_point',
        },
        {
          id: 't9',
          t: 'am',
          why: '`am learning` מתאר רק את עכשיו. "מאז מרץ" מחייב `have been learning`.',
          err: 'present_for_duration',
        },
        {
          id: 't10',
          t: 'learned',
          why: '`learned` מספר על לימוד שהושלם. אתה עדיין לומד: `have been learning`.',
          err: 'v3_for_ongoing',
          as: 'meaning_mismatch',
        },
      ],
      accept: [{ a: 'I have been learning the guitar since March', o: 'correct_target' }],
      rules: [
        {
          has: ['have learning'],
          lacks: ['been'],
          as: 'form_error',
          err: 'missing_been',
          fb: 'בין `have` ל-`learning` חסרה המילה `been`: `have been learning`.',
        },
        {
          has: ['been learned'],
          as: 'form_error',
          err: 'been_v3',
          fb: 'אחרי `been` במבנה המתמשך בא פועל עם ing: `have been learning`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S03-C4',
      v: 1,
      skill: 'S03',
      unit: 'S03',
      sub: 'contrast',
      type: 'correct',
      role: 'check',
      stage: 3,
      ctx: 'work.project',
      fam: 'S03.project-january',
      goal: 'לומר ממתי אתם עובדים על הפרויקט',
      instr: 'בדוק את המשפט. אם יש טעות — תקן; אם הוא תקין, בחר "אין צורך בתיקון".',
      sitHe: 'התחלתם לעבוד על הפרויקט בינואר, ואתם עדיין עובדים עליו.',
      hint: 'מה קורה לפועל כשמוסיפים "מאז ינואר"?',
      explain: 'מינואר ועד עכשיו: `We have been working on this project since January`.',
      source: [
        { id: 's1', t: 'we' },
        {
          id: 's2',
          t: 'are',
          why: '`are working` מתאר רק את עכשיו. "מאז ינואר" מחייב present perfect: `have been working` (או `have worked`).',
          err: 'present_for_duration',
        },
        { id: 's3', t: 'working' },
        { id: 's4', t: 'on this project' },
        { id: 's5', t: 'since January' },
      ],
      tokens: [
        { id: 't1', t: 'have' },
        { id: 't2', t: 'been' },
        { id: 't3', t: 'has', why: 'עם `we` משתמשים ב-`have`.', err: 'have_agreement' },
        { id: 't4', t: 'worked' },
      ],
      accept: [
        { a: 'We have been working on this project since January', o: 'correct_target' },
        {
          a: 'We have worked on this project since January',
          o: 'valid_alternative',
          note: 'גם נכון. המבנה המתמשך מדגיש שהעבודה עדיין בעיצומה.',
        },
      ],
      wrong: [
        {
          a: 'We are working on this project since January',
          as: 'form_error',
          err: 'present_for_duration',
          fb: 'בעברית "אנחנו עובדים על זה מאז ינואר" — בהווה. באנגלית, עם `since`: `We have been working on this project since January`.',
        },
      ],
      rules: [
        {
          has: ['are', 'been'],
          as: 'form_error',
          err: 'double_aux',
          fb: 'אין צורך ב-`are`: `We have been working…`.',
        },
        {
          has: ['are', 'have'],
          as: 'form_error',
          err: 'double_aux',
          fb: 'אין צורך ב-`are`: `We have been working…`.',
        },
        {
          has: ['have working'],
          lacks: ['been'],
          as: 'form_error',
          err: 'missing_been',
          fb: 'בין `have` ל-`working` חסרה המילה `been`: `have been working`.',
        },
        {
          has: ['been worked'],
          as: 'form_error',
          err: 'been_v3',
          fb: 'אחרי `been` במבנה המתמשך בא פועל עם ing: `been working` — או בלי `been`: `have worked`.',
        },
      ],
      end: '.',
    },
  ],
};
