import type { SkillPack } from '../schema';

/**
 * S04 HOW_LONG_QUESTIONS.
 * Item S04-01 belongs to the scripted first segment: keep it unchanged.
 */
export const S04: SkillPack = {
  skill: 'S04',
  lessons: [
    {
      unit: 'S04',
      title: 'לשאול כמה זמן: `How long have you been…?`',
      short:
        'כדי לשאול כמה זמן משהו נמשך עד עכשיו: `How long` + `have / has` + נושא + `been` + פועל עם ing. רק `have / has` עובר לפני הנושא — `been` נשאר אחריו.',
      chain: ['How long', 'have / has', 'נושא', 'been', 'V-ing'],
      examples: [
        { en: 'How long have you been waiting?', he: 'כמה זמן אתה כבר מחכה?' },
        { en: 'How long has she been working here?', he: 'כמה זמן היא כבר עובדת כאן?' },
        {
          en: 'How long have you known each other?',
          he: 'כמה זמן אתם כבר מכירים?',
          note: '`know` הוא פועל מצב: `have known`, בלי ing.',
        },
      ],
      contrast: {
        a: { en: 'How long did you work there?', he: 'כמה זמן עבדת שם? (כבר לא עובד שם)' },
        b: { en: 'How long have you been working here?', he: 'כמה זמן אתה כבר עובד כאן? (עדיין עובד)' },
        note: 'בעברית שתי השאלות נשמעות כמעט אותו דבר. באנגלית בודקים אם זה עדיין נכון: נגמר — `did you work`; עדיין נמשך — `have you been working` (או `have you worked`).',
      },
      deep:
        '• הסדר בשאלה: `How long` ← `have / has` ← נושא ← `been` ← פועל עם ing. רק `have / has` עובר לפני הנושא: `How long has she been waiting?` — לא `How long has been she waiting?`\n' +
        '• `have` עם `I / you / we / they`; `has` עם `he / she / it`, עם שם של אדם ועם דבר אחד: `How long has the phone been ringing?`\n' +
        '• פעלי מצב (`know`, `have` במובן של בעלות, `be`) באים ב-present perfect פשוט: `How long have you known Dana?`, `How long have you had this car?` — לא `been knowing`, לא `been having`.\n' +
        '• עם `work`, `live`, `study` שתי הצורות תקינות למשהו שעדיין נמשך: `How long have you worked here?` וגם `How long have you been working here?`\n' +
        '• `How long did you…?` — על תקופה שהסתיימה. `How long are you…?` שואל על עכשיו או על תוכנית (`How long are you staying?` — עד מתי תישאר), לא על כמה זמן זה כבר נמשך.\n' +
        '• שאלת כן/לא: `Have you been waiting long?` — בלי `how`, ו-`long` בסוף.\n' +
        '• בתשובה: `for` + פרק זמן (`for two months`), או `since` + נקודת התחלה (`since March`).',
      pitfalls: [
        '`How long you have been working here?` — בשאלה ישירה `have` בא לפני הנושא.',
        '`How long have you working here?` — חסר `been`.',
        '`How long are you working here?` — שואל על עכשיו או על תוכנית, לא על כמה זמן זה כבר נמשך.',
        '`How long did you live here?` — כשעדיין גרים כאן: `How long have you lived here?`',
        '`How long have you been knowing him?` — עם `know`: `How long have you known him?`',
      ],
    },
  ],
  examples: {
    S04: [
      { en: 'How long has it been raining?', he: 'כמה זמן כבר יורד גשם?' },
      { en: 'How long have you had this laptop?', he: 'כמה זמן המחשב הנייד הזה אצלך?' },
      { en: 'Has he been working on it long?', he: 'הוא כבר הרבה זמן עובד על זה?' },
      {
        en: 'How long did you live in London?',
        he: 'כמה זמן גרת בלונדון?',
        note: 'התקופה בלונדון הסתיימה, ולכן `did`.',
      },
    ],
  },
  items: [
    {
      id: 'S04-01',
      v: 2,
      skill: 'S04',
      unit: 'S04',
      sub: 'question',
      type: 'assemble',
      role: 'practice',
      stage: 1,
      ctx: 'work.software',
      fam: 'S04.using-software',
      goal: 'לשאול עמית כמה זמן הוא כבר עובד עם התוכנה',
      instr: 'בנה את השאלה באנגלית. לא חייבים להשתמש בכל המילים.',
      promptHe: 'כמה זמן אתה כבר משתמש בתוכנה הזאת?',
      target: 'שאלה במבנה המתמשך `have … been + V-ing`',
      scaffold: ['How long', 'have / has', 'you', 'been', 'V-ing'],
      hint: 'הסדר: `How long` ← `have` ← `you` ← `been` ← פועל עם ing.',
      explain: 'בשאלה, `have` עובר לפני `you`, ואחריו `been` ופועל עם ing: `How long have you been using…?`',
      deep: 'השאלה בנויה בדיוק כמו המשפט `You have been using this software`, רק ש-`have` קופץ לפני הנושא. `Are you using` שואל על עכשיו, ולא על כמה זמן זה נמשך.',
      tokens: [
        { id: 't1', t: 'how long' },
        { id: 't2', t: 'have' },
        { id: 't3', t: 'you' },
        { id: 't4', t: 'been' },
        { id: 't5', t: 'using' },
        { id: 't6', t: 'this software' },
        { id: 't7', t: 'has', why: 'עם `you` משתמשים ב-`have`: `have you`.', err: 'have_agreement' },
        {
          id: 't8',
          t: 'are',
          why: '`are you using` שואל על עכשיו. כדי לשאול כמה זמן זה נמשך עד עכשיו: `have you been using`.',
          err: 'present_for_duration',
        },
        {
          id: 't9',
          t: 'do',
          why: '`do` לא מתאים כאן: פועל העזר של המבנה הוא `have`.',
          err: 'do_with_perfect',
        },
        { id: 't10', t: 'used' },
      ],
      accept: [
        { a: 'How long have you been using this software', o: 'correct_target' },
        {
          a: 'How long have you used this software',
          o: 'target_not_used',
          note: 'תקין — present perfect. התרגיל ביקש את המבנה המתמשך, שמדגיש שהשימוש עדיין נמשך.',
        },
      ],
      wrong: [
        {
          a: 'How long are you using this software',
          as: 'meaning_mismatch',
          err: 'present_for_duration',
          fb: '`How long are you using this software?` שואל על תוכנית — כמה זמן עוד תשתמש בה. כדי לשאול כמה זמן זה כבר נמשך: `How long have you been using this software?`',
        },
      ],
      rules: [
        {
          order: ['you', 'have'],
          as: 'form_error',
          err: 'no_inversion',
          fb: 'בשאלה ישירה `have` בא לפני הנושא: `How long have you been…?`',
        },
        {
          has: ['have you using'],
          lacks: ['been'],
          as: 'form_error',
          err: 'missing_been',
          fb: 'בין `you` ל-`using` חסרה המילה `been`: `have you been using`.',
        },
        {
          has: ['been used'],
          as: 'form_error',
          err: 'been_v3',
          fb: 'אחרי `been` במבנה המתמשך בא פועל עם ing: `been using`.',
        },
      ],
      end: '?',
    },
    {
      id: 'S04-02',
      v: 2,
      skill: 'S04',
      unit: 'S04',
      sub: 'question',
      type: 'assemble',
      role: 'practice',
      stage: 1,
      ctx: 'work.job',
      fam: 'S04.she-working-here',
      goal: 'לשאול כמה זמן עמיתה כבר עובדת כאן',
      instr: 'בנה את השאלה באנגלית. לא חייבים להשתמש בכל המילים.',
      promptHe: 'כמה זמן היא כבר עובדת כאן?',
      sitHe: 'אתה מדבר עם עמית על מיכל מהקומה השנייה, שנראה שהיא מכירה כאן את כולם.',
      target: 'שאלה במבנה המתמשך `has … been + V-ing`',
      scaffold: ['How long', 'have / has', 'she', 'been', 'V-ing'],
      hint: 'עם `she` בא `has`. הוא עובר לפני הנושא, ו-`been` נשאר אחריו.',
      explain: 'עם `she` בא `has`, והוא עובר לפני הנושא: `How long has she been working here?`',
      deep: 'המשפט `She has been working here` הופך לשאלה כש-`has` קופץ לפני `she`; `been` ו-`working` נשארים במקומם. גם `How long has she worked here?` תקין — present perfect פשוט.',
      tokens: [
        { id: 't1', t: 'how long' },
        { id: 't2', t: 'has' },
        { id: 't3', t: 'she' },
        { id: 't4', t: 'been' },
        { id: 't5', t: 'working' },
        { id: 't6', t: 'here' },
        { id: 't7', t: 'have', why: 'עם `she` משתמשים ב-`has`, לא ב-`have`.', err: 'have_agreement' },
        {
          id: 't8',
          t: 'is',
          why: '`is` + ing מתאר את עכשיו (או תוכנית), לא כמה זמן זה כבר נמשך. כאן: `has she been working`.',
          err: 'present_for_duration',
          as: 'meaning_mismatch',
        },
        {
          id: 't9',
          t: 'did',
          why: '`did` שואל על תקופה שהסתיימה, ואחריו בא פועל בסיס. היא עדיין עובדת כאן: `How long has she been working here?`',
          err: 'did_for_ongoing',
        },
        { id: 't10', t: 'worked' },
      ],
      accept: [
        { a: 'How long has she been working here', o: 'correct_target' },
        {
          a: 'How long has she worked here',
          o: 'target_not_used',
          note: 'תקין — present perfect פשוט, ועם `work` הוא מתאים גם למשהו שעדיין נמשך. התרגיל ביקש את המבנה המתמשך.',
        },
        {
          a: 'How long has she been here',
          o: 'target_not_used',
          note: 'תקין וטבעי: `has she been here` שואל כמה זמן היא כאן. התרגיל ביקש את המבנה המתמשך: `has she been working here`.',
        },
      ],
      wrong: [
        {
          a: 'How long is she working here',
          as: 'meaning_mismatch',
          err: 'present_for_duration',
          fb: 'המשפט תקין, אבל הוא שואל על עכשיו או על תוכנית — למשל עד מתי היא תעבוד כאן. כדי לשאול כמה זמן זה כבר נמשך: `How long has she been working here?`',
        },
      ],
      rules: [
        {
          order: ['she', 'has'],
          as: 'form_error',
          err: 'no_inversion',
          fb: 'בשאלה ישירה `has` בא לפני הנושא: `How long has she been working here?`',
        },
        {
          has: ['has been she'],
          as: 'form_error',
          err: 'aux_order',
          fb: 'רק `has` עובר לפני הנושא; `been` נשאר אחריו: `How long has she been working here?`',
        },
        {
          has: ['has she working'],
          lacks: ['been'],
          as: 'form_error',
          err: 'missing_been',
          fb: 'בין `she` ל-`working` חסרה המילה `been`: `has she been working`.',
        },
        {
          has: ['been worked'],
          as: 'form_error',
          err: 'been_v3',
          fb: 'אחרי `been` במבנה המתמשך בא פועל עם ing: `been working` — או בלי `been`: `has she worked`.',
        },
        {
          has: ['is', 'been'],
          as: 'form_error',
          err: 'double_aux',
          fb: '`is` ו-`been` לא הולכים יחד כאן. למשך עד עכשיו: `How long has she been working here?`',
        },
        {
          has: ['is', 'worked'],
          as: 'form_error',
          err: 'be_v3',
          fb: '`is worked` אינו מבנה תקין כאן. למשך עד עכשיו: `How long has she been working here?`',
        },
      ],
      end: '?',
    },
    {
      id: 'S04-03',
      v: 2,
      skill: 'S04',
      unit: 'S04',
      sub: 'question',
      type: 'transform',
      role: 'practice',
      stage: 1,
      ctx: 'daily.home',
      fam: 'S04.living-haifa',
      goal: 'לנסח את השאלה שעליה עונה משפט על משך',
      instr: 'המשפט הזה הוא תשובה. הפוך אותו לשאלה שמתחילה ב-`How long` — השאלה שעליה הוא עונה.',
      sitHe: 'חבר מספר לך על השכנים החדשים שלו.',
      target: 'שאלה שמתחילה ב-`How long`',
      scaffold: ['How long', 'have / has', 'they', 'been', 'V-ing'],
      fromLabel: 'משפט',
      toLabel: 'שאלה עם `How long`',
      hint: 'מה מחליף את `for five years`? ואיזו מילה עוברת לפני `they`?',
      explain: 'בשאלה `have` עובר לפני הנושא, ו-`How long` מחליף את `for five years`: `How long have they been living in Haifa?`',
      deep: 'המשפט והשאלה בנויים מאותן חוליות: `they have been living` ← `have they been living`. רק `have` זז. גם `How long have they lived in Haifa?` תקין — עם `live` שתי הצורות מתאימות.',
      source: [
        { id: 's1', t: 'they' },
        { id: 's2', t: 'have' },
        { id: 's3', t: 'been' },
        { id: 's4', t: 'living' },
        { id: 's5', t: 'in Haifa' },
        {
          id: 's6',
          t: 'for five years',
          why: 'התבקשת שאלה עם `How long`. `How long` שואל בדיוק על `for five years`, ולכן הביטוי לא נשאר בשאלה.',
          err: 'duration_kept',
          as: 'target_not_used',
        },
      ],
      sourceEnd: '.',
      tokens: [
        { id: 't1', t: 'how long' },
        { id: 't2', t: 'has', why: 'עם `they` משתמשים ב-`have`, לא ב-`has`.', err: 'have_agreement' },
        {
          id: 't3',
          t: 'are',
          why: '`are` + ing שואל על עכשיו או על תוכנית, לא כמה זמן זה כבר נמשך. המבנה נשאר `have … been living`.',
          err: 'present_for_duration',
          as: 'meaning_mismatch',
        },
        { id: 't4', t: 'lived' },
      ],
      accept: [
        { a: 'How long have they been living in Haifa', o: 'correct_target' },
        {
          a: 'How long have they lived in Haifa',
          o: 'valid_alternative',
          note: 'גם נכון: עם `live` גם present perfect פשוט מתאים למשהו שעדיין נמשך.',
        },
        {
          a: 'How long have they been in Haifa',
          o: 'valid_alternative',
          note: 'גם נכון: `been in Haifa` — "הם בחיפה". אחרי `been` לא תמיד בא ing.',
        },
      ],
      wrong: [
        {
          a: 'They have been living in Haifa for five years',
          as: 'target_not_used',
          err: 'not_transformed',
          fb: 'זה המשפט המקורי — תקין, אבל התבקשת להפוך אותו לשאלה עם `How long`.',
        },
        {
          a: 'They have lived in Haifa for five years',
          as: 'target_not_used',
          err: 'not_transformed',
          fb: 'משפט תקין — אבל התבקשת להפוך אותו לשאלה עם `How long`.',
        },
        {
          a: 'They have been living in Haifa',
          as: 'target_not_used',
          err: 'not_transformed',
          fb: 'משפט תקין — אבל התבקשת להפוך אותו לשאלה עם `How long`.',
        },
        {
          a: 'They have lived in Haifa',
          as: 'target_not_used',
          err: 'not_transformed',
          fb: 'משפט תקין — אבל התבקשת להפוך אותו לשאלה עם `How long`.',
        },
        {
          a: 'Have they been living in Haifa for five years',
          as: 'target_not_used',
          err: 'yes_no_question',
          fb: 'שאלה תקינה — אבל זו שאלת כן/לא. התבקשת לשאול כמה זמן: `How long have they been living in Haifa?`',
        },
        {
          a: 'How long are they living in Haifa',
          as: 'meaning_mismatch',
          err: 'present_for_duration',
          fb: 'השאלה תקינה, אבל היא שואלת על תוכנית — עד מתי הם יגורו בחיפה. כדי לשאול כמה זמן זה כבר נמשך: `How long have they been living in Haifa?`',
        },
      ],
      rules: [
        {
          has: ['how long', 'for five years'],
          as: 'form_error',
          err: 'duration_twice',
          fb: '`How long` כבר שואל על משך הזמן, ולכן `for five years` יוצא מהשאלה.',
        },
        {
          order: ['they', 'have'],
          as: 'form_error',
          err: 'no_inversion',
          fb: 'בשאלה ישירה `have` בא לפני הנושא: `How long have they been living in Haifa?`',
        },
        {
          has: ['have been they'],
          as: 'form_error',
          err: 'aux_order',
          fb: 'רק `have` עובר לפני הנושא; `been` נשאר אחריו: `How long have they been living in Haifa?`',
        },
        {
          has: ['have they living'],
          lacks: ['been'],
          as: 'form_error',
          err: 'missing_been',
          fb: 'בין `they` ל-`living` חסרה המילה `been`: `have they been living`.',
        },
        {
          has: ['been lived'],
          as: 'form_error',
          err: 'been_v3',
          fb: 'אחרי `been` כאן בא פועל עם ing: `been living` — או בלי `been`: `have they lived`.',
        },
        {
          has: ['are', 'been'],
          as: 'form_error',
          err: 'double_aux',
          fb: '`are` ו-`been` לא הולכים יחד כאן. למשך עד עכשיו: `How long have they been living in Haifa?`',
        },
        {
          has: ['are', 'lived'],
          as: 'form_error',
          err: 'be_v3',
          fb: '`are lived` אינו מבנה תקין כאן. למשך עד עכשיו: `How long have they lived in Haifa?`',
        },
      ],
      end: '?',
    },
    {
      id: 'S04-04',
      v: 1,
      skill: 'S04',
      unit: 'S04',
      sub: 'question_stative',
      type: 'assemble',
      role: 'practice',
      stage: 1,
      ctx: 'daily.family',
      fam: 'S04.known-dana',
      goal: 'לשאול חבר כמה זמן הוא מכיר את דנה',
      instr: 'בנה את השאלה באנגלית. לא חייבים להשתמש בכל המילים.',
      promptHe: 'כמה זמן אתה מכיר את דנה?',
      sitHe: 'במסיבה אתה רואה שחבר שלך ודנה מדברים כמו חברים ותיקים.',
      scaffold: ['How long', 'have / has', 'you', 'V3'],
      hint: 'פועל מצב כמו `know` לא בא כאן עם ing. מה צורת ה-V3 שלו?',
      explain: '`know` הוא פועל מצב, ולכן present perfect פשוט: `How long have you known Dana?` — לא `have you been knowing`.',
      deep: 'בעברית "כמה זמן אתה מכיר" — בהווה. באנגלית, כמו בכל משך עד עכשיו, צריך present perfect. עם פעלי מצב (`know`, `have` במובן של בעלות, `believe`) לא משתמשים בצורת ing, ולכן `have known`. `How long do you know Dana?` הוא העתקה מהעברית ואינו תקין.',
      tokens: [
        { id: 't1', t: 'how long' },
        { id: 't2', t: 'have' },
        { id: 't3', t: 'you' },
        { id: 't4', t: 'known' },
        { id: 't5', t: 'Dana' },
        {
          id: 't6',
          t: 'been',
          why: '`know` הוא פועל מצב, ולכן אין כאן `been` + ing: `How long have you known Dana?`',
          err: 'stative_continuous',
        },
        {
          id: 't7',
          t: 'knowing',
          why: '`know` הוא פועל מצב ולא בא כאן בצורת ing: `have you known`.',
          err: 'stative_continuous',
        },
        {
          id: 't8',
          t: 'do',
          why: '`do you know` שואל רק על ההווה. "כמה זמן אתה מכיר" — עד עכשיו — מחייב `have you known`.',
          err: 'present_for_duration',
        },
        {
          id: 't9',
          t: 'know',
          why: 'אחרי `have` בא V3 — `known`. (`do you know` שואל רק על ההווה, לא על כמה זמן.)',
          err: 'base_for_v3',
        },
        { id: 't10', t: 'has', why: 'עם `you` משתמשים ב-`have`, לא ב-`has`.', err: 'have_agreement' },
      ],
      accept: [{ a: 'How long have you known Dana', o: 'correct_target' }],
      wrong: [
        {
          a: 'How long do you know Dana',
          as: 'form_error',
          err: 'present_for_duration',
          fb: 'זו העתקה מהעברית ("כמה זמן אתה מכיר"). באנגלית משך עד עכשיו מחייב present perfect: `How long have you known Dana?`',
        },
        {
          a: 'Do you know Dana',
          as: 'meaning_mismatch',
          err: 'no_how_long',
          fb: 'שאלה תקינה, אבל היא שואלת אם אתה מכיר את דנה — לא כמה זמן. כאן: `How long have you known Dana?`',
        },
      ],
      rules: [
        {
          has: ['been knowing'],
          as: 'form_error',
          err: 'stative_continuous',
          fb: '`know` הוא פועל מצב ולא בא בצורת ing: `How long have you known Dana?`',
        },
        {
          order: ['you', 'have'],
          as: 'form_error',
          err: 'no_inversion',
          fb: 'בשאלה ישירה `have` בא לפני הנושא: `How long have you known Dana?`',
        },
      ],
      end: '?',
    },
    {
      id: 'S04-05',
      v: 1,
      skill: 'S04',
      unit: 'S04',
      sub: 'question',
      type: 'correct',
      role: 'practice',
      stage: 2,
      ctx: 'work.clinic',
      fam: 'S04.phone-ringing',
      goal: 'לשאול כמה זמן הטלפון כבר מצלצל',
      instr: 'אם יש טעות — גע במילה או ברווח ובחר תיקון. אם המשפט תקין, בחר "אין צורך בתיקון".',
      sitHe: 'בדלפק הקבלה במרפאה הטלפון מצלצל בלי הפסקה, ואף אחד לא עונה. אתה שואל את העמית שיושב לידך.',
      hint: 'בדוק את החוליות בין `has` לבין `ringing`.',
      explain: 'בשאלה על משך עד עכשיו: `has` ← נושא ← `been` ← פועל עם ing. חסר `been`: `How long has the phone been ringing?`',
      deep: '`has` כבר עבר לפני הנושא (`the phone`), וזה נכון. אבל בלי `been` השרשרת נשברת: `has … ringing` אינו מבנה תקין. `the phone` הוא דבר אחד, ולכן `has` ולא `have`.',
      source: [
        { id: 's1', t: 'how long' },
        { id: 's2', t: 'has' },
        { id: 's3', t: 'the phone' },
        { id: 's4', t: 'ringing' },
      ],
      tokens: [
        { id: 't1', t: 'been' },
        {
          id: 't2',
          t: 'is',
          why: '`is ringing` מתאר את עכשיו, לא כמה זמן זה כבר נמשך. כאן: `has the phone been ringing`.',
          err: 'present_for_duration',
          as: 'meaning_mismatch',
        },
        {
          id: 't3',
          t: 'being',
          why: '`being` לא מתאים כאן. במבנה המתמשך של present perfect משתמשים ב-`been`.',
          err: 'being_for_been',
        },
        { id: 't4', t: 'have', why: '`the phone` הוא דבר אחד, ולכן `has`, לא `have`.', err: 'have_agreement' },
      ],
      accept: [{ a: 'How long has the phone been ringing', o: 'correct_target' }],
      wrong: [
        {
          a: 'How long has the phone ringing',
          as: 'form_error',
          err: 'missing_been',
          fb: 'בין `the phone` ל-`ringing` חסרה המילה `been`: `How long has the phone been ringing?`',
        },
      ],
      rules: [
        {
          has: ['has been the phone'],
          as: 'form_error',
          err: 'aux_order',
          fb: 'רק `has` עובר לפני הנושא; `been` נשאר אחריו: `How long has the phone been ringing?`',
        },
        {
          order: ['the phone', 'has'],
          as: 'form_error',
          err: 'no_inversion',
          fb: 'בשאלה ישירה `has` בא לפני הנושא: `How long has the phone been ringing?`',
        },
        {
          has: ['is', 'been'],
          as: 'form_error',
          err: 'double_aux',
          fb: '`is` ו-`been` לא הולכים יחד כאן. למשך עד עכשיו: `How long has the phone been ringing?`',
        },
        {
          has: ['is', 'being'],
          as: 'form_error',
          err: 'being_for_been',
          fb: '`is being ringing` אינו מבנה תקין. למשך עד עכשיו: `How long has the phone been ringing?`',
        },
      ],
      end: '?',
    },
    {
      id: 'S04-06',
      v: 1,
      skill: 'S04',
      unit: 'S04',
      sub: 'contrast',
      type: 'correct',
      role: 'practice',
      stage: 2,
      ctx: 'daily.learning',
      fam: 'S04.studying-english',
      goal: 'לשאול משתתף בקורס כמה זמן הוא כבר לומד אנגלית',
      instr: 'אם יש טעות — גע במילה או ברווח ובחר תיקון. אם המשפט תקין, בחר "אין צורך בתיקון".',
      sitHe: 'בקורס ערב אתה פוגש משתתף שמדבר אנגלית טובה מאוד. הוא מספר שהוא עדיין לומד אנגלית כל שבוע. אתה שואל אותו:',
      hint: 'הוא עדיין לומד. האם `did` מתאים למשהו שעדיין נמשך?',
      explain: '`did` שואל על תקופה שהסתיימה. הוא עדיין לומד, ולכן `How long have you been studying English?` (או `have you studied`).',
      deep: '`How long did you study English?` היא שאלה תקינה — כשמדובר בתקופה שנגמרה, למשל מישהו שלמד אנגלית בתיכון והפסיק. כאן הלימוד עדיין נמשך, ולכן צריך present perfect. עם `study` שתי הצורות מתאימות; `have you been studying` מדגיש את התהליך המתמשך.',
      diff: '`How long did you study English?` — תקופה שהסתיימה. `How long have you been studying English?` — עדיין לומד.',
      source: [
        { id: 's1', t: 'how long' },
        {
          id: 's2',
          t: 'did',
          why: '`did` שואל על תקופה שהסתיימה. הוא עדיין לומד, ולכן `have you been studying` או `have you studied`.',
          err: 'did_for_ongoing',
          as: 'meaning_mismatch',
        },
        { id: 's3', t: 'you' },
        {
          id: 's4',
          t: 'study',
          why: '`study` היא צורת הבסיס, והיא באה אחרי `did`. אחרי `have` בא `studied`, או `been studying`.',
          err: 'base_after_have',
        },
        { id: 's5', t: 'English' },
      ],
      tokens: [
        { id: 't1', t: 'have' },
        { id: 't2', t: 'been' },
        { id: 't3', t: 'studying' },
        { id: 't4', t: 'studied' },
        { id: 't5', t: 'has', why: 'עם `you` משתמשים ב-`have`, לא ב-`has`.', err: 'have_agreement' },
      ],
      accept: [
        { a: 'How long have you been studying English', o: 'correct_target' },
        {
          a: 'How long have you studied English',
          o: 'valid_alternative',
          note: 'גם נכון — present perfect פשוט. עם `study` שתי הצורות מתאימות למשהו שעדיין נמשך.',
        },
      ],
      wrong: [
        {
          a: 'How long did you study English',
          as: 'meaning_mismatch',
          err: 'did_for_ongoing',
          fb: 'השאלה תקינה, אבל `did` שואל על תקופה שהסתיימה — כאילו הוא כבר לא לומד. הוא עדיין לומד: `How long have you been studying English?`',
        },
      ],
      rules: [
        {
          has: ['did', 'studied'],
          as: 'form_error',
          err: 'did_v2',
          fb: 'אחרי `did` בא פועל בסיס — ובכל מקרה כאן צריך `have`: `How long have you studied English?`',
        },
        {
          has: ['did', 'been'],
          as: 'form_error',
          err: 'did_with_perfect',
          fb: '`did` ו-`been` לא הולכים יחד. למשך עד עכשיו: `How long have you been studying English?`',
        },
        {
          has: ['did', 'studying'],
          as: 'form_error',
          err: 'did_ing',
          fb: 'אחרי `did` לא בא פועל עם ing. למשך עד עכשיו: `How long have you been studying English?`',
        },
        {
          order: ['you', 'have'],
          as: 'form_error',
          err: 'no_inversion',
          fb: 'בשאלה ישירה `have` בא לפני הנושא: `How long have you been studying English?`',
        },
        {
          has: ['have you studying'],
          lacks: ['been'],
          as: 'form_error',
          err: 'missing_been',
          fb: 'בין `you` ל-`studying` חסרה המילה `been`: `have you been studying`.',
        },
        {
          has: ['been studied'],
          as: 'form_error',
          err: 'been_v3',
          fb: 'אחרי `been` כאן בא פועל עם ing: `been studying` — או בלי `been`: `have you studied`.',
        },
      ],
      end: '?',
    },
    {
      id: 'S04-07',
      v: 1,
      skill: 'S04',
      unit: 'S04',
      sub: 'question',
      type: 'assemble',
      role: 'practice',
      stage: 2,
      ctx: 'work.email',
      fam: 'S04.eli-email',
      goal: 'לשאול כמה זמן עמית כבר כותב את אותו מייל',
      instr: 'קרא את הסיטואציה ובנה שאלה אחת באנגלית.',
      sitEn: 'Eli started writing an important email before lunch. Now it is 3 p.m., and he is still writing it. You are surprised. Ask a colleague a question with "how long".',
      trHe: 'אלי התחיל לכתוב מייל חשוב לפני הצהריים. עכשיו שלוש, והוא עדיין כותב אותו. אתה מופתע. שאל עמית שאלה עם `how long`.',
      hint: 'התחיל לפני הצהריים ועדיין כותב — איזה מבנה מתאר את זה? ומה עובר לפני הנושא בשאלה?',
      explain: 'התחיל בעבר ועדיין כותב: `How long has Eli been writing that email?` — `has` לפני `Eli`, ו-`been` אחריו.',
      deep: '`Eli` הוא אדם אחד, ולכן `has`. `is writing` מתאר רק את עכשיו, ו-`did … write` מדבר על כתיבה שהסתיימה — אבל הוא עדיין כותב. לכן `has … been writing`.',
      tokens: [
        { id: 't1', t: 'how long' },
        { id: 't2', t: 'has' },
        { id: 't3', t: 'Eli' },
        { id: 't4', t: 'been' },
        { id: 't5', t: 'writing' },
        { id: 't6', t: 'that email' },
        { id: 't7', t: 'have', why: '`Eli` הוא אדם אחד, ולכן `has`, לא `have`.', err: 'have_agreement' },
        {
          id: 't8',
          t: 'is',
          why: '`is writing` מתאר רק את עכשיו, לא כמה זמן זה כבר נמשך. כאן: `has Eli been writing`.',
          err: 'present_for_duration',
          as: 'meaning_mismatch',
        },
        {
          id: 't9',
          t: 'did',
          why: '`did` שואל על משהו שהסתיים, ואחריו בא פועל בסיס. הוא עדיין כותב: `has Eli been writing`.',
          err: 'did_for_ongoing',
        },
        {
          id: 't10',
          t: 'wrote',
          why: '`wrote` הוא עבר פשוט — משהו שהסתיים. הוא עדיין כותב: `been writing`.',
          err: 'past_for_ongoing',
        },
      ],
      accept: [
        { a: 'How long has Eli been writing that email', o: 'correct_target' },
        {
          a: 'How long has Eli been writing',
          o: 'valid_alternative',
          note: 'גם נכון: ההקשר ברור גם בלי `that email`.',
        },
      ],
      rules: [
        {
          order: ['Eli', 'has'],
          as: 'form_error',
          err: 'no_inversion',
          fb: 'בשאלה ישירה `has` בא לפני הנושא: `How long has Eli been writing that email?`',
        },
        {
          has: ['has been Eli'],
          as: 'form_error',
          err: 'aux_order',
          fb: 'רק `has` עובר לפני הנושא; `been` נשאר אחריו: `How long has Eli been writing…?`',
        },
        {
          has: ['has Eli writing'],
          lacks: ['been'],
          as: 'form_error',
          err: 'missing_been',
          fb: 'בין `Eli` ל-`writing` חסרה המילה `been`: `has Eli been writing`.',
        },
        {
          has: ['is', 'been'],
          as: 'form_error',
          err: 'double_aux',
          fb: '`is` ו-`been` לא הולכים יחד כאן. למשך עד עכשיו: `How long has Eli been writing that email?`',
        },
      ],
      end: '?',
    },
    {
      id: 'S04-08',
      v: 2,
      skill: 'S04',
      unit: 'S04',
      sub: 'question_stative',
      type: 'correct',
      role: 'practice',
      stage: 3,
      ctx: 'daily.travel',
      fam: 'S04.car-had',
      goal: 'לשאול חבר כמה זמן הרכב שלו כבר אצלו',
      instr: 'אם יש טעות — גע במילה או ברווח ובחר תיקון. אם המשפט תקין, בחר "אין צורך בתיקון".',
      sitHe: 'חבר אוסף אותך ברכב שלו. הוא קנה את הרכב לפני כמה שנים, והוא עדיין שלו. שאלת אותו:',
      hint: '`have` במובן של "יש לי / שלי" הוא פועל מצב. האם צריך כאן ing?',
      explain: 'המשפט תקין. `have` במובן של בעלות הוא פועל מצב, ולכן present perfect פשוט: `How long have you had this car?`',
      deep: '`have … had` נראה מוזר, אבל זה פשוט `have` (פועל עזר) + `had` (צורת V3 של `have`). `been having` לא מתאים לבעלות. `How long did you have this car?` מתאים רק אם הרכב כבר לא שלו, ו-`How long do you have this car?` שואל עד מתי הרכב אצלו — למשל רכב שכור.',
      diff: '`How long have you had this car?` — כמה זמן הוא כבר שלך. `How long did you have that car?` — רכב שכבר אינו שלך.',
      source: [
        { id: 's1', t: 'how long' },
        { id: 's2', t: 'have' },
        { id: 's3', t: 'you' },
        { id: 's4', t: 'had' },
        { id: 's5', t: 'this car' },
      ],
      tokens: [
        {
          id: 't1',
          t: 'been',
          why: '`have` במובן של בעלות הוא פועל מצב — בלי `been` + ing. המשפט המקורי תקין.',
          err: 'stative_continuous',
        },
        {
          id: 't2',
          t: 'having',
          why: '`have` במובן של בעלות לא בא בצורת ing: `have you had`.',
          err: 'stative_continuous',
        },
        {
          id: 't3',
          t: 'did',
          why: '`did` שואל על תקופה שהסתיימה — כאילו הרכב כבר לא שלו. הרכב עדיין שלו: `have you had`.',
          err: 'did_for_ongoing',
          as: 'meaning_mismatch',
        },
        {
          id: 't4',
          t: 'do',
          why: '`do you have` שואל על ההווה — למשל עד מתי הרכב אצלך. כדי לשאול כמה זמן הוא כבר שלך: `have you had`.',
          err: 'present_for_duration',
          as: 'meaning_mismatch',
        },
      ],
      accept: [{ a: 'How long have you had this car', o: 'correct_target' }],
      wrong: [
        {
          a: 'How long did you have this car',
          as: 'meaning_mismatch',
          err: 'did_for_ongoing',
          fb: 'השאלה תקינה, אבל `did` מדבר על תקופה שהסתיימה — כאילו הרכב כבר לא שלו. הרכב עדיין שלו, והמשפט המקורי היה נכון.',
        },
        {
          a: 'How long do you have this car',
          as: 'meaning_mismatch',
          err: 'present_for_duration',
          fb: 'השאלה הזאת שואלת עד מתי הרכב אצלו (למשל רכב שכור), לא כמה זמן הוא כבר שלו. המשפט המקורי היה נכון: `How long have you had this car?`',
        },
      ],
      rules: [
        {
          has: ['been having'],
          as: 'form_error',
          err: 'stative_continuous',
          fb: '`have` במובן של בעלות הוא פועל מצב ולא בא בצורת ing. המשפט המקורי היה תקין: `How long have you had this car?`',
        },
        {
          has: ['did', 'had'],
          as: 'form_error',
          err: 'did_v2',
          fb: 'אחרי `did` בא פועל בסיס, ובכל מקרה הרכב עדיין שלו. המשפט המקורי היה תקין: `How long have you had this car?`',
        },
        {
          has: ['do', 'had'],
          as: 'form_error',
          err: 'do_v3',
          fb: 'אחרי `do` בא פועל בסיס. כאן אין צורך בתיקון: `How long have you had this car?`',
        },
        {
          has: ['you have had'],
          as: 'form_error',
          err: 'no_inversion',
          fb: 'בשאלה ישירה `have` בא לפני הנושא. המשפט המקורי היה תקין: `How long have you had this car?`',
        },
      ],
      end: '?',
    },
    {
      id: 'S04-09',
      v: 1,
      skill: 'S04',
      unit: 'S04',
      sub: 'contrast',
      type: 'discriminate',
      role: 'practice',
      stage: 3,
      ctx: 'daily.past',
      fam: 'S04.eilat-finished',
      goal: 'לשאול על תקופה שהסתיימה',
      instr: 'בחר את השאלה שמתאימה לסיטואציה.',
      sitHe: 'חברה גרה כמה שנים באילת, ולפני שנה עברה לתל אביב. אתה רוצה לשאול אותה כמה זמן היא גרה באילת.',
      hint: 'האם היא עדיין גרה באילת?',
      explain: 'התקופה באילת הסתיימה — היא כבר גרה בתל אביב. לכן `How long did you live in Eilat?`',
      deep: 'בעברית "כמה זמן גרת באילת" לא מבחין בין מה שנגמר למה שנמשך. באנגלית זה ההבדל: נגמר — `did you live`; עדיין נמשך — `have you lived` או `have you been living`.',
      diff: '`How long did you live there?` — תקופה שנגמרה. `How long have you lived there?` — עדיין גרים שם.',
      multi: false,
      options: [
        {
          id: 'a',
          en: 'How long did you live in Eilat?',
          v: 'fits',
          why: 'התקופה באילת הסתיימה, ולכן עבר פשוט: `did you live`.',
        },
        {
          id: 'b',
          en: 'How long have you lived in Eilat?',
          v: 'other_meaning',
          why: 'תקין, אבל `have you lived` אומר שהיא עדיין גרה באילת — והיא כבר עברה לתל אביב.',
          err: 'perfect_for_finished',
        },
        {
          id: 'c',
          en: 'How long have you been living in Eilat?',
          v: 'other_meaning',
          why: 'תקין, אבל המבנה המתמשך מתאר משהו שעדיין נמשך — והיא כבר לא גרה באילת.',
          err: 'perfect_for_finished',
        },
        {
          id: 'd',
          en: 'How long did you lived in Eilat?',
          v: 'ungrammatical',
          why: 'אחרי `did` בא פועל בסיס: `did you live`, לא `did you lived`.',
          err: 'did_v2',
        },
      ],
    },
    {
      id: 'S04-10',
      v: 1,
      skill: 'S04',
      unit: 'S04',
      sub: 'question',
      type: 'correct',
      role: 'practice',
      stage: 2,
      ctx: 'work.project',
      fam: 'S04.ron-project',
      goal: 'לשאול כמה זמן רון כבר מנהל את הפרויקט',
      instr: 'אם יש טעות — גע במילה או ברווח ובחר תיקון. אם המשפט תקין, בחר "אין צורך בתיקון".',
      sitHe: 'רון מנהל פרויקט גדול בחברה. אתה רוצה לשאול עמיתה כמה זמן הוא כבר מנהל אותו, וכתבת:',
      hint: 'בשאלה ישירה — מה בא לפני הנושא?',
      explain: 'בשאלה ישירה `has` עובר לפני הנושא: `How long has Ron been managing the project?`',
      deep: 'הסדר `Ron has been managing` נכון במשפט רגיל — וגם בשאלה עקיפה: `Do you know how long Ron has been managing it?`. בשאלה ישירה `has` קופץ לפני הנושא, ו-`been` נשאר אחריו.',
      source: [
        { id: 's1', t: 'how long' },
        { id: 's2', t: 'Ron' },
        { id: 's3', t: 'has' },
        { id: 's4', t: 'been' },
        { id: 's5', t: 'managing' },
        { id: 's6', t: 'the project' },
      ],
      tokens: [
        {
          id: 't1',
          t: 'is',
          why: '`is managing` מתאר את עכשיו (או תוכנית), לא כמה זמן זה כבר נמשך. המבנה נשאר `has … been managing`.',
          err: 'present_for_duration',
          as: 'meaning_mismatch',
        },
        { id: 't2', t: 'have', why: '`Ron` הוא אדם אחד, ולכן `has`, לא `have`.', err: 'have_agreement' },
        { id: 't3', t: 'managed' },
      ],
      accept: [
        { a: 'How long has Ron been managing the project', o: 'correct_target' },
        {
          a: 'How long has Ron managed the project',
          o: 'valid_alternative',
          note: 'גם נכון — present perfect פשוט. עם `manage` שתי הצורות מתאימות למשהו שעדיין נמשך.',
        },
      ],
      wrong: [
        {
          a: 'How long Ron has been managing the project',
          as: 'form_error',
          err: 'no_inversion',
          fb: 'בשאלה ישירה `has` בא לפני הנושא: `How long has Ron been managing the project?` (הסדר `Ron has been` נכון רק במשפט רגיל או בשאלה עקיפה.)',
        },
        {
          a: 'How long is Ron managing the project',
          as: 'meaning_mismatch',
          err: 'present_for_duration',
          fb: 'השאלה תקינה, אבל היא שואלת על תוכנית — עד מתי רון ינהל את הפרויקט. כדי לשאול כמה זמן זה כבר נמשך: `How long has Ron been managing the project?`',
        },
      ],
      rules: [
        {
          has: ['has been Ron'],
          as: 'form_error',
          err: 'aux_order',
          fb: 'רק `has` עובר לפני הנושא; `been` נשאר אחריו: `How long has Ron been managing the project?`',
        },
        {
          order: ['Ron', 'has'],
          as: 'form_error',
          err: 'no_inversion',
          fb: 'בשאלה ישירה `has` בא לפני הנושא: `How long has Ron been managing the project?`',
        },
        {
          has: ['has Ron managing'],
          lacks: ['been'],
          as: 'form_error',
          err: 'missing_been',
          fb: 'בין `Ron` ל-`managing` חסרה המילה `been`: `has Ron been managing`.',
        },
        {
          has: ['been managed'],
          as: 'form_error',
          err: 'been_v3',
          fb: 'אחרי `been` כאן בא פועל עם ing: `been managing` — או בלי `been`: `has Ron managed`.',
        },
        {
          has: ['is', 'been'],
          as: 'form_error',
          err: 'double_aux',
          fb: '`is` ו-`been` לא הולכים יחד כאן. למשך עד עכשיו: `How long has Ron been managing the project?`',
        },
        {
          has: ['is', 'managed'],
          as: 'form_error',
          err: 'be_v3',
          fb: '`is managed` הוא מבנה סביל — לא מה שצריך כאן. למשך עד עכשיו: `How long has Ron been managing the project?`',
        },
      ],
      end: '?',
    },
    {
      id: 'S04-11',
      v: 1,
      skill: 'S04',
      unit: 'S04',
      sub: 'question_stative',
      type: 'transform',
      role: 'practice',
      stage: 2,
      ctx: 'daily.shopping',
      fam: 'S04.avi-phone',
      goal: 'לנסח שאלת `How long` עם פועל מצב',
      instr: 'המשפט הזה הוא תשובה. הפוך אותו לשאלה שמתחילה ב-`How long` — השאלה שעליה הוא עונה.',
      sitHe: 'אבי סוף סוף קונה טלפון חדש. חבר שלו מספר לך:',
      target: 'שאלה שמתחילה ב-`How long`',
      fromLabel: 'משפט',
      toLabel: 'שאלה עם `How long`',
      hint: '`has` עובר לפני `Avi`. האם `had` צריך להשתנות?',
      explain: '`has` עובר לפני הנושא, ו-`had` נשאר — `have` במובן של בעלות הוא פועל מצב: `How long has Avi had his old phone?`',
      deep: '`has had` הוא present perfect של `have`: `has` הוא פועל העזר ו-`had` הוא צורת V3. בעלות היא מצב, ולכן אין כאן `been having`. `How long` מחליף את `since 2020`.',
      source: [
        { id: 's1', t: 'Avi' },
        { id: 's2', t: 'has' },
        { id: 's3', t: 'had' },
        { id: 's4', t: 'his old phone' },
        {
          id: 's5',
          t: 'since 2020',
          why: 'התבקשת שאלה עם `How long`. `How long` שואל בדיוק על המשך, ולכן `since 2020` לא נשאר בשאלה.',
          err: 'duration_kept',
          as: 'target_not_used',
        },
      ],
      sourceEnd: '.',
      tokens: [
        { id: 't1', t: 'how long' },
        {
          id: 't2',
          t: 'been',
          why: '`have` במובן של בעלות הוא פועל מצב — בלי `been` + ing: `How long has Avi had his old phone?`',
          err: 'stative_continuous',
        },
        {
          id: 't3',
          t: 'having',
          why: '`have` במובן של בעלות לא בא בצורת ing: `has Avi had`.',
          err: 'stative_continuous',
        },
        {
          id: 't4',
          t: 'did',
          why: '`did` שואל על תקופה שהסתיימה, ואחריו בא פועל בסיס. הטלפון עדיין שלו: `How long has Avi had…?`',
          err: 'did_for_ongoing',
        },
      ],
      accept: [{ a: 'How long has Avi had his old phone', o: 'correct_target' }],
      wrong: [
        {
          a: 'Avi has had his old phone since 2020',
          as: 'target_not_used',
          err: 'not_transformed',
          fb: 'זה המשפט המקורי — תקין, אבל התבקשת להפוך אותו לשאלה עם `How long`.',
        },
        {
          a: 'Avi has had his old phone',
          as: 'target_not_used',
          err: 'not_transformed',
          fb: 'משפט תקין — אבל התבקשת להפוך אותו לשאלה עם `How long`.',
        },
        {
          a: 'Has Avi had his old phone since 2020',
          as: 'target_not_used',
          err: 'yes_no_question',
          fb: 'שאלה תקינה — אבל זו שאלת כן/לא. התבקשת לשאול כמה זמן: `How long has Avi had his old phone?`',
        },
      ],
      rules: [
        {
          has: ['how long', 'since 2020'],
          as: 'form_error',
          err: 'duration_twice',
          fb: '`How long` כבר שואל על משך הזמן, ולכן `since 2020` יוצא מהשאלה.',
        },
        {
          order: ['Avi', 'has'],
          as: 'form_error',
          err: 'no_inversion',
          fb: 'בשאלה ישירה `has` בא לפני הנושא: `How long has Avi had his old phone?`',
        },
        {
          has: ['been having'],
          as: 'form_error',
          err: 'stative_continuous',
          fb: '`have` במובן של בעלות הוא פועל מצב ולא בא בצורת ing: `How long has Avi had his old phone?`',
        },
        {
          has: ['did', 'had'],
          as: 'form_error',
          err: 'did_v2',
          fb: 'אחרי `did` בא פועל בסיס — וממילא הטלפון עדיין שלו: `How long has Avi had his old phone?`',
        },
      ],
      end: '?',
    },
    {
      id: 'S04-D1',
      v: 2,
      skill: 'S04',
      unit: 'S04',
      sub: 'dialogue',
      type: 'dialogue',
      role: 'practice',
      stage: 2,
      ctx: 'daily.family',
      fam: 'S04.dialogue-cafe',
      goal: 'לשאול אם מישהי מחכה הרבה זמן, ולענות על שאלת `How long`',
      instr: 'ענה לתמר בכל תור.',
      partnerName: 'Tamar',
      setupHe: 'קבעת עם תמר, חברה, בבית קפה. איחרת ברבע שעה, והיא כבר יושבת ליד שולחן.',
      hint: 'בתור הראשון — שאלת כן/לא על המתנה שעדיין נמשכת. בתור השני — כמה זמן, עם `for`.',
      explain: '`Have you been waiting long?` — שאלת כן/לא על משך עד עכשיו. בתשובה: `I have been living there for two months`.',
      turns: [
        {
          partner: { en: 'Hi! I got us a table by the window.', he: 'היי! תפסתי לנו שולחן ליד החלון.' },
          sub: 'yes_no',
          instr: 'התנצלת על האיחור. עכשיו שאל אותה אם היא מחכה כבר הרבה זמן.',
          hint: 'שאלת כן/לא — בלי `how`. איזו מילה פותחת אותה, ואיפה `long`?',
          explain: 'היא התחילה לחכות לפני שהגעת, וההמתנה נמשכת עד עכשיו: `Have you been waiting long?`',
          build: {
            tokens: [
              { id: 't1', t: 'have' },
              { id: 't2', t: 'you' },
              { id: 't3', t: 'been' },
              { id: 't4', t: 'waiting' },
              { id: 't5', t: 'long' },
              {
                id: 't6',
                t: 'are',
                why: '`are you waiting` שואל על עכשיו. כדי לשאול אם ההמתנה כבר נמשכת הרבה זמן: `Have you been waiting long?`',
                err: 'present_for_duration',
                as: 'meaning_mismatch',
              },
              { id: 't7', t: 'has', why: 'עם `you` משתמשים ב-`have`, לא ב-`has`.', err: 'have_agreement' },
            ],
            accept: [{ a: 'Have you been waiting long', o: 'correct_target' }],
            rules: [
              {
                order: ['you', 'have'],
                as: 'form_error',
                err: 'no_inversion',
                fb: 'בשאלה `have` בא לפני `you`: `Have you been waiting long?`',
              },
              {
                has: ['have been you'],
                as: 'form_error',
                err: 'aux_order',
                fb: 'רק `have` עובר לפני `you`; `been` נשאר אחריו: `Have you been waiting long?`',
              },
              {
                has: ['have you waiting'],
                lacks: ['been'],
                as: 'form_error',
                err: 'missing_been',
                fb: 'בין `you` ל-`waiting` חסרה המילה `been`: `Have you been waiting long?`',
              },
              {
                has: ['are', 'been'],
                as: 'form_error',
                err: 'double_aux',
                fb: '`are` ו-`been` לא הולכים יחד. במקום `are` בא `have`: `Have you been waiting long?`',
              },
            ],
            end: '?',
          },
        },
        {
          partner: {
            en: "Only ten minutes, don't worry. So, how long have you been living in your new apartment?",
            he: 'רק עשר דקות, אל תדאג. אז כמה זמן אתה כבר גר בדירה החדשה?',
          },
          sub: 'answer',
          instr: 'ענה לה: עברת לדירה לפני חודשיים, ואתה עדיין גר שם.',
          target: 'משפט מלא עם `have` ומשך הזמן',
          hint: 'חודשיים הם פרק זמן — איזו מילה באה לפניו?',
          explain: 'משך עד עכשיו: `I have been living there for two months` — `for` לפני פרק זמן.',
          build: {
            tokens: [
              { id: 't1', t: 'I' },
              { id: 't2', t: 'have' },
              { id: 't3', t: 'been' },
              { id: 't4', t: 'living' },
              { id: 't5', t: 'lived' },
              { id: 't6', t: 'there' },
              { id: 't7', t: 'for' },
              { id: 't8', t: 'two months' },
              {
                id: 't9',
                t: 'since',
                why: '`since` בא לפני נקודת התחלה (`since May`). לפרק זמן כמו חודשיים: `for`.',
                err: 'since_period',
              },
              {
                id: 't10',
                t: 'am',
                why: '`am` מתאר את ההווה. כשאומרים כמה זמן זה נמשך עד עכשיו צריך `have`: `I have been living there…`',
                err: 'present_for_duration',
              },
            ],
            accept: [
              { a: 'I have been living there for two months', o: 'correct_target' },
              {
                a: 'I have lived there for two months',
                o: 'valid_alternative',
                note: 'גם נכון: עם `live` שתי הצורות מתאימות למשהו שעדיין נמשך.',
              },
              {
                a: 'For two months',
                o: 'target_not_used',
                note: 'תשובה קצרה וטבעית בשיחה. כאן התבקש משפט מלא: `I have been living there for two months`.',
              },
              {
                a: 'Two months',
                o: 'target_not_used',
                note: 'תשובה קצרה וטבעית בשיחה. כאן התבקש משפט מלא: `I have been living there for two months`.',
              },
              {
                a: 'I have been there for two months',
                o: 'valid_alternative',
                note: 'גם נכון: `been there` — "אני שם". אחרי `been` לא תמיד בא ing.',
              },
            ],
            wrong: [
              {
                a: 'I lived there for two months',
                as: 'meaning_mismatch',
                err: 'past_for_ongoing',
                fb: 'המשפט תקין, אבל בלי `have` הוא מתאר תקופה שהסתיימה — כאילו כבר לא גרים שם. אתה עדיין גר שם: `I have lived there for two months` או `I have been living there for two months`.',
              },
              {
                a: 'I am living there for two months',
                as: 'meaning_mismatch',
                err: 'present_for_duration',
                fb: 'המשפט הזה נשמע כמו סידור זמני מתוכנן — שתגור שם חודשיים. כדי לומר כמה זמן זה נמשך עד עכשיו: `I have been living there for two months`.',
              },
              {
                a: 'I am living there',
                as: 'target_not_used',
                err: 'missing_duration',
                fb: 'תקין, אבל הוא לא עונה כמה זמן. עם משך עד עכשיו עוברים ל-`have`: `I have been living there for two months`.',
              },
            ],
            rules: [
              {
                has: ['since two months'],
                as: 'form_error',
                err: 'since_period',
                fb: '`since` בא לפני נקודת התחלה (`since May`). לפרק זמן: `for two months`.',
              },
              {
                has: ['have living'],
                lacks: ['been'],
                as: 'form_error',
                err: 'missing_been',
                fb: 'בין `have` ל-`living` חסרה המילה `been`: `I have been living there`.',
              },
              {
                has: ['been lived'],
                as: 'form_error',
                err: 'been_v3',
                fb: 'אחרי `been` בא כאן פועל עם ing: `been living` — או בלי `been`: `I have lived there`.',
              },
            ],
            end: '.',
          },
        },
      ],
      closing: { en: "Two months already? Time flies. Let's order.", he: 'כבר חודשיים? הזמן טס. בוא נזמין.' },
    },
    {
      id: 'S04-D2',
      v: 2,
      skill: 'S04',
      unit: 'S04',
      sub: 'dialogue',
      type: 'dialogue',
      role: 'practice',
      stage: 3,
      ctx: 'work.job',
      fam: 'S04.dialogue-new-colleague',
      goal: 'לשאול על משך של משהו שעדיין נמשך — ושל משהו שכבר הסתיים',
      instr: 'ענה לנועה בכל תור.',
      partnerName: 'Noa',
      setupHe: 'במטבחון במשרד אתה פוגש את נועה, שעובדת בצוות השכן. עוד לא יצא לכם לדבר.',
      hint: 'בתור הראשון — משהו שעדיין נמשך. בתור השני — משהו שכבר הסתיים.',
      explain: 'עדיין עובדת כאן: `How long have you been working here?`. כבר לא עובדת שם: `How long did you work there?`',
      turns: [
        {
          partner: { en: "Hi, I'm Noa. I sit in the room next to yours.", he: 'היי, אני נועה. אני יושבת בחדר שליד החדר שלך.' },
          sub: 'question',
          instr: 'שאל אותה כמה זמן היא כבר עובדת כאן.',
          hint: 'היא עדיין עובדת כאן. מה בא אחרי `How long`?',
          explain: 'עדיין עובדת כאן: `How long have you been working here?` — או `How long have you worked here?`',
          build: {
            tokens: [
              { id: 't1', t: 'how long' },
              { id: 't2', t: 'have' },
              { id: 't3', t: 'you' },
              { id: 't4', t: 'been' },
              { id: 't5', t: 'working' },
              { id: 't6', t: 'worked' },
              { id: 't7', t: 'here' },
              {
                id: 't8',
                t: 'did',
                why: '`did` שואל על תקופה שהסתיימה. היא עדיין עובדת כאן: `have you been working` (או `have you worked`).',
                err: 'did_for_ongoing',
                as: 'meaning_mismatch',
              },
              {
                id: 't9',
                t: 'work',
                why: '`work` היא צורת הבסיס — היא באה אחרי `did` או `do`. היא עדיין עובדת כאן: `have you been working` או `have you worked`.',
                err: 'base_form',
              },
              {
                id: 't10',
                t: 'are',
                why: '`are you working` שואל על עכשיו או על תוכנית (עד מתי). כדי לשאול כמה זמן זה כבר נמשך: `have you been working`.',
                err: 'present_for_duration',
                as: 'meaning_mismatch',
              },
            ],
            accept: [
              { a: 'How long have you been working here', o: 'correct_target' },
              {
                a: 'How long have you worked here',
                o: 'valid_alternative',
                note: 'גם נכון: עם `work` גם present perfect פשוט מתאים למשהו שעדיין נמשך.',
              },
              {
                a: 'How long have you been here',
                o: 'valid_alternative',
                note: 'גם נכון וטבעי במקום עבודה: "כמה זמן את כאן?". אחרי `been` לא תמיד בא ing.',
              },
            ],
            wrong: [
              {
                a: 'How long did you work here',
                as: 'meaning_mismatch',
                err: 'did_for_ongoing',
                fb: 'השאלה תקינה, אבל `did` שואל על תקופה שהסתיימה — והיא עדיין עובדת כאן. כאן: `How long have you been working here?`',
              },
              {
                a: 'How long are you working here',
                as: 'meaning_mismatch',
                err: 'present_for_duration',
                fb: 'השאלה תקינה, אבל היא שואלת על תוכנית — עד מתי היא תעבוד כאן. כדי לשאול כמה זמן זה כבר נמשך: `How long have you been working here?`',
              },
            ],
            rules: [
              {
                order: ['you', 'have'],
                as: 'form_error',
                err: 'no_inversion',
                fb: 'בשאלה ישירה `have` בא לפני הנושא: `How long have you been working here?`',
              },
              {
                has: ['have you working'],
                lacks: ['been'],
                as: 'form_error',
                err: 'missing_been',
                fb: 'בין `you` ל-`working` חסרה המילה `been`: `have you been working`.',
              },
              {
                has: ['been worked'],
                as: 'form_error',
                err: 'been_v3',
                fb: 'אחרי `been` כאן בא פועל עם ing: `been working` — או בלי `been`: `have you worked`.',
              },
              {
                has: ['did', 'worked'],
                as: 'form_error',
                err: 'did_v2',
                fb: 'אחרי `did` בא פועל בסיס — ובכל מקרה היא עדיין עובדת כאן: `How long have you been working here?`',
              },
              {
                has: ['are', 'been'],
                as: 'form_error',
                err: 'double_aux',
                fb: '`are` ו-`been` לא הולכים יחד כאן. למשך עד עכשיו: `How long have you been working here?`',
              },
              {
                has: ['did', 'been'],
                as: 'form_error',
                err: 'did_with_perfect',
                fb: '`did` ו-`been` לא הולכים יחד. למשך עד עכשיו: `How long have you been working here?`',
              },
              {
                has: ['did', 'working'],
                as: 'form_error',
                err: 'did_ing',
                fb: 'אחרי `did` לא בא פועל עם ing. היא עדיין עובדת כאן: `How long have you been working here?`',
              },
            ],
            end: '?',
          },
        },
        {
          partner: {
            en: 'Almost three years. Before that, I was at a software company in Haifa for a while.',
            he: 'כמעט שלוש שנים. לפני זה הייתי תקופה בחברת תוכנה בחיפה.',
          },
          sub: 'contrast',
          instr: 'שאל אותה כמה זמן היא עבדה שם.',
          hint: 'האם היא עדיין עובדת שם?',
          explain: 'התקופה ההיא הסתיימה, ולכן עבר פשוט: `How long did you work there?`',
          build: {
            tokens: [
              { id: 't1', t: 'how long' },
              { id: 't2', t: 'did' },
              { id: 't3', t: 'you' },
              { id: 't4', t: 'work' },
              { id: 't5', t: 'there' },
              {
                id: 't6',
                t: 'worked',
                why: 'אחרי `did` בא פועל בסיס (`work`). ו-`have worked` היה אומר שהיא עדיין עובדת שם.',
                err: 'did_v2',
              },
              {
                id: 't7',
                t: 'have',
                why: '`have` מחבר את התקופה להווה — כאילו היא עדיין עובדת שם. התקופה הסתיימה: `did you work`.',
                err: 'perfect_for_finished',
                as: 'meaning_mismatch',
              },
              {
                id: 't8',
                t: 'been',
                why: '`been` + ing מתאר משהו שעדיין נמשך. היא כבר לא עובדת שם: `How long did you work there?`',
                err: 'perfect_for_finished',
              },
              {
                id: 't9',
                t: 'working',
                why: 'פועל עם ing מתאר כאן משהו שנמשך — אבל התקופה ההיא הסתיימה: `did you work`.',
                err: 'perfect_for_finished',
              },
            ],
            accept: [{ a: 'How long did you work there', o: 'correct_target' }],
            wrong: [
              {
                a: 'How long have you worked there',
                as: 'meaning_mismatch',
                err: 'perfect_for_finished',
                fb: 'השאלה תקינה, אבל `have you worked` שואל על משהו שנמשך עד היום — והיא כבר לא עובדת שם. לתקופה שהסתיימה: `How long did you work there?`',
              },
              {
                a: 'How long have you been working there',
                as: 'meaning_mismatch',
                err: 'perfect_for_finished',
                fb: 'השאלה תקינה, אבל היא מניחה שהיא עדיין עובדת שם. התקופה הסתיימה: `How long did you work there?`',
              },
            ],
            rules: [
              {
                has: ['did', 'worked'],
                as: 'form_error',
                err: 'did_v2',
                fb: 'אחרי `did` בא פועל בסיס: `did you work`, לא `did you worked`.',
              },
              {
                order: ['you', 'did'],
                as: 'form_error',
                err: 'no_inversion',
                fb: 'בשאלה ישירה `did` בא לפני הנושא: `How long did you work there?`',
              },
              {
                has: ['you worked'],
                lacks: ['did', 'have'],
                as: 'form_error',
                err: 'missing_did',
                fb: 'בשאלה בעבר פשוט צריך `did` לפני הנושא, והפועל חוזר לבסיס: `How long did you work there?`',
              },
              {
                has: ['have you work'],
                as: 'form_error',
                err: 'have_base',
                fb: 'אחרי `have` לא בא פועל בסיס — וממילא התקופה הסתיימה: `How long did you work there?`',
              },
            ],
            end: '?',
          },
        },
      ],
      closing: { en: 'About four years. Then I wanted something new.', he: 'בערך ארבע שנים. אחר כך רציתי משהו חדש.' },
    },
    {
      id: 'S04-C1',
      v: 1,
      skill: 'S04',
      unit: 'S04',
      sub: 'question',
      type: 'assemble',
      role: 'check',
      stage: 2,
      ctx: 'work.meeting',
      fam: 'S04.managers-inside',
      goal: 'לשאול כמה זמן ישיבה כבר נמשכת',
      instr: 'קרא את הסיטואציה ובנה שאלה אחת באנגלית. לא חייבים להשתמש בכל המילים.',
      sitEn: 'The managers went into the meeting room at nine. It is almost twelve, and they are still inside. You need to talk to one of them. Ask a colleague a question with "how long".',
      trHe: 'המנהלים נכנסו לחדר הישיבות בתשע. עכשיו כמעט שתים-עשרה, והם עדיין בפנים. אתה צריך לדבר עם אחד מהם. שאל עמית שאלה עם `how long`.',
      hint: 'הם התחילו בעבר ועדיין בפנים. מה בא לפני הנושא בשאלה?',
      explain: 'הם עדיין בפנים: `How long have they been talking?` — או `How long have they been in the meeting?`',
      deep: 'עם `they` בא `have`. אחרי `been` לא תמיד בא ing: `have they been in the meeting` ("כמה זמן הם בישיבה") תקין גם הוא. `How long are they in the meeting?` שואל על מה שמתוכנן — עד מתי — ולא על כמה זמן זה כבר נמשך.',
      tokens: [
        { id: 't1', t: 'how long' },
        { id: 't2', t: 'have' },
        { id: 't3', t: 'they' },
        { id: 't4', t: 'been' },
        { id: 't5', t: 'talking' },
        { id: 't6', t: 'in the meeting' },
        { id: 't7', t: 'has', why: 'עם `they` משתמשים ב-`have`, לא ב-`has`.', err: 'have_agreement' },
        {
          id: 't8',
          t: 'are',
          why: '`are they …` שואל על עכשיו או על מה שמתוכנן (עד מתי). כדי לשאול כמה זמן זה כבר נמשך: `have they been`.',
          err: 'present_for_duration',
          as: 'meaning_mismatch',
        },
        {
          id: 't9',
          t: 'did',
          why: '`did` שואל על משהו שהסתיים. הם עדיין בפנים: `How long have they been…?`',
          err: 'did_for_ongoing',
        },
      ],
      accept: [
        { a: 'How long have they been talking', o: 'correct_target' },
        { a: 'How long have they been talking in the meeting', o: 'correct_target' },
        {
          a: 'How long have they been in the meeting',
          o: 'valid_alternative',
          note: 'גם נכון: `been in the meeting` — "הם בישיבה". אחרי `been` לא תמיד בא ing.',
        },
      ],
      wrong: [
        {
          a: 'How long are they in the meeting',
          as: 'meaning_mismatch',
          err: 'present_for_duration',
          fb: 'השאלה תקינה, אבל היא שואלת על מה שמתוכנן — עד מתי הם בישיבה. כדי לשאול כמה זמן זה כבר נמשך: `How long have they been in the meeting?`',
        },
        {
          a: 'How long are they talking',
          as: 'meaning_mismatch',
          err: 'present_for_duration',
          fb: 'השאלה שואלת על עכשיו או על מה שמתוכנן, לא כמה זמן זה כבר נמשך: `How long have they been talking?`',
        },
      ],
      rules: [
        {
          order: ['they', 'have'],
          as: 'form_error',
          err: 'no_inversion',
          fb: 'בשאלה ישירה `have` בא לפני הנושא: `How long have they been talking?`',
        },
        {
          has: ['have been they'],
          as: 'form_error',
          err: 'aux_order',
          fb: 'רק `have` עובר לפני הנושא; `been` נשאר אחריו: `How long have they been talking?`',
        },
        {
          has: ['have they talking'],
          lacks: ['been'],
          as: 'form_error',
          err: 'missing_been',
          fb: 'בין `they` ל-`talking` חסרה המילה `been`: `have they been talking`.',
        },
        {
          has: ['are', 'been'],
          as: 'form_error',
          err: 'double_aux',
          fb: '`are` ו-`been` לא הולכים יחד כאן. למשך עד עכשיו: `How long have they been talking?`',
        },
      ],
      end: '?',
    },
    {
      id: 'S04-C2',
      v: 1,
      skill: 'S04',
      unit: 'S04',
      sub: 'question',
      type: 'correct',
      role: 'check',
      stage: 2,
      ctx: 'daily.health',
      fam: 'S04.yoga',
      goal: 'לשאול חברה כמה זמן היא כבר עושה יוגה',
      instr: 'אם יש טעות — גע במילה או ברווח ובחר תיקון. אם המשפט תקין, בחר "אין צורך בתיקון".',
      sitHe: 'חברה מספרת שהיא עושה יוגה פעמיים בשבוע, כבר די הרבה זמן. כתבת לה שאלה:',
      hint: 'היא עושה יוגה כבר הרבה זמן ועדיין ממשיכה. האם `are` מתאים לזה?',
      explain: '`are you doing` שואל על עכשיו. כדי לשאול כמה זמן זה כבר נמשך: `How long have you been doing yoga?`',
      deep: 'בעברית "כמה זמן את עושה יוגה" נאמר בהווה. באנגלית `How long are you doing yoga?` שואל על עכשיו או על תוכנית (למשל כמה זמן יימשך האימון היום). משך עד עכשיו: `have you been doing`.',
      source: [
        { id: 's1', t: 'how long' },
        {
          id: 's2',
          t: 'are',
          why: '`are you doing` שואל על עכשיו או על תוכנית, לא כמה זמן זה כבר נמשך. כאן: `have you been doing`.',
          err: 'present_for_duration',
        },
        { id: 's3', t: 'you' },
        { id: 's4', t: 'doing' },
        { id: 's5', t: 'yoga' },
      ],
      tokens: [
        { id: 't1', t: 'have' },
        { id: 't2', t: 'been' },
        { id: 't3', t: 'has', why: 'עם `you` משתמשים ב-`have`, לא ב-`has`.', err: 'have_agreement' },
        {
          id: 't4',
          t: 'did',
          why: '`did` שואל על משהו שהסתיים, ואחריו בא פועל בסיס. היא עדיין עושה יוגה: `How long have you been doing yoga?`',
          err: 'did_for_ongoing',
        },
      ],
      accept: [{ a: 'How long have you been doing yoga', o: 'correct_target' }],
      wrong: [
        {
          a: 'How long are you doing yoga',
          as: 'meaning_mismatch',
          err: 'present_for_duration',
          fb: 'בעברית "כמה זמן את עושה יוגה" נאמר בהווה. באנגלית `are you doing` שואל על עכשיו או על תוכנית; כדי לשאול כמה זמן זה כבר נמשך: `How long have you been doing yoga?`',
        },
        {
          a: 'Are you doing yoga',
          as: 'meaning_mismatch',
          err: 'no_how_long',
          fb: 'שאלה תקינה, אבל היא שואלת אם היא עושה יוגה עכשיו — לא כמה זמן. כאן: `How long have you been doing yoga?`',
        },
      ],
      rules: [
        {
          has: ['are', 'been'],
          as: 'form_error',
          err: 'double_aux',
          fb: '`are` ו-`been` לא הולכים יחד. במקום `are` בא `have`: `How long have you been doing yoga?`',
        },
        {
          has: ['are', 'have'],
          as: 'form_error',
          err: 'double_aux',
          fb: '`are` ו-`have` לא הולכים יחד. הסר את `are`: `How long have you been doing yoga?`',
        },
        {
          has: ['have you doing'],
          lacks: ['been'],
          as: 'form_error',
          err: 'missing_been',
          fb: 'בין `you` ל-`doing` חסרה המילה `been`: `have you been doing`.',
        },
        {
          order: ['you', 'have'],
          as: 'form_error',
          err: 'no_inversion',
          fb: 'בשאלה ישירה `have` בא לפני הנושא: `How long have you been doing yoga?`',
        },
      ],
      end: '?',
    },
    {
      id: 'S04-C3',
      v: 1,
      skill: 'S04',
      unit: 'S04',
      sub: 'contrast',
      type: 'assemble',
      role: 'check',
      stage: 3,
      ctx: 'work.municipality',
      fam: 'S04.planning-before',
      goal: 'לשאול על תקופה שהסתיימה',
      instr: 'בנה שאלה אחת באנגלית. לא חייבים להשתמש בכל המילים.',
      sitHe: 'עמית חדש במחלקה שלך עבד כמה שנים במחלקת התכנון של העירייה, ובחודש שעבר עבר אליכם. אתה רוצה לדעת כמה זמן הוא עבד שם.',
      hint: 'האם הוא עדיין עובד במחלקת התכנון?',
      explain: 'התקופה בתכנון הסתיימה, ולכן עבר פשוט: `How long did you work in planning?`',
      deep: '`in planning` = במחלקת התכנון. `How long have you worked in planning?` היה מתאים רק אם הוא עדיין עובד שם. בשאלה בעבר פשוט `did` בא לפני הנושא, והפועל בצורת בסיס.',
      tokens: [
        { id: 't1', t: 'how long' },
        { id: 't2', t: 'did' },
        { id: 't3', t: 'you' },
        { id: 't4', t: 'work' },
        { id: 't5', t: 'in planning' },
        {
          id: 't6',
          t: 'worked',
          why: 'אחרי `did` בא פועל בסיס (`work`). ו-`have worked` היה אומר שהוא עדיין עובד שם.',
          err: 'did_v2',
        },
        {
          id: 't7',
          t: 'have',
          why: '`have` מחבר את התקופה להווה — כאילו הוא עדיין עובד שם. התקופה הסתיימה: `did you work`.',
          err: 'perfect_for_finished',
          as: 'meaning_mismatch',
        },
        {
          id: 't8',
          t: 'been',
          why: '`been` + ing מתאר משהו שעדיין נמשך. הוא כבר לא עובד שם: `How long did you work in planning?`',
          err: 'perfect_for_finished',
        },
        {
          id: 't9',
          t: 'working',
          why: 'פועל עם ing מתאר כאן משהו שנמשך — אבל התקופה ההיא הסתיימה: `did you work`.',
          err: 'perfect_for_finished',
        },
      ],
      accept: [{ a: 'How long did you work in planning', o: 'correct_target' }],
      wrong: [
        {
          a: 'How long have you worked in planning',
          as: 'meaning_mismatch',
          err: 'perfect_for_finished',
          fb: 'השאלה תקינה, אבל `have you worked` מניח שהוא עדיין עובד בתכנון. התקופה הסתיימה: `How long did you work in planning?`',
        },
        {
          a: 'How long have you been working in planning',
          as: 'meaning_mismatch',
          err: 'perfect_for_finished',
          fb: 'השאלה תקינה, אבל היא מניחה שהוא עדיין עובד בתכנון. התקופה הסתיימה: `How long did you work in planning?`',
        },
      ],
      rules: [
        {
          has: ['did', 'worked'],
          as: 'form_error',
          err: 'did_v2',
          fb: 'אחרי `did` בא פועל בסיס: `did you work`, לא `did you worked`.',
        },
        {
          order: ['you', 'did'],
          as: 'form_error',
          err: 'no_inversion',
          fb: 'בשאלה ישירה `did` בא לפני הנושא: `How long did you work in planning?`',
        },
        {
          has: ['you worked'],
          lacks: ['did', 'have'],
          as: 'form_error',
          err: 'missing_did',
          fb: 'בשאלה בעבר פשוט צריך `did` לפני הנושא, והפועל חוזר לבסיס: `How long did you work in planning?`',
        },
        {
          has: ['have you work'],
          as: 'form_error',
          err: 'have_base',
          fb: 'אחרי `have` לא בא פועל בסיס — וממילא התקופה הסתיימה: `How long did you work in planning?`',
        },
      ],
      end: '?',
    },
  ],
};
