import type { SkillPack } from '../schema';

/**
 * S05 FOR_SINCE.
 * Item S05-01 belongs to the scripted first segment: keep it unchanged.
 */
export const S05: SkillPack = {
  skill: 'S05',
  lessons: [
    {
      unit: 'S05',
      title: '`for` או `since`: כמה זמן, או ממתי',
      short:
        '`for` + כמה זמן (`for two hours`, `for years`); `since` + מאיזו נקודה (`since Monday`, `since 2023`, `since I moved here`). כשמשהו נמשך עד עכשיו, שניהם באים עם present perfect.',
      chain: ['have / has + V3 / been + V-ing', 'for + פרק זמן', 'since + נקודת התחלה'],
      examples: [
        { en: 'I have been waiting for twenty minutes.', he: 'אני מחכה כבר עשרים דקות.' },
        { en: "We've lived here since 2023.", he: 'אנחנו גרים כאן מ-2023.' },
        {
          en: 'I have known him since we worked together.',
          he: 'אני מכיר אותו מאז שעבדנו יחד.',
          note: 'אחרי `since` אפשר משפט שלם, בעבר פשוט.',
        },
      ],
      contrast: {
        a: { en: 'I started the report two hours ago.', he: 'התחלתי את הדוח לפני שעתיים.' },
        b: { en: 'I have been working on the report for two hours.', he: 'אני עובד על הדוח כבר שעתיים.' },
        note: '`ago` אומר מתי משהו קרה, ובא עם עבר פשוט. `for` אומר כמה זמן — וכשזה נמשך עד עכשיו, עם present perfect. `since` אומר מאיזו נקודה: `since nine`.',
      },
      deep:
        '• `for` + פרק זמן: `for ten minutes`, `for three years`, `for a long time`, `for ages`.\n' +
        "• `since` + נקודת התחלה: יום (`since Monday`), שנה (`since 2023`), שעה (`since nine o'clock`), אירוע (`since the meeting`), או משפט בעבר פשוט (`since I moved here`, `since the meeting started`).\n" +
        '• בעברית "מ-" ו"כבר" מכסים את שניהם. באנגלית בודקים מה בא אחרי: כמה זמן → `for`; ממתי → `since`. כשמשהו נמשך עד עכשיו לא אומרים `from Monday` או `from two hours`; `from` בא בדרך כלל בצירוף `from … to …`.\n' +
        '• החלק הראשי הוא present perfect: `I have worked here since 2020` — לא `I work here since 2020`. פעלי מצב (`know`, `have`, `be`) בלי ing: `I have known him since 2019`.\n' +
        '• `ago` שייך לעבר פשוט: `I started two hours ago`. את אותה עובדה אפשר לומר כמשך עד עכשיו: `I have been working for two hours`.\n' +
        '• `for` מתאים גם לתקופה שהסתיימה — ואז עם עבר פשוט: `I lived in Haifa for two years` (כבר לא גר שם).\n' +
        '• המשפט שאחרי `since` מתאר את נקודת ההתחלה, ולכן בדרך כלל בעבר פשוט: `since we met`, `since I moved here`.\n' +
        "• במשפט שלילי אפשר גם `in`, בעיקר באנגלית אמריקאית: `I haven't seen him in years` = `I haven't seen him for years`.",
      pitfalls: [
        '`since two hours` — לפרק זמן: `for two hours`.',
        '`for Monday` — לנקודת התחלה: `since Monday`.',
        '`from two hours` — `for two hours`.',
        '`I work here since 2020` — עם `since` החלק הראשי ב-present perfect: `I have worked here since 2020`.',
        '`I have started two hours ago` — עם `ago` עבר פשוט: `I started two hours ago`.',
      ],
    },
  ],
  examples: {
    S05: [
      { en: "It hasn't rained for weeks.", he: 'כבר שבועות שלא ירד גשם.' },
      { en: 'She has been much calmer since the meeting ended.', he: 'היא הרבה יותר רגועה מאז שהפגישה נגמרה.' },
      { en: "We've had this printer for ages.", he: 'המדפסת הזאת אצלנו כבר נצח.' },
      { en: "The shop has been closed since nine o'clock.", he: 'החנות סגורה מתשע.' },
    ],
  },
  items: [
    {
      id: 'S05-01',
      v: 1,
      skill: 'S05',
      unit: 'S05',
      sub: 'contrast',
      type: 'assemble',
      role: 'practice',
      stage: 3,
      ctx: 'work.meeting',
      fam: 'S05.meeting-nine',
      goal: 'לומר כמה זמן הפגישה כבר נמשכת',
      instr: 'בנה משפט באנגלית. אפשר עם `for` ואפשר עם `since` — בחר אחד והתאם אליו את הזמן.',
      sitHe: 'הפגישה התחילה בתשע. עכשיו אחת-עשרה, ואתם עדיין מדברים.',
      hint: '`for` + כמה זמן; `since` + מאיזו נקודה.',
      explain:
        '`for two hours` — כמה זמן זה נמשך; `since nine` — ממתי זה התחיל. שניהם מתאימים כאן, כל אחד עם סוג הזמן שלו.',
      tokens: [
        { id: 't1', t: 'we' },
        { id: 't2', t: 'have' },
        { id: 't3', t: 'been' },
        { id: 't4', t: 'talking' },
        { id: 't5', t: 'for' },
        { id: 't6', t: 'since' },
        { id: 't7', t: 'two hours' },
        { id: 't8', t: 'nine' },
        {
          id: 't9',
          t: 'are',
          why: '`are talking` מתאר רק את מה שקורה עכשיו. כדי לומר כמה זמן זה נמשך עד עכשיו: `have been talking`.',
          err: 'present_for_duration',
        },
      ],
      accept: [
        { a: 'We have been talking for two hours', o: 'correct_target' },
        { a: 'We have been talking since nine', o: 'correct_target' },
      ],
      wrong: [
        {
          a: 'We are talking for two hours',
          as: 'meaning_mismatch',
          err: 'present_for_duration',
          fb: '`We are talking for two hours` נשמע כמו תוכנית ("נדבר שעתיים"). כדי לומר שזה כבר נמשך שעתיים עד עכשיו: `We have been talking for two hours`.',
        },
      ],
      rules: [
        {
          has: ['for nine'],
          as: 'form_error',
          err: 'for_point',
          fb: '`for` בא לפני פרק זמן (`for two hours`). לפני שעה מסוימת (`nine`) משתמשים ב-`since`.',
        },
        {
          has: ['since two hours'],
          as: 'form_error',
          err: 'since_period',
          fb: '`since` בא לפני נקודת התחלה (`since nine`). לפרק זמן: `for two hours`.',
        },
        {
          has: ['have talking'],
          lacks: ['been'],
          as: 'form_error',
          err: 'missing_been',
          fb: 'בין `have` ל-`talking` חסרה המילה `been`: `have been talking`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S05-02',
      v: 1,
      skill: 'S05',
      unit: 'S05',
      sub: 'since',
      type: 'assemble',
      role: 'practice',
      stage: 1,
      ctx: 'work.email',
      fam: 'S05.reach-them-monday',
      goal: 'לומר ממתי אתה מנסה להשיג מחלקה אחרת',
      instr: 'בנה את המשפט באנגלית. לא חייבים להשתמש בכל המילים.',
      promptHe: 'אני מנסה להשיג אותם מיום שני.',
      sitHe: 'ביום שני התחלת להתקשר ולכתוב למחלקת הכספים. היום חמישי, ועדיין לא הצלחת להשיג אותם.',
      scaffold: ['have been + V-ing', 'for + פרק זמן / since + נקודת התחלה'],
      hint: '"מיום שני" — נקודה שממנה זה התחיל, או פרק זמן?',
      explain: '`Monday` הוא נקודת התחלה, ולכן `since Monday`. "מ-" בעברית כאן הוא `since`, לא `from`.',
      deep: 'בעברית "מיום שני" — עם "מ-". באנגלית, כשמשהו התחיל בנקודה מסוימת ונמשך עד עכשיו, משתמשים ב-`since`. `from Monday` מתאים לצירוף `from Monday to Thursday`, או להתחלה בעתיד: `from next Monday`.',
      tokens: [
        { id: 't1', t: 'I' },
        { id: 't2', t: 'have' },
        { id: 't3', t: 'been' },
        { id: 't4', t: 'trying' },
        { id: 't5', t: 'to reach them' },
        { id: 't6', t: 'since' },
        { id: 't7', t: 'Monday' },
        {
          id: 't8',
          t: 'for',
          why: '`for` בא לפני פרק זמן (`for three days`). לפני יום שבו זה התחיל: `since Monday`.',
          err: 'for_point',
        },
        {
          id: 't9',
          t: 'from',
          why: 'כאן לא אומרים `from Monday`: למשהו שהתחיל ביום שני ונמשך עד עכשיו משתמשים ב-`since`. (`from` בא בדרך כלל בצירוף `from … to …`.)',
          err: 'from_for_since',
        },
        {
          id: 't10',
          t: 'am',
          why: '`am trying` מתאר רק את עכשיו. עם `since` — מאז ועד עכשיו — צריך `have been trying`.',
          err: 'present_for_duration',
        },
      ],
      accept: [
        { a: 'I have been trying to reach them since Monday', o: 'correct_target' },
        {
          a: 'Since Monday, I have been trying to reach them',
          o: 'valid_alternative',
          note: 'גם נכון: `since Monday` בתחילת המשפט.',
        },
      ],
      wrong: [
        {
          a: 'I am trying to reach them since Monday',
          as: 'form_error',
          err: 'present_for_duration',
          fb: 'בעברית "אני מנסה" — בהווה. באנגלית, עם `since` (מאז ועד עכשיו) צריך present perfect: `I have been trying to reach them since Monday`.',
        },
        {
          a: 'I am trying to reach them',
          as: 'meaning_mismatch',
          err: 'missing_duration',
          fb: 'המשפט תקין, אבל חסר ממתי — "מיום שני". כשמוסיפים `since Monday` עוברים ל-present perfect: `I have been trying to reach them since Monday`.',
        },
      ],
      rules: [
        {
          has: ['for Monday'],
          as: 'form_error',
          err: 'for_point',
          fb: '`for` בא לפני פרק זמן (`for three days`). לפני יום שבו זה התחיל: `since Monday`.',
        },
        {
          has: ['from Monday'],
          as: 'form_error',
          err: 'from_for_since',
          fb: 'למשהו שהתחיל ביום שני ונמשך עד עכשיו: `since Monday`, לא `from Monday`.',
        },
        {
          has: ['have trying'],
          lacks: ['been'],
          as: 'form_error',
          err: 'missing_been',
          fb: 'בין `have` ל-`trying` חסרה המילה `been`: `I have been trying`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S05-03',
      v: 2,
      skill: 'S05',
      unit: 'S05',
      sub: 'for',
      type: 'assemble',
      role: 'practice',
      stage: 1,
      ctx: 'daily.home',
      fam: 'S05.apartment-six-years',
      goal: 'לומר כמה זמן אתם גרים בדירה',
      instr: 'בנה את המשפט באנגלית. לא חייבים להשתמש בכל המילים.',
      promptHe: 'אנחנו גרים בדירה הזאת כבר שש שנים.',
      scaffold: ['have + V3 / have been + V-ing', 'for + פרק זמן / since + נקודת התחלה'],
      hint: '"כבר שש שנים" — פרק זמן. איזו מילה באה לפניו?',
      explain: '`six years` הוא פרק זמן, ולכן `for six years`. משך עד עכשיו — present perfect: `We have lived in this apartment for six years`.',
      deep: 'בעברית "אנחנו גרים ... כבר שש שנים" — בהווה. באנגלית: present perfect (`have lived` או `have been living`) + `for`. `We live here for six years` הוא העתקה מהעברית ואינו תקין.',
      tokens: [
        { id: 't1', t: 'we' },
        { id: 't2', t: 'have' },
        { id: 't3', t: 'lived' },
        { id: 't4', t: 'been' },
        { id: 't5', t: 'living' },
        { id: 't6', t: 'in this apartment' },
        { id: 't7', t: 'for' },
        { id: 't8', t: 'six years' },
        {
          id: 't9',
          t: 'since',
          why: '`since` בא לפני נקודת התחלה (`since 2020`). לפרק זמן כמו שש שנים: `for`.',
          err: 'since_period',
        },
        {
          id: 't10',
          t: 'live',
          why: '`live` היא צורת ההווה/הבסיס. למשך שנמשך עד עכשיו צריך `have lived` (או `have been living`).',
          err: 'present_for_duration',
        },
      ],
      accept: [
        { a: 'We have lived in this apartment for six years', o: 'correct_target' },
        { a: 'We have been living in this apartment for six years', o: 'correct_target' },
        {
          a: 'For six years, we have lived in this apartment',
          o: 'valid_alternative',
          note: 'גם נכון, אבל פחות שכיח. הסדר הרגיל: `We have lived in this apartment for six years`.',
        },
        {
          a: 'For six years, we have been living in this apartment',
          o: 'valid_alternative',
          note: 'גם נכון, אבל פחות שכיח. הסדר הרגיל: `We have been living in this apartment for six years`.',
        },
        {
          a: 'We have been in this apartment for six years',
          o: 'valid_alternative',
          note: 'גם נכון: `have been in this apartment` — "אנחנו בדירה הזאת". כדי לומר במפורש "גרים": `have lived` או `have been living`.',
        },
      ],
      wrong: [
        {
          a: 'We live in this apartment for six years',
          as: 'form_error',
          err: 'present_for_duration',
          fb: 'בעברית "אנחנו גרים" — בהווה. באנגלית, כשאומרים כמה זמן זה נמשך עד עכשיו: `We have lived in this apartment for six years`.',
        },
        {
          a: 'We live in this apartment',
          as: 'meaning_mismatch',
          err: 'missing_duration',
          fb: 'המשפט תקין, אבל חסר כמה זמן — "כבר שש שנים". כשמוסיפים `for six years` עוברים ל-present perfect: `We have lived in this apartment for six years`.',
        },
      ],
      rules: [
        {
          has: ['since six years'],
          as: 'form_error',
          err: 'since_period',
          fb: '`since` בא לפני נקודת התחלה (`since 2020`). לפרק זמן: `for six years`.',
        },
        {
          has: ['have living'],
          lacks: ['been'],
          as: 'form_error',
          err: 'missing_been',
          fb: 'בין `have` ל-`living` חסרה המילה `been`: `have been living`.',
        },
        {
          has: ['been lived'],
          as: 'form_error',
          err: 'been_v3',
          fb: 'אחרי `been` בא כאן פועל עם ing: `been living` — או בלי `been`: `have lived`.',
        },
        {
          has: ['we lived'],
          lacks: ['have'],
          as: 'meaning_mismatch',
          err: 'past_for_ongoing',
          fb: 'המשפט תקין, אבל בלי `have` הוא מתאר תקופה שהסתיימה — כאילו כבר לא גרים בדירה. אתם עדיין גרים בה: `We have lived in this apartment for six years`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S05-04',
      v: 2,
      skill: 'S05',
      unit: 'S05',
      sub: 'since',
      type: 'correct',
      role: 'practice',
      stage: 1,
      ctx: 'work.job',
      fam: 'S05.work-here-2020',
      goal: 'לומר ממתי אתה עובד במקום',
      instr: 'אם יש טעות — גע במילה או ברווח ובחר תיקון. אם המשפט תקין, בחר "אין צורך בתיקון".',
      sitHe: 'עמית חדש שואל ממתי אתה עובד בחברה. התחלת ב-2020, ואתה עדיין כאן. כתבת לו:',
      scaffold: ['have + V3 / have been + V-ing', 'since + נקודת התחלה'],
      hint: '`since 2020` נכון. בדוק את הפועל: מאז ועד עכשיו.',
      explain: 'עם `since` (מאז ועד עכשיו) החלק הראשי הוא present perfect: `I have worked here since 2020` או `I have been working here since 2020`.',
      deep: 'בעברית "אני עובד כאן מ-2020" — בהווה. באנגלית ההווה הפשוט (`I work`) לא מתחבר ל-`since`. `since 2020` עצמו נכון — 2020 היא נקודת התחלה.',
      source: [
        { id: 's1', t: 'I' },
        {
          id: 's2',
          t: 'work',
          why: '`work` בהווה פשוט לא מתחבר ל-`since`. מאז ועד עכשיו: `have worked` או `have been working`.',
          err: 'present_for_duration',
        },
        { id: 's3', t: 'here' },
        { id: 's4', t: 'since' },
        { id: 's5', t: '2020' },
      ],
      tokens: [
        { id: 't1', t: 'have' },
        { id: 't2', t: 'worked' },
        { id: 't3', t: 'been' },
        { id: 't4', t: 'working' },
        {
          id: 't5',
          t: 'for',
          why: '`for` בא לפני פרק זמן (`for six years`). לפני שנה שבה זה התחיל: `since 2020`.',
          err: 'for_point',
        },
        {
          id: 't6',
          t: 'am',
          why: '`am working` מתאר רק את עכשיו. עם `since` צריך `have been working`.',
          err: 'present_for_duration',
        },
      ],
      accept: [
        { a: 'I have worked here since 2020', o: 'correct_target' },
        { a: 'I have been working here since 2020', o: 'correct_target' },
        {
          a: 'Since 2020, I have worked here',
          o: 'valid_alternative',
          note: 'גם נכון: `since 2020` בתחילת המשפט.',
        },
        {
          a: 'Since 2020, I have been working here',
          o: 'valid_alternative',
          note: 'גם נכון: `since 2020` בתחילת המשפט.',
        },
        {
          a: 'I have been here since 2020',
          o: 'valid_alternative',
          note: 'גם נכון וטבעי: "אני כאן מ-2020" — `have been` ומקום, בלי ing.',
        },
      ],
      wrong: [
        {
          a: 'I work here',
          as: 'meaning_mismatch',
          err: 'missing_duration',
          fb: 'המשפט תקין, אבל נמחק ממנו ממתי. `since 2020` נכון — רק הפועל צריך present perfect: `I have worked here since 2020`.',
        },
        {
          a: 'I am working here',
          as: 'meaning_mismatch',
          err: 'missing_duration',
          fb: 'המשפט תקין, אבל נמחק ממנו ממתי. `since 2020` נכון — רק הפועל צריך present perfect: `I have been working here since 2020`.',
        },
        {
          a: 'I work here since 2020',
          as: 'form_error',
          err: 'present_for_duration',
          fb: 'בעברית "אני עובד כאן מ-2020" — בהווה. באנגלית, עם `since` צריך present perfect: `I have worked here since 2020`.',
        },
        {
          a: 'I am working here since 2020',
          as: 'form_error',
          err: 'present_for_duration',
          fb: '`am working` מתאר את ההווה. עם `since` — מאז ועד עכשיו: `I have been working here since 2020`.',
        },
      ],
      rules: [
        {
          has: ['for 2020'],
          as: 'form_error',
          err: 'for_point',
          fb: '`for` בא לפני פרק זמן (`for six years`). לפני שנה שבה זה התחיל: `since 2020`.',
        },
        {
          has: ['have work'],
          as: 'form_error',
          err: 'have_base',
          fb: 'אחרי `have` בא V3: `have worked`.',
        },
        {
          has: ['have working'],
          lacks: ['been'],
          as: 'form_error',
          err: 'missing_been',
          fb: 'בין `have` ל-`working` חסרה המילה `been`: `have been working`.',
        },
        {
          has: ['been worked'],
          as: 'form_error',
          err: 'been_v3',
          fb: 'אחרי `been` בא כאן פועל עם ing: `been working` — או בלי `been`: `have worked`.',
        },
        {
          has: ['i worked', 'since'],
          lacks: ['have'],
          as: 'form_error',
          err: 'past_for_duration',
          fb: 'עם `since` (מאז ועד עכשיו) לא משתמשים בעבר פשוט: `I have worked here since 2020` או `I have been working here since 2020`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S05-05',
      v: 2,
      skill: 'S05',
      unit: 'S05',
      sub: 'contrast',
      type: 'transform',
      role: 'practice',
      stage: 2,
      ctx: 'daily.travel',
      fam: 'S05.train-since-ten',
      goal: 'לומר את אותו משך בעזרת נקודת ההתחלה',
      instr: 'נסח את אותו משפט עם `since` במקום `for`.',
      sitHe: 'אתם מחכים לרכבת בתחנה. התחלתם לחכות בעשר, ועכשיו 10:40.',
      target: 'אותו משפט עם `since` + נקודת ההתחלה',
      fromLabel: '`for` + פרק זמן',
      toLabel: '`since` + נקודת התחלה',
      hint: 'מתי התחלתם לחכות? זו נקודת ההתחלה.',
      explain: 'התחלתם בעשר: `We have been waiting since ten`. `for forty minutes` ו-`since ten` אומרים אותו דבר — כל אחד עם סוג הזמן שלו.',
      deep: '`for` מודד כמה זמן (`forty minutes`); `since` מצביע על נקודת ההתחלה (`ten`). החלק `We have been waiting` לא משתנה — רק ביטוי הזמן.',
      source: [
        { id: 's1', t: 'we' },
        { id: 's2', t: 'have' },
        { id: 's3', t: 'been' },
        { id: 's4', t: 'waiting' },
        {
          id: 's5',
          t: 'for',
          why: 'התבקשת לנסח עם `since`. `for` בא לפני פרק זמן, ו-`ten` הוא נקודת התחלה.',
          err: 'for_kept',
          as: 'target_not_used',
        },
        {
          id: 's6',
          t: 'forty minutes',
          why: 'התבקשת לנסח עם `since`. `forty minutes` הוא פרק זמן — הוא הולך עם `for`; עם `since` צריך את נקודת ההתחלה: `since ten`.',
          err: 'period_kept',
          as: 'target_not_used',
        },
      ],
      sourceEnd: '.',
      tokens: [
        { id: 't1', t: 'since' },
        { id: 't2', t: 'ten' },
        {
          id: 't3',
          t: 'from',
          why: '`from` לא מתאים כאן: למשהו שנמשך עד עכשיו — `since ten` (ממתי) או `for forty minutes` (כמה זמן).',
          err: 'from_for_since',
        },
      ],
      accept: [
        { a: 'We have been waiting since ten', o: 'correct_target' },
        {
          a: 'Since ten, we have been waiting',
          o: 'valid_alternative',
          note: 'גם נכון, אבל פחות שכיח. הסדר הרגיל: `We have been waiting since ten`.',
        },
      ],
      wrong: [
        {
          a: 'We have been waiting for forty minutes',
          as: 'target_not_used',
          err: 'not_transformed',
          fb: 'המשפט המקורי תקין — אבל התבקשת לנסח אותו עם `since` ונקודת ההתחלה: `We have been waiting since ten`.',
        },
      ],
      rules: [
        {
          has: ['for ten'],
          as: 'form_error',
          err: 'for_point',
          fb: '`for` בא לפני פרק זמן. לפני שעה שבה זה התחיל: `since ten`.',
        },
        {
          has: ['since forty minutes'],
          as: 'form_error',
          err: 'since_period',
          fb: '`since` בא לפני נקודת התחלה (`since ten`). לפרק זמן: `for forty minutes`.',
        },
        {
          has: ['have waiting'],
          lacks: ['been'],
          as: 'form_error',
          err: 'missing_been',
          fb: 'בין `have` ל-`waiting` חסרה המילה `been`: `We have been waiting since ten`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S05-06',
      v: 2,
      skill: 'S05',
      unit: 'S05',
      sub: 'ago',
      type: 'assemble',
      role: 'practice',
      stage: 3,
      ctx: 'work.project',
      fam: 'S05.joined-three-months',
      goal: 'לספר לעמית חדש ממתי אתה בפרויקט',
      instr: 'בנה משפט אחד — עם `ago` או עם `for`. לא חייבים להשתמש בכל המילים.',
      sitHe: 'הצטרפת לפרויקט לפני שלושה חודשים, ואתה עדיין עובד בו. עמית חדש שואל אותך על זה.',
      hint: '`ago` — מתי זה קרה (עבר פשוט). `for` — כמה זמן זה נמשך עד עכשיו (present perfect).',
      explain: '`I joined the project three months ago` — מתי הצטרפת, בעבר פשוט. `I have worked on the project for three months` — כמה זמן זה נמשך עד עכשיו.',
      deep: '`ago` מסמן נקודה בעבר ("לפני"), ולכן בא עם עבר פשוט: `joined … ago`. `for` מודד משך; כשהמשך נמשך עד עכשיו — present perfect: `have worked … for`. `I worked on the project for three months`, בלי `have`, אומר שכבר לא עובדים בו.',
      diff: '`three months ago` — מתי (עבר פשוט). `for three months` — כמה זמן, ועד עכשיו: present perfect.',
      tokens: [
        { id: 't1', t: 'I' },
        { id: 't2', t: 'joined' },
        { id: 't3', t: 'have' },
        { id: 't4', t: 'worked' },
        { id: 't5', t: 'on' },
        { id: 't6', t: 'the project' },
        { id: 't7', t: 'three months' },
        { id: 't8', t: 'ago' },
        { id: 't9', t: 'for' },
        {
          id: 't10',
          t: 'since',
          why: '`since` בא לפני נקודת התחלה (`since June`). לפרק זמן: `for three months`; לנקודה בעבר: `three months ago`.',
          err: 'since_period',
        },
      ],
      accept: [
        { a: 'I joined the project three months ago', o: 'correct_target' },
        { a: 'I have worked on the project for three months', o: 'correct_target' },
        {
          a: 'Three months ago I joined the project',
          o: 'valid_alternative',
          note: 'גם נכון: `three months ago` בתחילת המשפט.',
        },
        {
          a: 'I have worked for three months on the project',
          o: 'valid_alternative',
          note: 'גם הסדר הזה תקין. הסדר הרגיל: `I have worked on the project for three months`.',
        },
      ],
      wrong: [
        {
          a: 'I worked on the project for three months',
          as: 'meaning_mismatch',
          err: 'past_for_ongoing',
          fb: 'המשפט תקין, אבל בלי `have` הוא מתאר תקופה שהסתיימה — כאילו כבר לא עובדים בפרויקט. אתה עדיין בו: `I have worked on the project for three months`.',
        },
        {
          a: 'I worked on the project three months ago',
          as: 'meaning_mismatch',
          err: 'past_event',
          fb: 'המשפט תקין, אבל הוא אומר שעבדת על הפרויקט אז, לפני שלושה חודשים. כדי לומר מתי הצטרפת: `I joined the project three months ago`.',
        },
      ],
      rules: [
        {
          has: ['for three months ago'],
          as: 'form_error',
          err: 'for_ago',
          fb: '`for` ו-`ago` לא באים יחד: `three months ago` (מתי) או `for three months` (כמה זמן).',
        },
        {
          has: ['have', 'ago'],
          as: 'form_error',
          err: 'ago_with_perfect',
          fb: '`ago` מסמן זמן שעבר, ולכן בא עם עבר פשוט: `I joined the project three months ago`. עם `have` — `for`: `I have worked on the project for three months`.',
        },
        {
          has: ['since three months'],
          as: 'form_error',
          err: 'since_period',
          fb: '`since` בא לפני נקודת התחלה (`since June`). לפרק זמן: `for three months`.',
        },
        {
          has: ['joined', 'for'],
          as: 'meaning_mismatch',
          err: 'joined_for',
          fb: '`joined … for three months` אומר שהצטרפת מראש לתקופה של שלושה חודשים. כדי לומר כמה זמן אתה כבר בפרויקט: `I have worked on the project for three months`, או מתי הצטרפת: `I joined the project three months ago`.',
        },
        {
          has: ['since i joined'],
          as: 'form_error',
          err: 'since_fragment',
          fb: '`since I joined the project` תקין בפני עצמו, אבל חסר כאן משפט ראשי (למשל `It has been three months since I joined the project`). עם המילים שכאן: `I joined the project three months ago` או `I have worked on the project for three months`.',
        },
        {
          has: ['i worked', 'for three months'],
          lacks: ['have'],
          as: 'meaning_mismatch',
          err: 'past_for_ongoing',
          fb: 'המשפט תקין, אבל בלי `have` הוא מתאר תקופה שהסתיימה — כאילו כבר לא עובדים בפרויקט. אתה עדיין בו: `I have worked on the project for three months`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S05-07',
      v: 1,
      skill: 'S05',
      unit: 'S05',
      sub: 'contrast',
      type: 'discriminate',
      role: 'practice',
      stage: 3,
      ctx: 'work.clinic',
      fam: 'S05.booking-system',
      goal: 'לזהות את כל הדרכים הנכונות לומר ממתי משתמשים במערכת',
      instr: 'בחר את כל המשפטים שמתאימים לסיטואציה.',
      sitHe: 'המרפאה עברה למערכת זימון תורים חדשה בתחילת מרץ. עכשיו תחילת מאי, ועדיין משתמשים בה.',
      hint: 'בדוק כל משפט: האם הוא אומר ממתי (`since`), כמה זמן (`for`) או מתי זה התחיל (`ago`) — ובאיזה זמן דקדוקי.',
      explain: '`since March` — ממתי; `for two months` — כמה זמן עד עכשיו; `two months ago` — מתי זה התחיל, עם עבר פשוט.',
      deep: 'שלושת המשפטים הנכונים מוסרים אותה עובדה בשלוש דרכים. `We used … for two months` תקין דקדוקית, אבל בלי `have` הוא מתאר תקופה שהסתיימה. `since two months` אינו תקין: `since` בא לפני נקודה, לא לפני פרק זמן.',
      diff: '`for two months` — כמה זמן. `since March` — ממתי. `two months ago` — מתי, עם עבר פשוט.',
      multi: true,
      options: [
        {
          id: 'a',
          en: 'We have used the new booking system since March.',
          v: 'fits',
          why: 'נכון: `since` + נקודת ההתחלה (מרץ), עם present perfect.',
        },
        {
          id: 'b',
          en: 'We have used the new booking system for two months.',
          v: 'fits',
          why: 'נכון: `for` + פרק הזמן (חודשיים) שנמשך עד עכשיו.',
        },
        {
          id: 'c',
          en: 'We have used the new booking system since two months.',
          v: 'ungrammatical',
          why: '`since` בא לפני נקודת התחלה, לא לפני פרק זמן: `for two months` או `since March`.',
          err: 'since_period',
        },
        {
          id: 'd',
          en: 'We started using the new booking system two months ago.',
          v: 'fits',
          why: 'נכון: `ago` + עבר פשוט אומר מתי זה התחיל.',
        },
        {
          id: 'e',
          en: 'We used the new booking system for two months.',
          v: 'other_meaning',
          why: 'תקין דקדוקית, אבל בלי `have` זה מתאר תקופה שהסתיימה — כאילו כבר לא משתמשים במערכת.',
          err: 'past_for_ongoing',
        },
      ],
    },
    {
      id: 'S05-08',
      v: 1,
      skill: 'S05',
      unit: 'S05',
      sub: 'stative',
      type: 'assemble',
      role: 'practice',
      stage: 2,
      ctx: 'work.job',
      fam: 'S05.head-since-january',
      goal: 'לומר ממתי מישהי בתפקיד',
      instr: 'קרא את הסיטואציה וענה במשפט אחד באנגלית. לא חייבים להשתמש בכל המילים.',
      sitEn: 'Dana became the head of the department in January, and she is still in that role. A new employee asks you: "Is Dana new in this role?"',
      trHe: 'דנה התמנתה לראש המחלקה בינואר, והיא עדיין בתפקיד. עובד חדש שואל אותך: "דנה חדשה בתפקיד?"',
      target: 'משפט שאומר ממתי היא בתפקיד',
      hint: 'מצב שהתחיל בינואר ונמשך עד היום. `be` הוא פועל מצב — בלי ing.',
      explain: 'מצב שהתחיל בינואר ונמשך עד היום: `Dana has been the head of the department since January`.',
      deep: 'בעברית "היא ראש המחלקה מינואר" — בהווה. באנגלית, עם `since`, צריך present perfect: `has been`. כאן אחרי `been` בא שם עצם ולא ing. אפשר גם `for` עם פרק זמן: `for a few months`.',
      tokens: [
        { id: 't1', t: 'Dana' },
        { id: 't2', t: 'has' },
        { id: 't3', t: 'been' },
        { id: 't4', t: 'the head of the department' },
        { id: 't5', t: 'since' },
        { id: 't6', t: 'January' },
        {
          id: 't7',
          t: 'is',
          why: '`is` מתאר רק את ההווה. עם `since` (מאז ועד היום) צריך `has been`.',
          err: 'present_for_duration',
        },
        {
          id: 't8',
          t: 'for',
          why: '`for` בא לפני פרק זמן (`for a few months`). לפני חודש שבו זה התחיל: `since January`.',
          err: 'for_point',
        },
        {
          id: 't9',
          t: 'was',
          why: '`was` מתאר עבר שהסתיים, והיא עדיין בתפקיד. עם `since`: `has been`.',
          err: 'past_for_ongoing',
        },
        { id: 't10', t: 'have', why: '`Dana` היא אדם אחד, ולכן `has`, לא `have`.', err: 'have_agreement' },
      ],
      accept: [
        { a: 'Dana has been the head of the department since January', o: 'correct_target' },
        {
          a: 'Since January, Dana has been the head of the department',
          o: 'valid_alternative',
          note: 'גם נכון: `since January` בתחילת המשפט.',
        },
      ],
      wrong: [
        {
          a: 'Dana is the head of the department since January',
          as: 'form_error',
          err: 'present_for_duration',
          fb: 'בעברית "היא ראש המחלקה מינואר" — בהווה. באנגלית, עם `since`, צריך present perfect: `Dana has been the head of the department since January`.',
        },
        {
          a: 'Dana is the head of the department',
          as: 'target_not_used',
          err: 'missing_since',
          fb: 'המשפט תקין, אבל הוא לא אומר ממתי. עם `since January` עוברים ל-present perfect: `Dana has been the head of the department since January`.',
        },
        {
          a: 'Dana was the head of the department',
          as: 'meaning_mismatch',
          err: 'past_for_ongoing',
          fb: 'המשפט תקין, אבל `was` אומר שהיא כבר לא בתפקיד — והיא עדיין בו. מאז ינואר ועד היום: `Dana has been the head of the department since January`.',
        },
      ],
      rules: [
        {
          has: ['for January'],
          as: 'form_error',
          err: 'for_point',
          fb: '`for` בא לפני פרק זמן. לפני חודש שבו זה התחיל: `since January`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S05-09',
      v: 1,
      skill: 'S05',
      unit: 'S05',
      sub: 'for',
      type: 'correct',
      role: 'practice',
      stage: 1,
      ctx: 'work.municipality',
      fam: 'S05.traffic-light',
      goal: 'לדווח כמה זמן רמזור מקולקל',
      instr: 'אם יש טעות — גע במילה או ברווח ובחר תיקון. אם המשפט תקין, בחר "אין צורך בתיקון".',
      promptHe: 'הרמזור מקולקל כבר שעתיים.',
      sitHe: 'אתה מדווח למוקד העירייה שהרמזור בפינת הרחוב לא עובד. הוא התקלקל לפני שעתיים. כתבת:',
      scaffold: ['has been + ...', 'for + פרק זמן / since + נקודת התחלה'],
      hint: 'שעתיים — נקודת התחלה או פרק זמן?',
      explain: "`two hours` הוא פרק זמן, ולכן `for two hours`. `since` בא לפני נקודת התחלה, כמו `since ten o'clock`.",
      deep: 'זו טעות נפוצה אצל דוברי עברית: "כבר שעתיים" מתורגם ל-`since two hours`. שאל מה בא אחרי המילה: משך (שעתיים, שבוע) — `for`; נקודה (עשר, יום שני, 2020) — `since`. גם `from two hours` אינו תקין.',
      source: [
        { id: 's1', t: 'the traffic light' },
        { id: 's2', t: 'has' },
        { id: 's3', t: 'been' },
        { id: 's4', t: 'broken' },
        {
          id: 's5',
          t: 'since',
          why: '`since` בא לפני נקודת התחלה (`since ten`). לפרק זמן כמו שעתיים: `for two hours`.',
          err: 'since_period',
        },
        { id: 's6', t: 'two hours' },
      ],
      tokens: [
        { id: 't1', t: 'for' },
        {
          id: 't2',
          t: 'from',
          why: '`from two hours` אינו תקין. לפרק זמן שנמשך עד עכשיו: `for two hours`.',
          err: 'from_for_since',
        },
        {
          id: 't3',
          t: 'is',
          why: '`is broken` מתאר רק את עכשיו. כשאומרים כמה זמן זה נמשך עד עכשיו: `has been broken for two hours`.',
          err: 'present_for_duration',
        },
      ],
      accept: [{ a: 'The traffic light has been broken for two hours', o: 'correct_target' }],
      wrong: [
        {
          a: 'The traffic light has been broken since two hours',
          as: 'form_error',
          err: 'since_period',
          fb: "`since` בא לפני נקודת התחלה (`since ten o'clock`). לפני פרק זמן כמו שעתיים: `for two hours`.",
        },
        {
          a: 'The traffic light is broken',
          as: 'meaning_mismatch',
          err: 'missing_duration',
          fb: 'המשפט תקין, אבל הוא לא אומר כמה זמן. עם משך עד עכשיו: `The traffic light has been broken for two hours`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S05-10',
      v: 1,
      skill: 'S05',
      unit: 'S05',
      sub: 'since_clause',
      type: 'correct',
      role: 'practice',
      stage: 3,
      ctx: 'daily.family',
      fam: 'S05.maya-neighbors',
      goal: 'לומר ממתי אתה מכיר מישהי — עם `since` ומשפט',
      instr: 'אם יש טעות — גע במילה או ברווח ובחר תיקון. אם המשפט תקין, בחר "אין צורך בתיקון".',
      sitHe: 'אתה מספר על מאיה: הייתם שכנים לפני שנים, ומאז אתם בקשר. כתבת:',
      hint: 'בדוק שני דברים: החלק הראשי (מאז ועד היום), והחלק שאחרי `since` (מה היה אז).',
      explain: 'המשפט תקין: `have known` — מצב שנמשך עד היום, ואחרי `since` עבר פשוט: `since we were neighbors`.',
      deep: 'אחרי `since` אפשר לשים משפט שלם שמתאר את נקודת ההתחלה, בעבר פשוט: `since we met`, `since I moved here`, `since the meeting started`. החלק הראשי נשאר present perfect, ועם `know` — בלי ing.',
      source: [
        { id: 's1', t: 'I' },
        { id: 's2', t: 'have' },
        { id: 's3', t: 'known' },
        { id: 's4', t: 'Maya' },
        { id: 's5', t: 'since' },
        { id: 's6', t: 'we' },
        { id: 's7', t: 'were' },
        { id: 's8', t: 'neighbors' },
      ],
      tokens: [
        {
          id: 't1',
          t: 'for',
          why: '`for` בא לפני פרק זמן (`for ten years`). לפני מה שקרה בנקודת ההתחלה: `since we were neighbors`. המשפט המקורי היה נכון.',
          err: 'for_point',
        },
        {
          id: 't2',
          t: 'know',
          why: '`know` בהווה לא מתחבר ל-`since`; עם `since` צריך `have known`. המשפט המקורי היה נכון.',
          err: 'present_for_duration',
        },
        {
          id: 't3',
          t: 'are',
          why: 'אחרי `since` מתארים את נקודת ההתחלה — מה שהיה אז — בעבר פשוט: `since we were neighbors`. המשפט המקורי היה נכון.',
          err: 'since_clause_tense',
        },
      ],
      accept: [{ a: 'I have known Maya since we were neighbors', o: 'correct_target' }],
      wrong: [
        {
          a: 'I know Maya since we were neighbors',
          as: 'form_error',
          err: 'present_for_duration',
          fb: 'עם `since` (מאז ועד היום) החלק הראשי צריך present perfect. המשפט המקורי היה נכון: `I have known Maya since we were neighbors`.',
        },
        {
          a: 'I know Maya',
          as: 'meaning_mismatch',
          err: 'missing_since',
          fb: 'המשפט תקין, אבל נמחק ממנו ממתי אתם מכירים. המשפט המקורי היה נכון: `I have known Maya since we were neighbors`.',
        },
      ],
      rules: [
        {
          has: ['since we are'],
          as: 'form_error',
          err: 'since_clause_tense',
          fb: 'אחרי `since` בא מה שהיה בנקודת ההתחלה, בעבר פשוט: `since we were neighbors`. המשפט המקורי היה נכון.',
        },
        {
          has: ['for we'],
          as: 'form_error',
          err: 'for_point',
          fb: 'לפני משפט שמתאר מתי זה התחיל בא `since`, לא `for`. המשפט המקורי היה נכון.',
        },
      ],
      end: '.',
    },
    {
      id: 'S05-11',
      v: 2,
      skill: 'S05',
      unit: 'S05',
      sub: 'since_clause',
      type: 'assemble',
      role: 'practice',
      stage: 2,
      ctx: 'daily.home',
      fam: 'S05.walking-since-moved',
      goal: 'לומר ממתי יש לך הרגל חדש — עם `since` ומשפט',
      instr: 'בנה משפט אחד באנגלית: מה אתה עושה מאז, ומה קרה אז. לא חייבים להשתמש בכל המילים.',
      sitHe: 'לפני שנה עברת לדירה ליד העבודה. מאז אתה הולך לעבודה ברגל כל יום.',
      hint: 'מה קרה בנקודת ההתחלה? אחרי `since` אפשר משפט שלם — באיזה זמן?',
      explain: 'אחרי `since` בא משפט שמתאר את נקודת ההתחלה, בעבר פשוט: `since I moved here`. החלק הראשי — present perfect: `I have been walking to work`.',
      deep: 'המשפט שאחרי `since` מתאר רגע אחד בעבר (עברת דירה), ולכן עבר פשוט: `since I moved here`. החלק הראשי מתאר מה שנמשך מאז ועד עכשיו: `I have been walking` או `I have walked`. אפשר גם להתחיל ב-`Since I moved here` — ובכתב לשים אחריו פסיק.',
      tokens: [
        { id: 't1', t: 'I' },
        { id: 't2', t: 'have' },
        { id: 't3', t: 'been' },
        { id: 't4', t: 'walking' },
        { id: 't5', t: 'walked' },
        { id: 't6', t: 'to work' },
        { id: 't7', t: 'since' },
        { id: 't8', t: 'I' },
        { id: 't9', t: 'moved' },
        { id: 't10', t: 'here' },
        {
          id: 't11',
          t: 'move',
          why: '`move` בהווה לא מתאים כאן: אחרי `since` מתארים מה קרה אז, בעבר פשוט — `since I moved here`.',
          err: 'since_clause_tense',
        },
        {
          id: 't12',
          t: 'for',
          why: '`for` בא לפני פרק זמן (`for a year`). לפני מה שקרה בנקודת ההתחלה: `since I moved here`.',
          err: 'for_point',
        },
      ],
      accept: [
        { a: 'I have been walking to work since I moved here', o: 'correct_target' },
        {
          a: 'I have walked to work since I moved here',
          o: 'valid_alternative',
          note: 'גם נכון: present perfect פשוט מתאים גם להרגל שנמשך עד עכשיו.',
        },
        {
          a: 'Since I moved here, I have been walking to work',
          o: 'valid_alternative',
          note: 'גם נכון: החלק עם `since` יכול לבוא בהתחלה (בכתב — עם פסיק אחריו).',
        },
        {
          a: 'Since I moved here, I have walked to work',
          o: 'valid_alternative',
          note: 'גם נכון: החלק עם `since` בהתחלה, ו-present perfect פשוט להרגל שנמשך.',
        },
      ],
      rules: [
        {
          has: ['have walking'],
          lacks: ['been'],
          as: 'form_error',
          err: 'missing_been',
          fb: 'בין `have` ל-`walking` חסרה המילה `been`: `I have been walking`.',
        },
        {
          has: ['been walked'],
          as: 'form_error',
          err: 'been_v3',
          fb: 'אחרי `been` בא כאן פועל עם ing: `been walking` — או בלי `been`: `I have walked`.',
        },
        {
          has: ['i walked', 'since'],
          lacks: ['have'],
          as: 'form_error',
          err: 'past_for_duration',
          fb: 'עם `since` (מאז ועד עכשיו) החלק הראשי בא ב-present perfect: `I have been walking to work since I moved here` או `I have walked to work since I moved here`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S05-12',
      v: 1,
      skill: 'S05',
      unit: 'S05',
      sub: 'negative',
      type: 'assemble',
      role: 'practice',
      stage: 2,
      ctx: 'daily.past',
      fam: 'S05.old-friend-five-years',
      goal: 'לומר לחבר ותיק כמה זמן לא התראיתם',
      instr: 'בנה משפט אחד באנגלית. לא חייבים להשתמש בכל המילים.',
      sitHe: 'בסופר אתה פוגש במקרה חבר מהעבר. הפעם האחרונה שראית אותו הייתה לפני חמש שנים.',
      hint: 'עד היום לא ראית אותו. חמש שנים — איזו מילה באה לפני פרק זמן?',
      explain: "עד עכשיו זה לא קרה: `I haven't seen you` + פרק זמן: `for five years`. באנגלית אמריקאית גם `in five years`.",
      deep: 'במשפט שלילי עם present perfect, `for` ו-`in` (בעיקר באמריקאית) אומרים שניהם "כבר חמש שנים ש…לא". `since` מתאים רק לנקודת התחלה: `I haven\'t seen you since 2021`.',
      tokens: [
        { id: 't1', t: 'I' },
        { id: 't2', t: "haven't" },
        { id: 't3', t: 'seen' },
        { id: 't4', t: 'you' },
        { id: 't5', t: 'for' },
        { id: 't6', t: 'in' },
        { id: 't7', t: 'five years' },
        {
          id: 't8',
          t: 'since',
          why: '`since` בא לפני נקודת התחלה (`since 2021`). לפרק זמן כמו חמש שנים: `for` (או במשפט שלילי גם `in`).',
          err: 'since_period',
        },
        {
          id: 't9',
          t: 'saw',
          why: "`saw` הוא עבר פשוט. אחרי `haven't` בא V3: `seen`.",
          err: 'have_v2',
        },
      ],
      accept: [
        { a: "I haven't seen you for five years", o: 'correct_target' },
        {
          a: "I haven't seen you in five years",
          o: 'valid_alternative',
          note: 'גם נכון, ונפוץ מאוד באנגלית אמריקאית: במשפט שלילי `in five years` = `for five years`.',
        },
      ],
      wrong: [
        {
          a: 'I saw you',
          as: 'meaning_mismatch',
          err: 'missing_duration',
          fb: 'המשפט תקין, אבל הוא לא אומר שלא התראיתם כבר חמש שנים: `I haven\'t seen you for five years`.',
        },
      ],
      rules: [
        {
          has: ['since five years'],
          as: 'form_error',
          err: 'since_period',
          fb: '`since` בא לפני נקודת התחלה (`since 2021`). לפרק זמן: `for five years`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S05-D1',
      v: 2,
      skill: 'S05',
      unit: 'S05',
      sub: 'dialogue',
      type: 'dialogue',
      role: 'practice',
      stage: 2,
      ctx: 'work.software',
      fam: 'S05.dialogue-system-down',
      goal: 'לעדכן מנהלת ממתי תקלה נמשכת ומתי פנית לתמיכה',
      instr: 'ענה לרות בכל תור.',
      partnerName: 'Ruth',
      setupHe: 'השעה 11:00. מערכת ההזמנות נפלה בשמונה בבוקר, ועדיין לא עובדת. רות, המנהלת שלך, ניגשת אליך.',
      hint: 'בתור הראשון — ממתי או כמה זמן זה נמשך עד עכשיו. בתור השני — מתי עשית משהו (`ago`).',
      explain: 'עד עכשיו: `It has been down since eight` (או `for three hours`). מתי זה קרה: `I called them an hour ago` — עבר פשוט.',
      turns: [
        {
          partner: { en: 'Is the booking system still down?', he: 'מערכת ההזמנות עדיין לא עובדת?' },
          sub: 'for_since',
          instr: 'ענה שכן, ואמור ממתי — או כמה זמן — היא לא עובדת.',
          target: 'לומר גם ממתי או כמה זמן',
          hint: 'היא נפלה בשמונה, ועכשיו אחת-עשרה. `for` + כמה זמן, או `since` + ממתי.',
          explain: '`It has been down since eight` — ממתי; `It has been down for three hours` — כמה זמן. שניהם נכונים.',
          build: {
            tokens: [
              { id: 't1', t: 'yes' },
              { id: 't2', t: 'it' },
              { id: 't3', t: 'has' },
              { id: 't4', t: 'been' },
              { id: 't5', t: 'down' },
              { id: 't6', t: 'since' },
              { id: 't7', t: 'for' },
              { id: 't8', t: 'eight' },
              { id: 't9', t: 'three hours' },
              {
                id: 't10',
                t: 'is',
                why: '`is down` מתאר רק את עכשיו. כדי לומר ממתי או כמה זמן זה נמשך עד עכשיו: `has been down`.',
                err: 'present_for_duration',
              },
              {
                id: 't11',
                t: 'from',
                why: '`from` לא מתאים כאן: למשהו שנמשך עד עכשיו — `since eight` (ממתי) או `for three hours` (כמה זמן).',
                err: 'from_for_since',
              },
            ],
            accept: [
              { a: 'Yes, it has been down since eight', o: 'correct_target' },
              { a: 'Yes, it has been down for three hours', o: 'correct_target' },
              { a: 'It has been down since eight', o: 'correct_target' },
              { a: 'It has been down for three hours', o: 'correct_target' },
            ],
            wrong: [
              {
                a: 'Yes, it is',
                as: 'target_not_used',
                err: 'missing_duration',
                fb: 'תשובה תקינה, אבל התבקשת לומר גם ממתי או כמה זמן: `It has been down since eight`.',
              },
              {
                a: 'Yes, it is down',
                as: 'target_not_used',
                err: 'missing_duration',
                fb: 'תשובה תקינה, אבל התבקשת לומר גם ממתי או כמה זמן. אז עוברים ל-present perfect: `It has been down since eight`.',
              },
              {
                a: 'It is down',
                as: 'target_not_used',
                err: 'missing_duration',
                fb: 'תשובה תקינה, אבל התבקשת לומר גם ממתי או כמה זמן. אז עוברים ל-present perfect: `It has been down since eight`.',
              },
              {
                a: 'Yes, it is down since eight',
                as: 'form_error',
                err: 'present_for_duration',
                fb: 'בעברית "היא לא עובדת משמונה" — בהווה. באנגלית, עם `since`: `It has been down since eight`.',
              },
              {
                a: 'It is down since eight',
                as: 'form_error',
                err: 'present_for_duration',
                fb: 'בעברית "היא לא עובדת משמונה" — בהווה. באנגלית, עם `since`: `It has been down since eight`.',
              },
              {
                a: 'Yes, it is down for three hours',
                as: 'meaning_mismatch',
                err: 'present_for_duration',
                fb: '`is down for three hours` נשמע כמו השבתה מתוכננת של שלוש שעות. כדי לומר כמה זמן זה נמשך עד עכשיו: `It has been down for three hours`.',
              },
              {
                a: 'It is down for three hours',
                as: 'meaning_mismatch',
                err: 'present_for_duration',
                fb: '`is down for three hours` נשמע כמו השבתה מתוכננת של שלוש שעות. כדי לומר כמה זמן זה נמשך עד עכשיו: `It has been down for three hours`.',
              },
            ],
            rules: [
              {
                has: ['since three hours'],
                as: 'form_error',
                err: 'since_period',
                fb: '`since` בא לפני נקודת התחלה (`since eight`). לפרק זמן: `for three hours`.',
              },
              {
                has: ['for eight'],
                as: 'form_error',
                err: 'for_point',
                fb: '`for` בא לפני פרק זמן (`for three hours`). לפני שעה שבה זה התחיל: `since eight`.',
              },
            ],
            end: '.',
          },
        },
        {
          partner: { en: "That's a long time. Have you called the support team?", he: 'זה הרבה זמן. התקשרת לצוות התמיכה?' },
          variants: [
            {
              ifPrev: [0, 2],
              line: {
                en: "Since eight? That's three hours. Have you called the support team?",
                he: 'משמונה? זה שלוש שעות. התקשרת לצוות התמיכה?',
              },
            },
            {
              ifPrev: [1, 3],
              line: { en: 'Three hours? Have you called the support team?', he: 'שלוש שעות? התקשרת לצוות התמיכה?' },
            },
          ],
          sub: 'ago',
          instr: 'ענה שכן — התקשרת אליהם לפני שעה.',
          target: 'משפט מלא שאומר מתי התקשרת — עם `ago`',
          hint: '"לפני שעה" — מתי זה קרה. איזה זמן הולך עם `ago`?',
          explain: '`ago` אומר מתי משהו קרה, ולכן עבר פשוט: `I called them an hour ago` — בלי `have`.',
          build: {
            tokens: [
              { id: 't1', t: 'yes' },
              { id: 't2', t: 'I' },
              { id: 't3', t: 'called' },
              { id: 't4', t: 'them' },
              { id: 't5', t: 'an hour' },
              { id: 't6', t: 'ago' },
              {
                id: 't7',
                t: 'have',
                why: '`have called` לא אומר מתי. כדי לומר שהתקשרת לפני שעה: `I called them an hour ago` — עם `ago` בא עבר פשוט, בלי `have`.',
                err: 'ago_with_perfect',
              },
              {
                id: 't8',
                t: 'for',
                why: '`for` אומר כמה זמן משהו נמשך. כדי לומר מתי התקשרת: `an hour ago`, עם עבר פשוט.',
                err: 'for_for_ago',
                as: 'meaning_mismatch',
              },
              {
                id: 't9',
                t: 'since',
                why: '`since` בא לפני נקודת התחלה של משהו שנמשך עד עכשיו. כדי לומר מתי התקשרת: `an hour ago`, עם עבר פשוט.',
                err: 'since_for_ago',
              },
            ],
            accept: [
              { a: 'Yes, I called them an hour ago', o: 'correct_target' },
              { a: 'I called them an hour ago', o: 'correct_target' },
              {
                a: 'Yes, I called an hour ago',
                o: 'valid_alternative',
                note: 'גם נכון: מההקשר ברור למי התקשרת, גם בלי `them`.',
              },
              {
                a: 'I called an hour ago',
                o: 'valid_alternative',
                note: 'גם נכון: מההקשר ברור למי התקשרת, גם בלי `them`.',
              },
              {
                a: 'Yes, an hour ago',
                o: 'target_not_used',
                note: 'תשובה קצרה וטבעית בשיחה. כאן התבקש משפט מלא: `I called them an hour ago`.',
              },
              {
                a: 'An hour ago',
                o: 'target_not_used',
                note: 'תשובה קצרה וטבעית בשיחה. כאן התבקש משפט מלא: `I called them an hour ago`.',
              },
            ],
            wrong: [
              {
                a: 'Yes, I have',
                as: 'target_not_used',
                err: 'missing_time',
                fb: 'תשובה תקינה, אבל התבקשת לומר גם מתי התקשרת. עם `an hour ago` עוברים לעבר פשוט: `I called them an hour ago`.',
              },
              {
                a: 'Yes, I have called them',
                as: 'target_not_used',
                err: 'missing_time',
                fb: 'תקין, אבל בלי מתי. כשמוסיפים `an hour ago` עוברים לעבר פשוט: `I called them an hour ago`.',
              },
              {
                a: 'I have called them',
                as: 'target_not_used',
                err: 'missing_time',
                fb: 'תקין, אבל בלי מתי. כשמוסיפים `an hour ago` עוברים לעבר פשוט: `I called them an hour ago`.',
              },
            ],
            rules: [
              {
                has: ['for an hour ago'],
                as: 'form_error',
                err: 'for_ago',
                fb: '`for` ו-`ago` לא באים יחד. מתי התקשרת: `an hour ago`.',
              },
              {
                has: ['have', 'ago'],
                as: 'form_error',
                err: 'ago_with_perfect',
                fb: '`ago` אומר מתי זה קרה — זמן שעבר — ולכן עבר פשוט, בלי `have`: `I called them an hour ago`.',
              },
            ],
            end: '.',
          },
        },
      ],
      closing: { en: "OK. If they don't answer by twelve, let me know.", he: 'בסדר. אם הם לא עונים עד שתים-עשרה, תעדכן אותי.' },
    },
    {
      id: 'S05-C1',
      v: 1,
      skill: 'S05',
      unit: 'S05',
      sub: 'since',
      type: 'assemble',
      role: 'check',
      stage: 2,
      ctx: 'daily.learning',
      fam: 'S05.spanish-october',
      goal: 'לענות כמה זמן אתה כבר לומד משהו',
      instr: 'קרא את הסיטואציה ובנה משפט אחד באנגלית. לא חייבים להשתמש בכל המילים.',
      sitEn: 'You started a Spanish class in October. You still go every week. A friend asks: "How long have you been learning Spanish?" Answer in a full sentence.',
      trHe: 'התחלת שיעורי ספרדית באוקטובר, ואתה עדיין הולך כל שבוע. חבר שואל: "כמה זמן אתה כבר לומד ספרדית?" ענה במשפט מלא.',
      target: 'תשובה במשפט מלא',
      hint: 'אוקטובר — פרק זמן או נקודת התחלה?',
      explain: '`October` הוא נקודת התחלה, ולכן `since October`, עם present perfect: `I have been learning Spanish since October`.',
      deep: 'עם פרק זמן אומרים `for`: `for a few months`. `from October` מתאים רק לצירוף כמו `from October to June`, ולא למשהו שנמשך עד עכשיו.',
      tokens: [
        { id: 't1', t: 'I' },
        { id: 't2', t: 'have' },
        { id: 't3', t: 'been' },
        { id: 't4', t: 'learning' },
        { id: 't5', t: 'Spanish' },
        { id: 't6', t: 'since' },
        { id: 't7', t: 'October' },
        {
          id: 't8',
          t: 'for',
          why: '`for` בא לפני פרק זמן (`for a few months`). לפני חודש שבו זה התחיל: `since October`.',
          err: 'for_point',
        },
        {
          id: 't9',
          t: 'from',
          why: '`from October` לא מתאר משהו שנמשך עד עכשיו (הוא בא בצירוף `from … to …`). כאן: `since October`.',
          err: 'from_for_since',
        },
        {
          id: 't10',
          t: 'am',
          why: '`am learning` מתאר את ההווה. עם `since` — מאז ועד עכשיו — צריך `have been learning`.',
          err: 'present_for_duration',
        },
      ],
      accept: [
        { a: 'I have been learning Spanish since October', o: 'correct_target' },
        {
          a: 'Since October',
          o: 'target_not_used',
          note: 'תשובה קצרה וטבעית בשיחה. כאן התבקש משפט מלא: `I have been learning Spanish since October`.',
        },
      ],
      wrong: [
        {
          a: 'I am learning Spanish since October',
          as: 'form_error',
          err: 'present_for_duration',
          fb: 'בעברית "אני לומד ספרדית מאוקטובר" — בהווה. באנגלית, עם `since`, צריך present perfect: `I have been learning Spanish since October`.',
        },
        {
          a: 'I am learning Spanish',
          as: 'meaning_mismatch',
          err: 'missing_duration',
          fb: 'המשפט תקין, אבל הוא לא עונה כמה זמן. עם `since October` עוברים ל-present perfect: `I have been learning Spanish since October`.',
        },
      ],
      rules: [
        {
          has: ['for October'],
          as: 'form_error',
          err: 'for_point',
          fb: '`for` בא לפני פרק זמן. לפני חודש שבו זה התחיל: `since October`.',
        },
        {
          has: ['from October'],
          as: 'form_error',
          err: 'from_for_since',
          fb: 'למשהו שהתחיל באוקטובר ונמשך עד עכשיו: `since October`, לא `from October`.',
        },
        {
          has: ['have learning'],
          lacks: ['been'],
          as: 'form_error',
          err: 'missing_been',
          fb: 'בין `have` ל-`learning` חסרה המילה `been`: `I have been learning`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S05-C2',
      v: 2,
      skill: 'S05',
      unit: 'S05',
      sub: 'since',
      type: 'correct',
      role: 'check',
      stage: 2,
      ctx: 'daily.health',
      fam: 'S05.pool-since-summer',
      goal: 'לספר על הרגל שהתחיל בקיץ שעבר ועדיין נמשך',
      instr: 'אם יש טעות — גע במילה או ברווח ובחר תיקון. אם המשפט תקין, בחר "אין צורך בתיקון".',
      sitHe: 'בקיץ שעבר התחלת ללכת לבריכה כל יום שישי, ואתה עדיין הולך. כתבת לחבר:',
      hint: '`since last summer` נכון. בדוק את הפועל.',
      explain: 'הרגל שהתחיל בקיץ שעבר ונמשך עד עכשיו: `I have been going to the pool every Friday since last summer`.',
      deep: 'בעברית "אני הולך לבריכה מהקיץ שעבר" — בהווה. באנגלית ההווה הפשוט (`I go`) מתאר הרגל, אבל לא מתחבר ל-`since`. עם `since` — present perfect: `have been going` או `have gone`.',
      source: [
        { id: 's1', t: 'I' },
        {
          id: 's2',
          t: 'go',
          why: '`go` בהווה פשוט לא מתחבר ל-`since`. מאז ועד עכשיו: `have been going` (או `have gone`).',
          err: 'present_for_duration',
        },
        { id: 's3', t: 'to the pool' },
        { id: 's4', t: 'every Friday' },
        { id: 's5', t: 'since' },
        { id: 's6', t: 'last summer' },
      ],
      tokens: [
        { id: 't1', t: 'have' },
        { id: 't2', t: 'been' },
        { id: 't3', t: 'going' },
        { id: 't4', t: 'gone' },
        {
          id: 't5',
          t: 'for',
          why: '`for` בא לפני פרק זמן (`for a year`). לפני נקודת התחלה כמו `last summer`: `since`.',
          err: 'for_point',
        },
        {
          id: 't6',
          t: 'am',
          why: '`am going` מתאר את ההווה (או תוכנית). עם `since` צריך `have been going`.',
          err: 'present_for_duration',
        },
      ],
      accept: [
        { a: 'I have been going to the pool every Friday since last summer', o: 'correct_target' },
        {
          a: 'I have gone to the pool every Friday since last summer',
          o: 'valid_alternative',
          note: 'גם נכון: present perfect פשוט מתאים גם להרגל שנמשך עד עכשיו.',
        },
        {
          a: 'I have been to the pool every Friday since last summer',
          o: 'valid_alternative',
          note: 'גם נכון: `have been to the pool` — "הייתי בבריכה" (הלכתי וחזרתי). המבנה המתמשך מדגיש את ההרגל: `have been going`.',
        },
      ],
      wrong: [
        {
          a: 'I go to the pool every Friday since last summer',
          as: 'form_error',
          err: 'present_for_duration',
          fb: 'בעברית "אני הולך ... מהקיץ שעבר" — בהווה. באנגלית, עם `since` צריך present perfect: `I have been going to the pool every Friday since last summer`.',
        },
        {
          a: 'I am going to the pool every Friday since last summer',
          as: 'form_error',
          err: 'present_for_duration',
          fb: '`am going` מתאר את ההווה. עם `since` — מאז ועד עכשיו: `I have been going to the pool every Friday since last summer`.',
        },
        {
          a: 'I go to the pool every Friday',
          as: 'meaning_mismatch',
          err: 'missing_duration',
          fb: 'המשפט תקין, אבל נמחק ממנו ממתי. `since last summer` נכון — רק הפועל צריך present perfect: `I have been going to the pool every Friday since last summer`.',
        },
        {
          a: 'I am going to the pool every Friday',
          as: 'meaning_mismatch',
          err: 'missing_duration',
          fb: 'המשפט תקין, אבל נמחק ממנו ממתי. `since last summer` נכון — רק הפועל צריך present perfect: `I have been going to the pool every Friday since last summer`.',
        },
      ],
      rules: [
        {
          has: ['for last summer'],
          as: 'form_error',
          err: 'for_point',
          fb: '`for` בא לפני פרק זמן. לפני נקודת התחלה כמו `last summer`: `since`.',
        },
        {
          has: ['have go'],
          as: 'form_error',
          err: 'have_base',
          fb: 'אחרי `have` בא V3 (`gone`), או `been going`.',
        },
        {
          has: ['have going'],
          lacks: ['been'],
          as: 'form_error',
          err: 'missing_been',
          fb: 'בין `have` ל-`going` חסרה המילה `been`: `have been going`.',
        },
        {
          has: ['been gone'],
          as: 'form_error',
          err: 'been_v3',
          fb: 'אחרי `been` בא כאן פועל עם ing: `been going` — או בלי `been`: `have gone`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S05-C3',
      v: 2,
      skill: 'S05',
      unit: 'S05',
      sub: 'stative',
      type: 'assemble',
      role: 'check',
      stage: 3,
      ctx: 'work.schedule',
      fam: 'S05.opening-hours',
      goal: 'לומר ממתי או כמה זמן יש לכם את שעות הפתיחה',
      instr: 'קרא את הסיטואציה ובנה משפט אחד באנגלית. לא חייבים להשתמש בכל המילים.',
      sitEn: 'Your office changed its opening hours at the beginning of January. It is now early April. A visitor thinks the hours are new. Tell him they are not new.',
      trHe: 'המשרד שלכם שינה את שעות הפתיחה בתחילת ינואר. עכשיו תחילת אפריל. מבקר חושב שהשעות חדשות. אמור לו שהן לא חדשות.',
      hint: 'משהו שיש לכם מינואר ועד עכשיו. `have` במובן "יש לנו" הוא פועל מצב.',
      explain: '`have` במובן "יש לנו" הוא פועל מצב: `We have had these opening hours since January` — או `for three months`.',
      deep: 'בעברית "יש לנו את השעות האלה מינואר" — בהווה. באנגלית, מאז ועד עכשיו: `have had` (`have` + צורת V3 של `have`). `We have these opening hours for three months` נשמע כמו תקופה מתוכננת של שלושה חודשים.',
      tokens: [
        { id: 't1', t: 'we' },
        { id: 't2', t: 'have' },
        { id: 't3', t: 'had' },
        { id: 't4', t: 'these opening hours' },
        { id: 't5', t: 'since' },
        { id: 't6', t: 'for' },
        { id: 't7', t: 'January' },
        { id: 't8', t: 'three months' },
        {
          id: 't9',
          t: 'having',
          why: '`have` במובן של "יש לנו" הוא פועל מצב, ולכן `have had`, בלי ing.',
          err: 'stative_continuous',
        },
        { id: 't10', t: 'has', why: 'עם `we` משתמשים ב-`have`, לא ב-`has`.', err: 'have_agreement' },
      ],
      accept: [
        { a: 'We have had these opening hours since January', o: 'correct_target' },
        { a: 'We have had these opening hours for three months', o: 'correct_target' },
      ],
      wrong: [
        {
          a: 'We have these opening hours since January',
          as: 'form_error',
          err: 'present_for_duration',
          fb: 'בעברית "יש לנו את השעות האלה מינואר" — בהווה. באנגלית, עם `since` צריך present perfect: `We have had these opening hours since January`.',
        },
        {
          a: 'We have these opening hours for three months',
          as: 'meaning_mismatch',
          err: 'present_for_duration',
          fb: 'המשפט נשמע כמו תקופה מתוכננת — שעות שיהיו לכם שלושה חודשים. כדי לומר כמה זמן זה כבר נמשך: `We have had these opening hours for three months`.',
        },
        {
          a: 'We had these opening hours since January',
          as: 'form_error',
          err: 'past_for_duration',
          fb: 'עם `since` (מאז ועד עכשיו) לא משתמשים בעבר פשוט: `We have had these opening hours since January`.',
        },
        {
          a: 'We had these opening hours for three months',
          as: 'meaning_mismatch',
          err: 'past_for_ongoing',
          fb: 'המשפט תקין, אבל בלי `have` הוא מתאר תקופה שהסתיימה — כאילו השעות האלה כבר לא בתוקף. הן עדיין בתוקף: `We have had these opening hours for three months`.',
        },
      ],
      rules: [
        {
          has: ['since three months'],
          as: 'form_error',
          err: 'since_period',
          fb: '`since` בא לפני נקודת התחלה (`since January`). לפרק זמן: `for three months`.',
        },
        {
          has: ['for January'],
          as: 'form_error',
          err: 'for_point',
          fb: '`for` בא לפני פרק זמן (`for three months`). לפני חודש שבו זה התחיל: `since January`.',
        },
      ],
      end: '.',
    },
  ],
};
