import type { SkillPack } from '../schema';

/**
 * S06 PAST_VS_PERFECT.
 * Items S06-01 and S06-02 belong to the scripted first segment (one contrast sentence built
 * in two parts): keep them unchanged.
 */
export const S06: SkillPack = {
  skill: 'S06',
  lessons: [
    {
      unit: 'S06',
      title: 'אתמול מול עד עכשיו: `sent` או `have sent`',
      short:
        'זמן שהסתיים (`yesterday`, `last week`, `in 2021`) — עבר פשוט: `I sent the report yesterday`. בלי זמן מוגמר, או בתקופה שעוד נמשכת (`ever`, `yet`, `so far`, `this week`) — present perfect: `I have sent the report`.',
      examples: [
        { en: 'I sent the report yesterday.', he: 'שלחתי את הדוח אתמול.' },
        { en: 'Have you ever been to London?', he: 'היית פעם בלונדון?', note: 'כל החיים עד עכשיו — בלי זמן מסוים.' },
        { en: 'Did you go to London last year?', he: 'נסעת ללונדון בשנה שעברה?', note: 'זמן שהסתיים — עבר פשוט.' },
        { en: "I've lost my keys.", he: 'איבדתי את המפתחות (ואין לי אותם עכשיו).' },
      ],
      contrast: {
        a: { en: 'I have sent the report.', he: 'שלחתי את הדוח (הוא כבר אצלך; לא אומרים מתי).' },
        b: {
          en: 'I sent the report yesterday, so you can read it now.',
          he: 'שלחתי את הדוח אתמול, אז אתה יכול לקרוא אותו עכשיו.',
        },
        note: 'הקשר להווה לא מבטל את `yesterday`. ברגע שמציינים זמן שהסתיים — עבר פשוט, גם אם התוצאה חשובה עכשיו.',
      },
      deep:
        '• עבר פשוט (`sent`, `went`, `lost`) — כשהזמן גמור וידוע: `yesterday`, `last week`, `two days ago`, `in 2021`, `on Monday`, `when I was a student`. גם בשאלה: `Did you go to London last year?`\n' +
        '• present perfect (`have / has` + V3) — כשלא אומרים מתי, או כשהתקופה עוד לא נגמרה: `ever`, `never`, `already`, `yet`, `so far`, `recently`, `this week`, `today`. `Have you ever been to London?` שואל על כל החיים עד עכשיו.\n' +
        '• תוצאה עכשיו: `I\'ve lost my keys` — אין לי אותם עכשיו. אבל ברגע שמוסיפים זמן שהסתיים: `I lost my keys yesterday`.\n' +
        '• `this morning`: כשעדיין בוקר, שתי הצורות אפשריות. אחר הצהריים הבוקר כבר נגמר — עבר פשוט: `I called her this morning`.\n' +
        '• באנגלית אמריקאית מדוברת שומעים גם `Did you send it yet?` ו-`I already sent it`. זו לא טעות; הצורה הסטנדרטית ל"עד עכשיו": `Have you sent it yet?`, `I\'ve already sent it`.',
      pitfalls: [
        '`I\'ve sent the report yesterday` — עם `yesterday` רק עבר פשוט: `I sent the report yesterday`.',
        '`Have you been to London last year?` — על זמן שהסתיים שואלים בעבר פשוט: `Did you go to London last year?`',
        '"יש קשר להווה, אז צריך `have`" — לא כשמציינים זמן שהסתיים.',
      ],
    },
  ],
  examples: {
    S06: [
      { en: 'She changed her phone number last month.', he: 'היא החליפה את מספר הטלפון שלה בחודש שעבר.' },
      { en: 'We have had two power cuts so far this month.', he: 'היו לנו כבר שתי הפסקות חשמל החודש (והחודש עוד לא נגמר).' },
      { en: 'Have you seen the new schedule yet?', he: 'כבר ראית את לוח הזמנים החדש?' },
      { en: 'It has rained a lot this week.', he: 'ירד הרבה גשם השבוע (והשבוע עוד לא נגמר).' },
    ],
  },
  items: [
    {
      id: 'S06-01',
      v: 2,
      skill: 'S06',
      unit: 'S06',
      sub: 'finished_time',
      type: 'assemble',
      role: 'practice',
      stage: 3,
      ctx: 'work.email',
      fam: 'S06.email-reply',
      goal: 'לומר מתי שלחת את המייל',
      instr: 'בנה את החלק הראשון של התשובה: מתי שלחת.',
      sitHe: 'מנהלת שואלת אם שלחת את המייל. שלחת אותו אתמול — ועדיין אין תשובה.',
      promptHe: 'שלחתי את המייל אתמול.',
      target: 'לומר גם מתי — עם `yesterday`',
      hint: '`yesterday` הוא זמן שהסתיים.',
      explain: 'עם זמן עבר שהסתיים, כמו `yesterday`, משתמשים בעבר פשוט: `I sent the email yesterday`.',
      deep: 'גם כשלמשהו שקרה אתמול יש חשיבות עכשיו, ציון זמן מוגמר (`yesterday`, `last week`, `on Monday`) מחייב עבר פשוט. בלי ציון זמן אפשר `I have sent the email`.',
      tokens: [
        { id: 't1', t: 'I' },
        { id: 't2', t: 'sent' },
        { id: 't3', t: 'the email' },
        { id: 't4', t: 'yesterday' },
        {
          id: 't5',
          t: 'have',
          why: 'עם `yesterday` — זמן שהסתיים — משתמשים בעבר פשוט `sent`, בלי `have`.',
          err: 'perfect_with_finished_time',
        },
        { id: 't6', t: 'send', why: '`send` היא צורת הבסיס. לעבר: `sent`.', err: 'base_for_past' },
      ],
      accept: [
        { a: 'I sent the email yesterday', o: 'correct_target' },
        { a: 'Yesterday I sent the email', o: 'valid_alternative', note: 'גם נכון: `yesterday` בתחילת המשפט.' },
        {
          a: 'I have sent the email',
          o: 'target_not_used',
          note: 'תקין — בלי ציון זמן present perfect מתאים. אבל התבקשת לומר מתי שלחת, ועם `yesterday` עוברים לעבר פשוט: `I sent the email yesterday`.',
        },
        {
          a: 'I sent the email',
          o: 'target_not_used',
          note: 'תקין, אבל חסר מתי: `I sent the email yesterday`.',
        },
      ],
      wrong: [
        {
          a: 'I have sent the email yesterday',
          as: 'form_error',
          err: 'perfect_with_finished_time',
          fb: '`yesterday` הוא זמן שהסתיים, ולכן עבר פשוט: `I sent the email yesterday`. `have sent` מתאים רק בלי ציון זמן מוגמר.',
        },
      ],
      rules: [
        {
          has: ['have send'],
          as: 'form_error',
          err: 'have_base',
          fb: 'אחרי `have` בא V3: `sent`, לא `send`. וכאן, עם `yesterday`, עבר פשוט בלי `have`: `I sent the email yesterday`.',
        },
        {
          has: ['have the email'],
          lacks: ['sent', 'send'],
          as: 'meaning_mismatch',
          err: 'missing_verb',
          fb: '`I have the email` אומר "המייל אצלי" — חסר הפועל. כאן: `I sent the email yesterday`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S06-02',
      v: 2,
      skill: 'S06',
      unit: 'S06',
      sub: 'up_to_now',
      type: 'assemble',
      role: 'practice',
      stage: 3,
      ctx: 'work.email',
      fam: 'S06.email-reply',
      goal: 'להוסיף שעדיין לא הגיעה תשובה',
      instr: 'השלם את המשפט: עדיין לא קיבלת תשובה.',
      promptHe: '…אבל עדיין לא קיבלתי תשובה.',
      target: 'עד עכשיו זה לא קרה: `haven\'t` + V3',
      hint: 'עד עכשיו זה עוד לא קרה: `haven\'t` + V3 … `yet`.',
      explain:
        '`yesterday` — זמן שהסתיים, לכן `I sent`. "עדיין לא קיבלתי" — עד עכשיו, לכן `I haven\'t received … yet`.',
      deep: 'באותו משפט יכולים לעבוד שני זמנים: החלק שקרה בזמן מוגמר (`yesterday`) בעבר פשוט, והחלק שנמשך עד עכשיו (`not yet`) ב-present perfect. באנגלית אמריקאית מדוברת שומעים גם `I didn\'t receive a reply yet`; הצורה הסטנדרטית היא `I haven\'t received a reply yet`.',
      lead: 'I sent the email yesterday,',
      tokens: [
        { id: 't1', t: 'but' },
        { id: 't2', t: 'I' },
        { id: 't3', t: "haven't" },
        { id: 't4', t: 'received' },
        { id: 't5', t: 'a reply' },
        { id: 't6', t: 'yet' },
        { id: 't7', t: 'still' },
        { id: 't8', t: "didn't" },
        { id: 't9', t: 'receive' },
      ],
      accept: [
        { a: "but I haven't received a reply yet", o: 'correct_target' },
        {
          a: "but I still haven't received a reply",
          o: 'valid_alternative',
          note: 'גם נכון: `still` לפני `haven\'t` מדגיש שזה עדיין לא קרה.',
        },
        {
          a: "but I haven't yet received a reply",
          o: 'valid_alternative',
          note: 'גם נכון, בסגנון רשמי יותר.',
        },
        {
          a: "but I haven't received a reply",
          o: 'valid_alternative',
          note: 'גם נכון. `yet` (או `still`) מוסיף את ה"עדיין".',
        },
        {
          a: "but I didn't receive a reply",
          o: 'target_not_used',
          note: 'תקין — עבר פשוט. התרגיל ביקש `haven\'t received`: "עדיין לא" נמשך עד עכשיו — `I haven\'t received a reply yet`.',
        },
        {
          a: "but I didn't receive a reply yet",
          o: 'target_not_used',
          note: 'נפוץ באנגלית אמריקאית מדוברת. התרגיל ביקש `haven\'t received`, הצורה הסטנדרטית ל"עד עכשיו".',
        },
        {
          a: "but I still didn't receive a reply",
          o: 'target_not_used',
          note: 'נשמע באנגלית אמריקאית מדוברת. הצורה הסטנדרטית: `I still haven\'t received a reply`.',
        },
      ],
      rules: [
        {
          has: ["haven't receive"],
          as: 'form_error',
          err: 'have_base',
          fb: 'אחרי `haven\'t` בא V3: `haven\'t received`.',
        },
        {
          has: ["didn't received"],
          as: 'form_error',
          err: 'did_v2',
          fb: 'אחרי `didn\'t` בא פועל בסיס: `didn\'t receive`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S06-03',
      v: 1,
      skill: 'S06',
      unit: 'S06',
      sub: 'finished_time',
      type: 'correct',
      role: 'practice',
      stage: 1,
      ctx: 'work.report',
      fam: 'S06.report-yesterday',
      goal: 'לומר שהדוח נשלח אתמול',
      instr: 'בדוק את המשפט. אם יש טעות — גע במילה או ברווח ובחר תיקון; אם הוא תקין, בחר "אין צורך בתיקון".',
      promptHe: 'שלחתי את הדוח אתמול.',
      sitHe: 'מנהל שואל איפה הדוח. שלחת אותו אתמול, והוא כבר אצלו בתיבה.',
      target: 'לומר גם מתי שלחת — עם `yesterday`',
      hint: '`yesterday` הוא זמן שהסתיים. האם `I\'ve` מתאים לו?',
      explain:
        'עם `yesterday` — זמן שהסתיים — משתמשים בעבר פשוט: `I sent the report yesterday`. זה נכון גם כשהדוח חשוב עכשיו.',
      deep: 'זו הטעות מהשיעורים עצמם: `I\'ve sent the report yesterday`. `I\'ve` = `I have`, כלומר present perfect, שלא אומר מתי. ברגע שמוסיפים זמן מוגמר (`yesterday`, `last week`, `on Monday`) עוברים לעבר פשוט. בלי ציון זמן אפשר לומר `I\'ve sent the report` — אבל אז לא אומרים מתי.',
      source: [
        { id: 's1', t: "I've" },
        { id: 's2', t: 'sent' },
        { id: 's3', t: 'the report' },
        { id: 's4', t: 'yesterday' },
      ],
      tokens: [
        { id: 't1', t: 'I' },
        { id: 't2', t: 'send', why: '`send` היא צורת הבסיס. כאן צריך `sent`.', err: 'base_for_past' },
        { id: 't3', t: 'has', why: 'עם `I` לא משתמשים ב-`has`.', err: 'have_agreement' },
      ],
      accept: [
        { a: 'I sent the report yesterday', o: 'correct_target' },
        { a: 'Yesterday I sent the report', o: 'valid_alternative', note: 'גם נכון: `yesterday` בתחילת המשפט.' },
        {
          a: "I've sent the report",
          o: 'target_not_used',
          note: 'תקין — בלי ציון זמן present perfect מתאים. אבל התבקשת לומר גם מתי, ועם `yesterday` צריך `I sent`.',
        },
        {
          a: 'I sent the report',
          o: 'target_not_used',
          note: 'תקין, אבל חסר מתי. עם הזמן: `I sent the report yesterday`.',
        },
      ],
      wrong: [
        {
          a: "I've sent the report yesterday",
          as: 'form_error',
          err: 'perfect_with_finished_time',
          fb: '`yesterday` הוא זמן שהסתיים, ולכן עבר פשוט: `I sent the report yesterday`. `I\'ve sent` מתאים רק בלי ציון זמן מוגמר — גם כשהדוח חשוב עכשיו.',
        },
      ],
      rules: [
        {
          has: ["I've", 'yesterday'],
          as: 'form_error',
          err: 'perfect_with_finished_time',
          fb: 'עם `yesterday` לא משתמשים ב-`I\'ve` (`I have`). עבר פשוט: `I sent the report yesterday`.',
        },
        {
          has: ['yesterday the report'],
          as: 'form_error',
          err: 'word_order',
          fb: 'בדוק את סדר המילים: הזמן בא בסוף או בהתחלה — `I sent the report yesterday`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S06-04',
      v: 2,
      skill: 'S06',
      unit: 'S06',
      sub: 'experience',
      type: 'assemble',
      role: 'practice',
      stage: 1,
      ctx: 'daily.travel',
      fam: 'S06.ever-london',
      goal: 'לשאול אם מישהו היה אי פעם בלונדון',
      instr: 'בנה את השאלה באנגלית. לא חייבים להשתמש בכל המילים.',
      promptHe: 'היית פעם בלונדון?',
      sitHe: 'שיחה על נסיעות. אתה רוצה לדעת אם החבר שלך היה אי פעם בלונדון — לא מתי.',
      target: 'שאלה על ניסיון עד היום: `Have you ever` + V3',
      scaffold: ['Have / Has', 'you', 'ever', 'V3'],
      hint: 'לא שואלים מתי, אלא אם אי פעם. `been` הוא ה-V3 של `be`.',
      explain: 'שאלה על ניסיון בחיים, בלי זמן מסוים: `Have you ever been to London?` — `ever` פירושו אי פעם, עד עכשיו.',
      deep: 'present perfect מתאים כשהתקופה היא "כל החיים עד עכשיו" והזמן המדויק לא חשוב. כששואלים על נסיעה בזמן שהסתיים — עבר פשוט: `Did you go to London last year?`. `been to London` = היית שם (וחזרת).',
      tokens: [
        { id: 't1', t: 'have' },
        { id: 't2', t: 'you' },
        { id: 't3', t: 'ever' },
        { id: 't4', t: 'been' },
        { id: 't5', t: 'to London' },
        { id: 't6', t: 'has', why: 'עם `you` משתמשים ב-`have`, לא ב-`has`.', err: 'have_agreement' },
        {
          id: 't7',
          t: 'did',
          why: 'אחרי `did` בא פועל בסיס, ו-`been` אינו כזה. לשאלה על ניסיון עד היום: `Have you ever been…?`',
          err: 'did_with_perfect',
        },
        { id: 't8', t: 'being', why: '`being` אינו V3. אחרי `have` בא `been`: `Have you ever been…?`', err: 'being_for_been' },
      ],
      accept: [
        { a: 'Have you ever been to London', o: 'correct_target' },
        {
          a: 'Have you been to London',
          o: 'valid_alternative',
          note: 'גם נכון — שואל אם היית שם עד עכשיו. `ever` מוסיף את ה"אי פעם".',
        },
      ],
      rules: [
        {
          order: ['you', 'have', 'ever'],
          as: 'form_error',
          err: 'no_inversion',
          fb: 'בשאלה `Have` בא לפני `you`: `Have you ever been to London?`. (`ever` לא בא במשפט חיובי רגיל.)',
        },
        {
          order: ['you', 'have'],
          as: 'target_not_used',
          err: 'declarative_question',
          fb: '`You have been to London?` אפשרי בדיבור, כשמופתעים. שאלה רגילה מתחילה ב-`Have`: `Have you ever been to London?`',
        },
        {
          has: ['been ever'],
          as: 'form_error',
          err: 'word_order',
          fb: '`ever` בא לפני ה-V3: `Have you ever been…?`',
        },
        {
          has: ['ever to london'],
          as: 'form_error',
          err: 'missing_verb',
          fb: 'אחרי `ever` בא מיד ה-V3, `been`: `Have you ever been to London?`',
        },
      ],
      end: '?',
    },
    {
      id: 'S06-05',
      v: 1,
      skill: 'S06',
      unit: 'S06',
      sub: 'result_vs_time',
      type: 'transform',
      role: 'practice',
      stage: 1,
      ctx: 'daily.home',
      fam: 'S06.lost-keys',
      goal: 'להוסיף מתי איבדת את המפתחות',
      instr: 'הוסף למשפט את `yesterday` ותקן מה שצריך.',
      promptHe: 'איבדתי את המפתחות אתמול.',
      sitHe: 'אמרת לחבר `I have lost my keys` — אין לך אותם עכשיו. עכשיו אתה מוסיף שזה קרה אתמול.',
      target: 'לומר מתי — עם `yesterday`',
      fromLabel: 'בלי זמן: התוצאה עכשיו',
      toLabel: 'עם זמן שהסתיים',
      hint: 'ברגע שמוסיפים `yesterday`, מה קורה ל-`have`?',
      explain:
        '`I have lost my keys` — התוצאה עכשיו, בלי לומר מתי. עם `yesterday` עוברים לעבר פשוט: `I lost my keys yesterday`.',
      deep: 'שני המשפטים נכונים, כל אחד במקומו. present perfect מדבר על המצב עכשיו (המפתחות חסרים) ולא אומר מתי. ברגע שנותנים זמן שהסתיים עוברים לעבר פשוט — גם אם המפתחות עדיין חסרים. באנגלית אמריקאית נפוץ מאוד גם `I lost my keys` בלי ציון זמן.',
      source: [
        { id: 's1', t: 'I' },
        {
          id: 's2',
          t: 'have',
          why: 'בתרגיל הזה מוסיפים `yesterday` — זמן שהסתיים — ולכן אין `have`: `I lost my keys yesterday`.',
          err: 'perfect_with_finished_time',
        },
        { id: 's3', t: 'lost' },
        { id: 's4', t: 'my keys' },
      ],
      sourceEnd: '.',
      tokens: [
        { id: 't1', t: 'yesterday' },
        { id: 't2', t: 'lose', why: '`lose` היא צורת הבסיס. לעבר: `lost`.', err: 'base_for_past' },
        { id: 't3', t: 'has', why: 'עם `I` לא משתמשים ב-`has`.', err: 'have_agreement' },
      ],
      accept: [
        { a: 'I lost my keys yesterday', o: 'correct_target' },
        { a: 'Yesterday I lost my keys', o: 'valid_alternative', note: 'גם נכון: `yesterday` בתחילת המשפט.' },
      ],
      wrong: [
        {
          a: 'I have lost my keys',
          as: 'target_not_used',
          err: 'not_transformed',
          fb: 'המשפט תקין — present perfect, התוצאה עכשיו. אבל התבקשת להוסיף `yesterday`, ואז צריך עבר פשוט: `I lost my keys yesterday`.',
        },
        {
          a: 'I have lost my keys yesterday',
          as: 'form_error',
          err: 'perfect_with_finished_time',
          fb: 'עם `yesterday` — זמן שהסתיים — אין `have`: `I lost my keys yesterday`. זה נכון גם אם המפתחות עדיין חסרים.',
        },
        {
          a: 'I lost my keys',
          as: 'target_not_used',
          err: 'missing_time',
          fb: 'המשפט תקין, אבל לא הוספת `yesterday`: `I lost my keys yesterday`.',
        },
      ],
      rules: [
        {
          has: ['have', 'yesterday'],
          as: 'form_error',
          err: 'perfect_with_finished_time',
          fb: 'עם `yesterday` לא משתמשים ב-`have`. עבר פשוט: `I lost my keys yesterday`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S06-06',
      v: 1,
      skill: 'S06',
      unit: 'S06',
      sub: 'finished_time',
      type: 'assemble',
      role: 'practice',
      stage: 1,
      ctx: 'work.project',
      fam: 'S06.project-ago',
      goal: 'לומר לפני כמה זמן התחלתם את הפרויקט',
      instr: 'בנה את המשפט באנגלית. לא חייבים להשתמש בכל המילים.',
      promptHe: 'התחלנו את הפרויקט לפני יומיים.',
      target: 'לומר מתי — "לפני יומיים"',
      hint: '"לפני יומיים" הוא זמן שהסתיים. באנגלית `ago` בא אחרי פרק הזמן.',
      explain: '`two days ago` הוא זמן שהסתיים, ולכן עבר פשוט: `We started the project two days ago`.',
      deep: '"לפני יומיים" באנגלית: `two days ago` — פרק הזמן ואחריו `ago`. `before` בא לפני נקודה או אירוע (`before Monday`, `before the meeting`). וכמו עם `yesterday`: עם `ago` אין `have`.',
      tokens: [
        { id: 't1', t: 'we' },
        { id: 't2', t: 'started' },
        { id: 't3', t: 'the project' },
        { id: 't4', t: 'two days ago' },
        { id: 't5', t: 'have' },
        { id: 't6', t: 'start', why: '`start` היא צורת הבסיס. כאן צריך `started`.', err: 'base_for_past' },
        {
          id: 't7',
          t: 'before two days',
          why: '"לפני יומיים" באנגלית: `two days ago`. `before` בא לפני נקודה או אירוע (`before Monday`), לא לפני פרק זמן.',
          err: 'before_for_ago',
        },
      ],
      accept: [
        { a: 'We started the project two days ago', o: 'correct_target' },
        { a: 'Two days ago we started the project', o: 'valid_alternative', note: 'גם נכון: הזמן בתחילת המשפט.' },
        {
          a: 'We started the project',
          o: 'target_not_used',
          note: 'תקין, אבל חסר מתי: `two days ago`.',
        },
        {
          a: 'We have started the project',
          o: 'target_not_used',
          note: 'תקין — present perfect בלי ציון זמן. אבל התבקשת לומר מתי, ועם `two days ago` צריך עבר פשוט: `We started`.',
        },
      ],
      rules: [
        {
          has: ['have', 'ago'],
          as: 'form_error',
          err: 'perfect_with_finished_time',
          fb: '`two days ago` הוא זמן שהסתיים, ולכן בלי `have`: `We started the project two days ago`.',
        },
        {
          has: ['have start'],
          as: 'form_error',
          err: 'have_base',
          fb: 'אחרי `have` בא V3 (`started`). אבל כאן, עם "לפני יומיים", צריך עבר פשוט בלי `have`: `We started the project two days ago`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S06-07',
      v: 2,
      skill: 'S06',
      unit: 'S06',
      sub: 'unfinished_period',
      type: 'assemble',
      role: 'practice',
      stage: 2,
      ctx: 'work.meeting',
      fam: 'S06.meetings-this-week',
      goal: 'לספר כמה פעמים נפגשתם השבוע, כשהשבוע עוד לא נגמר',
      instr: 'בנה משפט אחד באנגלית.',
      sitHe: 'יום רביעי, והשבוע עוד לא נגמר. מיום ראשון נפגשתם כבר שלוש פעמים עם המעצבים. ספר למנהל.',
      target: 'present perfect — השבוע עוד נמשך',
      hint: 'השבוע עוד לא נגמר: סופרים מה קרה עד עכשיו.',
      explain: 'השבוע עוד נמשך, ולכן present perfect: `We have met with the designers three times this week`.',
      deep: '`this week`, `today`, `this month` — כשהתקופה עוד לא נגמרה, present perfect סופר מה קרה עד עכשיו. בסוף השבוע, כשהוא כבר נגמר, אפשר לומר `We met with them three times this week`. `last week` הוא זמן שהסתיים — רק עבר פשוט.',
      tokens: [
        { id: 't1', t: 'we' },
        { id: 't2', t: 'have' },
        { id: 't3', t: 'met' },
        { id: 't4', t: 'with the designers' },
        { id: 't5', t: 'three times' },
        { id: 't6', t: 'this week' },
        { id: 't7', t: 'has', why: 'עם `we` משתמשים ב-`have`, לא ב-`has`.', err: 'have_agreement' },
        {
          id: 't8',
          t: 'meeting',
          why: '`meeting` לא מתאים כאן: אחרי `have` בא V3 — `have met`.',
          err: 'ing_for_v3',
        },
        {
          id: 't9',
          t: 'last week',
          why: '`last week` = השבוע שעבר, זמן שהסתיים. הפגישות היו השבוע, והוא עוד נמשך: `this week`.',
          err: 'wrong_period',
          as: 'meaning_mismatch',
        },
      ],
      accept: [
        { a: 'We have met with the designers three times this week', o: 'correct_target' },
        {
          a: 'This week we have met with the designers three times',
          o: 'valid_alternative',
          note: 'גם נכון: `this week` בתחילת המשפט.',
        },
        {
          a: 'We met with the designers three times this week',
          o: 'target_not_used',
          note: 'נשמע גם כך, בעיקר באנגלית אמריקאית. כשהשבוע עוד נמשך, present perfect מדגיש "עד עכשיו" — וזה מה שהתרגיל ביקש.',
        },
        {
          a: 'This week we met with the designers three times',
          o: 'target_not_used',
          note: 'נשמע גם כך, בעיקר באנגלית אמריקאית. כשהשבוע עוד נמשך, present perfect מדגיש "עד עכשיו" — וזה מה שהתרגיל ביקש.',
        },
        {
          a: 'We have met three times with the designers this week',
          o: 'valid_alternative',
          note: 'גם נכון: `three times` לפני `with the designers`.',
        },
        {
          a: 'This week we have met three times with the designers',
          o: 'valid_alternative',
          note: 'גם נכון: `this week` בתחילת המשפט, ו-`three times` לפני `with the designers`.',
        },
        {
          a: 'We met three times with the designers this week',
          o: 'target_not_used',
          note: 'נשמע גם כך, בעיקר באנגלית אמריקאית. כשהשבוע עוד נמשך, present perfect מדגיש "עד עכשיו" — וזה מה שהתרגיל ביקש.',
        },
        {
          a: 'This week we met three times with the designers',
          o: 'target_not_used',
          note: 'נשמע גם כך, בעיקר באנגלית אמריקאית. כשהשבוע עוד נמשך, present perfect מדגיש "עד עכשיו" — וזה מה שהתרגיל ביקש.',
        },
      ],
      rules: [
        {
          has: ['have', 'last week'],
          as: 'form_error',
          err: 'perfect_with_finished_time',
          fb: '`last week` הוא זמן שהסתיים — אין איתו `have`. וממילא הפגישות היו השבוע: `We have met with the designers three times this week`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S06-08',
      v: 1,
      skill: 'S06',
      unit: 'S06',
      sub: 'finished_time_present_link',
      type: 'correct',
      role: 'practice',
      stage: 3,
      ctx: 'work.software',
      fam: 'S06.file-monday-now',
      goal: 'לומר שעדכנת את הקובץ ביום שני, ולכן אפשר להשתמש בו עכשיו',
      instr: 'אם יש טעות — גע במילה או ברווח ובחר תיקון. אם המשפט תקין, בחר "אין צורך בתיקון".',
      sitHe: 'ביום שני עדכנת את קובץ המחירים המשותף. היום עמיתה שואלת אם אפשר כבר לעבוד איתו.',
      hint: 'יש כאן זמן שהסתיים (`on Monday`) וגם קשר להווה (`now`). מה מהם קובע את צורת הפועל?',
      explain:
        'המשפט נכון כמו שהוא: `on Monday` הוא זמן שהסתיים, ולכן `updated`. הקשר להווה (`so you can use it now`) לא משנה את זה.',
      deep: 'זו המלכודת: "יש תוצאה עכשיו, אז צריך `have`". אבל ציון זמן מוגמר (`on Monday`) קובע עבר פשוט, גם כשהתוצאה חשובה עכשיו. בלי `on Monday` אפשר גם `I have updated the shared file, so you can use it now`.',
      source: [
        { id: 's1', t: 'I' },
        { id: 's2', t: 'updated' },
        { id: 's3', t: 'the shared file' },
        { id: 's4', t: 'on Monday' },
        { id: 's5', t: 'so you can use it now' },
      ],
      tokens: [
        { id: 't1', t: 'have' },
        { id: 't2', t: 'has', why: 'עם `I` לא משתמשים ב-`has`.', err: 'have_agreement' },
      ],
      accept: [
        { a: 'I updated the shared file on Monday, so you can use it now', o: 'correct_target' },
        {
          a: 'On Monday I updated the shared file, so you can use it now',
          o: 'valid_alternative',
          note: 'גם נכון — אבל המשפט המקורי היה תקין כמו שהוא.',
        },
        {
          a: 'I have updated the shared file, so you can use it now',
          o: 'valid_alternative',
          note: 'גם נכון: בלי ציון זמן present perfect מתאים. אבל המשפט המקורי היה תקין — עם `on Monday` משתמשים בעבר פשוט.',
        },
        {
          a: 'I updated the shared file, so you can use it now',
          o: 'valid_alternative',
          note: 'גם נכון, רק בלי `on Monday`. המשפט המקורי היה תקין כמו שהוא.',
        },
      ],
      wrong: [
        {
          a: 'I have updated the shared file on Monday, so you can use it now',
          as: 'form_error',
          err: 'perfect_with_finished_time',
          fb: 'המשפט המקורי היה נכון. `on Monday` הוא זמן שהסתיים, ולכן `I updated` — גם כשהתוצאה חשובה עכשיו.',
        },
      ],
      rules: [
        {
          has: ['have', 'on Monday'],
          as: 'form_error',
          err: 'perfect_with_finished_time',
          fb: 'עם `on Monday` — זמן שהסתיים — אין `have`. המשפט המקורי היה נכון: `I updated the shared file on Monday…`',
        },
      ],
      end: '.',
    },
    {
      id: 'S06-09',
      v: 1,
      skill: 'S06',
      unit: 'S06',
      sub: 'this_morning',
      type: 'assemble',
      role: 'practice',
      stage: 2,
      ctx: 'work.schedule',
      fam: 'S06.this-morning-afternoon',
      goal: 'לומר שהתקשרת הבוקר, כשכבר אחר הצהריים',
      instr: 'קרא את הסיטואציה ובנה משפט אחד באנגלית.',
      sitEn:
        'It\'s 3 p.m. At nine this morning you called the technician about the broken printer. Your manager asks: "When did you call the technician?"',
      trHe: 'השעה שלוש אחר הצהריים. בתשע בבוקר התקשרת לטכנאי בגלל המדפסת המקולקלת. המנהלת שואלת: "מתי התקשרת לטכנאי?"',
      hint: 'בשלוש אחר הצהריים — הבוקר עוד נמשך או שכבר נגמר?',
      explain:
        'בשלוש אחר הצהריים הבוקר כבר נגמר, ולכן `this morning` הוא זמן שהסתיים: `I called the technician this morning`.',
      deep: '`this morning` תלוי בשעה. כשעדיין בוקר, הבוקר הוא תקופה שעוד נמשכת, ואפשר גם `I have called him this morning`. אחר הצהריים הבוקר כבר מאחוריך — עבר פשוט. וגם השאלה עצמה (`When did you…?`) מבקשת זמן, ועל "מתי" עונים בעבר פשוט.',
      tokens: [
        { id: 't1', t: 'I' },
        { id: 't2', t: 'called' },
        { id: 't3', t: 'the technician' },
        { id: 't4', t: 'this morning' },
        {
          id: 't5',
          t: 'have',
          why: '`have called` לא עונה על "מתי", ועם `this morning` הוא מתאים רק כשעדיין בוקר. בשלוש אחר הצהריים: `I called`.',
          err: 'perfect_with_finished_time',
        },
        { id: 't6', t: 'call', why: '`call` היא צורת הבסיס. כאן צריך `called`.', err: 'base_for_past' },
        { id: 't7', t: 'has', why: 'עם `I` לא משתמשים ב-`has`.', err: 'have_agreement' },
      ],
      accept: [
        { a: 'I called the technician this morning', o: 'correct_target' },
        {
          a: 'This morning I called the technician',
          o: 'valid_alternative',
          note: 'גם נכון: `this morning` בתחילת המשפט.',
        },
      ],
      wrong: [
        {
          a: 'I have called the technician this morning',
          as: 'form_error',
          err: 'perfect_with_finished_time',
          fb: 'בשלוש אחר הצהריים הבוקר כבר נגמר, ולכן עבר פשוט: `I called the technician this morning`. `have called … this morning` מתאים רק כשעדיין בוקר.',
        },
        {
          a: 'I have called the technician',
          as: 'meaning_mismatch',
          err: 'missing_time',
          fb: 'המשפט תקין, אבל המנהלת שאלה מתי. על "מתי" עונים עם הזמן, בעבר פשוט: `I called the technician this morning`.',
        },
      ],
      rules: [
        {
          has: ['have', 'this morning'],
          as: 'form_error',
          err: 'perfect_with_finished_time',
          fb: 'אחר הצהריים `this morning` הוא זמן שהסתיים, ולכן בלי `have`: `I called the technician this morning`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S06-10',
      v: 1,
      skill: 'S06',
      unit: 'S06',
      sub: 'this_morning',
      type: 'discriminate',
      role: 'practice',
      stage: 2,
      ctx: 'work.email',
      fam: 'S06.emails-still-morning',
      goal: 'לספר כמה מיילים ענית הבוקר, כשהבוקר עוד לא נגמר',
      instr: 'בחר את כל המשפטים שמתאימים למצב.',
      sitHe: 'השעה עשר וחצי בבוקר. מאז שהגעת בשמונה ענית על עשרים מיילים. עמיתה שואלת איך עובר עליך הבוקר.',
      hint: 'הבוקר עוד לא נגמר. האם זה משאיר רק צורה אחת?',
      explain:
        'כשעדיין בוקר, `this morning` הוא תקופה שעוד נמשכת: present perfect מתאים, וגם עבר פשוט אפשרי. עם `yesterday` אין `have`.',
      deep: 'אחר הצהריים היית אומר רק `I answered twenty emails this morning`, כי הבוקר כבר נגמר. בזמן שהבוקר עוד נמשך, `I\'ve answered` מדגיש "עד עכשיו", ו-`I answered` מציג את המיילים כמשהו שכבר נעשה — שתי הצורות תקינות.',
      multi: true,
      options: [
        {
          id: 'a',
          en: "I've answered twenty emails this morning.",
          v: 'fits',
          why: 'הבוקר עוד לא נגמר, ו-present perfect סופר מה קרה עד עכשיו.',
        },
        {
          id: 'b',
          en: 'I answered twenty emails this morning.',
          v: 'fits',
          why: 'כשעדיין בוקר גם עבר פשוט אפשרי: הוא מציג את המיילים כמשהו שכבר נעשה.',
        },
        {
          id: 'c',
          en: "I've answered twenty emails yesterday.",
          v: 'ungrammatical',
          why: '`yesterday` הוא זמן שהסתיים — אין איתו `have`. וממילא המיילים נענו היום.',
          err: 'perfect_with_finished_time',
        },
        {
          id: 'd',
          en: "I'm answering twenty emails this morning.",
          v: 'other_meaning',
          why: 'משפט תקין, אבל הוא מתאר מה אתה עושה עכשיו או מתכנן — לא כמה מיילים כבר ענית.',
          err: 'progressive_for_result',
        },
      ],
    },
    {
      id: 'S06-11',
      v: 2,
      skill: 'S06',
      unit: 'S06',
      sub: 'yet_question',
      type: 'assemble',
      role: 'practice',
      stage: 2,
      ctx: 'work.project',
      fam: 'S06.budget-yet',
      goal: 'לשאול אם עמית כבר סיים את הצעת התקציב',
      instr: 'בנה את השאלה באנגלית.',
      sitHe: 'הצעת התקציב צריכה להיות מוכנה עד סוף השבוע. אתה רוצה לדעת אם עמית כבר סיים אותה — עד עכשיו.',
      target: 'present perfect עם `yet`',
      hint: 'שואלים על "עד עכשיו", בלי זמן שהסתיים. `yet` בא בסוף השאלה.',
      explain: 'שאלה על עד עכשיו, בלי זמן שהסתיים: `Have you finished the budget proposal yet?` — `yet` בא בסוף.',
      deep: 'באנגלית אמריקאית מדוברת שומעים הרבה `Did you finish it yet?` — זו לא טעות. הצורה הסטנדרטית, שמתאימה בכל מקום: `Have you finished it yet?`. אחרי `did` בא פועל בסיס (`finish`), ואחרי `have` בא V3 (`finished`).',
      tokens: [
        { id: 't1', t: 'have' },
        { id: 't2', t: 'you' },
        { id: 't3', t: 'finished' },
        { id: 't4', t: 'the budget proposal' },
        { id: 't5', t: 'yet' },
        { id: 't6', t: 'did' },
        { id: 't7', t: 'finish' },
        { id: 't8', t: 'has', why: 'עם `you` משתמשים ב-`have`, לא ב-`has`.', err: 'have_agreement' },
      ],
      accept: [
        { a: 'Have you finished the budget proposal yet', o: 'correct_target' },
        {
          a: 'Have you finished the budget proposal',
          o: 'valid_alternative',
          note: 'גם נכון, בלי `yet`. `yet` מוסיף את ה"כבר / עד עכשיו".',
        },
        {
          a: 'Did you finish the budget proposal yet',
          o: 'target_not_used',
          note: 'נפוץ באנגלית אמריקאית מדוברת ואינו טעות. התרגיל ביקש present perfect: `Have you finished … yet?`',
        },
        {
          a: 'Did you finish the budget proposal',
          o: 'target_not_used',
          note: 'תקין — שאלה בעבר פשוט. התרגיל ביקש present perfect עם `yet`: `Have you finished the budget proposal yet?`',
        },
        {
          a: 'Have you finished yet',
          o: 'valid_alternative',
          note: 'נכון, כשברור על מה מדובר. עם המושא: `Have you finished the budget proposal yet?`',
        },
        {
          a: 'Did you finish yet',
          o: 'target_not_used',
          note: 'נפוץ באנגלית אמריקאית מדוברת ואינו טעות. התרגיל ביקש present perfect: `Have you finished the budget proposal yet?`',
        },
      ],
      rules: [
        {
          has: ['have you finish'],
          as: 'form_error',
          err: 'have_base',
          fb: 'אחרי `have` בא V3: `Have you finished…?`',
        },
        {
          has: ['did you finished'],
          as: 'form_error',
          err: 'did_v2',
          fb: 'אחרי `did` בא פועל בסיס: `Did you finish…?`. בצורה הסטנדרטית: `Have you finished … yet?`',
        },
        {
          has: ['yet the budget proposal'],
          as: 'form_error',
          err: 'word_order',
          fb: '`yet` בא בסוף השאלה: `Have you finished the budget proposal yet?`',
        },
        {
          order: ['you', 'have'],
          has: ['yet'],
          lacks: ['did'],
          as: 'form_error',
          err: 'no_inversion',
          fb: 'בשאלה `Have` בא לפני `you`: `Have you finished the budget proposal yet?`',
        },
        {
          order: ['you', 'have'],
          lacks: ['did'],
          as: 'target_not_used',
          err: 'declarative_question',
          fb: '`You have finished…?` אפשרי בדיבור, כשמופתעים. שאלה רגילה מתחילה ב-`Have`: `Have you finished the budget proposal yet?`',
        },
      ],
      end: '?',
    },
    {
      id: 'S06-12',
      v: 1,
      skill: 'S06',
      unit: 'S06',
      sub: 'contrast',
      type: 'discriminate',
      role: 'practice',
      stage: 3,
      ctx: 'daily.travel',
      fam: 'S06.london-last-year',
      goal: 'לשאול על נסיעה בזמן שהסתיים',
      instr: 'בחר את השאלה שמתאימה למצב.',
      sitHe: 'חברה סיפרה שבשנה שעברה טיילה באנגליה. אתה רוצה לדעת אם בטיול ההוא היא הגיעה ללונדון.',
      hint: 'השאלה היא על הטיול של שנה שעברה — זמן שהסתיים.',
      explain:
        'על זמן שהסתיים (`last year`) שואלים בעבר פשוט: `Did you go to London last year?`. `Have you ever been…?` שואל על כל החיים.',
      deep: 'שלוש השאלות נראות קרובות, אבל כל אחת עושה משהו אחר. `Have you been to London last year?` שגויה, כי present perfect לא הולך עם זמן שהסתיים. `Have you ever been to London?` תקינה לגמרי — אבל היא שואלת אם אי פעם, לא על הטיול.',
      multi: false,
      options: [
        {
          id: 'a',
          en: 'Did you go to London last year?',
          v: 'fits',
          why: 'שאלה על זמן שהסתיים — עבר פשוט: `did` + `go`.',
        },
        {
          id: 'b',
          en: 'Have you been to London last year?',
          v: 'ungrammatical',
          why: '`last year` הוא זמן שהסתיים — אין איתו `have`. על זמן כזה שואלים: `Did you go…?`',
          err: 'perfect_with_finished_time',
        },
        {
          id: 'c',
          en: 'Have you ever been to London?',
          v: 'other_meaning',
          why: 'שאלה תקינה, אבל היא שואלת אם אי פעם היית בלונדון — לא על הטיול בשנה שעברה.',
          err: 'experience_for_specific',
        },
      ],
    },
    {
      id: 'S06-D1',
      v: 1,
      skill: 'S06',
      unit: 'S06',
      sub: 'dialogue',
      type: 'dialogue',
      role: 'practice',
      stage: 2,
      ctx: 'work.software',
      fam: 'S06.dialogue-booking-system',
      goal: 'לספר לעמיתה מתי ניסית את המערכת ומה עשית בה עד עכשיו',
      instr: 'ענה לדנה בכל תור.',
      partnerName: 'Dana',
      setupHe: 'דנה, עמיתה חדשה, שואלת אותך על מערכת זימון התורים החדשה.',
      hint: 'בתור הראשון — מתי (זמן שהסתיים). בתור השני — כמה עד עכשיו.',
      explain: 'זמן שהסתיים: `I tried it on Monday`. עד עכשיו: `I have booked five appointments so far`.',
      turns: [
        {
          partner: { en: 'Have you tried the new booking system yet?', he: 'כבר ניסית את מערכת זימון התורים החדשה?' },
          sub: 'finished_time',
          instr: 'ענה שכן, ואמור שניסית אותה ביום שני.',
          target: 'לומר מתי — עם `on Monday`',
          hint: 'היא שאלה ב-present perfect, אבל אתה מוסיף זמן שהסתיים.',
          explain:
            'עם `on Monday` — זמן שהסתיים — עונים בעבר פשוט: `Yes, I tried it on Monday`, גם כשהשאלה הייתה `Have you…?`',
          build: {
            tokens: [
              { id: 't1', t: 'yes' },
              { id: 't2', t: 'I' },
              { id: 't3', t: 'tried' },
              { id: 't4', t: 'it' },
              { id: 't5', t: 'on Monday' },
              { id: 't6', t: 'have' },
              { id: 't7', t: 'try', why: '`try` היא צורת הבסיס. כאן צריך `tried`.', err: 'base_for_past' },
              { id: 't8', t: 'in Monday', why: 'לפני יום בשבוע באה `on`: `on Monday`.', err: 'preposition_day' },
            ],
            accept: [
              { a: 'Yes, I tried it on Monday', o: 'correct_target' },
              { a: 'I tried it on Monday', o: 'valid_alternative', note: 'גם נכון, גם בלי `yes`.' },
              {
                a: 'Yes, I have tried it',
                o: 'target_not_used',
                note: 'תשובה טבעית לשאלה, אבל התבקשת לומר גם מתי — ועם `on Monday` צריך עבר פשוט: `I tried it on Monday`.',
              },
              {
                a: 'I have tried it',
                o: 'target_not_used',
                note: 'תשובה טבעית לשאלה, אבל התבקשת לומר גם מתי — ועם `on Monday` צריך עבר פשוט: `I tried it on Monday`.',
              },
              {
                a: 'Yes, I have',
                o: 'target_not_used',
                note: 'תשובה קצרה וטבעית, אבל התבקשת לומר גם מתי: `Yes, I tried it on Monday`.',
              },
            ],
            wrong: [
              {
                a: 'Yes, I have tried it on Monday',
                as: 'form_error',
                err: 'perfect_with_finished_time',
                fb: 'עם `on Monday` — זמן שהסתיים — אין `have`: `Yes, I tried it on Monday`. זה נכון גם כשהשאלה נשאלה ב-`Have you…?`',
              },
            ],
            rules: [
              {
                has: ['have', 'on Monday'],
                as: 'form_error',
                err: 'perfect_with_finished_time',
                fb: 'עם `on Monday` — זמן שהסתיים — אין `have`: `Yes, I tried it on Monday`.',
              },
              {
                has: ['have try'],
                as: 'form_error',
                err: 'have_base',
                fb: 'אחרי `have` בא V3 (`tried`). וכאן, עם `on Monday`, צריך עבר פשוט: `I tried it on Monday`.',
              },
            ],
            end: '.',
          },
        },
        {
          partner: {
            en: 'Nice. How many appointments have you booked with it so far?',
            he: 'יפה. כמה תורים כבר קבעת בה עד עכשיו?',
          },
          sub: 'so_far',
          instr: 'ענה שקבעת בה חמישה תורים עד עכשיו.',
          target: 'עד עכשיו: `have` + V3',
          hint: '`so far` = עד עכשיו. התקופה עוד לא נגמרה.',
          explain: '`so far` — עד עכשיו, בלי זמן שהסתיים: `I have booked five appointments so far`.',
          build: {
            tokens: [
              { id: 't1', t: 'I' },
              { id: 't2', t: 'have' },
              { id: 't3', t: 'booked' },
              { id: 't4', t: 'five appointments' },
              { id: 't5', t: 'so far' },
              { id: 't6', t: 'has', why: 'עם `I` לא משתמשים ב-`has`.', err: 'have_agreement' },
              { id: 't7', t: 'book', why: '`book` היא צורת הבסיס. כאן צריך `booked`.', err: 'base_for_v3' },
            ],
            accept: [
              { a: 'I have booked five appointments so far', o: 'correct_target' },
              { a: 'So far I have booked five appointments', o: 'valid_alternative', note: 'גם נכון: `so far` בתחילת המשפט.' },
              {
                a: 'I booked five appointments so far',
                o: 'target_not_used',
                note: 'נשמע לפעמים בדיבור, בעיקר באנגלית אמריקאית. עם `so far` הצורה הרגילה היא present perfect: `I have booked`.',
              },
              {
                a: 'So far I booked five appointments',
                o: 'target_not_used',
                note: 'נשמע לפעמים בדיבור, בעיקר באנגלית אמריקאית. עם `so far` הצורה הרגילה היא present perfect: `I have booked`.',
              },
            ],
            end: '.',
          },
        },
      ],
      closing: { en: 'Great, so you can show me how it works.', he: 'מצוין, אז תוכל להראות לי איך זה עובד.' },
    },
    {
      id: 'S06-C1',
      v: 2,
      skill: 'S06',
      unit: 'S06',
      sub: 'finished_time',
      type: 'assemble',
      role: 'check',
      stage: 2,
      ctx: 'work.job',
      fam: 'S06.started-2021',
      goal: 'לומר באיזו שנה התחלת לעבוד במקום',
      instr: 'קרא את הסיטואציה ובנה משפט אחד באנגלית.',
      sitEn: 'A new colleague asks: "When did you start working here?" You started in 2021.',
      trHe: 'עמית חדש שואל: "מתי התחלת לעבוד כאן?" התחלת ב-2021.',
      hint: 'השאלה היא "מתי". שנה שכבר נגמרה היא זמן שהסתיים.',
      explain: '`in 2021` הוא זמן שהסתיים, ולכן עבר פשוט: `I started working here in 2021`.',
      deep: 'על "מתי התחלת" עונים בעבר פשוט, עם הזמן: `in 2021`. אם רוצים לומר כמה זמן זה נמשך עד היום, זה משפט אחר: `I have worked here since 2021`.',
      tokens: [
        { id: 't1', t: 'I' },
        { id: 't2', t: 'started' },
        { id: 't3', t: 'working here' },
        { id: 't4', t: 'in' },
        { id: 't5', t: '2021' },
        {
          id: 't6',
          t: 'have',
          why: 'השאלה היא מתי, והתשובה היא זמן שהסתיים — עבר פשוט, בלי `have`: `I started working here in 2021`.',
          err: 'perfect_with_finished_time',
        },
        {
          id: 't7',
          t: 'since',
          why: '`since 2021` מתאר "מאז ועד עכשיו" ובא עם present perfect (`I have worked here since 2021`). לשאלה "מתי התחלת": `in 2021`.',
          err: 'since_for_when',
        },
        { id: 't8', t: 'start', why: '`start` היא צורת הבסיס. כאן צריך `started`.', err: 'base_for_past' },
      ],
      accept: [
        { a: 'I started working here in 2021', o: 'correct_target' },
        { a: 'In 2021 I started working here', o: 'valid_alternative', note: 'גם נכון: הזמן בתחילת המשפט.' },
        {
          a: 'I started in 2021',
          o: 'valid_alternative',
          note: 'נכון — תשובה קצרה וטבעית לשאלה "מתי". המשפט המלא: `I started working here in 2021`.',
        },
      ],
      wrong: [
        {
          a: 'I have started working here',
          as: 'meaning_mismatch',
          err: 'missing_time',
          fb: 'המשפט תקין, אבל הוא לא עונה על "מתי". עם הזמן, בעבר פשוט: `I started working here in 2021`.',
        },
      ],
      rules: [
        {
          has: ['have', 'in 2021'],
          as: 'form_error',
          err: 'perfect_with_finished_time',
          fb: '`in 2021` הוא זמן שהסתיים, ולכן בלי `have`: `I started working here in 2021`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S06-C2',
      v: 2,
      skill: 'S06',
      unit: 'S06',
      sub: 'finished_time',
      type: 'correct',
      role: 'check',
      stage: 3,
      ctx: 'daily.learning',
      fam: 'S06.french-student',
      goal: 'לספר שלמדת צרפתית בתקופת הלימודים',
      instr: 'אם יש טעות — גע במילה או ברווח ובחר תיקון. אם המשפט תקין, בחר "אין צורך בתיקון".',
      sitHe: 'חבר שואל אם אתה יודע צרפתית. למדת קצת צרפתית כשהיית סטודנט, ומאז לא.',
      hint: '`when I was a student` — התקופה הזאת עוד נמשכת?',
      explain:
        '`when I was a student` היא תקופה שהסתיימה, ולכן עבר פשוט: `I studied French when I was a student`.',
      deep: '`when I was…` מציין זמן גמור בדיוק כמו `in 2015` או `last year`, גם בלי תאריך. בלי ציון זמן אפשר לדבר על ניסיון: `I have studied French` — אבל אז לא אומרים מתי.',
      source: [
        { id: 's1', t: 'I' },
        { id: 's2', t: 'have' },
        { id: 's3', t: 'studied' },
        { id: 's4', t: 'French' },
        { id: 's5', t: 'when I was a student' },
      ],
      tokens: [
        { id: 't1', t: 'study', why: '`study` היא צורת הבסיס. כאן צריך `studied`.', err: 'base_for_past' },
        { id: 't2', t: 'has', why: 'עם `I` לא משתמשים ב-`has`.', err: 'have_agreement' },
      ],
      accept: [
        { a: 'I studied French when I was a student', o: 'correct_target' },
        {
          a: 'When I was a student, I studied French',
          o: 'valid_alternative',
          note: 'גם נכון: חלק הזמן בתחילת המשפט.',
        },
        {
          a: 'I have studied French',
          o: 'valid_alternative',
          note: 'גם נכון — ניסיון, בלי לומר מתי. כשמשאירים את `when I was a student` צריך עבר פשוט: `I studied`.',
        },
        {
          a: 'I studied French',
          o: 'valid_alternative',
          note: 'גם נכון, בלי לומר מתי. עם `when I was a student` המשפט המלא: `I studied French when I was a student`.',
        },
      ],
      wrong: [
        {
          a: 'I have studied French when I was a student',
          as: 'form_error',
          err: 'perfect_with_finished_time',
          fb: '`when I was a student` היא תקופה שהסתיימה, ולכן עבר פשוט: `I studied French when I was a student`.',
        },
      ],
      rules: [
        {
          has: ['have', 'when I was a student'],
          as: 'form_error',
          err: 'perfect_with_finished_time',
          fb: 'עם `when I was a student` — תקופה שהסתיימה — אין `have`: `I studied French when I was a student`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S06-C3',
      v: 2,
      skill: 'S06',
      unit: 'S06',
      sub: 'experience',
      type: 'assemble',
      role: 'check',
      stage: 2,
      ctx: 'work.clinic',
      fam: 'S06.phone-system-never',
      goal: 'לומר שעד היום לא השתמשת במערכת הטלפונים החדשה',
      instr: 'בנה משפט אחד באנגלית.',
      sitHe: 'במרפאה עברו לפני חודש למערכת טלפונים חדשה. עמית שואל אם אתה כבר מכיר אותה. עד היום לא השתמשת בה אפילו פעם אחת.',
      target: 'present perfect — עד היום',
      hint: 'מדובר בכל התקופה עד היום, בלי זמן שהסתיים. "אף פעם" = `never`.',
      explain: 'עד היום, בלי זמן שהסתיים: `I have never used the new phone system` — `never` בא בין `have` ל-V3.',
      deep: '`never` ו-`ever` מתארים את כל התקופה עד עכשיו, ולכן present perfect. `ever` בא בשאלות (`Have you ever used it?`); במשפט שאומר "אף פעם" — `never`. באנגלית אמריקאית מדוברת נשמע גם `I never used it`.',
      tokens: [
        { id: 't1', t: 'I' },
        { id: 't2', t: 'have' },
        { id: 't3', t: 'never' },
        { id: 't4', t: 'used' },
        { id: 't5', t: 'the new phone system' },
        {
          id: 't6',
          t: 'ever',
          why: '`ever` לא בא במשפט חיובי רגיל. כדי לומר "אף פעם": `never` — `I have never used…`',
          err: 'ever_in_statement',
        },
        { id: 't7', t: 'using', why: '`using` לא מתאים כאן: אחרי `have` בא V3 — `used`.', err: 'ing_for_v3' },
        { id: 't8', t: 'has', why: 'עם `I` לא משתמשים ב-`has`.', err: 'have_agreement' },
      ],
      accept: [
        { a: 'I have never used the new phone system', o: 'correct_target' },
        {
          a: 'I never used the new phone system',
          o: 'target_not_used',
          note: 'נשמע באנגלית אמריקאית מדוברת. כשמדובר בכל התקופה עד היום, הצורה הסטנדרטית היא `I have never used`.',
        },
        {
          a: 'I have never ever used the new phone system',
          o: 'valid_alternative',
          note: 'נכון — `never ever` מדגיש: "אף פעם, אפילו לא פעם אחת". בדרך כלל מספיק `never`.',
        },
        {
          a: 'I never ever used the new phone system',
          o: 'target_not_used',
          note: 'נשמע באנגלית אמריקאית מדוברת. כשמדובר בכל התקופה עד היום, הצורה הסטנדרטית היא `I have never (ever) used`.',
        },
      ],
      wrong: [
        {
          a: 'I used the new phone system',
          as: 'meaning_mismatch',
          err: 'affirmative_for_never',
          fb: 'המשפט תקין, אבל הוא אומר שכן השתמשת במערכת. כדי לומר "אף פעם": `I have never used the new phone system`.',
        },
      ],
      rules: [
        {
          has: ['using'],
          as: 'form_error',
          err: 'ing_for_v3',
          fb: '`using` לא מתאים כאן: אחרי `have` בא V3 — `I have never used the new phone system`.',
        },
        {
          has: ['have used'],
          lacks: ['never'],
          as: 'meaning_mismatch',
          err: 'affirmative_for_never',
          fb: 'המשפט תקין, אבל הוא אומר שכן השתמשת במערכת. כדי לומר "אף פעם": `I have never used the new phone system`.',
        },
        {
          has: ['never'],
          ends: 'ever',
          as: 'form_error',
          err: 'ever_position',
          fb: 'להדגשה `ever` בא מיד אחרי `never`: `I have never ever used the new phone system`. בסוף משפט כתוב, אחרי `never`, הוא לא טבעי.',
        },
      ],
      end: '.',
    },
  ],
};
