import type { SkillPack } from '../schema';

/**
 * S07 DO_BASE — do / does / did + base verb in questions and negatives.
 * Subject questions (no do: `Who called?`) belong to S09.
 */

const CORRECT_INSTR = 'אם יש טעות — גע במילה או ברווח ובחר תיקון. אם המשפט תקין, בחר "אין צורך בתיקון".';

export const S07: SkillPack = {
  skill: 'S07',
  lessons: [
    {
      unit: 'S07',
      title: '`do / does / did` + צורת בסיס',
      short:
        'בשאלה ובשלילה, `do / does / did` נושאים את הזמן ואת ה-s של גוף שלישי — ולכן הפועל שאחריהם חוזר לצורת הבסיס. `She sent it` ← `Did she send it?`',
      chain: ['do / does / did', 'V (base)'],
      examples: [
        { en: 'Where did she send it?', he: 'לאן היא שלחה את זה?' },
        { en: 'Does he work on Fridays?', he: 'הוא עובד בימי שישי?' },
        { en: "We didn't know.", he: 'לא ידענו.' },
      ],
      contrast: {
        a: { en: 'He works on Fridays.', he: 'הוא עובד בימי שישי.' },
        b: { en: "He doesn't work on Fridays.", he: 'הוא לא עובד בימי שישי.' },
        note: 'ה-s עוברת מהפועל ל-`doesn\'t`, ו-`work` חוזר לבסיס. כך גם בעבר: `She sent it` ← `She didn\'t send it` — הזמן מסומן פעם אחת בלבד.',
      },
      deep:
        '• `do / does / did` הם פועלי העזר של הפעלים הרגילים. בשאלה ובשלילה הם מקבלים את הזמן (`did`) ואת ה-s של `he / she / it` (`does`), ולכן הפועל הראשי נשאר בצורת הבסיס: `Did she call?`, `He doesn\'t know`.\n' +
        '• `does / doesn\'t` — עם `he / she / it` או עם שם ביחיד (`the clinic`, `my manager`). עם `I / you / we / they` — `do / don\'t`. `did / didn\'t` — זהה לכל הגופים.\n' +
        '• `he don\'t` נשמע בדיבור בחלק מהניבים, אבל אינו תקני. באנגלית תקנית: `he doesn\'t`.\n' +
        '• גם `have` כפועל ראשי ("יש ל…") מתנהג כך: `Does the hotel have parking?`, `The hotel doesn\'t have parking` — לא `has`.\n' +
        '• עם `be` ועם פעלים מודאליים (`can`, `must`, `will`) לא משתמשים ב-`do`: `Is she here?`, `Can you come?`.\n' +
        '• כששואלים על הנושא עצמו אין `do`: `Who called you?` — נלמד בנפרד.\n' +
        '• `I did send it` (בהדגשה: "כן, באמת שלחתי") הוא משפט חיובי תקין — גם שם אחרי `did` בא פועל בסיס.',
      pitfalls: [
        '`Did you invited them?` — אחרי `did` בא פועל בסיס: `Did you invite them?`',
        '`Does she works here?` — ה-s כבר נמצאת ב-`does`: `Does she work here?`',
        '`She don\'t need it` — עם `she`: `She doesn\'t need it`.',
        '`We didn\'t knew` — `We didn\'t know`.',
      ],
    },
  ],
  examples: {
    S07: [
      { en: 'Do you need a ride to the station?', he: 'אתה צריך הסעה לתחנה?' },
      { en: "Why didn't he answer the phone?", he: 'למה הוא לא ענה לטלפון?' },
      { en: "The new printer doesn't print in color.", he: 'המדפסת החדשה לא מדפיסה בצבע.' },
      {
        en: 'How much did the repair cost?',
        he: 'כמה עלה התיקון?',
        note: 'ל-`cost` אותה צורה בבסיס ובעבר. אחרי `did` זו צורת הבסיס.',
      },
    ],
  },
  items: [
    {
      id: 'S07-01',
      v: 2,
      skill: 'S07',
      unit: 'S07',
      sub: 'question',
      type: 'assemble',
      role: 'practice',
      stage: 1,
      ctx: 'work.meeting',
      fam: 'S07.invite-them-meeting',
      goal: 'לוודא עם עמית שהוא הזמין אותם לפגישה',
      instr: 'בנה את השאלה באנגלית. לא חייבים להשתמש בכל המילים.',
      promptHe: 'הזמנת אותם לפגישה?',
      sitHe: 'מחר יש פגישה עם נציגי הספק. עמית היה אמור להזמין אותם, ואתה רוצה לוודא שזה נעשה.',
      target: 'שאלה עם `did`',
      scaffold: ['Did', 'subject', 'V (base)'],
      hint: 'העבר כבר מסומן ב-`did`. באיזו צורה בא הפועל אחריו?',
      explain: 'בשאלה על העבר `did` בא לפני הנושא, והפועל חוזר לצורת הבסיס: `Did you invite them to the meeting?`',
      deep: 'בעברית שאלת כן/לא נשמעת כמו משפט רגיל, רק בטון אחר. באנגלית צריך פועל עזר בתחילת השאלה — בעבר זה `did`. הזמן מסומן פעם אחת בלבד, ב-`did`, ולכן `invited` חוזר ל-`invite`.',
      tokens: [
        { id: 't1', t: 'did' },
        { id: 't2', t: 'you' },
        { id: 't3', t: 'invite' },
        { id: 't4', t: 'them' },
        { id: 't5', t: 'to the meeting' },
        {
          id: 't6',
          t: 'invited',
          why: '`invited` בא רק במשפט רגיל בלי פועל עזר (`You invited them`). אחרי `did` בא פועל בסיס: `Did you invite them…?`',
          err: 'did_v2',
        },
        {
          id: 't7',
          t: 'do',
          why: '`Do you invite…?` שואל על הרגל — אם אתה נוהג להזמין אותם. כאן שואלים על הזמנה אחת שכבר הייתה אמורה לקרות: `Did you invite…?`',
          err: 'present_for_past',
          as: 'meaning_mismatch',
        },
      ],
      accept: [{ a: 'Did you invite them to the meeting', o: 'correct_target' }],
      wrong: [
        {
          a: 'You invited them to the meeting',
          as: 'target_not_used',
          err: 'declarative_question',
          fb: 'בדיבור אפשר לשאול גם בטון בלבד (`You invited them?`), בעיקר כדי לוודא משהו או להביע הפתעה. כאן התבקשה שאלה רגילה עם `did`: `Did you invite them to the meeting?`',
        },
        {
          a: 'You invited them',
          as: 'target_not_used',
          err: 'declarative_question',
          fb: 'בדיבור אפשר לשאול גם בטון בלבד (`You invited them?`), בעיקר כדי לוודא משהו או להביע הפתעה. כאן התבקשה שאלה רגילה עם `did`: `Did you invite them to the meeting?`',
        },
      ],
      rules: [
        {
          has: ['did', 'invited'],
          as: 'form_error',
          err: 'did_v2',
          fb: 'אחרי `did` בא פועל בסיס: `Did you invite them…?` העבר כבר מסומן ב-`did`, ולא מסמנים אותו שוב ב-`invited`.',
        },
        {
          has: ['do', 'invited'],
          as: 'form_error',
          err: 'did_v2',
          fb: 'אחרי פועל עזר בא פועל בסיס, והשאלה היא על העבר: `Did you invite them to the meeting?`',
        },
        {
          has: ['did', 'do'],
          as: 'form_error',
          err: 'double_aux',
          fb: 'בשאלה יש פועל עזר אחד בלבד — כאן `did`: `Did you invite them to the meeting?`',
        },
      ],
      end: '?',
    },
    {
      id: 'S07-02',
      v: 1,
      skill: 'S07',
      unit: 'S07',
      sub: 'wh_question',
      type: 'correct',
      role: 'practice',
      stage: 1,
      ctx: 'work.email',
      fam: 'S07.why-write-department',
      goal: 'לשאול למה עמיתה כתבה לכל המחלקה',
      instr: CORRECT_INSTR,
      sitHe: 'רונית שלחה מייל לכל המחלקה, אף שהוא היה מיועד רק למנהל. אתה שואל עמית למה היא עשתה את זה.',
      scaffold: ['Why', 'did', 'subject', 'V (base)'],
      hint: 'בדוק את הפועל שבא אחרי `did`.',
      explain: 'העבר כבר מסומן ב-`did`, ולכן הפועל חוזר לצורת הבסיס: `Why did she write to the whole department?`',
      deep: '`wrote` הוא העבר של `write`. בשאלה עם `did` העבר מסומן פעם אחת — ב-`did` — ואם מסמנים אותו גם בפועל, זו שגיאה: `did … wrote`. כך בכל פועל: `did … go`, `did … say`, `did … send`.',
      source: [
        { id: 's1', t: 'why' },
        { id: 's2', t: 'did' },
        { id: 's3', t: 'she' },
        {
          id: 's4',
          t: 'wrote',
          why: 'אחרי `did` בא פועל בסיס: `did she write`. העבר כבר מסומן ב-`did`.',
          err: 'did_v2',
        },
        { id: 's5', t: 'to the whole department' },
      ],
      tokens: [
        { id: 't1', t: 'write' },
        {
          id: 't2',
          t: 'writes',
          why: 'אחרי `did` בא פועל בסיס, בלי s ובלי סיומת עבר: `did she write`.',
          err: 'did_v_s',
        },
      ],
      accept: [{ a: 'Why did she write to the whole department', o: 'correct_target' }],
      wrong: [
        {
          a: 'Why did she wrote to the whole department',
          as: 'form_error',
          err: 'did_v2',
          fb: 'אחרי `did` בא פועל בסיס: `Why did she write to the whole department?` העבר כבר מסומן ב-`did`, ולכן לא מסמנים אותו שוב ב-`wrote`.',
        },
      ],
      rules: [
        {
          has: ['did', 'wrote'],
          as: 'form_error',
          err: 'did_v2',
          fb: 'אחרי `did` בא פועל בסיס: `did she write`. העבר כבר מסומן ב-`did`.',
        },
        {
          has: ['did', 'writes'],
          as: 'form_error',
          err: 'did_v_s',
          fb: 'אחרי `did` בא פועל בסיס, בלי s: `did she write`.',
        },
        {
          lacks: ['did'],
          as: 'form_error',
          err: 'missing_do',
          fb: 'בשאלה ישירה עם פועל רגיל צריך פועל עזר לפני הנושא — כאן `did` — ואחריו פועל בסיס: `Why did she write…?`',
        },
      ],
      end: '?',
    },
    {
      id: 'S07-03',
      v: 1,
      skill: 'S07',
      unit: 'S07',
      sub: 'question_does',
      type: 'assemble',
      role: 'practice',
      stage: 1,
      ctx: 'work.job',
      fam: 'S07.manager-speak-hebrew',
      goal: 'לשאול אם המנהל החדש מדבר עברית',
      instr: 'בנה את השאלה באנגלית. לא חייבים להשתמש בכל המילים.',
      promptHe: 'המנהל החדש מדבר עברית?',
      sitHe: 'מנהל חדש מגיע מחו"ל לעבוד איתכם. אתה רוצה לדעת אם הוא מדבר עברית.',
      target: 'שאלה עם `does`',
      scaffold: ['Does', 'subject', 'V (base)'],
      hint: 'עם נושא בגוף שלישי יחיד השאלה נפתחת ב-`does`. מה קורה אז ל-s של הפועל?',
      explain: 'ה-s של גוף שלישי עוברת ל-`does`, והפועל נשאר בצורת הבסיס: `Does the new manager speak Hebrew?`',
      deep: 'במשפט רגיל ה-s על הפועל: `He speaks Hebrew`. בשאלה ובשלילה היא עוברת לפועל העזר: `Does he speak…?`, `He doesn\'t speak…`. ה-s מופיעה פעם אחת בלבד.',
      tokens: [
        { id: 't1', t: 'does' },
        { id: 't2', t: 'the new manager' },
        { id: 't3', t: 'speak' },
        { id: 't4', t: 'Hebrew' },
        {
          id: 't5',
          t: 'speaks',
          why: '`speaks` (עם s) בא רק במשפט רגיל: `He speaks Hebrew`. בשאלה ה-s עוברת ל-`does`, והפועל חוזר לבסיס: `Does … speak…?`',
          err: 'does_v_s',
        },
        {
          id: 't6',
          t: 'do',
          why: 'עם נושא בגוף שלישי יחיד (`he`, `the new manager`) משתמשים ב-`does`, לא ב-`do`.',
          err: 'do_does_agreement',
        },
      ],
      accept: [{ a: 'Does the new manager speak Hebrew', o: 'correct_target' }],
      wrong: [
        {
          a: 'The new manager speaks Hebrew',
          as: 'target_not_used',
          err: 'declarative_question',
          fb: 'בדיבור אפשר לשאול גם בטון בלבד, בעיקר כדי לוודא משהו שכבר שמעת. כאן התבקשה שאלה רגילה עם `does`: `Does the new manager speak Hebrew?`',
        },
      ],
      rules: [
        {
          has: ['does', 'speaks'],
          as: 'form_error',
          err: 'does_v_s',
          fb: 'ה-s כבר נמצאת ב-`does`, ולכן אחריו בא פועל בסיס: `Does the new manager speak Hebrew?`',
        },
      ],
      end: '?',
    },
    {
      id: 'S07-04',
      v: 1,
      skill: 'S07',
      unit: 'S07',
      sub: 'negative_does',
      type: 'assemble',
      role: 'practice',
      stage: 2,
      ctx: 'work.software',
      fam: 'S07.doesnt-need-program',
      goal: 'להסביר שמאיה לא צריכה את התוכנה',
      instr: 'קרא את הסיטואציה ובנה משפט אחד באנגלית.',
      sitEn:
        "A technician wants to install a design program on Maya's computer. Maya never works with graphics. What do you tell the technician about Maya and the program?",
      trHe: 'טכנאי רוצה להתקין תוכנת עיצוב במחשב של מאיה. מאיה אף פעם לא עובדת עם גרפיקה. מה אתה אומר לטכנאי על מאיה ועל התוכנה?',
      hint: 'עובדה כללית בהווה, בשלילה, עם `she`.',
      explain: 'שלילה בהווה עם `she`: `doesn\'t` + פועל בסיס — `She doesn\'t need this program`.',
      deep: '`doesn\'t` = `does not`. ה-s של `she needs` עוברת ל-`doesn\'t`, ולכן `need` בא בלי s. עם `I / you / we / they` אומרים `don\'t need`.',
      tokens: [
        { id: 't1', t: 'she' },
        { id: 't2', t: "doesn't" },
        { id: 't3', t: 'need' },
        { id: 't4', t: 'this program' },
        {
          id: 't5',
          t: 'needs',
          why: '`needs` (עם s) בא רק במשפט חיובי. בשלילה ה-s עוברת ל-`doesn\'t`, והפועל חוזר לבסיס: `She doesn\'t need…`',
          err: 'does_v_s',
        },
        {
          id: 't6',
          t: "don't",
          why: 'עם `she` השלילה היא `doesn\'t`. (`she don\'t` נשמע בדיבור בחלק מהניבים, אבל אינו תקני.)',
          err: 'do_does_agreement',
        },
        {
          id: 't7',
          t: 'not',
          why: '`not` לבד לא יוצר שלילה עם פועל רגיל. צריך פועל עזר: `She doesn\'t need…`',
          err: 'not_without_do',
        },
      ],
      accept: [{ a: "She doesn't need this program", o: 'correct_target' }],
      wrong: [
        {
          a: 'She needs this program',
          as: 'meaning_mismatch',
          err: 'affirmative_for_negative',
          fb: 'המשפט תקין, אבל הוא אומר שהיא כן צריכה את התוכנה. כאן: `She doesn\'t need this program`.',
        },
      ],
      rules: [
        {
          has: ['she need'],
          lacks: ["doesn't"],
          as: 'form_error',
          err: 'missing_do',
          fb: 'חסרה השלילה: `She doesn\'t need this program`. (במשפט חיובי עם `she` היה בא `needs`.)',
        },
      ],
      end: '.',
    },
    {
      id: 'S07-05',
      v: 1,
      skill: 'S07',
      unit: 'S07',
      sub: 'negative_did',
      type: 'correct',
      role: 'practice',
      stage: 2,
      ctx: 'work.municipality',
      fam: 'S07.didnt-know-parking-rules',
      goal: 'להסביר שלא ידעתם על הכללים החדשים',
      instr: CORRECT_INSTR,
      sitHe: 'בעירייה עודכנו לפני חודש הכללים לחניית עובדים, אבל אף אחד לא הודיע לכם. אתה מסביר את זה לאחראי על החניון.',
      hint: 'בדוק את הפועל שבא אחרי `didn\'t`.',
      explain: 'העבר מסומן ב-`didn\'t`, ולכן הפועל חוזר לצורת הבסיס: `We didn\'t know about the new parking rules`.',
      deep: 'השגיאה `didn\'t knew` נפוצה מאוד: המשפט בעבר, ולכן יש נטייה לסמן את העבר גם בפועל. באנגלית העבר מסומן רק פעם אחת — ב-`didn\'t`. כך גם `didn\'t go`, `didn\'t see`, `didn\'t send`.',
      source: [
        { id: 's1', t: 'we' },
        { id: 's2', t: "didn't" },
        {
          id: 's3',
          t: 'knew',
          why: 'אחרי `didn\'t` בא פועל בסיס: `didn\'t know`. העבר כבר מסומן ב-`didn\'t`.',
          err: 'did_v2',
        },
        { id: 's4', t: 'about the new parking rules' },
      ],
      tokens: [
        { id: 't1', t: 'know' },
        {
          id: 't2',
          t: 'known',
          why: '`known` היא צורת V3 (כמו ב-`have known`). אחרי `didn\'t` בא פועל בסיס: `didn\'t know`.',
          err: 'did_v3',
        },
      ],
      accept: [{ a: "We didn't know about the new parking rules", o: 'correct_target' }],
      wrong: [
        {
          a: "We didn't knew about the new parking rules",
          as: 'form_error',
          err: 'did_v2',
          fb: 'אחרי `didn\'t` בא פועל בסיס: `We didn\'t know about the new parking rules`. העבר כבר מסומן ב-`didn\'t`, ולכן לא מסמנים אותו שוב ב-`knew`.',
        },
        {
          a: 'We knew about the new parking rules',
          as: 'meaning_mismatch',
          err: 'affirmative_for_negative',
          fb: 'המשפט תקין, אבל הוא אומר שכן ידעתם. בשלילה: `We didn\'t know about the new parking rules`.',
        },
        {
          a: 'We know about the new parking rules',
          as: 'meaning_mismatch',
          err: 'affirmative_for_negative',
          fb: 'המשפט תקין, אבל הוא אומר שאתם יודעים (עכשיו). כאן מסבירים שלא ידעתם: `We didn\'t know about the new parking rules`.',
        },
      ],
      rules: [
        {
          has: ["didn't knew"],
          as: 'form_error',
          err: 'did_v2',
          fb: 'אחרי `didn\'t` בא פועל בסיס: `didn\'t know`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S07-06',
      v: 1,
      skill: 'S07',
      unit: 'S07',
      sub: 'wh_question',
      type: 'correct',
      role: 'practice',
      stage: 2,
      ctx: 'work.project',
      fam: 'S07.say-new-budget',
      goal: 'לשאול מה המנהל אמר על התקציב',
      instr: CORRECT_INSTR,
      sitHe: 'לא היית בישיבת הפרויקט אתמול. המנהל דיבר שם על התקציב החדש, ואתה שואל עמית מה הוא אמר.',
      hint: 'בדוק את שני החלקים: פועל העזר, והצורה של הפועל שאחריו.',
      explain: 'המשפט תקין: `did` נושא את העבר, ו-`say` בא בצורת הבסיס. `What did he said?` היה שגוי.',
      deep: 'בעברית "מה הוא אמר?" — הפועל בעבר. באנגלית העבר עובר ל-`did`, ולכן `say` נשאר בבסיס. משפט כזה "נשמע" לפעמים לא נכון דווקא כשהוא תקין, כי האוזן מחפשת עבר בפועל.',
      source: [
        { id: 's1', t: 'what' },
        { id: 's2', t: 'did' },
        { id: 's3', t: 'he' },
        { id: 's4', t: 'say' },
        { id: 's5', t: 'about the new budget' },
      ],
      tokens: [
        {
          id: 't1',
          t: 'said',
          why: 'אחרי `did` בא פועל בסיס: `did he say`. `said` בא רק בלי `did`, למשל בתשובה: `He said…`',
          err: 'did_v2',
        },
        {
          id: 't2',
          t: 'says',
          why: 'אחרי `did` בא פועל בסיס, בלי s: `did he say`.',
          err: 'did_v_s',
        },
      ],
      accept: [{ a: 'What did he say about the new budget', o: 'correct_target' }],
      rules: [
        {
          has: ['did', 'said'],
          as: 'form_error',
          err: 'did_v2',
          fb: 'אחרי `did` בא פועל בסיס: `What did he say…?` העבר כבר מסומן ב-`did`.',
        },
        {
          has: ['did', 'says'],
          as: 'form_error',
          err: 'did_v_s',
          fb: 'אחרי `did` בא פועל בסיס, בלי s: `did he say`.',
        },
        {
          lacks: ['did'],
          as: 'form_error',
          err: 'missing_do',
          fb: 'בשאלה ישירה עם פועל רגיל צריך `did` לפני הנושא, ואחריו פועל בסיס: `What did he say…?`',
        },
      ],
      end: '?',
    },
    {
      id: 'S07-07',
      v: 1,
      skill: 'S07',
      unit: 'S07',
      sub: 'wh_question_does',
      type: 'assemble',
      role: 'practice',
      stage: 2,
      ctx: 'work.clinic',
      fam: 'S07.clinic-open-sundays',
      goal: 'לשאול באיזו שעה המרפאה נפתחת בימי ראשון',
      instr: 'קרא את הסיטואציה ובנה את השאלה באנגלית. לא חייבים להשתמש בכל המילים.',
      sitEn:
        "You need to drop off some forms at the clinic on Sunday morning, but you don't know its opening hours. Ask the receptionist.",
      trHe: 'אתה צריך למסור טפסים במרפאה ביום ראשון בבוקר, אבל אתה לא יודע מה שעות הפתיחה. שאל את פקידת הקבלה.',
      hint: 'מילת שאלה ← `does` ← הנושא ← פועל בסיס.',
      explain: 'לוח זמנים קבוע, נושא בגוף שלישי יחיד: `What time does the clinic open on Sundays?` — ה-s עוברת ל-`does`.',
      deep: 'במשפט רגיל: `The clinic opens at eight`. בשאלה ה-s עוברת ל-`does`, והפועל חוזר לבסיס: `does the clinic open`. בתוך שאלה עקיפה הסדר חוזר להיות רגיל — `Do you know what time the clinic opens?` — אבל זה נושא נפרד.',
      tokens: [
        { id: 't1', t: 'what time' },
        { id: 't2', t: 'when' },
        { id: 't3', t: 'does' },
        { id: 't4', t: 'the clinic' },
        { id: 't5', t: 'open' },
        { id: 't6', t: 'on Sundays' },
        {
          id: 't7',
          t: 'opens',
          why: '`opens` (עם s) בא רק במשפט רגיל: `The clinic opens at eight`. בשאלה ה-s עוברת ל-`does`: `does the clinic open`.',
          err: 'does_v_s',
        },
        {
          id: 't8',
          t: 'do',
          why: 'עם `the clinic` (גוף שלישי יחיד) משתמשים ב-`does`, לא ב-`do`.',
          err: 'do_does_agreement',
        },
      ],
      accept: [
        { a: 'What time does the clinic open on Sundays', o: 'correct_target' },
        {
          a: 'When does the clinic open on Sundays',
          o: 'valid_alternative',
          note: 'גם נכון: `when` שואל "מתי", ו-`what time` — על השעה המדויקת.',
        },
        {
          a: 'On Sundays, what time does the clinic open',
          o: 'valid_alternative',
          note: 'גם נכון: `on Sundays` בתחילת השאלה.',
        },
        {
          a: 'On Sundays, when does the clinic open',
          o: 'valid_alternative',
          note: 'גם נכון: `on Sundays` בתחילת השאלה.',
        },
      ],
      rules: [
        {
          has: ['does', 'opens'],
          as: 'form_error',
          err: 'does_v_s',
          fb: 'ה-s כבר נמצאת ב-`does`, ולכן אחריו בא פועל בסיס: `does the clinic open`.',
        },
        {
          has: ['opens'],
          lacks: ['does', 'do'],
          as: 'form_error',
          err: 'missing_do',
          fb: 'בשאלה ישירה עם פועל רגיל צריך `does` לפני הנושא, והפועל חוזר לבסיס: `What time does the clinic open…?` (בלי `does` — רק בתוך שאלה עקיפה: `Do you know what time the clinic opens?`)',
        },
        {
          has: ['the clinic open'],
          lacks: ['does', 'do'],
          as: 'form_error',
          err: 'missing_do',
          fb: 'בשאלה ישירה עם פועל רגיל צריך `does` לפני הנושא: `What time does the clinic open on Sundays?`',
        },
      ],
      end: '?',
    },
    {
      id: 'S07-08',
      v: 1,
      skill: 'S07',
      unit: 'S07',
      sub: 'question',
      type: 'transform',
      role: 'practice',
      stage: 2,
      ctx: 'work.schedule',
      fam: 'S07.moved-meeting-thursday',
      goal: 'לוודא שהפגישה הועברה ליום חמישי',
      instr: 'הפוך את המשפט לשאלת כן/לא.',
      sitHe: 'שמעת במסדרון שהפגישה הדו-שבועית הועברה ליום חמישי. אתה רוצה לוודא את זה עם המזכירה.',
      target: 'שאלת כן/לא עם `did`',
      fromLabel: 'משפט חיובי',
      toLabel: 'שאלת כן/לא',
      hint: 'בשאלה על העבר `did` בא בהתחלה, ואחריו הנושא ופועל בסיס.',
      explain: '`did` עובר לתחילת השאלה ולוקח את העבר, ולכן `moved` חוזר ל-`move`: `Did they move the meeting to Thursday?`',
      deep: 'במשפט `They moved…` העבר מסומן ב-`moved`. בשאלה העבר עובר ל-`did`, והפועל חוזר לבסיס. כך בכל פועל: `She called` ← `Did she call?`; `He went` ← `Did he go?`.',
      source: [
        { id: 's1', t: 'they' },
        {
          id: 's2',
          t: 'moved',
          why: 'אחרי `did` בא פועל בסיס: `did they move`. העבר כבר מסומן ב-`did`.',
          err: 'did_v2',
        },
        { id: 's3', t: 'the meeting' },
        { id: 's4', t: 'to Thursday' },
      ],
      sourceEnd: '.',
      tokens: [
        { id: 't1', t: 'did' },
        { id: 't2', t: 'move' },
        {
          id: 't3',
          t: 'does',
          why: '`does` הוא הווה, והוא בא עם `he / she / it`. ההעברה כבר קרתה, והנושא הוא `they`: `Did they move…?`',
          err: 'does_for_past',
        },
      ],
      accept: [{ a: 'Did they move the meeting to Thursday', o: 'correct_target' }],
      wrong: [
        {
          a: 'They moved the meeting to Thursday',
          as: 'target_not_used',
          err: 'not_transformed',
          fb: 'זה המשפט המקורי. בדיבור אפשר להפוך אותו לשאלה בטון בלבד, אבל התבקשת לבנות שאלה עם `did`: `Did they move the meeting to Thursday?`',
        },
      ],
      rules: [
        {
          has: ['did', 'moved'],
          as: 'form_error',
          err: 'did_v2',
          fb: 'אחרי `did` בא פועל בסיס: `Did they move…?` העבר כבר מסומן ב-`did`.',
        },
        {
          lacks: ['did'],
          as: 'form_error',
          err: 'missing_do',
          fb: 'בשאלת כן/לא על העבר צריך `did` בתחילת השאלה, ואחריו פועל בסיס: `Did they move the meeting to Thursday?`',
        },
      ],
      end: '?',
    },
    {
      id: 'S07-D1',
      v: 1,
      skill: 'S07',
      unit: 'S07',
      sub: 'dialogue',
      type: 'dialogue',
      role: 'practice',
      stage: 2,
      ctx: 'work.software',
      fam: 'S07.dialogue-logged-out',
      goal: 'לענות לעמיתה על תקלה ולשאול מתי היא התחילה',
      instr: 'ענה לנועה בכל תור.',
      partnerName: 'Noa',
      setupHe: 'נועה, עמיתה לעבודה, לא מצליחה לעבוד במערכת — היא מתנתקת כל כמה דקות. היא חושבת שאולי שינית משהו בהגדרות.',
      hint: 'בתור הראשון — שלילה בעבר. בתור השני — שאלה על העבר עם מילת שאלה.',
      explain: 'שלילה בעבר: `didn\'t` + פועל בסיס. שאלה על העבר: `When did it stop working?` — גם כאן פועל בסיס אחרי `did`.',
      turns: [
        {
          partner: {
            en: 'The system keeps logging me out. Did you change the settings yesterday?',
            he: 'המערכת מנתקת אותי כל הזמן. שינית אתמול את ההגדרות?',
          },
          sub: 'negative_did',
          instr: 'ענה שלא — לא שינית שום דבר.',
          target: 'משפט מלא עם `didn\'t` ופועל',
          hint: 'שלילה בעבר: `didn\'t` ואחריו פועל בסיס.',
          explain: 'בעבר, בשלילה: `I didn\'t change anything` — `change` בצורת הבסיס.',
          build: {
            tokens: [
              { id: 't1', t: 'no' },
              { id: 't2', t: 'I' },
              { id: 't3', t: "didn't" },
              { id: 't4', t: 'change' },
              { id: 't5', t: 'anything' },
              {
                id: 't6',
                t: 'changed',
                why: '`changed` בא רק במשפט חיובי בלי פועל עזר. בשלילה בעבר: `didn\'t` + פועל בסיס — `I didn\'t change anything`.',
                err: 'did_v2',
              },
              {
                id: 't7',
                t: "don't",
                why: '`don\'t` מדבר על ההווה או על הרגל. השאלה היא על אתמול: `I didn\'t change anything`.',
                err: 'present_for_past',
                as: 'meaning_mismatch',
              },
            ],
            accept: [
              { a: "No, I didn't change anything", o: 'correct_target' },
              { a: "I didn't change anything", o: 'correct_target' },
              {
                a: "No, I didn't",
                o: 'target_not_used',
                note: 'תשובה קצרה תקינה וטבעית. כאן התבקש משפט מלא עם הפועל: `No, I didn\'t change anything`.',
              },
              {
                a: "I didn't",
                o: 'target_not_used',
                note: 'תשובה קצרה תקינה. כאן התבקש משפט מלא עם הפועל: `I didn\'t change anything`.',
              },
            ],
            rules: [
              {
                has: ["didn't changed"],
                as: 'form_error',
                err: 'did_v2',
                fb: 'אחרי `didn\'t` בא פועל בסיס: `I didn\'t change anything`.',
              },
              {
                has: ["don't", 'changed'],
                as: 'form_error',
                err: 'present_for_past',
                fb: 'אחרי פועל עזר בא פועל בסיס, והשאלה היא על אתמול: `I didn\'t change anything`.',
              },
              {
                has: ["didn't", "don't"],
                as: 'form_error',
                err: 'double_aux',
                fb: 'בשלילה יש פועל עזר אחד בלבד — כאן `didn\'t`: `I didn\'t change anything`.',
              },
            ],
            end: '.',
          },
        },
        {
          partner: { en: 'Strange. It worked fine last week.', he: 'מוזר. בשבוע שעבר זה עבד בסדר.' },
          sub: 'wh_question',
          instr: 'שאל אותה מתי זה הפסיק לעבוד.',
          hint: 'מילת שאלה ← `did` ← הנושא ← פועל בסיס.',
          explain: '`did` נושא את העבר, ולכן `stop` בא בצורת הבסיס: `When did it stop working?`',
          build: {
            tokens: [
              { id: 't1', t: 'when' },
              { id: 't2', t: 'did' },
              { id: 't3', t: 'it' },
              { id: 't4', t: 'stop' },
              { id: 't5', t: 'working' },
              {
                id: 't6',
                t: 'stopped',
                why: '`stopped` בא רק במשפט רגיל בלי פועל עזר (`It stopped working`). אחרי `did` בא פועל בסיס: `did it stop`.',
                err: 'did_v2',
              },
              {
                id: 't7',
                t: 'does',
                why: '`does` שואל על ההווה או על מה שקורה בדרך כלל — למשל באיזה שלב זה מתנתק בכל פעם. כאן שואלים מתי התקלה התחילה, בעבר: `When did it stop working?`',
                err: 'present_for_past',
                as: 'meaning_mismatch',
              },
              {
                id: 't8',
                t: 'to work',
                why: '`stop to work` פירושו "עצר כדי לעבוד". "הפסיק לעבוד" = `stop working`.',
                err: 'stop_to_inf',
              },
            ],
            accept: [{ a: 'When did it stop working', o: 'correct_target' }],
            rules: [
              {
                has: ['did', 'stopped'],
                as: 'form_error',
                err: 'did_v2',
                fb: 'אחרי `did` בא פועל בסיס: `When did it stop working?` העבר כבר מסומן ב-`did`.',
              },
              {
                has: ['does', 'stopped'],
                as: 'form_error',
                err: 'does_v2',
                fb: 'אחרי פועל עזר בא פועל בסיס, והתקלה התחילה בעבר: `When did it stop working?`',
              },
              {
                has: ['stopped'],
                lacks: ['did', 'does'],
                as: 'form_error',
                err: 'missing_do',
                fb: 'בשאלה ישירה עם פועל רגיל צריך `did` לפני הנושא, ואחריו פועל בסיס: `When did it stop working?`',
              },
              {
                starts: 'when it',
                lacks: ['did', 'does'],
                as: 'form_error',
                err: 'missing_do',
                fb: 'בשאלה ישירה עם פועל רגיל צריך `did` לפני הנושא: `When did it stop working?`',
              },
              {
                has: ['did', 'does'],
                as: 'form_error',
                err: 'double_aux',
                fb: 'בשאלה יש פועל עזר אחד בלבד — כאן `did`, כי התקלה התחילה בעבר: `When did it stop working?`',
              },
            ],
            end: '?',
          },
        },
      ],
      closing: { en: "I think it was Monday, after the update. I'll call IT.", he: 'נדמה לי שביום שני, אחרי העדכון. אני אתקשר למחשוב.' },
    },
    {
      id: 'S07-09',
      v: 1,
      skill: 'S07',
      unit: 'S07',
      sub: 'contrast',
      type: 'discriminate',
      role: 'practice',
      stage: 3,
      ctx: 'daily.shopping',
      fam: 'S07.sofa-delivery-choice',
      goal: 'לשאול את השכן אם החנות הביאה את הספה אתמול',
      instr: 'בחר את השאלה שמתאימה למצב.',
      sitHe: 'קנית ספה חדשה, והחנות הייתה אמורה להביא אותה אתמול, כשלא היית בבית. השכן הבטיח לפתוח לשליחים. אתה שואל אותו אם זה קרה.',
      hint: 'אירוע אחד, אתמול — איזה פועל עזר, ואיזו צורה של הפועל אחריו?',
      explain: 'על אירוע אחד בעבר שואלים עם `did` + פועל בסיס: `Did the store deliver the sofa yesterday?`',
      deep: '`Does the store deliver sofas?` שואל אם החנות עושה משלוחים בכלל — שאלה אחרת. `yesterday` הוא זמן שהסתיים, ולכן גם לא `has delivered`.',
      multi: false,
      options: [
        {
          id: 'a',
          en: 'Did the store deliver the sofa yesterday?',
          v: 'fits',
          why: 'שאלה על אירוע אחד בעבר: `did` + פועל בסיס.',
        },
        {
          id: 'b',
          en: 'Did the store delivered the sofa yesterday?',
          v: 'ungrammatical',
          why: 'אחרי `did` בא פועל בסיס: `deliver`, לא `delivered`.',
          err: 'did_v2',
        },
        {
          id: 'c',
          en: 'Does the store deliver sofas?',
          v: 'other_meaning',
          why: 'תקין, אבל שואל אם החנות עושה משלוחים של ספות באופן כללי — לא אם הספה שלך הגיעה אתמול.',
          err: 'present_for_past',
        },
        {
          id: 'd',
          en: 'Has the store delivered the sofa yesterday?',
          v: 'ungrammatical',
          why: '`yesterday` הוא זמן שהסתיים, ולכן לא `has delivered`. על אתמול: `Did the store deliver…?`',
          err: 'perfect_with_finished_time',
        },
      ],
    },
    {
      id: 'S07-10',
      v: 1,
      skill: 'S07',
      unit: 'S07',
      sub: 'contrast',
      type: 'assemble',
      role: 'practice',
      stage: 3,
      ctx: 'daily.home',
      fam: 'S07.washing-machine-now',
      goal: 'לשאול אם מכונת הכביסה עובדת עכשיו, אחרי התיקון',
      instr: 'בנה את השאלה באנגלית. לא חייבים להשתמש בכל המילים.',
      sitHe: 'מכונת הכביסה המשותפת בבניין התקלקלה בשבוע שעבר, ואתמול בא טכנאי. אתה פוגש שכנה ורוצה לדעת אם המכונה עובדת עכשיו.',
      hint: 'עכשיו או בעבר? זה קובע את פועל העזר.',
      explain: 'שואלים על המצב עכשיו, אחרי התיקון: `Does the washing machine work now?` — או `Is it working now?`. `did` היה שואל על העבר.',
      deep: '`did` ו-`does` נבחרים לפי הזמן: `Did it work yesterday?` שואל על העבר, `Does it work now?` — על ההווה. בשני המקרים הפועל שאחריהם בבסיס. למצב זמני ברגע זה מתאים גם הווה מתמשך: `Is it working now?`',
      tokens: [
        { id: 't1', t: 'does' },
        {
          id: 't2',
          t: 'did',
          why: '`did` שואל על העבר — למשל אם המכונה עבדה אתמול. כאן שואלים על עכשיו, אחרי התיקון: `Does … work now?`',
          err: 'past_for_present',
          as: 'meaning_mismatch',
        },
        { id: 't3', t: 'is' },
        { id: 't4', t: 'the washing machine' },
        { id: 't5', t: 'work' },
        { id: 't6', t: 'working' },
        { id: 't7', t: 'now' },
      ],
      accept: [
        { a: 'Does the washing machine work now', o: 'correct_target' },
        {
          a: 'Does the washing machine work',
          o: 'valid_alternative',
          note: 'גם נכון. `now` רק מדגיש "אחרי התיקון".',
        },
        {
          a: 'Is the washing machine working now',
          o: 'valid_alternative',
          note: 'גם נכון וטבעי מאוד: הווה מתמשך שואל על המצב ברגע זה.',
        },
        {
          a: 'Is the washing machine working',
          o: 'valid_alternative',
          note: 'גם נכון: הווה מתמשך שואל על המצב ברגע זה.',
        },
      ],
      rules: [
        {
          has: ['does', 'working'],
          as: 'form_error',
          err: 'does_ing',
          fb: 'אחרי `does` בא פועל בסיס: `Does the washing machine work now?` (או בלי `does`: `Is the washing machine working now?`)',
        },
        {
          has: ['is', 'work'],
          as: 'form_error',
          err: 'be_base',
          fb: 'אחרי `is` בא פועל עם ing: `Is the washing machine working now?` — או עם `does`: `Does the washing machine work now?`',
        },
        {
          has: ['did', 'working'],
          as: 'form_error',
          err: 'did_ing',
          fb: 'אחרי `did` בא פועל בסיס — ובכל מקרה, כאן שואלים על עכשיו: `Does the washing machine work now?`',
        },
        {
          has: ['did', 'does'],
          as: 'form_error',
          err: 'double_aux',
          fb: 'בשאלה יש פועל עזר אחד בלבד: `Does the washing machine work now?` או `Is the washing machine working now?`',
        },
        {
          has: ['did', 'is'],
          as: 'form_error',
          err: 'double_aux',
          fb: 'בשאלה יש פועל עזר אחד בלבד: `Does the washing machine work now?` או `Is the washing machine working now?`',
        },
        {
          has: ['does', 'is'],
          as: 'form_error',
          err: 'double_aux',
          fb: 'בשאלה יש פועל עזר אחד בלבד: `Does the washing machine work now?` או `Is the washing machine working now?`',
        },
      ],
      end: '?',
    },
    {
      id: 'S07-11',
      v: 2,
      skill: 'S07',
      unit: 'S07',
      sub: 'negative_does',
      type: 'assemble',
      role: 'practice',
      stage: 1,
      ctx: 'work.meeting',
      fam: 'S07.room-no-projector',
      goal: 'לומר שבחדר הישיבות אין מקרן',
      instr: 'בנה את המשפט באנגלית. לא חייבים להשתמש בכל המילים.',
      promptHe: 'לחדר הישיבות אין מקרן.',
      sitHe: 'מרצה אורח שואל אם יוכל להקרין מצגת בחדר הישיבות.',
      scaffold: ['subject', "don't / doesn't", 'V (base)'],
      hint: '"יש ל…" באנגלית זה `have`. בשלילה עם גוף שלישי יחיד: `doesn\'t` + פועל בסיס.',
      explain: '`have` כפועל ראשי מתנהג כמו כל פועל רגיל: בשלילה `doesn\'t have`, בלי s — `The meeting room doesn\'t have a projector`.',
      deep: 'במשפט חיובי: `The meeting room has a projector`. בשלילה ה-s עוברת ל-`doesn\'t`, ולכן `has` חוזר ל-`have`. אפשר גם `There isn\'t a projector in the meeting room` — מבנה אחר, אותה משמעות.',
      tokens: [
        { id: 't1', t: 'the meeting room' },
        { id: 't2', t: "doesn't" },
        { id: 't3', t: 'have' },
        { id: 't4', t: 'a projector' },
        {
          id: 't5',
          t: 'has',
          why: '`has` בא רק במשפט חיובי: `The room has a projector`. בשלילה ה-s עוברת ל-`doesn\'t`: `doesn\'t have`.',
          err: 'does_v_s',
        },
        {
          id: 't6',
          t: "don't",
          why: 'עם נושא בגוף שלישי יחיד (`the meeting room` = `it`) השלילה היא `doesn\'t`.',
          err: 'do_does_agreement',
        },
      ],
      accept: [{ a: "The meeting room doesn't have a projector", o: 'correct_target' }],
      wrong: [
        {
          a: 'The meeting room has a projector',
          as: 'meaning_mismatch',
          err: 'affirmative_for_negative',
          fb: 'המשפט תקין, אבל הוא אומר שיש מקרן. כאן: `The meeting room doesn\'t have a projector`.',
        },
        {
          a: "Doesn't the meeting room have a projector",
          as: 'meaning_mismatch',
          err: 'question_for_statement',
          fb: 'זו שאלה תקינה — "אין מקרן בחדר הישיבות?" — אבל כאן אתה מוסר למרצה מידע, לא שואל: `The meeting room doesn\'t have a projector`.',
        },
      ],
      rules: [
        {
          has: ["doesn't has"],
          as: 'form_error',
          err: 'does_v_s',
          fb: 'אחרי `doesn\'t` בא פועל בסיס: `doesn\'t have`. ה-s כבר נמצאת ב-`doesn\'t`.',
        },
        {
          has: ['the meeting room have'],
          lacks: ["doesn't"],
          as: 'form_error',
          err: 'missing_do',
          fb: 'חסרה השלילה: `The meeting room doesn\'t have a projector`. (במשפט חיובי עם נושא ביחיד היה בא `has`.)',
        },
        {
          order: ['have', "doesn't"],
          as: 'form_error',
          err: 'word_order',
          fb: '`doesn\'t` בא לפני הפועל: `The meeting room doesn\'t have a projector`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S07-C1',
      v: 1,
      skill: 'S07',
      unit: 'S07',
      sub: 'wh_question',
      type: 'assemble',
      role: 'check',
      stage: 2,
      ctx: 'daily.travel',
      fam: 'S07.flight-take',
      goal: 'לשאול חברה כמה זמן נמשכה הטיסה שלה',
      instr: 'קרא את הסיטואציה ובנה את השאלה באנגלית. לא חייבים להשתמש בכל המילים.',
      sitEn: 'Your friend Dana just got back from a trip to Japan. Ask her about the length of her flight.',
      trHe: 'דנה, חברה שלך, חזרה עכשיו מטיול ביפן. שאל אותה כמה זמן נמשכה הטיסה שלה.',
      hint: 'הטיסה כבר הייתה: `How long` ← פועל העזר של העבר ← הנושא ← פועל בסיס.',
      explain: 'הטיסה כבר הייתה, ולכן `did`, ואחריו פועל בסיס: `How long did the flight take?`',
      deep: '`take` במובן "לקח זמן": `The flight took twelve hours`. בשאלה העבר עובר ל-`did`, ו-`took` חוזר ל-`take`. גם `How long was the flight?` נכון — מבנה אחר, עם `was`.',
      tokens: [
        { id: 't1', t: 'how long' },
        { id: 't2', t: 'did' },
        { id: 't3', t: 'the flight' },
        { id: 't4', t: 'take' },
        {
          id: 't5',
          t: 'took',
          why: '`took` בא רק במשפט רגיל בלי פועל עזר (`The flight took twelve hours`). אחרי `did` בא פועל בסיס: `did the flight take`.',
          err: 'did_v2',
        },
        {
          id: 't6',
          t: 'does',
          why: '`How long does the flight take?` שואל כמה זמן הטיסה הזאת לוקחת בדרך כלל. דנה כבר טסה, ולכן שואלים על העבר: `did`.',
          err: 'present_for_past',
          as: 'meaning_mismatch',
        },
      ],
      accept: [{ a: 'How long did the flight take', o: 'correct_target' }],
      rules: [
        {
          has: ['did', 'took'],
          as: 'form_error',
          err: 'did_v2',
          fb: 'אחרי `did` בא פועל בסיס: `How long did the flight take?` העבר כבר מסומן ב-`did`.',
        },
        {
          has: ['does', 'took'],
          as: 'form_error',
          err: 'does_v2',
          fb: 'אחרי פועל עזר בא פועל בסיס, והטיסה כבר הייתה: `How long did the flight take?`',
        },
        {
          has: ['took'],
          lacks: ['did', 'does'],
          as: 'form_error',
          err: 'missing_do',
          fb: 'בשאלה ישירה עם פועל רגיל צריך `did` לפני הנושא, ואחריו פועל בסיס: `How long did the flight take?`',
        },
        {
          starts: 'how long the flight',
          lacks: ['did', 'does'],
          as: 'form_error',
          err: 'missing_do',
          fb: 'בשאלה ישירה עם פועל רגיל צריך `did` לפני הנושא: `How long did the flight take?`',
        },
        {
          has: ['did', 'does'],
          as: 'form_error',
          err: 'double_aux',
          fb: 'בשאלה יש פועל עזר אחד בלבד — כאן `did`, כי הטיסה כבר הייתה: `How long did the flight take?`',
        },
      ],
      end: '?',
    },
    {
      id: 'S07-C2',
      v: 1,
      skill: 'S07',
      unit: 'S07',
      sub: 'contrast',
      type: 'discriminate',
      role: 'check',
      stage: 3,
      ctx: 'daily.health',
      fam: 'S07.knee-still-hurt',
      goal: 'לשאול חבר אם הברך עדיין כואבת לו',
      instr: 'בחר את כל השאלות שמתאימות למצב.',
      sitHe: 'חבר נפל בשבוע שעבר במשחק כדורגל ונחבל בברך. אתה רוצה לדעת אם הברך עדיין כואבת לו עכשיו.',
      hint: 'עכשיו או בעבר? ומה בא אחרי `does`?',
      explain: 'על עכשיו שואלים `Does your knee still hurt?` או `Is your knee still hurting?`. `Did…` שואל על העבר, ו-`does … hurts` שגוי.',
      multi: true,
      options: [
        {
          id: 'a',
          en: 'Does your knee still hurt?',
          v: 'fits',
          why: 'שאלה על עכשיו, נושא בגוף שלישי יחיד: `does` + פועל בסיס.',
        },
        {
          id: 'b',
          en: 'Is your knee still hurting?',
          v: 'fits',
          why: 'גם נכון: הווה מתמשך מתאים למצב זמני שנמשך עכשיו.',
        },
        {
          id: 'c',
          en: 'Does your knee still hurts?',
          v: 'ungrammatical',
          why: 'אחרי `does` בא פועל בסיס: `hurt`, לא `hurts`.',
          err: 'does_v_s',
        },
        {
          id: 'd',
          en: 'Did your knee still hurt?',
          v: 'other_meaning',
          why: 'תקין, אבל שואל על זמן בעבר (למשל אם כאב לו אתמול), לא על עכשיו.',
          err: 'past_for_present',
        },
      ],
    },
  ],
};
