import type { SkillPack } from '../schema';

/**
 * S08 INDIRECT_ORDER — indirect questions: normal word order, no do / does / did inside.
 * CAL-4 (calibration.ts) already uses `Could you tell me when the new schedule takes effect?`.
 */

const CORRECT_INSTR = 'אם יש טעות — גע במילה או ברווח ובחר תיקון. אם המשפט תקין, בחר "אין צורך בתיקון".';

export const S08: SkillPack = {
  skill: 'S08',
  lessons: [
    {
      unit: 'S08',
      title: 'שאלה עקיפה: הסדר של משפט רגיל',
      short:
        'בתוך שאלה עקיפה הסדר הוא כמו במשפט רגיל — הנושא ואחריו הפועל — ובלי `do / does / did`. `Where is it?` ← `Could you tell me where it is?`',
      chain: ['Could you tell me / Do you know', 'where / what / if', 'subject', 'verb'],
      examples: [
        { en: 'Do you know what time it starts?', he: 'אתה יודע באיזו שעה זה מתחיל?' },
        { en: 'Can you tell me how long it will take?', he: 'אתה יכול להגיד לי כמה זמן זה ייקח?' },
        { en: "I'm not sure whether they received it.", he: 'אני לא בטוח אם הם קיבלו את זה.' },
      ],
      contrast: {
        a: { en: 'Where does he work?', he: 'איפה הוא עובד? (שאלה ישירה)' },
        b: { en: 'Do you know where he works?', he: 'אתה יודע איפה הוא עובד? (שאלה עקיפה)' },
        note: 'בשאלה הישירה `does` בא לפני הנושא ולוקח את ה-s. בשאלה העקיפה אין `does` והסדר רגיל — ולכן ה-s חוזרת לפועל: `he works`.',
      },
      deep:
        '• שאלה עקיפה היא שאלה שעטופה בפתיחה: `Could you tell me…`, `Do you know…`, `I wonder…`, `I\'m not sure…`. החלק הפנימי בנוי כמו משפט רגיל: `where the meeting is`, `what time it starts`, `why he left`.\n' +
        '• עם `be`: הנושא בא לפני `is / are / was` — `Do you know where the station is?`, לא `where is the station`.\n' +
        '• עם פועל רגיל: אין `do / does / did`, והפועל עצמו מקבל את הזמן ואת ה-s: `when it starts`, `why he left`.\n' +
        '• שאלת כן/לא עקיפה נפתחת ב-`if` או ב-`whether`: `Do you know if the office is open?`. בשאלות פשוטות כאלה שתי המילים נכונות; `whether` מעט רשמי יותר.\n' +
        '• בלי `if` המשמעות משתנה: `Do you know that the office is open?` מניח שזו עובדה, ושואל אם הוא יודע אותה.\n' +
        '• סימן הסיום נקבע לפי המשפט כולו: `Could you tell me…?` ו-`Do you know…?` הן שאלות; `I wonder…` ו-`I\'m not sure…` הם משפטי חיווי, ולכן בכתיבה מקפידה מסיימים אותם בנקודה. בכל המקרים הסדר בפנים זהה: הנושא ואחריו הפועל.\n' +
        '• כששואלים על הנושא עצמו הסדר לא משתנה: `Who called?` ← `Do you know who called?`',
      pitfalls: [
        '`Could you tell me when does it start?` — בלי `does`: `when it starts`.',
        '`Do you know where is the station?` — `where the station is`.',
        '`I wonder why did he leave.` — בלי `did`, והפועל בעבר: `why he left`.',
        '`Do you know the store is open?` — כדי לשאול אם הוא פתוח צריך `if`: `Do you know if the store is open?`',
      ],
    },
  ],
  examples: {
    S08: [
      { en: 'Do you know how much the tickets cost?', he: 'אתה יודע כמה עולים הכרטיסים?' },
      {
        en: 'Could you tell me who is in charge of the project?',
        he: 'תוכל להגיד לי מי אחראי על הפרויקט?',
        note: 'כששואלים על הנושא (`who`), הסדר לא משתנה.',
      },
      { en: 'I have no idea where I put my keys.', he: 'אין לי מושג איפה שמתי את המפתחות.' },
      { en: 'Can you tell me why the train is late?', he: 'אתה יכול להגיד לי למה הרכבת מאחרת?' },
    ],
  },
  items: [
    {
      id: 'S08-01',
      v: 1,
      skill: 'S08',
      unit: 'S08',
      sub: 'wh_indirect',
      type: 'transform',
      role: 'practice',
      stage: 1,
      ctx: 'work.meeting',
      fam: 'S08.where-meeting-is',
      goal: 'לשאול בנימוס איפה מתקיימת הפגישה',
      instr: 'הפוך את השאלה הישירה לשאלה עקיפה שמתחילה ב-`Could you tell me`.',
      sitHe: 'הגעת לבניין של חברה אחרת לפגישה, ואתה לא יודע באיזה חדר היא מתקיימת. אתה שואל את פקיד הקבלה.',
      target: 'שאלה עקיפה שמתחילה ב-`Could you tell me`',
      fromLabel: 'שאלה ישירה',
      toLabel: 'שאלה עקיפה',
      scaffold: ['Could you tell me', 'where', 'subject', 'is'],
      hint: 'אחרי `where` הסדר הוא כמו במשפט רגיל: קודם הנושא, ואז `is`.',
      explain: 'בתוך שאלה עקיפה הנושא בא לפני `is`: `Could you tell me where the meeting is?`',
      deep: 'בשאלה ישירה `is` קופץ לפני הנושא: `Where is the meeting?`. אחרי `Could you tell me` זו כבר לא שאלה ישירה אלא חלק ממשפט, ולכן הסדר חוזר להיות רגיל: `the meeting is`. סימן השאלה בסוף שייך ל-`Could you tell me…?`.',
      source: [
        { id: 's1', t: 'where' },
        { id: 's2', t: 'is' },
        { id: 's3', t: 'the meeting' },
      ],
      sourceEnd: '?',
      tokens: [{ id: 't1', t: 'could you tell me' }],
      accept: [{ a: 'Could you tell me where the meeting is', o: 'correct_target' }],
      wrong: [
        {
          a: 'Where is the meeting',
          as: 'target_not_used',
          err: 'not_transformed',
          fb: 'זו שאלה ישירה תקינה, אבל התבקשת להפוך אותה לשאלה עקיפה שמתחילה ב-`Could you tell me`.',
        },
      ],
      rules: [
        {
          order: ['could you tell me', 'is the meeting'],
          as: 'form_error',
          err: 'inversion_in_indirect',
          fb: 'בתוך שאלה עקיפה הנושא בא לפני `is`: `Could you tell me where the meeting is?`',
        },
      ],
      end: '?',
    },
    {
      id: 'S08-02',
      v: 1,
      skill: 'S08',
      unit: 'S08',
      sub: 'wh_indirect',
      type: 'assemble',
      role: 'practice',
      stage: 1,
      ctx: 'work.schedule',
      fam: 'S08.training-starts',
      goal: 'לשאול עמית באיזו שעה מתחילה ההדרכה',
      instr: 'בנה את השאלה באנגלית. לא חייבים להשתמש בכל המילים.',
      promptHe: 'אתה יודע באיזו שעה ההדרכה מתחילה?',
      sitHe: 'מחר יש הדרכה על המערכת החדשה, ואתה לא זוכר מתי היא מתחילה.',
      target: 'שאלה עקיפה שמתחילה ב-`Do you know`',
      scaffold: ['Do you know', 'what time', 'subject', 'verb'],
      hint: 'אחרי `what time` — קודם הנושא, ואז הפועל, בלי `does`.',
      explain: 'בתוך שאלה עקיפה אין `does`, ולכן הפועל מקבל s כמו במשפט רגיל: `Do you know what time the training starts?`',
      deep: 'בשאלה ישירה: `What time does the training start?` — `does` לוקח את ה-s. בשאלה עקיפה `does` נעלם, וה-s חוזרת לפועל: `the training starts`. ה-`do` שבהתחלה (`Do you know`) שייך לשאלה החיצונית, לא לחלק הפנימי.',
      tokens: [
        { id: 't1', t: 'do you know' },
        { id: 't2', t: 'what time' },
        { id: 't3', t: 'the training' },
        { id: 't4', t: 'starts' },
        {
          id: 't5',
          t: 'start',
          why: 'בלי `does` הפועל מקבל s כמו במשפט רגיל: `the training starts`.',
          err: 'agreement_s',
        },
        {
          id: 't6',
          t: 'does',
          why: 'בשאלה העקיפה שהתבקשה אין `does`: `Do you know what time the training starts?`',
          err: 'do_in_indirect',
        },
      ],
      accept: [{ a: 'Do you know what time the training starts', o: 'correct_target' }],
      wrong: [
        {
          a: 'What time does the training start',
          as: 'target_not_used',
          err: 'not_indirect',
          fb: 'זו שאלה ישירה תקינה. כאן התבקשה שאלה עקיפה עם `Do you know`: `Do you know what time the training starts?`',
        },
      ],
      rules: [
        {
          order: ['do you know', 'does'],
          as: 'form_error',
          err: 'do_in_indirect',
          fb: 'בתוך שאלה עקיפה אין `does`, והסדר הוא כמו במשפט רגיל: `what time the training starts`.',
        },
        {
          has: ['does', 'starts'],
          as: 'form_error',
          err: 'does_v_s',
          fb: 'אחרי `does` בא פועל בסיס — ובשאלה העקיפה שהתבקשה אין `does` בכלל: `Do you know what time the training starts?`',
        },
      ],
      end: '?',
    },
    {
      id: 'S08-03',
      v: 1,
      skill: 'S08',
      unit: 'S08',
      sub: 'yesno_indirect',
      type: 'transform',
      role: 'practice',
      stage: 1,
      ctx: 'daily.shopping',
      fam: 'S08.pharmacy-open-saturdays',
      goal: 'לשאול בנימוס אם בית המרקחת פתוח בשבת',
      instr: 'הפוך את השאלה הישירה לשאלה עקיפה שמתחילה ב-`Do you know`.',
      sitHe: 'אתה צריך לקנות משהו בבית המרקחת השכונתי בשבת, ולא בטוח שהוא פתוח. אתה שואל שכן.',
      target: 'שאלה עקיפה שמתחילה ב-`Do you know`',
      fromLabel: 'שאלה ישירה',
      toLabel: 'שאלה עקיפה',
      scaffold: ['Do you know', 'if / whether', 'subject', 'is'],
      hint: 'שאלת כן/לא עקיפה צריכה מילת חיבור: `if` או `whether`. אחריה — הנושא, ואז `is`.',
      explain: 'בשאלת כן/לא עקיפה מוסיפים `if` (או `whether`), והסדר רגיל: `Do you know if the pharmacy is open on Saturdays?`',
      deep: 'בשאלת כן/לא ישירה `is` בא בהתחלה: `Is the pharmacy open…?`. בשאלה עקיפה אין מילת שאלה, ולכן מוסיפים `if` או `whether` — ואחריה הסדר של משפט רגיל. בשאלות פשוטות כאלה שתי המילים נכונות; `whether` מעט רשמי יותר.',
      source: [
        { id: 's1', t: 'is' },
        { id: 's2', t: 'the pharmacy' },
        { id: 's3', t: 'open' },
        { id: 's4', t: 'on Saturdays' },
      ],
      sourceEnd: '?',
      tokens: [
        { id: 't1', t: 'do you know' },
        { id: 't2', t: 'if' },
        { id: 't3', t: 'whether' },
      ],
      accept: [
        { a: 'Do you know if the pharmacy is open on Saturdays', o: 'correct_target' },
        {
          a: 'Do you know whether the pharmacy is open on Saturdays',
          o: 'valid_alternative',
          note: 'גם נכון: בשאלת כן/לא עקיפה פשוטה אפשר `if` או `whether`. `whether` מעט רשמי יותר.',
        },
      ],
      wrong: [
        {
          a: 'Is the pharmacy open on Saturdays',
          as: 'target_not_used',
          err: 'not_transformed',
          fb: 'זו שאלה ישירה תקינה, אבל התבקשת להפוך אותה לשאלה עקיפה שמתחילה ב-`Do you know`.',
        },
        {
          a: 'Do you know the pharmacy is open on Saturdays',
          as: 'meaning_mismatch',
          err: 'missing_if',
          fb: 'בלי `if` המשפט שואל אם הוא יודע שבית המרקחת פתוח — כאילו זו עובדה ידועה. כדי לשאול אם הוא פתוח: `Do you know if the pharmacy is open on Saturdays?`',
        },
      ],
      rules: [
        {
          has: ['if is'],
          as: 'form_error',
          err: 'inversion_in_indirect',
          fb: 'אחרי `if` הסדר רגיל: קודם הנושא, ואז `is` — `if the pharmacy is open`.',
        },
        {
          has: ['whether is'],
          as: 'form_error',
          err: 'inversion_in_indirect',
          fb: 'אחרי `whether` הסדר רגיל: קודם הנושא, ואז `is` — `whether the pharmacy is open`.',
        },
        {
          has: ['the pharmacy open'],
          lacks: ['is'],
          as: 'form_error',
          err: 'missing_be',
          fb: 'חסר `is`: `if the pharmacy is open`. בעברית אין מילה כזאת בהווה, אבל באנגלית היא חובה.',
        },
        {
          has: ['do you know is'],
          as: 'form_error',
          err: 'missing_if',
          fb: 'בדיבור שומעים לפעמים `Do you know, is it open?` — שתי שאלות נפרדות. בשאלה עקיפה אחת מוסיפים `if` או `whether`, והסדר רגיל: `Do you know if the pharmacy is open on Saturdays?`',
        },
      ],
      end: '?',
    },
    {
      id: 'S08-04',
      v: 1,
      skill: 'S08',
      unit: 'S08',
      sub: 'wh_indirect',
      type: 'correct',
      role: 'practice',
      stage: 2,
      ctx: 'work.software',
      fam: 'S08.update-takes',
      goal: 'לשאול את איש המחשוב כמה זמן לוקח העדכון',
      instr: CORRECT_INSTR,
      sitHe: 'איש המחשוב עומד להתקין עדכון במחשב שלך. אתה רוצה לדעת כמה זמן זה לוקח, כדי לתכנן את היום.',
      target: 'שאלה עקיפה שמתחילה ב-`Can you tell me`',
      hint: 'בדוק את הסדר בחלק שאחרי `how long`.',
      explain: 'בתוך שאלה עקיפה אין `does`, והפועל מקבל s: `Can you tell me how long the update takes?`',
      deep: 'השאלה הישירה היא `How long does the update take?`. אחרי `Can you tell me` החלק הפנימי חוזר לסדר של משפט רגיל: `the update takes`. גם `will take` נכון כאן, כי העדכון עוד לא התחיל.',
      source: [
        { id: 's1', t: 'can you tell me' },
        { id: 's2', t: 'how long' },
        {
          id: 's3',
          t: 'does',
          why: 'בשאלה העקיפה אין `does`: `Can you tell me how long the update takes?`',
          err: 'do_in_indirect',
        },
        { id: 's4', t: 'the update' },
        { id: 's5', t: 'take' },
      ],
      tokens: [
        { id: 't1', t: 'takes' },
        { id: 't2', t: 'will' },
      ],
      accept: [
        { a: 'Can you tell me how long the update takes', o: 'correct_target' },
        {
          a: 'Can you tell me how long the update will take',
          o: 'valid_alternative',
          note: 'גם נכון: `will take` מתאים כשהעדכון עוד לא התחיל.',
        },
      ],
      wrong: [
        {
          a: 'Can you tell me how long does the update take',
          as: 'form_error',
          err: 'do_in_indirect',
          fb: 'בתוך שאלה עקיפה אין `does`, והסדר הוא כמו במשפט רגיל: `Can you tell me how long the update takes?`',
        },
        {
          a: 'How long does the update take',
          as: 'target_not_used',
          err: 'not_indirect',
          fb: 'זו שאלה ישירה תקינה, אבל כאן מתקנים את השאלה העקיפה שמתחילה ב-`Can you tell me`: `Can you tell me how long the update takes?`',
        },
        {
          a: 'How long will the update take',
          as: 'target_not_used',
          err: 'not_indirect',
          fb: 'זו שאלה ישירה תקינה, אבל כאן מתקנים את השאלה העקיפה שמתחילה ב-`Can you tell me`: `Can you tell me how long the update will take?`',
        },
      ],
      rules: [
        {
          order: ['can you tell me', 'does'],
          as: 'form_error',
          err: 'do_in_indirect',
          fb: 'בתוך שאלה עקיפה אין `does`: `how long the update takes`.',
        },
        {
          order: ['can you tell me', 'will the update'],
          as: 'form_error',
          err: 'inversion_in_indirect',
          fb: 'בתוך שאלה עקיפה אין היפוך: קודם הנושא, ואז `will` — `how long the update will take`.',
        },
        {
          has: ['the update take'],
          as: 'form_error',
          err: 'agreement_s',
          fb: 'בלי `does` הפועל מקבל s, כמו במשפט רגיל: `the update takes`.',
        },
        {
          has: ['does', 'takes'],
          as: 'form_error',
          err: 'does_v_s',
          fb: 'אחרי `does` בא פועל בסיס — ובתוך שאלה עקיפה אין `does` בכלל: `how long the update takes`.',
        },
        {
          has: ['will takes'],
          as: 'form_error',
          err: 'modal_v_s',
          fb: 'אחרי `will` בא פועל בסיס: `how long the update will take`.',
        },
      ],
      end: '?',
    },
    {
      id: 'S08-05',
      v: 1,
      skill: 'S08',
      unit: 'S08',
      sub: 'wh_indirect',
      type: 'correct',
      role: 'practice',
      stage: 2,
      ctx: 'daily.family',
      fam: 'S08.wonder-why-left',
      goal: 'לומר שאתה תוהה למה חבר הלך מוקדם',
      instr: CORRECT_INSTR,
      sitHe: 'במסיבה של חברים, תום הלך הביתה מוקדם בלי להיפרד. אתה אומר לחברה שאתה תוהה למה.',
      target: 'משפט שמתחיל ב-`I wonder`',
      hint: 'אחרי `I wonder why` — האם הסדר כאן הוא של משפט רגיל?',
      explain: 'המשפט תקין: אחרי `I wonder why` הסדר רגיל, בלי `did`, והפועל עצמו בעבר — `he left`. זה משפט חיווי, ולכן נקודה בסוף.',
      deep: 'השאלה הישירה היא `Why did he leave early?`. בשאלה עקיפה `did` נעלם, ולכן העבר עובר לפועל עצמו: `why he left early`. `I wonder…` הוא משפט ולא שאלה — לכן נקודה ולא סימן שאלה.',
      source: [
        { id: 's1', t: 'I wonder' },
        { id: 's2', t: 'why' },
        { id: 's3', t: 'he' },
        { id: 's4', t: 'left' },
        { id: 's5', t: 'early' },
      ],
      tokens: [
        {
          id: 't1',
          t: 'did',
          why: 'במשפט שמתחיל ב-`I wonder` אין `did`: הסדר רגיל, והפועל עצמו בעבר — `I wonder why he left early`.',
          err: 'do_in_indirect',
        },
        {
          id: 't2',
          t: 'leave',
          why: 'בלי `did` הפועל עצמו מקבל את העבר: `he left`.',
          err: 'base_without_do',
        },
      ],
      accept: [{ a: 'I wonder why he left early', o: 'correct_target' }],
      wrong: [
        {
          a: 'Why did he leave early',
          as: 'target_not_used',
          err: 'not_indirect',
          fb: 'זו שאלה ישירה תקינה (עם סימן שאלה). כאן המשפט מתחיל ב-`I wonder`, ובתוכו הסדר רגיל: `I wonder why he left early`.',
        },
      ],
      rules: [
        {
          order: ['i wonder', 'did'],
          as: 'form_error',
          err: 'do_in_indirect',
          fb: 'אחרי `I wonder why` אין `did` ואין היפוך: `I wonder why he left early`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S08-06',
      v: 1,
      skill: 'S08',
      unit: 'S08',
      sub: 'wh_indirect',
      type: 'transform',
      role: 'practice',
      stage: 2,
      ctx: 'daily.travel',
      fam: 'S08.last-bus-leaves',
      goal: 'לשאול בנימוס מתי יוצא האוטובוס האחרון',
      instr: 'הפוך את השאלה הישירה לשאלה עקיפה שמתחילה ב-`Do you know`.',
      sitHe: 'אתה בתחנה המרכזית בעיר זרה ולא בטוח מתי יוצא האוטובוס האחרון. אתה פונה לאדם שמחכה לידך.',
      target: 'שאלה עקיפה שמתחילה ב-`Do you know`',
      fromLabel: 'שאלה ישירה',
      toLabel: 'שאלה עקיפה',
      hint: 'בשאלה העקיפה `does` נעלם. מה קורה אז לפועל?',
      explain: 'בלי `does` הסדר רגיל והפועל מקבל s: `Do you know what time the last bus leaves?`',
      deep: 'השאלה הישירה: `What time does the last bus leave?` — ה-s נמצאת ב-`does`. בשאלה העקיפה `does` יוצא, וה-s חוזרת לפועל כמו במשפט רגיל: `The last bus leaves at eleven` ← `…what time the last bus leaves`.',
      source: [
        { id: 's1', t: 'what time' },
        {
          id: 's2',
          t: 'does',
          why: 'בשאלה העקיפה שהתבקשה אין `does`: `Do you know what time the last bus leaves?`',
          err: 'do_in_indirect',
        },
        { id: 's3', t: 'the last bus' },
        {
          id: 's4',
          t: 'leave',
          why: 'בלי `does` הפועל מקבל s כמו במשפט רגיל: `the last bus leaves`.',
          err: 'agreement_s',
        },
      ],
      sourceEnd: '?',
      tokens: [
        { id: 't1', t: 'do you know' },
        { id: 't2', t: 'leaves' },
      ],
      accept: [{ a: 'Do you know what time the last bus leaves', o: 'correct_target' }],
      wrong: [
        {
          a: 'What time does the last bus leave',
          as: 'target_not_used',
          err: 'not_transformed',
          fb: 'זו שאלה ישירה תקינה, אבל התבקשת להפוך אותה לשאלה עקיפה שמתחילה ב-`Do you know`.',
        },
      ],
      rules: [
        {
          order: ['do you know', 'does'],
          as: 'form_error',
          err: 'do_in_indirect',
          fb: 'בתוך שאלה עקיפה אין `does`, והסדר הוא כמו במשפט רגיל: `what time the last bus leaves`.',
        },
        {
          has: ['the last bus leave'],
          as: 'form_error',
          err: 'agreement_s',
          fb: 'בלי `does` הפועל מקבל s: `the last bus leaves`.',
        },
        {
          has: ['does', 'leaves'],
          as: 'form_error',
          err: 'does_v_s',
          fb: 'אחרי `does` בא פועל בסיס — ובשאלה העקיפה שהתבקשה אין `does` בכלל: `Do you know what time the last bus leaves?`',
        },
      ],
      end: '?',
    },
    {
      id: 'S08-07',
      v: 1,
      skill: 'S08',
      unit: 'S08',
      sub: 'yesno_indirect',
      type: 'discriminate',
      role: 'practice',
      stage: 3,
      ctx: 'work.job',
      fam: 'S08.office-closed-choice',
      goal: 'לברר אם המשרד סגור היום',
      instr: 'בחר את כל השאלות שמתאימות למצב.',
      sitHe: 'שמעת שמועה שהמשרד הראשי סגור היום בגלל שיפוץ, אבל אתה לא בטוח. אתה שואל עמית אם זה נכון.',
      hint: 'אתה לא יודע אם זה נכון — אתה בודק. איזו מילה מחברת שאלת כן/לא עקיפה?',
      explain: 'כדי לשאול אם משהו נכון: `if` או `whether`, והסדר רגיל — `Do you know if the office is closed today?`',
      deep: '`Do you know that the office is closed today?` מניח שזו עובדה ושואל אם השומע יודע אותה — זה מתאים כשמודיעים משהו, לא כשבודקים. `Do you know is the office…` מכניס שאלה ישירה לתוך שאלה עקיפה.',
      multi: true,
      options: [
        {
          id: 'a',
          en: 'Do you know if the office is closed today?',
          v: 'fits',
          why: 'שאלת כן/לא עקיפה: `if` ואחריו סדר רגיל.',
        },
        {
          id: 'b',
          en: 'Do you know whether the office is closed today?',
          v: 'fits',
          why: 'גם נכון: `whether` מתאים כאן בדיוק כמו `if`.',
        },
        {
          id: 'c',
          en: 'Do you know that the office is closed today?',
          v: 'other_meaning',
          why: 'תקין, אבל `that` מציג את הסגירה כעובדה ושואל אם הוא יודע אותה. אתה עצמך לא בטוח — לכן `if` או `whether`.',
          err: 'that_for_if',
        },
        {
          id: 'd',
          en: 'Do you know is the office closed today?',
          v: 'ungrammatical',
          why: 'בשאלה עקיפה של כן/לא צריך `if` או `whether`, והסדר רגיל: `Do you know if the office is closed today?`',
          err: 'inversion_in_indirect',
        },
      ],
    },
    {
      id: 'S08-08',
      v: 1,
      skill: 'S08',
      unit: 'S08',
      sub: 'wh_indirect',
      type: 'correct',
      role: 'practice',
      stage: 1,
      ctx: 'daily.shopping',
      fam: 'S08.restroom-is',
      goal: 'לשאול עובד בקניון איפה השירותים',
      instr: CORRECT_INSTR,
      sitHe: 'אתה בקניון גדול ומחפש את השירותים. אתה פונה לעובד באחת החנויות.',
      target: 'שאלה עקיפה שמתחילה ב-`Do you know`',
      scaffold: ['Do you know', 'where', 'subject', 'is'],
      hint: 'אחרי `where` בשאלה עקיפה: קודם הנושא, ואז `is`.',
      explain: 'בתוך שאלה עקיפה הנושא בא לפני `is`: `Do you know where the restroom is?`',
      deep: 'בשאלה ישירה `is` קופץ לפני הנושא: `Where is the restroom?`. בשאלה עקיפה הסדר חוזר להיות רגיל: `the restroom is`. גם `where the restroom is located` נכון.',
      source: [
        { id: 's1', t: 'do you know' },
        { id: 's2', t: 'where' },
        { id: 's3', t: 'is' },
        { id: 's4', t: 'the restroom' },
      ],
      tokens: [{ id: 't1', t: 'located' }],
      accept: [
        { a: 'Do you know where the restroom is', o: 'correct_target' },
        {
          a: 'Do you know where the restroom is located',
          o: 'valid_alternative',
          note: 'גם נכון: `is located` — "ממוקם".',
        },
      ],
      wrong: [
        {
          a: 'Do you know where is the restroom',
          as: 'form_error',
          err: 'inversion_in_indirect',
          fb: 'בתוך שאלה עקיפה הנושא בא לפני `is`: `Do you know where the restroom is?`',
        },
        {
          a: 'Where is the restroom',
          as: 'target_not_used',
          err: 'not_indirect',
          fb: 'זו שאלה ישירה תקינה, אבל כאן מתקנים את השאלה העקיפה שמתחילה ב-`Do you know`: `Do you know where the restroom is?`',
        },
        {
          a: 'Where is the restroom located',
          as: 'target_not_used',
          err: 'not_indirect',
          fb: 'זו שאלה ישירה תקינה, אבל כאן מתקנים את השאלה העקיפה שמתחילה ב-`Do you know`: `Do you know where the restroom is located?`',
        },
      ],
      rules: [
        {
          order: ['do you know', 'is the restroom'],
          as: 'form_error',
          err: 'inversion_in_indirect',
          fb: 'בתוך שאלה עקיפה הנושא בא לפני `is`: `where the restroom is`.',
        },
        {
          has: ['restroom located'],
          as: 'form_error',
          err: 'missing_be',
          fb: 'חסר `is`: `where the restroom is located`.',
        },
      ],
      end: '?',
    },
    {
      id: 'S08-D1',
      v: 2,
      skill: 'S08',
      unit: 'S08',
      sub: 'wh_indirect',
      type: 'dialogue',
      role: 'practice',
      stage: 2,
      ctx: 'work.meeting',
      fam: 'S08.dialogue-conference',
      goal: 'לשאול בנימוס שאלות מעשיות בכנס',
      instr: 'ענה לקרן בכל תור.',
      partnerName: 'Karen',
      setupHe: 'אתה מגיע לכנס מקצועי בבניין שלא הכרת, ופונה לקרן בדלפק המידע.',
      hint: 'בשני התורות — שאלה עקיפה: אחרי הפתיחה בא הסדר של משפט רגיל.',
      explain: 'בתוך שאלה עקיפה הנושא בא לפני הפועל, ואין `do / does`: `where the main hall is`, `if they serve lunch`.',
      turns: [
        {
          partner: { en: 'Good morning! How can I help you?', he: 'בוקר טוב. איך אפשר לעזור?' },
          sub: 'wh_indirect',
          instr: 'שאל אותה בנימוס איפה האולם הראשי. התחל ב-`Could you tell me`.',
          target: 'שאלה עקיפה שמתחילה ב-`Could you tell me`',
          hint: 'אחרי `where`: קודם הנושא, ואז `is`.',
          explain: 'בשאלה עקיפה הנושא בא לפני `is`: `Could you tell me where the main hall is?`',
          build: {
            tokens: [
              { id: 't1', t: 'could you tell me' },
              { id: 't2', t: 'where' },
              { id: 't3', t: 'the main hall' },
              { id: 't4', t: 'is' },
              { id: 't5', t: 'located' },
            ],
            accept: [
              { a: 'Could you tell me where the main hall is', o: 'correct_target' },
              {
                a: 'Could you tell me where the main hall is located',
                o: 'valid_alternative',
                note: 'גם נכון: `is located` — "ממוקם".',
              },
            ],
            wrong: [
              {
                a: 'Where is the main hall',
                as: 'target_not_used',
                err: 'not_indirect',
                fb: 'זו שאלה ישירה תקינה, אבל התבקשה שאלה עקיפה שמתחילה ב-`Could you tell me`: `Could you tell me where the main hall is?`',
              },
              {
                a: 'Where is the main hall located',
                as: 'target_not_used',
                err: 'not_indirect',
                fb: 'זו שאלה ישירה תקינה, אבל התבקשה שאלה עקיפה שמתחילה ב-`Could you tell me`: `Could you tell me where the main hall is located?`',
              },
            ],
            rules: [
              {
                order: ['could you tell me', 'is the main hall'],
                as: 'form_error',
                err: 'inversion_in_indirect',
                fb: 'בתוך שאלה עקיפה הנושא בא לפני `is`: `Could you tell me where the main hall is?`',
              },
              {
                has: ['main hall located'],
                as: 'form_error',
                err: 'missing_be',
                fb: 'חסר `is`: `where the main hall is located`.',
              },
            ],
            end: '?',
          },
        },
        {
          partner: {
            en: "Sure. It's on the second floor, next to the elevators.",
            he: 'בטח. הוא בקומה השנייה, ליד המעליות.',
          },
          sub: 'yesno_indirect',
          instr: 'שאל אותה אם מגישים ארוחת צהריים בכנס. התחל ב-`Do you know`.',
          target: 'שאלה עקיפה שמתחילה ב-`Do you know`',
          hint: 'שאלת כן/לא עקיפה: `if` או `whether`, ואחריהם סדר רגיל — בלי `do`.',
          explain: 'בלי `do` ובסדר רגיל: `Do you know if they serve lunch?` — גם `whether` נכון.',
          build: {
            tokens: [
              { id: 't1', t: 'do you know' },
              { id: 't2', t: 'if' },
              { id: 't3', t: 'whether' },
              { id: 't4', t: 'they' },
              { id: 't5', t: 'serve' },
              { id: 't6', t: 'lunch' },
              {
                id: 't7',
                t: 'do',
                why: 'בשאלה העקיפה אין `do` נוסף: `Do you know if they serve lunch?`',
                err: 'do_in_indirect',
              },
              {
                id: 't8',
                t: 'serves',
                why: 'עם `they` הפועל בא בלי s: `they serve`.',
                err: 'agreement_s',
              },
            ],
            accept: [
              { a: 'Do you know if they serve lunch', o: 'correct_target' },
              {
                a: 'Do you know whether they serve lunch',
                o: 'valid_alternative',
                note: 'גם נכון: בשאלת כן/לא עקיפה פשוטה `if` ו-`whether` שתיהן תקינות.',
              },
              {
                a: 'Do you know if they do lunch',
                o: 'valid_alternative',
                note: 'אפשרי בדיבור לא רשמי (בעיקר באנגלית בריטית): `do lunch` = "מגישים צהריים". הנוסח הרגיל: `serve lunch`.',
              },
              {
                a: 'Do you know whether they do lunch',
                o: 'valid_alternative',
                note: 'אפשרי בדיבור לא רשמי (בעיקר באנגלית בריטית): `do lunch` = "מגישים צהריים". הנוסח הרגיל: `serve lunch`.',
              },
            ],
            wrong: [
              {
                a: 'Do they serve lunch',
                as: 'target_not_used',
                err: 'not_indirect',
                fb: 'זו שאלה ישירה תקינה, אבל התבקשה שאלה עקיפה עם `Do you know`: `Do you know if they serve lunch?`',
              },
              {
                a: 'Do you know they serve lunch',
                as: 'meaning_mismatch',
                err: 'missing_if',
                fb: 'בלי `if` זה נשמע כאילו אתה כבר יודע שמגישים צהריים ובודק אם גם היא יודעת. כדי לשאול: `Do you know if they serve lunch?`',
              },
              {
                a: 'Do you know they do lunch',
                as: 'meaning_mismatch',
                err: 'missing_if',
                fb: 'בלי `if` זה נשמע כאילו אתה כבר יודע שמגישים צהריים ובודק אם גם היא יודעת. כדי לשאול: `Do you know if they serve lunch?`',
              },
            ],
            rules: [
              {
                has: ['if do'],
                as: 'form_error',
                err: 'do_in_indirect',
                fb: 'בתוך שאלה עקיפה אין `do`, והסדר רגיל: `if they serve lunch`.',
              },
              {
                has: ['whether do'],
                as: 'form_error',
                err: 'do_in_indirect',
                fb: 'בתוך שאלה עקיפה אין `do`, והסדר רגיל: `whether they serve lunch`.',
              },
              {
                starts: 'if',
                lacks: ['do you know'],
                as: 'form_error',
                err: 'missing_frame',
                fb: 'חסרה הפתיחה: השאלה העקיפה מתחילה ב-`Do you know`, ואחריה `if` וסדר רגיל — `Do you know if they serve lunch?`',
              },
              {
                starts: 'whether',
                lacks: ['do you know'],
                as: 'form_error',
                err: 'missing_frame',
                fb: 'חסרה הפתיחה: השאלה העקיפה מתחילה ב-`Do you know`, ואחריה `whether` וסדר רגיל — `Do you know whether they serve lunch?`',
              },
            ],
            end: '?',
          },
        },
      ],
      closing: { en: 'Yes, at one o\'clock, in the lobby. Enjoy the conference!', he: 'כן, באחת, בלובי. תיהנה בכנס.' },
    },
    {
      id: 'S08-09',
      v: 1,
      skill: 'S08',
      unit: 'S08',
      sub: 'wh_indirect',
      type: 'assemble',
      role: 'practice',
      stage: 3,
      ctx: 'daily.learning',
      fam: 'S08.word-means',
      goal: 'לשאול בנימוס חבר לכיתה מה פירוש מילה',
      instr: 'קרא את הסיטואציה ובנה את השאלה באנגלית. לא חייבים להשתמש בכל המילים.',
      sitEn:
        "In your English class you see a word you don't know. You turn to the classmate next to you and ask politely, starting with 'Do you know'.",
      trHe: 'בשיעור אנגלית אתה נתקל במילה שאתה לא מכיר. אתה פונה לחבר שיושב לידך ושואל בנימוס, בשאלה שמתחילה ב-`Do you know`.',
      target: 'שאלה עקיפה שמתחילה ב-`Do you know`',
      hint: 'אחרי `Do you know what` — הסדר של שאלה או של משפט רגיל?',
      explain: 'בשאלה העקיפה אין `does`, ולכן הפועל מקבל s: `Do you know what this word means?`',
      deep: 'ישירה: `What does this word mean?` — `does` לוקח את ה-s. עקיפה: `Do you know what this word means?` — `does` יוצא, וה-s חוזרת ל-`means`. שתי השאלות תקינות; הן פשוט בנויות אחרת.',
      tokens: [
        { id: 't1', t: 'do you know' },
        { id: 't2', t: 'what' },
        { id: 't3', t: 'this word' },
        { id: 't4', t: 'means' },
        {
          id: 't5',
          t: 'mean',
          why: 'בלי `does` הפועל מקבל s: `this word means`. `mean` בלי s בא רק אחרי `does`: `What does this word mean?`',
          err: 'agreement_s',
        },
        {
          id: 't6',
          t: 'does',
          why: 'בשאלה העקיפה שהתבקשה אין `does`: `Do you know what this word means?`',
          err: 'do_in_indirect',
        },
      ],
      accept: [{ a: 'Do you know what this word means', o: 'correct_target' }],
      wrong: [
        {
          a: 'What does this word mean',
          as: 'target_not_used',
          err: 'not_indirect',
          fb: 'זו שאלה ישירה תקינה, אבל התבקשה שאלה עקיפה עם `Do you know`: `Do you know what this word means?`',
        },
      ],
      rules: [
        {
          order: ['do you know', 'does'],
          as: 'form_error',
          err: 'do_in_indirect',
          fb: 'בתוך שאלה עקיפה אין `does`, והסדר רגיל: `Do you know what this word means?`',
        },
        {
          has: ['do you know', 'word mean'],
          as: 'form_error',
          err: 'agreement_s',
          fb: 'בלי `does` הפועל מקבל s: `this word means`.',
        },
        {
          has: ['does', 'means'],
          as: 'form_error',
          err: 'does_v_s',
          fb: 'אחרי `does` בא פועל בסיס: `What does this word mean?` — ובשאלה העקיפה שהתבקשה אין `does`: `Do you know what this word means?`',
        },
        {
          starts: 'what',
          lacks: ['does'],
          as: 'form_error',
          err: 'missing_do',
          fb: 'בשאלה ישירה צריך `does`: `What does this word mean?` — ובשאלה העקיפה שהתבקשה: `Do you know what this word means?`',
        },
      ],
      end: '?',
    },
    {
      id: 'S08-10',
      v: 1,
      skill: 'S08',
      unit: 'S08',
      sub: 'yesno_indirect',
      type: 'transform',
      role: 'practice',
      stage: 3,
      ctx: 'work.project',
      fam: 'S08.not-sure-approved',
      goal: 'לומר שאתה לא בטוח אם אישרו את התקציב',
      instr: 'הפוך את השאלה הישירה למשפט שמתחיל ב-`I\'m not sure`.',
      sitHe: 'עמית שואל אותך אם ההנהלה אישרה אתמול את התקציב לפרויקט. לא היית בישיבה, ואתה לא יודע.',
      target: 'שאלה עקיפה שמתחילה ב-`I\'m not sure`, עם `whether` או `if`',
      fromLabel: 'שאלה ישירה',
      toLabel: 'שאלה עקיפה (משפט חיווי)',
      hint: 'בשאלה העקיפה אין `did`. איפה יסומן עכשיו העבר?',
      explain: 'בשאלה העקיפה `did` יוצא, והעבר עובר לפועל: `I\'m not sure whether they approved the budget`. זה משפט חיווי, ולכן נקודה בסוף.',
      deep: '`Did they approve…?` — העבר ב-`did`, והפועל בבסיס. בשאלה העקיפה אין `did`, ולכן הפועל עצמו נושא את העבר: `they approved`. `if` ו-`whether` שתיהן נכונות כאן. `I\'m not sure they approved…` (בלי `whether`) גם תקין, אבל נוטה יותר לספק: "לא בטוח שאישרו".',
      source: [
        {
          id: 's1',
          t: 'did',
          why: 'במשפט שמתחיל ב-`I\'m not sure` אין `did`: `I\'m not sure whether they approved the budget`.',
          err: 'do_in_indirect',
        },
        { id: 's2', t: 'they' },
        {
          id: 's3',
          t: 'approve',
          why: 'בלי `did` הפועל עצמו צריך לשאת את העבר: `they approved`.',
          err: 'base_without_do',
        },
        { id: 's4', t: 'the budget' },
      ],
      sourceEnd: '?',
      tokens: [
        { id: 't1', t: "I'm not sure" },
        { id: 't2', t: 'whether' },
        { id: 't3', t: 'if' },
        { id: 't4', t: 'approved' },
      ],
      accept: [
        { a: "I'm not sure whether they approved the budget", o: 'correct_target' },
        {
          a: "I'm not sure if they approved the budget",
          o: 'valid_alternative',
          note: 'גם נכון: `if` ו-`whether` שתיהן תקינות כאן.',
        },
        {
          a: "I'm not sure they approved the budget",
          o: 'target_not_used',
          note: 'תקין — "אני לא בטוח שהם אישרו" (נוטה יותר לספק). התבקשה שאלה עקיפה עם `whether` או `if`.',
        },
      ],
      wrong: [
        {
          a: 'Did they approve the budget',
          as: 'target_not_used',
          err: 'not_transformed',
          fb: 'זו השאלה הישירה המקורית. התבקשת להפוך אותה למשפט שמתחיל ב-`I\'m not sure`.',
        },
        {
          a: 'They approved the budget',
          as: 'meaning_mismatch',
          err: 'statement_for_doubt',
          fb: 'המשפט הזה קובע שהם אישרו. כאן אתה לא יודע: `I\'m not sure whether they approved the budget`.',
        },
      ],
      rules: [
        {
          order: ["i'm not sure", 'did'],
          as: 'form_error',
          err: 'do_in_indirect',
          fb: 'בתוך שאלה עקיפה אין `did`. בלי `did` הפועל עצמו בעבר: `whether they approved the budget`.',
        },
        {
          has: ['did', 'approved'],
          as: 'form_error',
          err: 'did_v2',
          fb: 'אחרי `did` בא פועל בסיס — ובשאלה העקיפה אין `did` בכלל: `I\'m not sure whether they approved the budget`.',
        },
        {
          has: ['they approve the budget'],
          as: 'meaning_mismatch',
          err: 'base_without_do',
          fb: '`they approve` נשמע כמו הווה או הרגל, אבל ההחלטה התקבלה אתמול. בלי `did` הפועל עצמו נושא את העבר: `I\'m not sure whether they approved the budget`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S08-11',
      v: 2,
      skill: 'S08',
      unit: 'S08',
      sub: 'wh_indirect',
      type: 'assemble',
      role: 'practice',
      stage: 2,
      ctx: 'work.job',
      fam: 'S08.wonder-what-told',
      goal: 'לומר שאתה תוהה מה המנהלת אמרה לדן',
      instr: 'קרא את הסיטואציה ובנה משפט אחד באנגלית. לא חייבים להשתמש בכל המילים.',
      sitEn:
        "Your colleague Dan comes back from a short talk with the manager, and he looks upset. You'd like to know what she said to him. Share this thought with another colleague, starting with 'I wonder'.",
      trHe: 'דן, עמית שלך, חוזר משיחה קצרה עם המנהלת ונראה מוטרד. היית רוצה לדעת מה היא אמרה לו. שתף את המחשבה הזאת עם עמית אחר, במשפט שמתחיל ב-`I wonder`.',
      target: 'משפט שמתחיל ב-`I wonder`',
      hint: 'אחרי `I wonder what` — סדר רגיל, בלי `did`. איפה יסומן העבר?',
      explain: 'בלי `did` הפועל עצמו בעבר: `I wonder what the manager told him`. זה משפט חיווי, ולכן נקודה בסוף.',
      deep: 'השאלה הישירה: `What did the manager tell him?`. בשאלה העקיפה `did` יוצא, והעבר עובר לפועל: `told`. `I wonder…` הוא משפט ולא שאלה.',
      tokens: [
        { id: 't1', t: 'I wonder' },
        { id: 't2', t: 'what' },
        { id: 't3', t: 'the manager' },
        { id: 't4', t: 'told' },
        { id: 't5', t: 'him' },
        {
          id: 't6',
          t: 'did',
          why: 'במשפט שמתחיל ב-`I wonder` אין `did`: הסדר רגיל, והפועל עצמו בעבר — `I wonder what the manager told him`.',
          err: 'do_in_indirect',
        },
        {
          id: 't7',
          t: 'tell',
          why: 'בלי `did` הפועל עצמו מקבל את העבר: `the manager told him`.',
          err: 'base_without_do',
        },
      ],
      accept: [{ a: 'I wonder what the manager told him', o: 'correct_target' }],
      wrong: [
        {
          a: 'What did the manager tell him',
          as: 'target_not_used',
          err: 'not_indirect',
          fb: 'זו שאלה ישירה תקינה, אבל כאן התבקש משפט שמתחיל ב-`I wonder`: `I wonder what the manager told him`.',
        },
        {
          a: 'I wonder what the manager did',
          as: 'meaning_mismatch',
          err: 'other_verb',
          fb: 'המשפט תקין (`did` כאן הוא הפועל עצמו — "עשתה"), אבל הוא אומר שאתה תוהה מה המנהלת עשתה, לא מה היא אמרה לו: `I wonder what the manager told him`.',
        },
      ],
      rules: [
        {
          order: ['i wonder', 'did'],
          as: 'form_error',
          err: 'do_in_indirect',
          fb: 'אחרי `I wonder what` אין `did` ואין היפוך: `I wonder what the manager told him`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S08-12',
      v: 1,
      skill: 'S08',
      unit: 'S08',
      sub: 'yesno_indirect',
      type: 'correct',
      role: 'practice',
      stage: 2,
      ctx: 'daily.food',
      fam: 'S08.soup-contains-nuts',
      goal: 'לשאול מלצר אם יש אגוזים במרק',
      instr: CORRECT_INSTR,
      sitHe: 'במסעדה. חבר שלך אלרגי לאגוזים, ואתה שואל את המלצר אם יש אגוזים במרק.',
      target: 'שאלה עקיפה שמתחילה ב-`Could you tell me`',
      hint: 'בדוק את החלק שאחרי `whether`: האם הסדר בו הוא של משפט רגיל?',
      explain: 'בתוך שאלה עקיפה אין `does`, והפועל מקבל s: `Could you tell me whether the soup contains nuts?`',
      deep: 'השאלה הישירה: `Does the soup contain nuts?`. בשאלה העקיפה `does` יוצא, וה-s חוזרת לפועל: `the soup contains`. במקום `whether` אפשר גם `if`.',
      source: [
        { id: 's1', t: 'could you tell me' },
        { id: 's2', t: 'whether' },
        {
          id: 's3',
          t: 'does',
          why: 'בשאלה העקיפה אין `does`: `Could you tell me whether the soup contains nuts?`',
          err: 'do_in_indirect',
        },
        { id: 's4', t: 'the soup' },
        {
          id: 's5',
          t: 'contain',
          why: 'בלי `does` הפועל מקבל s: `the soup contains`.',
          err: 'agreement_s',
        },
        { id: 's6', t: 'nuts' },
      ],
      tokens: [
        { id: 't1', t: 'contains' },
        { id: 't2', t: 'if' },
      ],
      accept: [
        { a: 'Could you tell me whether the soup contains nuts', o: 'correct_target' },
        {
          a: 'Could you tell me if the soup contains nuts',
          o: 'valid_alternative',
          note: 'גם נכון: `if` ו-`whether` שתיהן תקינות כאן.',
        },
      ],
      wrong: [
        {
          a: 'Could you tell me whether does the soup contain nuts',
          as: 'form_error',
          err: 'do_in_indirect',
          fb: 'בתוך שאלה עקיפה אין `does`, והסדר רגיל: `Could you tell me whether the soup contains nuts?`',
        },
        {
          a: 'Does the soup contain nuts',
          as: 'target_not_used',
          err: 'not_indirect',
          fb: 'זו שאלה ישירה תקינה, אבל כאן מתקנים את השאלה העקיפה שמתחילה ב-`Could you tell me`: `Could you tell me whether the soup contains nuts?`',
        },
        {
          a: 'Could you tell me the soup contains nuts',
          as: 'meaning_mismatch',
          err: 'missing_if',
          fb: 'בלי `whether` או `if` זה נשמע כאילו אתה מבקש שיגיד לך שיש במרק אגוזים — לא שואל אם יש. `Could you tell me whether the soup contains nuts?`',
        },
      ],
      rules: [
        {
          order: ['could you tell me', 'does'],
          as: 'form_error',
          err: 'do_in_indirect',
          fb: 'בתוך שאלה עקיפה אין `does`: `whether the soup contains nuts`.',
        },
        {
          has: ['soup contain'],
          as: 'form_error',
          err: 'agreement_s',
          fb: 'בלי `does` הפועל מקבל s: `the soup contains`.',
        },
        {
          has: ['does', 'contains'],
          as: 'form_error',
          err: 'does_v_s',
          fb: 'אחרי `does` בא פועל בסיס — ובשאלה העקיפה אין `does` בכלל: `Could you tell me whether the soup contains nuts?`',
        },
      ],
      end: '?',
    },
    {
      id: 'S08-C1',
      v: 1,
      skill: 'S08',
      unit: 'S08',
      sub: 'wh_indirect',
      type: 'transform',
      role: 'check',
      stage: 2,
      ctx: 'work.municipality',
      fam: 'S08.documents-need',
      goal: 'לשאול בנימוס אילו מסמכים צריך להיתר',
      instr: 'הפוך את השאלה הישירה לשאלה עקיפה שמתחילה ב-`Could you tell me`.',
      sitHe: 'אתה בדלפק השירות של העירייה ורוצה להגיש בקשה להיתר. אתה שואל את הפקידה אילו מסמכים צריך להביא.',
      target: 'שאלה עקיפה שמתחילה ב-`Could you tell me`',
      fromLabel: 'שאלה ישירה',
      toLabel: 'שאלה עקיפה',
      hint: 'בשאלה העקיפה אין `do`. הסדר: `which documents` ← הנושא ← הפועל.',
      explain: 'בתוך שאלה עקיפה אין `do`, והסדר רגיל: `Could you tell me which documents I need for the permit?`',
      deep: 'ישירה: `Which documents do I need…?` — `do` בא לפני הנושא. עקיפה: `…which documents I need…` — `do` יוצא, והנושא `I` בא לפני הפועל. עם `I` הפועל נשאר בלי s.',
      source: [
        { id: 's1', t: 'which documents' },
        {
          id: 's2',
          t: 'do',
          why: 'בשאלה העקיפה שהתבקשה אין `do`: `Could you tell me which documents I need for the permit?`',
          err: 'do_in_indirect',
        },
        { id: 's3', t: 'I' },
        { id: 's4', t: 'need' },
        { id: 's5', t: 'for the permit' },
      ],
      sourceEnd: '?',
      tokens: [
        { id: 't1', t: 'could you tell me' },
        { id: 't2', t: 'needs', why: 'עם `I` הפועל בא בלי s: `I need`.', err: 'agreement_s' },
      ],
      accept: [{ a: 'Could you tell me which documents I need for the permit', o: 'correct_target' }],
      wrong: [
        {
          a: 'Which documents do I need for the permit',
          as: 'target_not_used',
          err: 'not_transformed',
          fb: 'זו שאלה ישירה תקינה, אבל התבקשת להפוך אותה לשאלה עקיפה שמתחילה ב-`Could you tell me`.',
        },
      ],
      rules: [
        {
          order: ['could you tell me', 'do'],
          as: 'form_error',
          err: 'do_in_indirect',
          fb: 'בתוך שאלה עקיפה אין `do`, והסדר רגיל: `which documents I need for the permit`.',
        },
      ],
      end: '?',
    },
    {
      id: 'S08-C2',
      v: 2,
      skill: 'S08',
      unit: 'S08',
      sub: 'wh_indirect',
      type: 'discriminate',
      role: 'check',
      stage: 3,
      ctx: 'daily.home',
      fam: 'S08.wonder-package-choice',
      goal: 'לומר לשכנה שאתה תוהה איפה החבילה',
      instr: 'בחר את כל המשפטים שמתאימים למצב.',
      sitHe: 'הזמנת חבילה שהייתה אמורה להגיע אתמול, והיא עוד לא הגיעה. אתה מדבר עם שכנה ומשתף אותה שאתה תוהה איפה החבילה.',
      hint: 'בדוק את הסדר אחרי `where`, והאם יש בו פועל עזר מיותר.',
      explain: 'אחרי `I wonder where` בא סדר של משפט רגיל, בלי `did`: `I wonder where the package is.` או, בעבר, `I wonder where the package went.`',
      multi: true,
      options: [
        {
          id: 'a',
          en: 'I wonder where the package is.',
          v: 'fits',
          why: 'סדר רגיל אחרי `where`: קודם הנושא, ואז `is`.',
        },
        {
          id: 'b',
          en: 'I wonder where is the package.',
          v: 'ungrammatical',
          why: 'בתוך שאלה עקיפה אין היפוך: `where the package is`.',
          err: 'inversion_in_indirect',
        },
        {
          id: 'c',
          en: 'I wonder where the package went.',
          v: 'fits',
          why: 'גם נכון: בלי `did`, והפועל עצמו בעבר — `where the package went`.',
        },
        {
          id: 'd',
          en: 'I wonder where did the package go.',
          v: 'ungrammatical',
          why: 'בתוך שאלה עקיפה אין `did`, והפועל עצמו בעבר: `where the package went`.',
          err: 'do_in_indirect',
        },
      ],
    },
    {
      id: 'S08-C3',
      v: 1,
      skill: 'S08',
      unit: 'S08',
      sub: 'yesno_indirect',
      type: 'assemble',
      role: 'check',
      stage: 2,
      ctx: 'daily.health',
      fam: 'S08.gym-has-pool',
      goal: 'לשאול חבר אם יש בריכה בחדר הכושר',
      instr: 'קרא את הסיטואציה ובנה את השאלה באנגלית. לא חייבים להשתמש בכל המילים.',
      sitEn:
        "You're thinking about joining a gym near your home. Your friend Omer trains there. Ask him politely about a swimming pool at the gym, starting with 'Do you know'.",
      trHe: 'אתה שוקל להירשם לחדר כושר ליד הבית. עומר, חבר שלך, מתאמן שם. שאל אותו בנימוס, בשאלה שמתחילה ב-`Do you know`, אם יש בחדר הכושר בריכה.',
      target: 'שאלה עקיפה שמתחילה ב-`Do you know`',
      hint: 'שאלת כן/לא עקיפה: `if` או `whether`, ואחריהם הסדר של משפט רגיל.',
      explain: 'בלי `does` הפועל מתאים לנושא כמו במשפט רגיל: `Do you know if the gym has a pool?`',
      deep: 'ישירה: `Does the gym have a pool?` — ה-s ב-`does`, ולכן `have`. עקיפה: `does` יוצא, וה-s חוזרת לפועל — `the gym has`. `if` ו-`whether` שתיהן נכונות כאן.',
      tokens: [
        { id: 't1', t: 'do you know' },
        { id: 't2', t: 'if' },
        { id: 't3', t: 'whether' },
        { id: 't4', t: 'the gym' },
        { id: 't5', t: 'has' },
        {
          id: 't6',
          t: 'have',
          why: 'בלי `does` הפועל מתאים לנושא כמו במשפט רגיל: `the gym has`.',
          err: 'agreement_s',
        },
        {
          id: 't7',
          t: 'does',
          why: 'בשאלה העקיפה שהתבקשה אין `does`: `Do you know if the gym has a pool?`',
          err: 'do_in_indirect',
        },
        { id: 't8', t: 'a pool' },
      ],
      accept: [
        { a: 'Do you know if the gym has a pool', o: 'correct_target' },
        {
          a: 'Do you know whether the gym has a pool',
          o: 'valid_alternative',
          note: 'גם נכון: `if` ו-`whether` שתיהן תקינות כאן.',
        },
      ],
      wrong: [
        {
          a: 'Does the gym have a pool',
          as: 'target_not_used',
          err: 'not_indirect',
          fb: 'זו שאלה ישירה תקינה, אבל התבקשה שאלה עקיפה עם `Do you know`: `Do you know if the gym has a pool?`',
        },
        {
          a: 'Do you know the gym has a pool',
          as: 'meaning_mismatch',
          err: 'missing_if',
          fb: 'בלי `if` זה נשמע כאילו אתה כבר יודע שיש בריכה ובודק אם גם הוא יודע. כדי לשאול: `Do you know if the gym has a pool?`',
        },
      ],
      rules: [
        {
          order: ['do you know', 'does'],
          as: 'form_error',
          err: 'do_in_indirect',
          fb: 'בתוך שאלה עקיפה אין `does`, והסדר רגיל: `if the gym has a pool`.',
        },
        {
          has: ['does', 'has'],
          as: 'form_error',
          err: 'does_v_s',
          fb: 'אחרי `does` בא פועל בסיס (`have`) — ובשאלה העקיפה שהתבקשה אין `does` בכלל: `Do you know if the gym has a pool?`',
        },
      ],
      end: '?',
    },
  ],
};
