import type { SkillPack } from '../schema';

/**
 * S09 SUBJECT_OBJECT — subject questions (no do: `Who invited you?`) vs object questions
 * (`Who did you invite?`). Every situation names who did what to whom.
 */

const CORRECT_INSTR = 'אם יש טעות — גע במילה או ברווח ובחר תיקון. אם המשפט תקין, בחר "אין צורך בתיקון".';

export const S09: SkillPack = {
  skill: 'S09',
  lessons: [
    {
      unit: 'S09',
      title: 'מי הזמין? את מי הזמנת?',
      short:
        'כש-`who / what / which` הוא מי שעשה את הפעולה, אין `did` והפועל בזמן הרגיל שלו: `Who invited you?` כשהוא מי שקיבל את הפעולה, צריך `did` + הנושא + פועל בסיס: `Who did you invite?`',
      examples: [
        { en: 'Who called you?', he: 'מי התקשר אליך?' },
        { en: 'Who did you call?', he: 'למי התקשרת?' },
        { en: 'What happened?', he: 'מה קרה?' },
        { en: 'What did she say?', he: 'מה היא אמרה?' },
      ],
      contrast: {
        a: { en: 'Who invited you?', he: 'מי הזמין אותך? (מישהו הזמין אותך — מי?)' },
        b: { en: 'Who did you invite?', he: 'את מי הזמנת? (אתה הזמנת מישהו — את מי?)' },
        note: 'בעברית ההבדל נשמע: "מי" מול "את מי". באנגלית שתי השאלות מתחילות ב-`Who`, וההבדל הוא ב-`did` ובסדר: בלי `did`, `who` הוא מי שהזמין; עם `did you`, `who` הוא מי שהוזמן.',
      },
      deep:
        '• שאלת נושא: `who / what / which` תופס את מקום הנושא, והסדר נשאר כמו במשפט רגיל: `Someone invited you` ← `Who invited you?`. אין `did`, והפועל בזמן הרגיל שלו: `invited`, `happened`, `won`.\n' +
        '• שאלת מושא: `who / what / which` הוא מי או מה שקיבל את הפעולה. אז צריך פועל עזר לפני הנושא, כמו בכל שאלה: `You invited someone` ← `Who did you invite?`.\n' +
        '• `What happened?` — בלי `did`, כי `what` הוא הנושא (משהו קרה). `What did you do?` — `you` הוא הנושא, ו-`what` הוא מה שעשית.\n' +
        '• בשאלת מושא, אחרי `did` בא פועל בסיס: `Who did you invite?` — לא `invited`.\n' +
        '• `Who did invite you?` אפשרי רק בהדגשה מיוחדת (למשל כשכל הניחושים התבררו כשגויים: "אז מי כן הזמין אותך?"). בשאלה רגילה: `Who invited you?`.\n' +
        '• מילת יחס נשארת לרוב בסוף השאלה: `Who did you send it to?`.',
      pitfalls: [
        '`Who did invite you?` — בשאלה רגילה על מי שהזמין: `Who invited you?`',
        '`What did happen?` — `What happened?`',
        '`Who you invited?` — חסר `did`: `Who did you invite?`',
        '`Who did you invited?` — אחרי `did` בא פועל בסיס: `Who did you invite?`',
      ],
    },
  ],
  examples: {
    S09: [
      { en: 'Who told you about the party?', he: 'מי סיפר לך על המסיבה?' },
      { en: 'Who did you tell about the party?', he: 'למי סיפרת על המסיבה?' },
      { en: 'Which bus goes to the airport?', he: 'איזה אוטובוס נוסע לשדה התעופה?' },
      { en: 'What did the technician say?', he: 'מה אמר הטכנאי?' },
    ],
  },
  items: [
    {
      id: 'S09-01',
      v: 1,
      skill: 'S09',
      unit: 'S09',
      sub: 'subject_question',
      type: 'assemble',
      role: 'practice',
      stage: 1,
      ctx: 'work.meeting',
      fam: 'S09.who-invited-you-meeting',
      goal: 'לשאול עמית מי הזמין אותו לישיבה',
      instr: 'בנה את השאלה באנגלית. לא חייבים להשתמש בכל המילים.',
      promptHe: 'מי הזמין אותך לישיבה?',
      sitHe: 'עמית מספר לך שהוזמן לישיבת ההנהלה של מחר. אתה רוצה לדעת מי הזמין אותו.',
      scaffold: ['Who', 'V (past)', '…'],
      hint: 'מי עשה את הפעולה? כש-`who` הוא הנושא, הסדר כמו במשפט רגיל — בלי `did`.',
      explain: '`who` הוא מי שהזמין — הנושא — ולכן אין `did`, והפועל בעבר: `Who invited you to the meeting?`',
      deep: 'המשפט הרגיל: `Someone invited you`. בשאלה `who` בא במקום `someone`, וכל השאר נשאר: `Who invited you?`. `Who did you invite?` היא שאלה אחרת — את מי אתה הזמנת.',
      tokens: [
        { id: 't1', t: 'who' },
        { id: 't2', t: 'invited' },
        { id: 't3', t: 'you' },
        { id: 't4', t: 'to the meeting' },
        {
          id: 't5',
          t: 'did',
          why: 'כש-`who` הוא מי שעשה את הפעולה (הזמין), אין `did`: `Who invited you…?`',
          err: 'did_in_subject_q',
        },
        {
          id: 't6',
          t: 'invite',
          why: '`invite` (בסיס) בא אחרי `did`. כש-`who` הוא הנושא, הפועל בעבר: `Who invited you…?`',
          err: 'base_in_subject_q',
        },
      ],
      accept: [{ a: 'Who invited you to the meeting', o: 'correct_target' }],
      rules: [
        {
          has: ['who did invite'],
          as: 'form_error',
          err: 'did_in_subject_q',
          fb: 'כש-`who` הוא מי שהזמין, לא מוסיפים `did`: `Who invited you to the meeting?` (`Who did invite you?` מתאים רק בהדגשה מיוחדת, למשל אחרי ויכוח.)',
        },
        {
          has: ['did you invited'],
          as: 'form_error',
          err: 'did_v2',
          fb: 'אחרי `did` בא פועל בסיס (`Who did you invite?`) — אבל כאן בכלל שואלים מי הזמין אותו: `Who invited you to the meeting?`',
        },
        {
          has: ['did you invite'],
          as: 'meaning_mismatch',
          err: 'object_for_subject',
          fb: 'המשפט תקין, אבל הוא שואל את מי אתה הזמנת. כאן רוצים לדעת מי הזמין אותו: `Who invited you to the meeting?`',
        },
        {
          starts: 'who you',
          as: 'form_error',
          err: 'missing_do',
          fb: 'חסר כאן `did` — ומשפט כזה היה שואל את מי אתה הזמנת. כאן רוצים לדעת מי הזמין אותו, ולכן `who` הוא הנושא: `Who invited you to the meeting?`',
        },
      ],
      end: '?',
    },
    {
      id: 'S09-02',
      v: 2,
      skill: 'S09',
      unit: 'S09',
      sub: 'object_question',
      type: 'assemble',
      role: 'practice',
      stage: 1,
      ctx: 'daily.family',
      fam: 'S09.who-did-you-invite-dinner',
      goal: 'לשאול חברה את מי היא הזמינה לארוחה',
      instr: 'בנה את השאלה באנגלית. לא חייבים להשתמש בכל המילים.',
      promptHe: 'את מי הזמנת לארוחת הערב?',
      sitHe: 'חברה שלך מארגנת ארוחת ערב גדולה ביום שישי. אתה רוצה לדעת את מי היא הזמינה.',
      scaffold: ['Who', 'did', 'subject', 'V (base)'],
      hint: 'היא הזמינה מישהו, ואתה שואל את מי. כש-`who` הוא מי שקיבל את הפעולה, צריך `did` לפני הנושא.',
      explain: '`who` הוא מי שהוזמן, והנושא הוא `you`, ולכן `did` + `you` + פועל בסיס: `Who did you invite to the dinner?`',
      deep: 'המשפט הרגיל: `You invited someone`. בשאלה על ה-`someone` צריך פועל עזר, כמו בכל שאלה: `Who did you invite?`. אחרי `did` בא פועל בסיס — `invite`, לא `invited`. בכתיבה רשמית אפשר גם `Whom did you invite?`.',
      tokens: [
        { id: 't1', t: 'who' },
        { id: 't2', t: 'did' },
        { id: 't3', t: 'you' },
        { id: 't4', t: 'invite' },
        { id: 't5', t: 'to the dinner' },
        {
          id: 't6',
          t: 'invited',
          why: '`invited` מתאים לשאלה על מי שהזמין (`Who invited you?`). כאן היא זו שהזמינה, ולכן `did` + פועל בסיס: `Who did you invite…?`',
          err: 'object_q_v2',
        },
      ],
      accept: [{ a: 'Who did you invite to the dinner', o: 'correct_target' }],
      rules: [
        {
          has: ['who did invite you'],
          as: 'meaning_mismatch',
          err: 'subject_for_object',
          fb: '`Who did invite you?` שואל (בהדגשה) מי הזמין אותך — כיוון הפוך. כאן היא הזמינה, ואתה שואל את מי: `Who did you invite to the dinner?`',
        },
        {
          has: ['who did invite'],
          as: 'form_error',
          err: 'did_in_subject_q',
          fb: 'אחרי `did` בא הנושא (`you`), ואחריו פועל בסיס: `Who did you invite to the dinner?`',
        },
        {
          has: ['did you invited'],
          as: 'form_error',
          err: 'did_v2',
          fb: 'אחרי `did` בא פועל בסיס: `Who did you invite to the dinner?`',
        },
        {
          has: ['who invited you'],
          as: 'meaning_mismatch',
          err: 'subject_for_object',
          fb: 'המשפט תקין, אבל הוא שואל מי הזמין אותך. כאן היא הזמינה אנשים, ואתה שואל את מי: `Who did you invite to the dinner?`',
        },
        {
          starts: 'who you',
          as: 'form_error',
          err: 'missing_do',
          fb: 'בשאלה על מי שקיבל את הפעולה, `did` בא לפני הנושא: `Who did you invite to the dinner?`',
        },
      ],
      end: '?',
    },
    {
      id: 'S09-03',
      v: 2,
      skill: 'S09',
      unit: 'S09',
      sub: 'contrast',
      type: 'discriminate',
      role: 'practice',
      stage: 3,
      ctx: 'work.email',
      fam: 'S09.who-sent-email-choice',
      goal: 'לשאול מי שלח מייל בלי חתימה',
      instr: 'בחר את כל השאלות שמתאימות למצב.',
      sitHe: 'קיבלת מייל חשוב בלי שם ובלי חתימה, מכתובת שאתה לא מכיר. אתה רוצה לדעת מי שלח אותו, ושואל עמית.',
      hint: 'מי עשה את הפעולה (שלח)? אז `who` הוא הנושא.',
      explain: 'שואלים על מי ששלח — הנושא — ולכן בלי `did`: `Who sent this email?` או `Who sent me this email?`',
      deep: '`Who did you send this email to?` שואל למי העמית שלח את המייל — שאלה על המקבל. `Who did send this email?` בלי הדגשה מיוחדת אינו מתאים לשאלה רגילה.',
      multi: true,
      options: [
        {
          id: 'a',
          en: 'Who sent this email?',
          v: 'fits',
          why: 'שאלה על מי ששלח: `who` הוא הנושא, ולכן בלי `did`.',
        },
        {
          id: 'b',
          en: 'Who sent me this email?',
          v: 'fits',
          why: 'גם נכון: אותה שאלה, עם `me` — המייל נשלח אליך.',
        },
        {
          id: 'c',
          en: 'Who did you send this email to?',
          v: 'other_meaning',
          why: 'תקין, אבל שואל למי העמית שלח את המייל — לא מי שלח אותו אליך.',
          err: 'object_for_subject',
        },
        {
          id: 'd',
          en: 'Who did send this email?',
          v: 'ungrammatical',
          why: 'כש-`who` הוא מי ששלח, לא מוסיפים `did`: `Who sent this email?` (`did` כאן מתאים רק בהדגשה מיוחדת.)',
          err: 'did_in_subject_q',
        },
      ],
    },
    {
      id: 'S09-04',
      v: 1,
      skill: 'S09',
      unit: 'S09',
      sub: 'subject_question',
      type: 'correct',
      role: 'practice',
      stage: 1,
      ctx: 'work.software',
      fam: 'S09.what-happened-server',
      goal: 'לשאול מה קרה לשרת בלילה',
      instr: CORRECT_INSTR,
      sitHe: 'הבוקר המערכת לא עובדת, ומישהו אמר שהייתה תקלה בשרת בלילה. אתה שואל את איש המחשוב מה קרה.',
      scaffold: ['What', 'V (past)', '…'],
      hint: '`what` כאן הוא מה שקרה — הנושא. צריך `did`?',
      explain: '`what` הוא הנושא (משהו קרה), ולכן אין `did` והפועל בעבר: `What happened to the server last night?`',
      deep: 'המשפט הרגיל: `Something happened to the server`. בשאלה `what` בא במקום `something`, והסדר נשאר: `What happened…?`. לעומת זאת `What did you do?` צריך `did`, כי שם הנושא הוא `you`.',
      source: [
        { id: 's1', t: 'what' },
        {
          id: 's2',
          t: 'did',
          why: '`what` הוא הנושא כאן (מה קרה), ולכן אין `did`: `What happened…?`',
          err: 'did_in_subject_q',
        },
        {
          id: 's3',
          t: 'happen',
          why: 'בלי `did` הפועל בעבר: `What happened…?`',
          err: 'base_in_subject_q',
        },
        { id: 's4', t: 'to the server' },
        { id: 's5', t: 'last night' },
      ],
      tokens: [{ id: 't1', t: 'happened' }],
      accept: [
        { a: 'What happened to the server last night', o: 'correct_target' },
        { a: 'What happened to the server', o: 'valid_alternative', note: 'גם נכון, בלי `last night`.' },
        { a: 'What happened last night', o: 'valid_alternative', note: 'גם נכון, בלי `to the server` — מההקשר ברור על מה מדובר.' },
        {
          a: 'Last night, what happened to the server',
          o: 'valid_alternative',
          note: 'גם נכון: `last night` בתחילת השאלה.',
        },
      ],
      wrong: [
        {
          a: 'What did happen to the server last night',
          as: 'form_error',
          err: 'did_in_subject_q',
          fb: '`what` הוא הנושא כאן — מה שקרה — ולכן אין `did`: `What happened to the server last night?`',
        },
      ],
      rules: [
        {
          has: ['did happened'],
          as: 'form_error',
          err: 'did_v2',
          fb: 'כאן לא צריך `did` בכלל, כי `what` הוא הנושא: `What happened to the server last night?`',
        },
        {
          has: ['did happen'],
          as: 'form_error',
          err: 'did_in_subject_q',
          fb: '`what` הוא הנושא כאן — מה שקרה — ולכן אין `did`: `What happened…?`',
        },
        {
          has: ['what happen'],
          as: 'form_error',
          err: 'base_in_subject_q',
          fb: 'בלי `did` הפועל בעבר: `What happened…?`',
        },
      ],
      end: '?',
    },
    {
      id: 'S09-05',
      v: 2,
      skill: 'S09',
      unit: 'S09',
      sub: 'object_question',
      type: 'assemble',
      role: 'practice',
      stage: 2,
      ctx: 'daily.family',
      fam: 'S09.what-did-you-do-weekend',
      goal: 'לשאול חבר מה הוא עשה בסוף השבוע',
      instr: 'בנה את השאלה באנגלית. לא חייבים להשתמש בכל המילים.',
      sitHe: 'תום, חבר שלך, מספר שהיה לו סוף שבוע מצוין. אתה רוצה לדעת מה הוא עשה.',
      hint: 'תום עשה משהו, ואתה שואל מה. מי הנושא כאן?',
      explain: 'הנושא הוא `you`, ו-`what` הוא מה שהוא עשה, ולכן `did` + `you` + פועל בסיס: `What did you do last weekend?`',
      deep: 'יש כאן שני `do`: `did` הוא פועל העזר, ו-`do` הוא הפועל עצמו ("לעשות"). אי אפשר לוותר על אף אחד מהם: `What did you do?`. `What happened last weekend?` שואל מה קרה — לא מה הוא עשה.',
      tokens: [
        { id: 't1', t: 'what' },
        { id: 't2', t: 'did' },
        { id: 't3', t: 'you' },
        { id: 't4', t: 'do' },
        { id: 't5', t: 'last weekend' },
        {
          id: 't6',
          t: 'happened',
          why: '`What happened?` שואל מה קרה, בלי קשר למה שתום עשה. כאן: `What did you do…?`',
          err: 'subject_for_object',
          as: 'meaning_mismatch',
        },
        {
          id: 't7',
          t: 'done',
          why: '`done` היא צורת V3 (כמו ב-`have done`). אחרי `did` בא פועל בסיס: `did you do`.',
          err: 'did_v3',
        },
      ],
      accept: [
        { a: 'What did you do last weekend', o: 'correct_target' },
        {
          a: 'What did you do',
          o: 'valid_alternative',
          note: 'גם נכון וטבעי: מההקשר ברור שמדובר בסוף השבוע.',
        },
        {
          a: 'Last weekend, what did you do',
          o: 'valid_alternative',
          note: 'גם נכון: `last weekend` בתחילת השאלה.',
        },
      ],
      rules: [
        {
          has: ['did', 'happened'],
          as: 'form_error',
          err: 'did_v2',
          fb: '`What happened?` בא בלי `did`. וכאן שואלים מה תום עשה: `What did you do last weekend?`',
        },
        {
          has: ['happened', 'you'],
          as: 'form_error',
          err: 'word_order',
          fb: '`What happened?` — מה קרה; `What did you do?` — מה עשית. כאן: `What did you do last weekend?`',
        },
        {
          has: ['did you'],
          lacks: ['do', 'done'],
          as: 'form_error',
          err: 'missing_main_verb',
          fb: 'חסר הפועל עצמו: `did` הוא פועל העזר, ו-`do` הוא "לעשות" — `What did you do last weekend?`',
        },
        {
          starts: 'what you',
          as: 'form_error',
          err: 'missing_do',
          fb: 'בשאלה על מה שהוא עשה, פועל העזר בא לפני הנושא: `What did you do last weekend?`',
        },
      ],
      end: '?',
    },
    {
      id: 'S09-06',
      v: 1,
      skill: 'S09',
      unit: 'S09',
      sub: 'subject_question',
      type: 'assemble',
      role: 'practice',
      stage: 2,
      ctx: 'daily.health',
      fam: 'S09.which-team-won',
      goal: 'לשאול חבר איזו קבוצה ניצחה',
      instr: 'קרא את הסיטואציה ובנה את השאלה באנגלית. לא חייבים להשתמש בכל המילים.',
      sitEn:
        "You missed last night's basketball game between Maccabi and Hapoel. Your friend watched it. Ask him about the result.",
      trHe: 'פספסת אתמול בערב את משחק הכדורסל בין מכבי להפועל. חבר שלך ראה אותו. שאל אותו על התוצאה.',
      hint: 'איזו קבוצה עשתה את הפעולה (ניצחה)? אז היא הנושא — בלי `did`.',
      explain: '`which team` הוא הנושא — מי שניצח — ולכן בלי `did`, והפועל בעבר: `Which team won last night?`',
      deep: 'המשפט הרגיל: `One of the teams won`. בשאלה `which team` בא במקום הנושא, והסדר נשאר: `Which team won?`. `Which team did you support?` שואל את מי אתה אהדת — שם `you` הוא הנושא, ולכן צריך `did`.',
      tokens: [
        { id: 't1', t: 'which team' },
        { id: 't2', t: 'won' },
        { id: 't3', t: 'last night' },
        {
          id: 't4',
          t: 'did',
          why: 'כש-`which team` הוא מי שניצח (הנושא), אין `did`: `Which team won?`',
          err: 'did_in_subject_q',
        },
        {
          id: 't5',
          t: 'win',
          why: '`win` (בסיס) בא אחרי `did`. כש-`which team` הוא הנושא, הפועל בעבר: `Which team won?`',
          err: 'base_in_subject_q',
        },
        {
          id: 't6',
          t: 'you',
          why: '`you` נכנס לשאלה רק אם שואלים על מה שאתה עשית (למשל את מי אהדת). כאן שואלים מי ניצח: `Which team won?`',
          err: 'object_for_subject',
          as: 'meaning_mismatch',
        },
        {
          id: 't7',
          t: 'support',
          why: '`support` מתאים לשאלה את מי אהדת (`Which team did you support?`) — לא לשאלה מי ניצח.',
          err: 'object_for_subject',
          as: 'meaning_mismatch',
        },
      ],
      accept: [
        { a: 'Which team won last night', o: 'correct_target' },
        { a: 'Which team won', o: 'valid_alternative', note: 'גם נכון, בלי `last night`.' },
        {
          a: 'Last night, which team won',
          o: 'valid_alternative',
          note: 'גם נכון: `last night` בתחילת השאלה.',
        },
      ],
      wrong: [
        {
          a: 'Which team did you support last night',
          as: 'meaning_mismatch',
          err: 'object_for_subject',
          fb: 'המשפט תקין, אבל הוא שואל איזו קבוצה אתה אהדת. כאן רוצים לדעת מי ניצח: `Which team won last night?`',
        },
        {
          a: 'Which team did you support',
          as: 'meaning_mismatch',
          err: 'object_for_subject',
          fb: 'המשפט תקין, אבל הוא שואל איזו קבוצה אתה אהדת. כאן רוצים לדעת מי ניצח: `Which team won last night?`',
        },
      ],
      rules: [
        {
          has: ['which team did win'],
          as: 'form_error',
          err: 'did_in_subject_q',
          fb: 'כש-`which team` הוא מי שניצח, לא מוסיפים `did`: `Which team won last night?` (`did win` מתאים רק בהדגשה מיוחדת.)',
        },
        {
          has: ['did', 'won'],
          as: 'form_error',
          err: 'did_v2',
          fb: 'אחרי `did` בא פועל בסיס — ובשאלה הזאת בכלל אין `did`: `Which team won last night?`',
        },
      ],
      end: '?',
    },
    {
      id: 'S09-07',
      v: 1,
      skill: 'S09',
      unit: 'S09',
      sub: 'subject_question',
      type: 'transform',
      role: 'practice',
      stage: 1,
      ctx: 'daily.home',
      fam: 'S09.who-left-door-open',
      goal: 'לשאול מי השאיר את הדלת פתוחה',
      instr: 'הפוך את המשפט לשאלה עם `who` על מי שעשה את הפעולה.',
      sitHe: 'דלת הכניסה לבניין נשארה פתוחה כל הלילה. אתה רוצה לדעת מי השאיר אותה פתוחה.',
      target: 'שאלה עם `who` על מי שעשה את הפעולה',
      fromLabel: 'משפט',
      toLabel: 'שאלה עם `who`',
      scaffold: ['Who', 'V (past)', '…'],
      hint: '`who` בא במקום `someone`, והשאר נשאר כמו שהוא.',
      explain: '`who` מחליף את `someone` — הנושא — ולכן הסדר לא משתנה ואין `did`: `Who left the door open?`',
      deep: 'בשאלת נושא לא מוסיפים פועל עזר: `Someone left the door open` ← `Who left the door open?`. `Did someone leave the door open?` היא שאלה אחרת — שאלת כן/לא: האם מישהו השאיר אותה פתוחה.',
      source: [
        {
          id: 's1',
          t: 'someone',
          why: '`who` בא במקום `someone`: `Who left the door open?`',
          err: 'subject_not_replaced',
        },
        { id: 's2', t: 'left' },
        { id: 's3', t: 'the door' },
        { id: 's4', t: 'open' },
      ],
      sourceEnd: '.',
      tokens: [
        { id: 't1', t: 'who' },
        {
          id: 't2',
          t: 'did',
          why: 'כש-`who` הוא מי שעשה את הפעולה, אין `did`: `Who left the door open?`',
          err: 'did_in_subject_q',
        },
        {
          id: 't3',
          t: 'leave',
          why: '`leave` (בסיס) בא אחרי `did`. בשאלה על הנושא הפועל בעבר: `Who left…?`',
          err: 'base_in_subject_q',
        },
      ],
      accept: [{ a: 'Who left the door open', o: 'correct_target' }],
      wrong: [
        {
          a: 'Someone left the door open',
          as: 'target_not_used',
          err: 'not_transformed',
          fb: 'זה המשפט המקורי. התבקשת להפוך אותו לשאלה עם `who`: `Who left the door open?`',
        },
        {
          a: 'Did someone leave the door open',
          as: 'target_not_used',
          err: 'yes_no_not_who',
          fb: 'זו שאלת כן/לא תקינה — "האם מישהו השאיר אותה פתוחה?". התבקשה שאלה עם `who`, על מי שהשאיר: `Who left the door open?`',
        },
      ],
      rules: [
        {
          has: ['who did leave'],
          as: 'form_error',
          err: 'did_in_subject_q',
          fb: 'כש-`who` הוא מי שהשאיר, לא מוסיפים `did`: `Who left the door open?`',
        },
        {
          has: ['did', 'left'],
          as: 'form_error',
          err: 'did_v2',
          fb: 'אחרי `did` בא פועל בסיס. וכאן התבקשה שאלה עם `who` על מי שהשאיר — בלי `did`: `Who left the door open?`',
        },
      ],
      end: '?',
    },
    {
      id: 'S09-08',
      v: 1,
      skill: 'S09',
      unit: 'S09',
      sub: 'subject_question',
      type: 'correct',
      role: 'practice',
      stage: 2,
      ctx: 'work.software',
      fam: 'S09.who-fixed-printer',
      goal: 'לשאול מי תיקן את המדפסת',
      instr: CORRECT_INSTR,
      sitHe: 'המדפסת במשרד הייתה מקולקלת כל השבוע, והבוקר היא פתאום עובדת. אתה שואל עמית מי תיקן אותה.',
      hint: 'מי עשה את הפעולה? בדוק אם צריך כאן פועל עזר.',
      explain: 'המשפט תקין: `who` הוא מי שתיקן — הנושא — ולכן אין `did`, והפועל בעבר: `Who fixed the printer?`',
      deep: 'המשפט הרגיל: `Someone fixed the printer`. בשאלה `who` בא במקום `someone` והשאר לא משתנה. יש נטייה להוסיף `did` כי זו שאלה על העבר — אבל כש-`who` הוא הנושא, אין צורך בפועל עזר.',
      source: [
        { id: 's1', t: 'who' },
        { id: 's2', t: 'fixed' },
        { id: 's3', t: 'the printer' },
      ],
      tokens: [
        {
          id: 't1',
          t: 'did',
          why: 'כש-`who` הוא מי שתיקן (הנושא), אין `did`: `Who fixed the printer?`',
          err: 'did_in_subject_q',
        },
        {
          id: 't2',
          t: 'fix',
          why: '`fix` (בסיס) בא אחרי `did`. בשאלה על הנושא הפועל בעבר: `Who fixed…?`',
          err: 'base_in_subject_q',
        },
      ],
      accept: [{ a: 'Who fixed the printer', o: 'correct_target' }],
      rules: [
        {
          has: ['who did fix'],
          as: 'form_error',
          err: 'did_in_subject_q',
          fb: 'כש-`who` הוא מי שתיקן, לא מוסיפים `did`: `Who fixed the printer?` (`Who did fix it?` מתאים רק בהדגשה מיוחדת.)',
        },
        {
          has: ['did', 'fixed'],
          as: 'form_error',
          err: 'did_v2',
          fb: 'אחרי `did` בא פועל בסיס — ובשאלה על הנושא אין `did` בכלל: `Who fixed the printer?`',
        },
      ],
      end: '?',
    },
    {
      id: 'S09-D1',
      v: 1,
      skill: 'S09',
      unit: 'S09',
      sub: 'dialogue',
      type: 'dialogue',
      role: 'practice',
      stage: 2,
      ctx: 'work.job',
      fam: 'S09.dialogue-farewell-party',
      goal: 'לברר מי עשה מה במסיבה במשרד',
      instr: 'ענה לליאור בכל תור.',
      partnerName: 'Lior',
      setupHe: 'ליאור, עמית לעבודה, מספר לך על מסיבת הפרידה של אתמול במשרד, שבה לא היית.',
      hint: 'בתור הראשון שואלים מי עשה את הפעולה; בתור השני — את מי היא הזמינה.',
      explain: 'מי הזמין את העוגה — `who` הוא הנושא, בלי `did`. את מי היא הזמינה — `who` הוא המושא: `did` + `she` + פועל בסיס.',
      turns: [
        {
          partner: {
            en: 'The party was great. Someone ordered a huge chocolate cake!',
            he: 'המסיבה הייתה מעולה. מישהו הזמין עוגת שוקולד ענקית.',
          },
          sub: 'subject_question',
          instr: 'שאל אותו מי הזמין את העוגה.',
          hint: 'מישהו עשה את הפעולה — `who` הוא הנושא, ולכן בלי `did`.',
          explain: '`who` הוא מי שהזמין: `Who ordered the cake?` — בלי `did`, והפועל בעבר.',
          build: {
            tokens: [
              { id: 't1', t: 'who' },
              { id: 't2', t: 'ordered' },
              { id: 't3', t: 'the cake' },
              {
                id: 't4',
                t: 'did',
                why: 'כש-`who` הוא מי שהזמין (הנושא), אין `did`: `Who ordered the cake?`',
                err: 'did_in_subject_q',
              },
              {
                id: 't5',
                t: 'order',
                why: '`order` (בסיס) בא אחרי `did`. כש-`who` הוא הנושא, הפועל בעבר: `Who ordered…?`',
                err: 'base_in_subject_q',
              },
            ],
            accept: [{ a: 'Who ordered the cake', o: 'correct_target' }],
            rules: [
              {
                has: ['who did order'],
                as: 'form_error',
                err: 'did_in_subject_q',
                fb: 'כש-`who` הוא מי שהזמין, לא מוסיפים `did`: `Who ordered the cake?`',
              },
              {
                has: ['did', 'ordered'],
                as: 'form_error',
                err: 'did_v2',
                fb: 'אחרי `did` בא פועל בסיס — ובשאלה על הנושא אין `did` בכלל: `Who ordered the cake?`',
              },
            ],
            end: '?',
          },
        },
        {
          partner: {
            en: 'Shira ordered it. She also invited some people from the other branch.',
            he: 'שירה הזמינה אותה. היא גם הזמינה כמה אנשים מהסניף השני.',
          },
          sub: 'object_question',
          instr: 'שאל אותו את מי היא הזמינה.',
          hint: 'שירה עשתה את הפעולה; אתה שואל על מי שקיבל אותה. צריך `did` לפני הנושא.',
          explain: '`who` הוא מי שהוזמן, והנושא הוא `she`: `Who did she invite?` — `did` + פועל בסיס.',
          build: {
            tokens: [
              { id: 't1', t: 'who' },
              { id: 't2', t: 'did' },
              { id: 't3', t: 'she' },
              { id: 't4', t: 'invite' },
              {
                id: 't5',
                t: 'invited',
                why: '`invited` מתאים לשאלה על מי שהזמין (`Who invited her?`). כאן היא זו שהזמינה, ולכן `did` + פועל בסיס: `Who did she invite?`',
                err: 'object_q_v2',
              },
              {
                id: 't6',
                t: 'her',
                why: 'שאלה עם `her` שואלת מי הזמין את שירה. כאן רוצים לדעת את מי היא הזמינה: `Who did she invite?`',
                err: 'subject_for_object',
                as: 'meaning_mismatch',
              },
            ],
            accept: [{ a: 'Who did she invite', o: 'correct_target' }],
            wrong: [
              {
                a: 'Who invited her',
                as: 'meaning_mismatch',
                err: 'subject_for_object',
                fb: 'המשפט תקין, אבל הוא שואל מי הזמין את שירה. כאן היא הזמינה אחרים: `Who did she invite?`',
              },
            ],
            rules: [
              {
                has: ['did she invited'],
                as: 'form_error',
                err: 'did_v2',
                fb: 'אחרי `did` בא פועל בסיס: `Who did she invite?`',
              },
              {
                has: ['did her'],
                as: 'form_error',
                err: 'object_pronoun_subject',
                fb: 'אחרי `did` בא הנושא, ולכן `she` ולא `her`: `Who did she invite?`',
              },
              {
                starts: 'who she',
                as: 'form_error',
                err: 'missing_do',
                fb: 'בשאלה על מי שקיבל את הפעולה, `did` בא לפני הנושא: `Who did she invite?`',
              },
            ],
            end: '?',
          },
        },
      ],
      closing: { en: 'A few people from the design team, I think.', he: 'כמה אנשים מצוות העיצוב, נדמה לי.' },
    },
    {
      id: 'S09-09',
      v: 1,
      skill: 'S09',
      unit: 'S09',
      sub: 'contrast',
      type: 'assemble',
      role: 'practice',
      stage: 3,
      ctx: 'work.job',
      fam: 'S09.who-did-maya-call',
      goal: 'לשאול למי מאיה התקשרה',
      instr: 'קרא את הסיטואציה ובנה את השאלה באנגלית. לא חייבים להשתמש בכל המילים.',
      sitEn:
        "This morning Maya spent an hour on the phone. She called someone about the new contract, but you don't know who. Ask a colleague.",
      trHe: 'הבוקר מאיה דיברה שעה בטלפון. היא התקשרה למישהו בעניין החוזה החדש, ואתה לא יודע למי. שאל עמית.',
      hint: 'מאיה עשתה את הפעולה (התקשרה). אתה שואל על מי שקיבל אותה.',
      explain: 'מאיה היא הנושא, ו-`who` הוא מי שקיבל את השיחה: `Who did Maya call this morning?`',
      deep: '`Who called Maya?` — מישהו התקשר אל מאיה (`who` = הנושא). `Who did Maya call?` — מאיה התקשרה למישהו (`who` = המושא). אותן מילים, כיוון הפוך — ו-`did` הוא מה שמסמן את ההבדל.',
      tokens: [
        { id: 't1', t: 'who' },
        { id: 't2', t: 'did' },
        { id: 't3', t: 'Maya' },
        { id: 't4', t: 'call' },
        {
          id: 't5',
          t: 'called',
          why: '`called` מתאים לשאלה על מי שהתקשר (`Who called Maya?`). כאן מאיה התקשרה, ולכן `did` + פועל בסיס: `Who did Maya call?`',
          err: 'object_q_v2',
        },
        { id: 't6', t: 'this morning' },
      ],
      accept: [
        { a: 'Who did Maya call this morning', o: 'correct_target' },
        { a: 'Who did Maya call', o: 'valid_alternative', note: 'גם נכון, בלי `this morning`.' },
        {
          a: 'This morning, who did Maya call',
          o: 'valid_alternative',
          note: 'גם נכון: `this morning` בתחילת השאלה.',
        },
      ],
      wrong: [
        {
          a: 'Who called Maya this morning',
          as: 'meaning_mismatch',
          err: 'subject_for_object',
          fb: 'המשפט תקין, אבל הוא שואל מי התקשר אל מאיה. כאן מאיה היא שהתקשרה: `Who did Maya call this morning?`',
        },
        {
          a: 'Who called Maya',
          as: 'meaning_mismatch',
          err: 'subject_for_object',
          fb: 'המשפט תקין, אבל הוא שואל מי התקשר אל מאיה. כאן מאיה היא שהתקשרה: `Who did Maya call?`',
        },
      ],
      rules: [
        {
          has: ['did maya called'],
          as: 'form_error',
          err: 'did_v2',
          fb: 'אחרי `did` בא פועל בסיס: `Who did Maya call…?`',
        },
        {
          has: ['who did call'],
          as: 'meaning_mismatch',
          err: 'subject_for_object',
          fb: '`Who did call Maya?` שואל (בהדגשה) מי התקשר אל מאיה — לא למי היא התקשרה. כאן: `Who did Maya call this morning?`',
        },
        {
          starts: 'who maya',
          as: 'form_error',
          err: 'missing_do',
          fb: 'בשאלה על מי שקיבל את הפעולה, `did` בא לפני הנושא: `Who did Maya call…?`',
        },
      ],
      end: '?',
    },
    {
      id: 'S09-10',
      v: 2,
      skill: 'S09',
      unit: 'S09',
      sub: 'object_question',
      type: 'assemble',
      role: 'practice',
      stage: 2,
      ctx: 'work.municipality',
      fam: 'S09.which-proposal-approve',
      goal: 'לשאול איזו הצעה הוועדה אישרה',
      instr: 'בנה את השאלה באנגלית. לא חייבים להשתמש בכל המילים.',
      sitHe: 'שתי חברות הגישו הצעות לשיפוץ הפארק העירוני. ועדת העירייה כבר אישרה אחת מהן. אתה שואל את מזכירת הוועדה איזו.',
      hint: 'הוועדה עשתה את הפעולה (אישרה). אתה שואל על ההצעה — מה שאושר.',
      explain: 'הוועדה היא הנושא, ו-`which proposal` הוא מה שאושר, ולכן `did` לפני הנושא: `Which proposal did the committee approve?`',
      deep: 'בלי `did` הכיוון מתהפך: `Which proposal approved the committee?` נשמע כאילו ההצעה אישרה את הוועדה. בשאלה על המושא: `did` + הנושא + פועל בסיס.',
      tokens: [
        { id: 't1', t: 'which proposal' },
        { id: 't2', t: 'did' },
        { id: 't3', t: 'the committee' },
        { id: 't4', t: 'approve' },
        {
          id: 't5',
          t: 'approved',
          why: '`approved` בלי `did` הופך את `which proposal` לנושא — כאילו ההצעה אישרה. כאן הוועדה אישרה: `Which proposal did the committee approve?`',
          err: 'object_q_v2',
        },
      ],
      accept: [{ a: 'Which proposal did the committee approve', o: 'correct_target' }],
      wrong: [
        {
          a: 'Which proposal approved the committee',
          as: 'meaning_mismatch',
          err: 'subject_for_object',
          fb: 'בלי `did`, `which proposal` הופך לנושא — "איזו הצעה אישרה את הוועדה". כאן הוועדה אישרה: `Which proposal did the committee approve?`',
        },
      ],
      rules: [
        {
          has: ['did the committee approved'],
          as: 'form_error',
          err: 'did_v2',
          fb: 'אחרי `did` בא פועל בסיס: `did the committee approve`.',
        },
        {
          starts: 'which proposal the committee',
          as: 'form_error',
          err: 'missing_do',
          fb: 'בשאלה על מה שקיבל את הפעולה, `did` בא לפני הנושא: `Which proposal did the committee approve?`',
        },
        {
          has: ['did approve'],
          as: 'meaning_mismatch',
          err: 'subject_for_object',
          fb: '`Which proposal did approve the committee?` שואל (בהדגשה) איזו הצעה אישרה את הוועדה — כיוון הפוך. כאן: `Which proposal did the committee approve?`',
        },
      ],
      end: '?',
    },
    {
      id: 'S09-11',
      v: 2,
      skill: 'S09',
      unit: 'S09',
      sub: 'object_question',
      type: 'correct',
      role: 'practice',
      stage: 2,
      ctx: 'work.report',
      fam: 'S09.what-tell-manager',
      goal: 'לשאול עמיתה מה היא אמרה למנהל על הדוח',
      instr: CORRECT_INSTR,
      sitHe: 'אלה, עמיתה שלך, נפגשה עם המנהל כדי לדבר על העיכוב בדוח. אתה שואל אותה מה היא אמרה לו.',
      hint: 'אלה עשתה את הפעולה (אמרה), ואתה שואל מה היא אמרה. בדוק מה בא לפני הנושא.',
      explain: '`what` הוא מה שנאמר, והנושא הוא `you`, ולכן `did` לפני הנושא ופועל בסיס: `What did you tell the manager about the report?`',
      deep: 'בלי `did` זו לא שאלה תקינה: `what you told…` הוא חלק ממשפט (`I know what you told him`), לא שאלה. בשאלה על המושא: `did` + הנושא + פועל בסיס — `tell`, לא `told`.',
      source: [
        { id: 's1', t: 'what' },
        { id: 's2', t: 'you' },
        {
          id: 's3',
          t: 'told',
          why: '`told` בא רק בלי פועל עזר. בשאלה על מה שנאמר צריך `did` + פועל בסיס: `What did you tell…?`',
          err: 'did_v2',
        },
        { id: 's4', t: 'the manager' },
        { id: 's5', t: 'about the report' },
      ],
      tokens: [
        { id: 't1', t: 'did' },
        { id: 't2', t: 'tell' },
      ],
      accept: [{ a: 'What did you tell the manager about the report', o: 'correct_target' }],
      wrong: [
        {
          a: 'What you told the manager about the report',
          as: 'form_error',
          err: 'missing_do',
          fb: 'חסר `did`: `what` הוא מה שנאמר, ולכן פועל העזר בא לפני הנושא, ואחריו פועל בסיס — `What did you tell the manager about the report?`',
        },
        {
          a: 'What told the manager about the report',
          as: 'meaning_mismatch',
          err: 'subject_for_object',
          fb: 'בלי `did` ובלי `you`, `what` הופך לנושא — "מה סיפר למנהל על הדוח". כאן אלה היא שסיפרה, ואתה שואל מה: `What did you tell the manager about the report?`',
        },
        {
          a: 'You told the manager about the report',
          as: 'meaning_mismatch',
          err: 'yes_no_not_wh',
          fb: 'בטון של שאלה זה רק מוודא שסיפרת למנהל. כדי לשאול מה אמרת: `What did you tell the manager about the report?`',
        },
        {
          a: 'Did you tell the manager about the report',
          as: 'meaning_mismatch',
          err: 'yes_no_not_wh',
          fb: 'המשפט תקין, אבל הוא שואל אם היא סיפרה למנהל על הדוח — לא מה היא אמרה לו: `What did you tell the manager about the report?`',
        },
      ],
      rules: [
        {
          has: ['did you told'],
          as: 'form_error',
          err: 'did_v2',
          fb: 'אחרי `did` בא פועל בסיס: `did you tell`.',
        },
        {
          starts: 'what you',
          as: 'form_error',
          err: 'missing_do',
          fb: 'חסר `did` לפני הנושא: `What did you tell the manager…?`',
        },
      ],
      end: '?',
    },
    {
      id: 'S09-C1',
      v: 1,
      skill: 'S09',
      unit: 'S09',
      sub: 'contrast',
      type: 'discriminate',
      role: 'check',
      stage: 3,
      ctx: 'daily.shopping',
      fam: 'S09.wallet-give-choice',
      goal: 'לשאול שכן למי הוא מסר ארנק שמצא',
      instr: 'בחר את השאלה שמתאימה למצב.',
      sitHe: 'רון, השכן שלך, מצא ארנק בסופרמרקט ומסר אותו למישהו. אתה שואל את רון למי הוא מסר אותו.',
      hint: 'רון עשה את הפעולה (מסר). אתה שואל על מי שקיבל.',
      explain: 'רון — `you` — הוא הנושא, ו-`who` הוא מי שקיבל את הארנק, ולכן `did` + `you` + פועל בסיס, ו-`to` בסוף: `Who did you give the wallet to?`',
      multi: false,
      options: [
        {
          id: 'a',
          en: 'Who did you give the wallet to?',
          v: 'fits',
          why: 'שאלה על מי שקיבל: `did` + הנושא + פועל בסיס, ו-`to` בסוף.',
        },
        {
          id: 'b',
          en: 'Who gave you the wallet?',
          v: 'other_meaning',
          why: 'תקין, אבל שואל מי נתן לרון את הארנק — לא למי רון מסר אותו.',
          err: 'subject_for_object',
        },
        {
          id: 'c',
          en: 'Who did you gave the wallet to?',
          v: 'ungrammatical',
          why: 'אחרי `did` בא פועל בסיס: `give`, לא `gave`.',
          err: 'did_v2',
        },
        {
          id: 'd',
          en: 'Who you gave the wallet to?',
          v: 'ungrammatical',
          why: 'חסר `did`: בשאלה על מי שקיבל את הפעולה, פועל העזר בא לפני הנושא.',
          err: 'missing_do',
        },
      ],
    },
    {
      id: 'S09-C2',
      v: 2,
      skill: 'S09',
      unit: 'S09',
      sub: 'object_question',
      type: 'assemble',
      role: 'check',
      stage: 3,
      ctx: 'daily.learning',
      fam: 'S09.which-student-teacher-choose',
      goal: 'לשאול איזה תלמיד המורה בחרה',
      instr: 'קרא את הסיטואציה ובנה את השאלה באנגלית. לא חייבים להשתמש בכל המילים.',
      sitEn:
        "Your English teacher had to pick one student to represent the class in a competition. You missed the lesson. Ask a classmate about the teacher's choice.",
      trHe: 'המורה לאנגלית הייתה צריכה לבחור תלמיד אחד שייצג את הכיתה בתחרות. פספסת את השיעור. שאל חבר לכיתה במי המורה בחרה.',
      hint: 'המורה עשתה את הפעולה (בחרה). אתה שואל על התלמיד — מי שנבחר.',
      explain: 'המורה היא הנושא, ו-`which student` הוא מי שנבחר, ולכן `did` לפני הנושא: `Which student did the teacher choose?`',
      deep: 'בלי `did` הכיוון מתהפך: `Which student chose the teacher?` שואל איזה תלמיד בחר את המורה. `did` + הנושא + פועל בסיס מסמנים שהשאלה היא על מי שקיבל את הפעולה.',
      tokens: [
        { id: 't1', t: 'which student' },
        { id: 't2', t: 'did' },
        { id: 't3', t: 'the teacher' },
        { id: 't4', t: 'choose' },
        {
          id: 't5',
          t: 'chose',
          why: '`chose` בלי `did` הופך את `which student` לנושא — מי שבחר. כאן המורה בחרה: `Which student did the teacher choose?`',
          err: 'object_q_v2',
        },
      ],
      accept: [{ a: 'Which student did the teacher choose', o: 'correct_target' }],
      wrong: [
        {
          a: 'Which student chose the teacher',
          as: 'meaning_mismatch',
          err: 'subject_for_object',
          fb: 'המשפט תקין, אבל הוא שואל איזה תלמיד בחר את המורה. כאן המורה בחרה: `Which student did the teacher choose?`',
        },
      ],
      rules: [
        {
          has: ['did the teacher chose'],
          as: 'form_error',
          err: 'did_v2',
          fb: 'אחרי `did` בא פועל בסיס: `did the teacher choose`.',
        },
        {
          starts: 'which student the teacher',
          as: 'form_error',
          err: 'missing_do',
          fb: 'בשאלה על מי שנבחר, `did` בא לפני הנושא: `Which student did the teacher choose?`',
        },
        {
          has: ['did choose'],
          as: 'meaning_mismatch',
          err: 'subject_for_object',
          fb: '`Which student did choose the teacher?` שואל (בהדגשה) איזה תלמיד בחר את המורה — כיוון הפוך. כאן: `Which student did the teacher choose?`',
        },
      ],
      end: '?',
    },
  ],
};
