import type { SkillPack } from '../schema';

/**
 * S10 MODAL_BASE — must / can / could / should / would / might / will + base verb.
 * Contrast: have to / need to / ought to / be able to keep their `to`.
 */

const INSTR_CORRECT = 'אם יש טעות — גע במילה או ברווח ובחר תיקון. אם המשפט תקין, בחר "אין צורך בתיקון".';

export const S10: SkillPack = {
  skill: 'S10',
  lessons: [
    {
      unit: 'S10',
      title: 'אחרי פועל מודאלי: צורת בסיס',
      short:
        'אחרי `must`, `can`, `could`, `should`, `would`, `might`, `will` בא הפועל בצורת בסיס — בלי `to`, בלי s ובלי צורת עבר: `I must go`, `she can speak`, `we would visit`. לעומת זאת ב-`have to`, `need to`, `ought to`, `be able to` ה-`to` הוא חלק מהצירוף ונשאר: `I have to go`.',
      chain: ['must / can / should / would…', 'V (base)'],
      examples: [
        { en: 'I must leave early today.', he: 'אני חייב לצאת מוקדם היום.' },
        { en: 'She can explain the new system.', he: 'היא יכולה להסביר את המערכת החדשה.' },
        { en: 'They said they would call back.', he: 'הם אמרו שיחזרו אלינו.' },
        { en: 'You should update the file.', he: 'כדאי שתעדכן את הקובץ.' },
      ],
      contrast: {
        a: { en: 'I must go.', he: 'אני חייב ללכת.' },
        b: { en: 'I have to go.', he: 'אני חייב / צריך ללכת.' },
        note: 'שני המשפטים נכונים. `must` הוא פועל מודאלי, ולכן הפועל בא מיד אחריו. ב-`have to` המילה `to` היא חלק מהצירוף ונשארת. הטעות היא לערבב: `I must to go`.',
      },
      deep:
        '• הפעלים המודאליים: `can`, `could`, `may`, `might`, `must`, `shall`, `should`, `will`, `would`. אחריהם תמיד צורת בסיס: `can speak` (לא `speaks`), `would visit` (לא `visited`), `should send` (לא `sent`), `must go` (לא `to go`).\n' +
        '• המודאלי עצמו לא משתנה לפי הנושא ולא צריך `do`: `she can`, `he must`. שאלה: `Can she…?`; שלילה: `can\'t`, `must not`, `won\'t`.\n' +
        '• גם כשמדברים על העבר, אחרי `would` בא בסיס: `She said she would send it`. העבר כבר מסומן ב-`would` עצמו.\n' +
        '• לביקורת על משהו שלא נעשה בעבר יש מבנה נפרד: `You should have sent it` — וגם שם `have` היא צורת בסיס.\n' +
        '• `have to`, `need to`, `ought to`, `be able to` אינם מודאליים רגילים, וה-`to` שלהם נשאר: `I have to go`, `We need to talk`, `You ought to rest`, `I won\'t be able to come`. גם אחרי ה-`to` הזה בא פועל בסיס. (ל-`need` יש גם שימוש מודאלי רשמי, `You needn\'t worry`, אבל הרגיל הוא `need to`.)\n' +
        '• שני מודאליים לא באים ברצף: לא `will can`, אלא `will be able to`.\n' +
        '• בשלילה המשמעות נפרדת: `You mustn\'t tell him` — אסור לספר לו. `You don\'t have to tell him` — לא חייבים לספר לו (מותר, אם רוצים). באנגלית אמריקאית הקיצור `mustn\'t` פחות נפוץ; לאיסור אומרים גם `must not` או `can\'t`.',
      pitfalls: [
        '`I must to go` — אחרי `must` אין `to`: `I must go`.',
        '`She can speaks` — אחרי מודאלי אין s, גם עם `she`: `she can speak`.',
        '`We would visited`, `You should sent` — אחרי מודאלי אין צורת עבר: `would visit`, `should send`.',
        '`I have go` — ב-`have to` ה-`to` נשאר: `I have to go`.',
      ],
    },
  ],
  examples: {
    S10: [
      { en: 'Could you check the numbers before Monday?', he: 'תוכל לבדוק את המספרים לפני יום שני?' },
      { en: 'The results might change next week.', he: 'ייתכן שהתוצאות ישתנו בשבוע הבא.' },
      {
        en: 'We need to talk about the budget.',
        he: 'אנחנו צריכים לדבר על התקציב.',
        note: '`need to` — כמו `have to` — שומר על ה-`to`.',
      },
      {
        en: 'You ought to back up your files.',
        he: 'כדאי לך לגבות את הקבצים שלך.',
        note: '`ought to` קרוב במשמעות ל-`should`, אבל עם `to`.',
      },
    ],
  },
  items: [
    {
      id: 'S10-01',
      v: 1,
      skill: 'S10',
      unit: 'S10',
      sub: 'must',
      type: 'correct',
      role: 'practice',
      stage: 1,
      ctx: 'work.meeting',
      fam: 'S10.must-go-now',
      goal: 'לומר שאתה חייב לצאת מהפגישה עכשיו',
      instr: INSTR_CORRECT,
      sitHe: 'הפגישה מתארכת, ויש לך עוד פגישה בצד השני של העיר. אתה אומר לכולם שאתה חייב ללכת.',
      scaffold: ['must', 'V (base)'],
      hint: 'מה בא מיד אחרי `must`?',
      explain:
        'אחרי `must` בא פועל בסיס ישירות, בלי `to`: `I must go now`. גם `I have to go now` נכון — שם ה-`to` הוא חלק מ-`have to`.',
      deep: 'בעברית "חייב ללכת", ו"ללכת" מרגיש כמו `to go`. אבל `must`, `can`, `should`, `will` ודומיהם הם פעלים מודאליים, והפועל שאחריהם בא בלי `to`. ב-`have to`, `need to`, `ought to` ה-`to` שייך לצירוף עצמו, ולכן הוא נשאר.',
      source: [
        { id: 's1', t: 'I' },
        { id: 's2', t: 'must' },
        { id: 's3', t: 'to' },
        { id: 's4', t: 'go' },
        { id: 's5', t: 'now' },
      ],
      tokens: [
        { id: 't1', t: 'have' },
        {
          id: 't2',
          t: 'going',
          why: '`going` לא מתאים כאן: אחרי `must` — וגם אחרי `have to` — בא פועל בסיס: `go`.',
          err: 'modal_ing',
        },
      ],
      accept: [
        { a: 'I must go now', o: 'correct_target' },
        {
          a: 'I have to go now',
          o: 'valid_alternative',
          note: 'גם נכון. ב-`have to` ה-`to` הוא חלק מהצירוף, ולכן הוא נשאר. `I must go` ו-`I have to go` תקינים שניהם.',
        },
      ],
      wrong: [
        {
          a: 'I must to go now',
          as: 'form_error',
          err: 'modal_to',
          fb: 'אחרי `must` לא בא `to`: `I must go now`. ה-`to` נשאר רק בצירופים כמו `have to`: `I have to go now`.',
        },
      ],
      rules: [
        {
          has: ['must', 'to'],
          as: 'form_error',
          err: 'modal_to',
          fb: 'אחרי `must` בא פועל בסיס ישירות — בלי `to`, ובלי `have to` נוסף. בוחרים אחד: `I must go now` או `I have to go now`.',
        },
        {
          has: ['have go'],
          as: 'form_error',
          err: 'have_to_missing_to',
          fb: 'ב-`have to` ה-`to` נשאר: `I have to go now`. רק אחרי `must` (ושאר המודאליים) אין `to`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S10-02',
      v: 1,
      skill: 'S10',
      unit: 'S10',
      sub: 'can',
      type: 'assemble',
      role: 'practice',
      stage: 1,
      ctx: 'work.project',
      fam: 'S10.can-help-presentation',
      goal: 'להציע לעמית עזרה במצגת',
      instr: 'בנה את המשפט באנגלית. לא חייבים להשתמש בכל המילים.',
      promptHe: 'אני יכול לעזור לך עם המצגת.',
      sitHe: 'עמית מכין מצגת לישיבה של מחר ונראה לחוץ.',
      scaffold: ['can', 'V (base)'],
      hint: 'אחרי `can` — פועל בסיס, בלי שום מילה ביניהם.',
      explain: 'אחרי `can` בא פועל בסיס ישירות: `I can help you`. בעברית "יכול לעזור", אבל באנגלית אין `to` אחרי `can`.',
      tokens: [
        { id: 't1', t: 'I' },
        { id: 't2', t: 'can' },
        { id: 't3', t: 'help' },
        { id: 't4', t: 'you' },
        { id: 't5', t: 'with the presentation' },
        {
          id: 't6',
          t: 'to',
          why: 'אחרי `can` בא פועל בסיס ישירות, בלי `to`: `can help`.',
          err: 'modal_to',
        },
        {
          id: 't7',
          t: 'helping',
          why: 'אחרי `can` בא פועל בסיס: `help`, לא `helping`.',
          err: 'modal_ing',
        },
      ],
      accept: [
        { a: 'I can help you with the presentation', o: 'correct_target' },
        { a: 'I can help with the presentation', o: 'correct_target' },
        {
          a: 'Can I help you with the presentation',
          o: 'valid_alternative',
          note: 'גם נכון — הצעה בצורת שאלה. גם כאן אחרי `can` בא פועל בסיס: `Can I help…?`',
        },
        {
          a: 'Can I help with the presentation',
          o: 'valid_alternative',
          note: 'גם נכון — הצעה בצורת שאלה. גם כאן אחרי `can` בא פועל בסיס: `Can I help…?`',
        },
      ],
      rules: [
        {
          has: ['can to'],
          as: 'form_error',
          err: 'modal_to',
          fb: 'אחרי `can` לא בא `to`: `I can help you`. בעברית "יכול לעזור", אבל באנגלית `can` מתחבר ישירות לפועל.',
        },
      ],
      end: '.',
    },
    {
      id: 'S10-03',
      v: 2,
      skill: 'S10',
      unit: 'S10',
      sub: 'would',
      type: 'correct',
      role: 'practice',
      stage: 1,
      ctx: 'work.email',
      fam: 'S10.would-send-price-list',
      goal: 'לספר מה נציג הספק הבטיח לשלוח',
      instr: INSTR_CORRECT,
      sitHe: 'ביום חמישי דיברת עם נציג של ספק, והוא הבטיח לשלוח מחירון חדש. היום יום ראשון, ואתה מעדכן עמיתה.',
      scaffold: ['would', 'V (base)'],
      hint: 'העבר כבר מסומן ב-`said` וב-`would`. מה בא אחרי `would`?',
      explain:
        'אחרי `would` בא פועל בסיס — גם כשמדברים על העבר: `he would send`. העבר כבר מסומן ב-`said` וב-`would` עצמו.',
      deep: 'זו בדיוק הטעות `We would visited`: כשהסיפור בעבר, מתחשק לשים גם את הפועל בעבר. אבל `would` הוא צורת העבר של `will`, והוא לוקח פועל בסיס בדיוק כמו `will`: `He will send it` ← `He said he would send it`.',
      source: [
        { id: 's1', t: 'he' },
        { id: 's2', t: 'said' },
        { id: 's3', t: 'he' },
        { id: 's4', t: 'would' },
        {
          id: 's5',
          t: 'sent',
          why: 'אחרי `would` בא פועל בסיס: `send`, לא `sent` — גם כשהסיפור בעבר.',
          err: 'modal_past',
        },
        { id: 's6', t: 'the price list' },
      ],
      tokens: [
        { id: 't1', t: 'send' },
        {
          id: 't2',
          t: 'sends',
          why: '`sends` לא מתאים כאן: ההבטחה היא `he would send`, ואחרי `would` הפועל לא מקבל s.',
          err: 'modal_s',
        },
        { id: 't3', t: 'to', why: 'אחרי `would` בא פועל בסיס ישירות, בלי `to`: `would send`.', err: 'modal_to' },
      ],
      accept: [{ a: 'He said he would send the price list', o: 'correct_target' }],
      wrong: [
        {
          a: 'He said he would sent the price list',
          as: 'form_error',
          err: 'modal_past',
          fb: 'אחרי `would` בא פועל בסיס: `he would send`. העבר כבר מסומן ב-`said` וב-`would` — הפועל עצמו נשאר בסיס.',
        },
      ],
      rules: [
        {
          has: ['sent'],
          lacks: ['would'],
          as: 'meaning_mismatch',
          err: 'promise_as_fact',
          fb: '`He said he sent…` אומר שהוא כבר שלח. הוא רק הבטיח לשלוח: `He said he would send the price list`.',
        },
        {
          has: ['he sends'],
          lacks: ['would'],
          as: 'meaning_mismatch',
          err: 'promise_as_fact',
          fb: '`He said he sends…` נשמע כמו משהו שהוא עושה בקביעות. הוא רק הבטיח לשלוח: `He said he would send the price list`.',
        },
        {
          has: ['he send'],
          as: 'form_error',
          err: 'missing_modal',
          fb: 'חסר `would`: ההבטחה היא `he would send`. בלי `would` הפועל היה צריך להתאים לזמן ולנושא.',
        },
      ],
      end: '.',
    },
    {
      id: 'S10-04',
      v: 1,
      skill: 'S10',
      unit: 'S10',
      sub: 'should',
      type: 'correct',
      role: 'practice',
      stage: 2,
      ctx: 'work.report',
      fam: 'S10.should-send-report',
      goal: 'לייעץ לעמית לשלוח את הדוח היום',
      instr: INSTR_CORRECT,
      sitHe: 'עמית שואל אם לחכות עם הדוח לשבוע הבא. אתה חושב שעדיף לשלוח אותו כבר היום, לפני שהמנהלת יוצאת לחופשה.',
      hint: 'עצה להיום: `should` + איזו צורה של הפועל?',
      explain: 'עצה: `should` + פועל בסיס — `You should send the report today`. אחרי `should` אין צורת עבר.',
      deep: 'אחרי `should` לא באה צורת עבר. כשמבקרים משהו שלא נעשה בעבר, יש מבנה אחר: `You should have sent it yesterday` (צורת הבסיס `have` + V3). כאן זו עצה להיום, ולכן פשוט `should send`.',
      source: [
        { id: 's1', t: 'you' },
        { id: 's2', t: 'should' },
        {
          id: 's3',
          t: 'sent',
          why: 'אחרי `should` בא פועל בסיס: `send`, לא `sent`.',
          err: 'modal_past',
        },
        { id: 's4', t: 'the report' },
        { id: 's5', t: 'today' },
      ],
      tokens: [
        { id: 't1', t: 'send' },
        { id: 't2', t: 'to', why: 'אחרי `should` בא פועל בסיס ישירות, בלי `to`: `should send`.', err: 'modal_to' },
      ],
      accept: [{ a: 'You should send the report today', o: 'correct_target' }],
      wrong: [
        {
          a: 'You should sent the report today',
          as: 'form_error',
          err: 'modal_past',
          fb: 'אחרי `should` בא פועל בסיס: `You should send the report today`. (`should have sent` הוא מבנה אחר — ביקורת על משהו שלא נעשה בעבר.)',
        },
      ],
      rules: [
        {
          has: ['sent'],
          lacks: ['should'],
          as: 'meaning_mismatch',
          err: 'fact_for_advice',
          fb: '`You sent the report today` מספר מה קרה — זו לא עצה. עצה: `You should send the report today`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S10-05',
      v: 2,
      skill: 'S10',
      unit: 'S10',
      sub: 'can',
      type: 'assemble',
      role: 'practice',
      stage: 2,
      ctx: 'work.job',
      fam: 'S10.can-speak-spanish',
      goal: 'לספר למנהל מה עמיתה חדשה יכולה לעשות',
      instr: 'קרא את הסיטואציה ובנה משפט אחד באנגלית.',
      sitEn:
        'Your manager needs someone for calls with a partner company in Spain. Your new colleague speaks English, French and Spanish. Tell your manager about her.',
      trHe: 'המנהל שלך צריך מישהו לשיחות עם חברה שותפה בספרד. העמיתה החדשה שלך מדברת אנגלית, צרפתית וספרדית. ספר עליה למנהל.',
      target: 'יכולת: `can` + פועל',
      hint: 'עם `she` מתחשק להוסיף s — אבל אחרי `can` הפועל תמיד בצורת בסיס.',
      explain: 'אחרי `can` הפועל נשאר בצורת בסיס גם עם `she`: `She can speak Spanish`. ה-s של `she speaks` נעלמת כשיש `can`.',
      deep: 'המודאלי "לוקח" את ההתאמה לנושא: `she can` (ולא `she cans`), והפועל שאחריו נשאר בסיס. כך גם עם `will`, `must`, `should`, `might`: `she will speak`, `he must sign`, `it might rain`. על שפות אומרים באנגלית גם בפשטות `She speaks Spanish` — זה נכון וטבעי מאוד.',
      tokens: [
        { id: 't1', t: 'she' },
        { id: 't2', t: 'can' },
        { id: 't3', t: 'speak' },
        { id: 't4', t: 'speaks' },
        { id: 't5', t: 'Spanish' },
        { id: 't6', t: 'three languages' },
        { id: 't7', t: 'to', why: 'אחרי `can` בא פועל בסיס ישירות, בלי `to`: `can speak`.', err: 'modal_to' },
      ],
      accept: [
        { a: 'She can speak Spanish', o: 'correct_target' },
        { a: 'She can speak three languages', o: 'correct_target' },
        {
          a: 'She speaks Spanish',
          o: 'target_not_used',
          note: 'נכון וטבעי מאוד — `speaks` בלי `can`. התרגיל ביקש את המבנה עם `can`.',
        },
        {
          a: 'She speaks three languages',
          o: 'target_not_used',
          note: 'נכון וטבעי מאוד — `speaks` בלי `can`. התרגיל ביקש את המבנה עם `can`.',
        },
      ],
      rules: [
        {
          has: ['can speaks'],
          as: 'form_error',
          err: 'modal_s',
          fb: 'אחרי `can` הפועל לא מקבל s, גם עם `she`: `She can speak…`. (בלי `can`: `She speaks…`.)',
        },
        {
          starts: 'can she speaks',
          as: 'form_error',
          err: 'modal_s',
          fb: 'אחרי `can` הפועל לא מקבל s, גם בשאלה: `Can she speak…?` — אבל כאן התבקשת לספר, לא לשאול: `She can speak Spanish`.',
        },
        {
          has: ['she speak'],
          lacks: ['can'],
          as: 'form_error',
          err: 'agreement_s',
          fb: 'בלי `can`, עם `she` צריך s: `She speaks Spanish`. עם `can`: `She can speak Spanish`.',
        },
        {
          starts: 'can she',
          as: 'meaning_mismatch',
          err: 'question_for_statement',
          fb: 'זו שאלה, אבל התבקשת לספר למנהל מה היא יכולה לעשות. משפט רגיל: `She can speak Spanish`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S10-06',
      v: 1,
      skill: 'S10',
      unit: 'S10',
      sub: 'have_to',
      type: 'correct',
      role: 'practice',
      stage: 3,
      ctx: 'work.schedule',
      fam: 'S10.have-to-submit',
      goal: 'לעדכן שהמועד להגשת התוכנית הוקדם',
      instr: INSTR_CORRECT,
      sitHe: 'המועד להגשת התוכנית הוקדם. עכשיו חייבים להגיש אותה עד יום חמישי, ואתה מעדכן את הצוות.',
      hint: 'לא כל `to` מיותר. האם `have to` הוא פועל מודאלי כמו `must`?',
      explain:
        'המשפט תקין: ב-`have to` ה-`to` הוא חלק מהצירוף ונשאר. רק אחרי מודאליים כמו `must` אין `to`: `We must submit…`.',
      deep: '`have to`, `need to`, `ought to`, `be able to` משמשים כמו מודאליים, אבל ה-`to` שלהם קבוע. לכן `We have to submit` ו-`We must submit` נכונים שניהם — ו-`We must to submit` או `We have submit` שגויים.',
      diff: '`must` + בסיס (`We must submit`), `have to` + בסיס (`We have to submit`). ההבדל בצורה: אחרי `must` אין `to`; ב-`have to` ה-`to` חלק מהצירוף.',
      source: [
        { id: 's1', t: 'we' },
        { id: 's2', t: 'have' },
        { id: 's3', t: 'to' },
        { id: 's4', t: 'submit' },
        { id: 's5', t: 'the plan' },
        { id: 's6', t: 'by Thursday' },
      ],
      tokens: [
        { id: 't1', t: 'must' },
        { id: 't2', t: 'need' },
      ],
      accept: [
        { a: 'We have to submit the plan by Thursday', o: 'correct_target' },
        {
          a: 'We must submit the plan by Thursday',
          o: 'valid_alternative',
          note: 'גם נכון: אחרי `must` בא פועל בסיס בלי `to`. אבל המשפט המקורי היה תקין — ב-`have to` ה-`to` נשאר.',
        },
        {
          a: 'We need to submit the plan by Thursday',
          o: 'valid_alternative',
          note: 'גם נכון: `need to` — כמו `have to` — שומר על ה-`to`. המשפט המקורי היה תקין.',
        },
      ],
      rules: [
        {
          has: ['must', 'to'],
          as: 'form_error',
          err: 'modal_to',
          fb: 'אחרי `must` בא פועל בסיס ישירות — בלי `to`, ובלי `have to` נוסף: `We must submit…`. שים לב: המשפט המקורי, `We have to submit…`, היה תקין.',
        },
        {
          has: ['have submit'],
          as: 'form_error',
          err: 'have_to_missing_to',
          fb: 'ב-`have to` ה-`to` נשאר: `We have to submit`. רק אחרי מודאליים כמו `must`, `can`, `should` אין `to`.',
        },
        {
          has: ['need submit'],
          as: 'form_error',
          err: 'need_to_missing_to',
          fb: 'ב-`need to` ה-`to` נשאר: `We need to submit`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S10-07',
      v: 1,
      skill: 'S10',
      unit: 'S10',
      sub: 'ought_to',
      type: 'discriminate',
      role: 'practice',
      stage: 3,
      ctx: 'daily.health',
      fam: 'S10.should-ought-day-off',
      goal: 'לייעץ לחבר מותש לקחת יום חופש',
      instr: 'בחר את כל המשפטים שנכונים ומתאימים לסיטואציה.',
      sitHe: 'חבר עובד כבר שבועות בלי הפסקה ונראה מותש. אתה רוצה להציע לו לקחת יום חופש.',
      hint: '`should` ו-`ought to` אומרים כמעט אותו דבר — אבל רק באחד מהם יש `to`.',
      explain: '`should` + בסיס, `ought to` + בסיס: שניהם נותנים עצה. `should to` שגוי, וב-`ought to` ה-`to` לא נשמט.',
      deep: '`ought to` הוא מקרה מיוחד: משמעותו קרובה ל-`should`, אבל ה-`to` הוא חלק ממנו — כמו ב-`have to` וב-`need to`. בשלילה אפשר `You ought not to…` (רשמי); ביום-יום נפוץ יותר `You shouldn\'t…`.',
      multi: true,
      options: [
        { id: 'a', en: 'You should take a day off.', v: 'fits', why: '`should` + פועל בסיס — עצה רגילה ונכונה.' },
        {
          id: 'b',
          en: 'You ought to take a day off.',
          v: 'fits',
          why: '`ought to` קרוב ל-`should`, וה-`to` הוא חלק מהצירוף. נכון.',
        },
        {
          id: 'c',
          en: 'You should to take a day off.',
          v: 'ungrammatical',
          why: 'אחרי `should` אין `to`: `You should take a day off`.',
          err: 'modal_to',
        },
        {
          id: 'd',
          en: 'You ought take a day off.',
          v: 'ungrammatical',
          why: 'ב-`ought to` ה-`to` לא נשמט: `You ought to take a day off`.',
          err: 'ought_missing_to',
        },
      ],
    },
    {
      id: 'S10-08',
      v: 1,
      skill: 'S10',
      unit: 'S10',
      sub: 'negative_meaning',
      type: 'discriminate',
      role: 'practice',
      stage: 3,
      ctx: 'work.software',
      fam: 'S10.dont-have-to-training',
      goal: 'להסביר לעמית חדש שההדרכה אינה חובה',
      instr: 'בחר את כל המשפטים שנכונים ומתאימים לסיטואציה.',
      sitHe: 'מחר יש הדרכה על המערכת החדשה. ההשתתפות לא חובה — מי שרוצה, מגיע. עמית חדש שואל אם הוא חייב לבוא.',
      hint: '"לא חייבים" ו"אסור" הם שני דברים שונים.',
      explain: '`don\'t have to` / `don\'t need to` — לא חייבים (אפשר אם רוצים). `mustn\'t` — אסור.',
      deep: 'בחיוב `must` ו-`have to` קרובים מאוד. בשלילה הם נפרדים: `You mustn\'t come` = אסור לך לבוא; `You don\'t have to come` = אתה לא חייב לבוא. גם `You don\'t need to come` אומר "אין צורך".',
      diff: '`mustn\'t` = אסור. `don\'t have to` = לא חייבים (מותר, אבל אין חובה).',
      multi: true,
      options: [
        {
          id: 'a',
          en: "You don't have to come to the training.",
          v: 'fits',
          why: '`don\'t have to` = לא חייבים. בדיוק המצב: מי שרוצה — בא.',
        },
        {
          id: 'b',
          en: "You don't need to come to the training.",
          v: 'fits',
          why: '`don\'t need to` = אין צורך. גם מתאים.',
        },
        {
          id: 'c',
          en: "You mustn't come to the training.",
          v: 'other_meaning',
          why: 'המשפט תקין, אבל `mustn\'t` אומר שאסור לו לבוא — וזה לא נכון.',
          err: 'mustnt_for_no_need',
        },
        {
          id: 'd',
          en: "You don't have come to the training.",
          v: 'ungrammatical',
          why: 'ב-`have to` ה-`to` נשאר גם בשלילה: `You don\'t have to come`.',
          err: 'have_to_missing_to',
        },
      ],
    },
    {
      id: 'S10-09',
      v: 1,
      skill: 'S10',
      unit: 'S10',
      sub: 'must_not',
      type: 'assemble',
      role: 'practice',
      stage: 2,
      ctx: 'daily.home',
      fam: 'S10.must-not-bike-stairwell',
      goal: 'להסביר לשכן חדש מה אסור בבניין',
      instr: 'בנה משפט אחד באנגלית. לא חייבים להשתמש בכל המילים.',
      sitHe: 'שכן חדש נכנס לבניין. לפי כללי הבניין אסור להשאיר אופניים בחדר המדרגות — הם חוסמים את היציאה. אתה מסביר לו.',
      target: 'איסור: `must not` + פועל',
      hint: 'אסור = `must not`. מה בא אחריו?',
      explain:
        'איסור: `must not` + פועל בסיס — `You must not leave your bike in the stairwell`. `don\'t have to` אומר רק שאין חובה.',
      deep: 'ביום-יום נפוץ גם הקיצור `mustn\'t`, ובאנגלית אמריקאית גם `You can\'t leave your bike…` משמש לאיסור. `You don\'t have to leave…` אומר משהו אחר לגמרי: שאין חובה להשאיר שם — כאילו זה מותר.',
      tokens: [
        { id: 't1', t: 'you' },
        { id: 't2', t: 'must' },
        { id: 't3', t: 'not' },
        { id: 't4', t: 'leave' },
        { id: 't5', t: 'your bike' },
        { id: 't6', t: 'in the stairwell' },
        {
          id: 't7',
          t: "don't have to",
          why: '`don\'t have to` אומר "לא חייבים", לא "אסור". לאיסור: `must not`.',
          err: 'dont_have_to_for_prohibition',
          as: 'meaning_mismatch',
        },
        { id: 't8', t: 'to', why: 'אחרי `must not` בא פועל בסיס ישירות, בלי `to`: `must not leave`.', err: 'modal_to' },
        {
          id: 't9',
          t: 'leaving',
          why: '`leaving` לא מתאים כאן: אחרי `must not` — וגם אחרי `have to` — בא פועל בסיס: `leave`.',
          err: 'modal_ing',
        },
      ],
      accept: [{ a: 'You must not leave your bike in the stairwell', o: 'correct_target' }],
      wrong: [
        {
          a: "You don't have to leave your bike in the stairwell",
          as: 'meaning_mismatch',
          err: 'dont_have_to_for_prohibition',
          fb: 'המשפט תקין, אבל הוא אומר "לא חייבים להשאיר שם" — לא שאסור. לאיסור: `You must not leave your bike in the stairwell`.',
        },
      ],
      rules: [
        {
          has: ['must leave'],
          lacks: ['not'],
          as: 'meaning_mismatch',
          err: 'obligation_for_prohibition',
          fb: '`You must leave your bike…` אומר שחובה להשאיר אותם שם — ההפך. איסור: `must not leave`.',
        },
        {
          has: ['not must'],
          as: 'form_error',
          err: 'not_position',
          fb: '`not` בא אחרי `must`: `You must not leave…`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S10-10',
      v: 2,
      skill: 'S10',
      unit: 'S10',
      sub: 'be_able_to',
      type: 'assemble',
      role: 'practice',
      stage: 2,
      ctx: 'work.meeting',
      fam: 'S10.wont-be-able-call',
      goal: 'להודיע מראש שלא תוכל להצטרף לשיחה',
      instr: 'בנה משפט אחד באנגלית. לא חייבים להשתמש בכל המילים.',
      sitHe: 'מחר בעשר יש שיחת צוות, אבל בדיוק באותה שעה אתה בהשתלמות. אתה מודיע מראש שלא תוכל להצטרף.',
      target: 'יכולת בעתיד: `won\'t be able to` + פועל',
      hint: 'אחרי `won\'t` לא יכול לבוא `can`. איזה צירוף מחליף את `can` בעתיד?',
      explain:
        'שני מודאליים לא באים ברצף, ולכן לא `won\'t can`. בעתיד: `I won\'t be able to join the call tomorrow`.',
      deep: '`won\'t` הוא מודאלי, ולכן אחריו בא בסיס — `be`. אחר כך `able to`, ששומר על ה-`to`, ואחריו שוב בסיס: `join`. בעברית "לא אוכל" היא מילה אחת; באנגלית זו שרשרת: `won\'t` + `be able to` + פועל. גם `I can\'t join the call tomorrow` נכון — `can\'t` משמש גם לתוכניות בעתיד. ו-`I won\'t be joining the call` (עתיד מתמשך) הוא הודעה מנומסת וטבעית על מה שיקרה — אבל היא לא אומרת שאינך יכול.',
      tokens: [
        { id: 't1', t: 'I' },
        { id: 't2', t: "won't" },
        { id: 't3', t: 'be' },
        { id: 't4', t: 'able' },
        { id: 't5', t: 'to' },
        { id: 't6', t: 'join' },
        { id: 't7', t: 'the call' },
        { id: 't8', t: 'tomorrow' },
        {
          id: 't9',
          t: 'can',
          why: '`can` לא מתאים כאן: אין שני מודאליים ברצף (`won\'t can`), ו-`can` לא בא יחד עם `be able to`. יכולת שלילית בעתיד: `won\'t be able to join`.',
          err: 'double_modal',
        },
        {
          id: 't10',
          t: 'joining',
          why: '`joining` לא מתאים כאן: מיד אחרי `won\'t` בא פועל בסיס, וגם אחרי `be able to`: `won\'t be able to join`.',
          err: 'modal_ing',
        },
      ],
      accept: [
        { a: "I won't be able to join the call tomorrow", o: 'correct_target' },
        { a: "Tomorrow I won't be able to join the call", o: 'correct_target' },
        { a: "I won't be able to join the call", o: 'correct_target' },
        {
          a: "I won't join the call tomorrow",
          o: 'target_not_used',
          note: 'תקין — אבל `I won\'t join` נשמע כמו החלטה שלך לא להצטרף, לא כמו חוסר יכולת. התרגיל ביקש `won\'t be able to`.',
        },
        {
          a: "Tomorrow I won't join the call",
          o: 'target_not_used',
          note: 'תקין — אבל `I won\'t join` נשמע כמו החלטה שלך לא להצטרף, לא כמו חוסר יכולת. התרגיל ביקש `won\'t be able to`.',
        },
        {
          a: "I won't join the call",
          o: 'target_not_used',
          note: 'תקין — אבל `I won\'t join` נשמע כמו החלטה שלך לא להצטרף, לא כמו חוסר יכולת. התרגיל ביקש `won\'t be able to`.',
        },
        {
          a: "I won't be joining the call tomorrow",
          o: 'target_not_used',
          note: 'תקין וטבעי: `won\'t be joining` מודיע בנימוס מה יקרה, אבל לא אומר שאינך יכול. התרגיל ביקש `won\'t be able to`.',
        },
        {
          a: "Tomorrow I won't be joining the call",
          o: 'target_not_used',
          note: 'תקין וטבעי: `won\'t be joining` מודיע בנימוס מה יקרה, אבל לא אומר שאינך יכול. התרגיל ביקש `won\'t be able to`.',
        },
        {
          a: "I won't be joining the call",
          o: 'target_not_used',
          note: 'תקין וטבעי: `won\'t be joining` מודיע בנימוס מה יקרה, אבל לא אומר שאינך יכול. התרגיל ביקש `won\'t be able to`.',
        },
      ],
      rules: [
        {
          has: ["won't can"],
          as: 'form_error',
          err: 'double_modal',
          fb: 'שני מודאליים לא באים ברצף: לא `won\'t can`. בעתיד: `won\'t be able to join`.',
        },
        {
          has: ['able join'],
          as: 'form_error',
          err: 'able_missing_to',
          fb: 'ב-`be able to` ה-`to` נשאר: `be able to join`.',
        },
        {
          has: ["won't able"],
          as: 'form_error',
          err: 'missing_be',
          fb: 'אחרי `won\'t` בא בסיס — `be`: `won\'t be able to join`.',
        },
        {
          starts: 'can I',
          as: 'meaning_mismatch',
          err: 'question_for_statement',
          fb: 'זו שאלה (בקשת רשות), אבל התבקשת להודיע שלא תוכל להצטרף: `I won\'t be able to join the call tomorrow`.',
        },
        {
          has: ['can join'],
          lacks: ["won't"],
          as: 'meaning_mismatch',
          err: 'can_for_cannot',
          fb: '`I can join` אומר שאתה כן יכול להצטרף — ההפך. `I won\'t be able to join the call tomorrow`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S10-D1',
      v: 2,
      skill: 'S10',
      unit: 'S10',
      sub: 'dialogue',
      type: 'dialogue',
      role: 'practice',
      stage: 2,
      ctx: 'work.schedule',
      fam: 'S10.dialogue-reschedule',
      goal: 'לתאם מחדש פגישה עם עמיתה',
      instr: 'ענה לנועה בכל תור.',
      partnerName: 'Noa',
      setupHe: 'נועה, עמיתה מצוות אחר, צריכה להזיז פגישה שקבעתם ליום חמישי.',
      hint: 'בתור הראשון — הצעה (`could`). בתור השני — אפשרות לא בטוחה (`might`). אחרי שניהם: פועל בסיס.',
      explain: 'הצעה: `We could meet on Friday morning`; אפשרות: `He might join us later`. אחרי כל מודאלי — פועל בסיס, גם עם `he`.',
      turns: [
        {
          partner: {
            en: "I'm sorry, I can't make it on Thursday. When else can we meet?",
            he: 'מצטערת, אני לא מסתדרת ביום חמישי. מתי עוד אפשר להיפגש?',
          },
          sub: 'could',
          instr: 'הצע להיפגש ביום שישי בבוקר.',
          hint: 'הצעה עדינה: `could` + פועל בסיס.',
          explain: 'הצעה: `We could meet on Friday morning`. אחרי `could` — פועל בסיס, בלי `to`.',
          build: {
            tokens: [
              { id: 't1', t: 'we' },
              { id: 't2', t: 'could' },
              { id: 't3', t: 'meet' },
              { id: 't4', t: 'on Friday morning' },
              { id: 't5', t: 'to', why: 'אחרי `could` בא פועל בסיס ישירות, בלי `to`: `could meet`.', err: 'modal_to' },
              {
                id: 't6',
                t: 'met',
                why: 'אחרי `could` בא פועל בסיס: `meet`. `could` כאן הוא הצעה לעתיד, לא עבר.',
                err: 'modal_past',
              },
              {
                id: 't7',
                t: 'meeting',
                why: '`meeting` לא מתאים כאן: ההצעה היא `could meet`, ואחרי `could` בא פועל בסיס.',
                err: 'modal_ing',
              },
            ],
            accept: [
              { a: 'We could meet on Friday morning', o: 'correct_target' },
              {
                a: 'Could we meet on Friday morning',
                o: 'valid_alternative',
                note: 'גם נכון — הצעה בצורת שאלה. גם כאן אחרי `could` בא פועל בסיס.',
              },
            ],
            rules: [
              {
                has: ['met'],
                lacks: ['could'],
                as: 'meaning_mismatch',
                err: 'past_for_suggestion',
                fb: '`We met…` מספר מה כבר קרה. כאן מציעים מועד: `We could meet on Friday morning`.',
              },
            ],
            end: '.',
          },
        },
        {
          partner: { en: 'Friday morning works for me. Is Dan coming too?', he: 'שישי בבוקר מתאים לי. גם דן מגיע?' },
          sub: 'might',
          instr: 'ענה שאתה לא בטוח — ייתכן שהוא יצטרף מאוחר יותר.',
          hint: 'אפשרות לא בטוחה: `might`. ומה קורה ל-s של `he` אחרי מודאלי?',
          explain: 'אפשרות: `He might join us later`. אחרי `might` הפועל בצורת בסיס, גם עם `he`.',
          build: {
            tokens: [
              { id: 't1', t: 'he' },
              { id: 't2', t: 'might' },
              { id: 't3', t: 'join' },
              { id: 't4', t: 'us' },
              { id: 't5', t: 'later' },
              { id: 't6', t: 'joins', why: 'אחרי `might` בא פועל בסיס, בלי s: `might join`.', err: 'modal_s' },
              { id: 't7', t: 'to', why: 'אחרי `might` בא פועל בסיס ישירות, בלי `to`: `might join`.', err: 'modal_to' },
            ],
            accept: [
              { a: 'He might join us later', o: 'correct_target' },
              { a: 'He might join later', o: 'correct_target' },
            ],
            rules: [
              {
                has: ['joins'],
                lacks: ['might'],
                as: 'meaning_mismatch',
                err: 'fact_for_possibility',
                fb: '`He joins us later` נשמע כמו דבר קבוע וידוע. אתה לא בטוח — אפשרות: `He might join us later`.',
              },
              {
                has: ['he join'],
                lacks: ['might'],
                as: 'form_error',
                err: 'missing_modal',
                fb: 'חסר `might`: `He might join us later`. (בלי מודאלי, עם `he` צריך s.)',
              },
              {
                starts: 'might he',
                as: 'meaning_mismatch',
                err: 'question_for_statement',
                fb: 'זו שאלה — אבל נועה שאלה אותך. תשובה: `He might join us later`.',
              },
            ],
            end: '.',
          },
        },
      ],
      closing: { en: "Great. I'll send an invitation for Friday at nine.", he: 'מעולה. אשלח זימון לשישי בתשע.' },
    },
    {
      id: 'S10-C1',
      v: 1,
      skill: 'S10',
      unit: 'S10',
      sub: 'must',
      type: 'assemble',
      role: 'check',
      stage: 2,
      ctx: 'daily.travel',
      fam: 'S10.must-buy-ticket',
      goal: 'להסביר לתיירת את הכלל לגבי כרטיסים',
      instr: 'קרא את הסיטואציה ובנה משפט אחד באנגלית.',
      sitEn:
        "A tourist wants to get on the light rail and pay the driver. On this line that isn't possible: everyone buys a ticket at the station first. Explain the rule to her.",
      trHe: 'תיירת רוצה לעלות לרכבת הקלה ולשלם לנהג. בקו הזה זה לא אפשרי: כולם קונים כרטיס בתחנה קודם. הסבר לה את הכלל.',
      target: 'חובה: `must` או `have to`',
      hint: 'שים לב מה בא אחרי כל אחד מהם.',
      explain: 'אחרי `must` — בסיס בלי `to`: `You must buy…`. ב-`have to` ה-`to` נשאר: `You have to buy…`.',
      tokens: [
        { id: 't1', t: 'you' },
        { id: 't2', t: 'must' },
        { id: 't3', t: 'have' },
        { id: 't4', t: 'to' },
        { id: 't5', t: 'buy' },
        { id: 't6', t: 'a ticket' },
        { id: 't7', t: 'at the station' },
        {
          id: 't8',
          t: 'buying',
          why: 'אחרי `must` — וגם אחרי `have to` — בא פועל בסיס: `buy`, לא `buying`.',
          err: 'modal_ing',
        },
      ],
      accept: [
        { a: 'You must buy a ticket at the station', o: 'correct_target' },
        { a: 'You have to buy a ticket at the station', o: 'correct_target' },
        {
          a: 'You buy a ticket at the station',
          o: 'target_not_used',
          note: 'תקין — כך מתארים נוהל. התרגיל ביקש לנסח חובה עם `must` או `have to`.',
        },
      ],
      rules: [
        {
          has: ['must', 'to'],
          as: 'form_error',
          err: 'modal_to',
          fb: 'אחרי `must` בא פועל בסיס ישירות — בלי `to`, ובלי `have to` נוסף: `You must buy…` או `You have to buy…`.',
        },
        {
          has: ['have buy'],
          as: 'form_error',
          err: 'have_to_missing_to',
          fb: 'ב-`have to` ה-`to` נשאר: `You have to buy a ticket at the station`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S10-C2',
      v: 2,
      skill: 'S10',
      unit: 'S10',
      sub: 'might',
      type: 'assemble',
      role: 'check',
      stage: 3,
      ctx: 'daily.shopping',
      fam: 'S10.might-package',
      goal: 'לומר שייתכן שהחבילה תגיע מחר',
      instr: 'בנה משפט אחד באנגלית. לא חייבים להשתמש בכל המילים.',
      sitHe: 'הזמנת משהו באינטרנט. לפי האתר החבילה אולי תגיע מחר — אבל זה לא בטוח. חבר שואל מתי היא תגיע.',
      hint: 'זה לא בטוח. איזה מודאלי מבטא אפשרות — ומה בא אחריו?',
      explain: 'אפשרות לא בטוחה: `The package might arrive tomorrow`. אחרי `might` בא פועל בסיס, בלי s.',
      deep: '`will arrive` מציג את ההגעה כעובדה, ו-`arrives tomorrow` כלוח זמנים קבוע. `might` (וגם `may` או `could`) משאיר מקום לספק. אחרי כולם — פועל בסיס.',
      tokens: [
        { id: 't1', t: 'the package' },
        { id: 't2', t: 'might' },
        { id: 't3', t: 'arrive' },
        { id: 't4', t: 'tomorrow' },
        {
          id: 't5',
          t: 'arrives',
          why: 'אחרי מודאלי הפועל לא מקבל s: `might arrive`.',
          err: 'modal_s',
        },
        {
          id: 't6',
          t: 'will',
          why: '`will` מציג את ההגעה כוודאית, אבל זה לא בטוח. לאפשרות: `might`.',
          err: 'will_for_possibility',
          as: 'meaning_mismatch',
        },
        { id: 't7', t: 'to', why: 'אחרי `might` בא פועל בסיס ישירות, בלי `to`: `might arrive`.', err: 'modal_to' },
      ],
      accept: [{ a: 'The package might arrive tomorrow', o: 'correct_target' }],
      rules: [
        {
          has: ['will', 'might'],
          as: 'form_error',
          err: 'double_modal',
          fb: 'שני מודאליים לא באים יחד. לאפשרות: `The package might arrive tomorrow`.',
        },
        {
          has: ['arrives'],
          lacks: ['might', 'will'],
          as: 'meaning_mismatch',
          err: 'schedule_for_possibility',
          fb: '`arrives tomorrow` מציג את זה כלוח זמנים קבוע. זה לא בטוח: `The package might arrive tomorrow`.',
        },
        {
          has: ['arrives'],
          as: 'form_error',
          err: 'modal_s',
          fb: 'אחרי מודאלי (`might`, וגם `will`) הפועל לא מקבל s: `might arrive`.',
        },
        {
          has: ['will arrive'],
          as: 'meaning_mismatch',
          err: 'will_for_possibility',
          fb: '`will arrive` מציג את זה כוודאי. האתר אמר שזה לא בטוח: `The package might arrive tomorrow`.',
        },
        {
          starts: 'might the package',
          as: 'meaning_mismatch',
          err: 'question_for_statement',
          fb: 'זו שאלה — אבל החבר שאל אותך. תשובה: `The package might arrive tomorrow`.',
        },
        {
          starts: 'will the package',
          as: 'meaning_mismatch',
          err: 'question_for_statement',
          fb: 'זו שאלה — אבל החבר שאל אותך. תשובה, כשזה לא בטוח: `The package might arrive tomorrow`.',
        },
        {
          has: ['package arrive'],
          as: 'form_error',
          err: 'missing_modal',
          fb: 'חסר מודאלי לפני הפועל: `The package might arrive tomorrow`.',
        },
      ],
      end: '.',
    },
  ],
};
