import type { SkillPack } from '../schema';

/**
 * S11 HABIT_MEANING — four units: used to / would / be used to / get used to.
 * The learner already had a full used-to lesson: these are deepening items, not a restart.
 */

const INSTR_CORRECT = 'אם יש טעות — גע במילה או ברווח ובחר תיקון. אם המשפט תקין, בחר "אין צורך בתיקון".';

export const S11: SkillPack = {
  skill: 'S11',
  lessons: [
    {
      unit: 'S11.used_to',
      title: '`used to` — פעם, והיום כבר לא',
      short:
        '`used to` + פועל בסיס מתאר הרגל או מצב בעבר שכבר לא נכונים היום: `I used to live in Haifa`. בשלילה ובשאלה נכנס `did`, ואחריו `use` בלי d: `I didn\'t use to…`, `Did you use to…?`',
      chain: ['used to', 'V (base)'],
      examples: [
        { en: 'I used to live in Haifa.', he: 'פעם גרתי בחיפה — היום כבר לא.' },
        { en: 'She used to work nights.', he: 'פעם היא עבדה במשמרות לילה.' },
        { en: "We didn't use to have a car.", he: 'פעם לא היה לנו רכב.' },
        { en: 'Did you use to play an instrument?', he: 'פעם ניגנת על כלי נגינה?' },
      ],
      contrast: {
        a: { en: 'I used to live in Haifa.', he: 'פעם גרתי בחיפה (היום כבר לא).' },
        b: { en: 'I lived in Haifa for five years.', he: 'גרתי בחיפה חמש שנים.' },
        note: 'שניהם תקינים. `used to` מדגיש שזה היה המצב הקבוע אז ושהיום זה כבר לא כך. כשמציינים כמה זמן זה נמשך (`for five years`) או כמה פעמים זה קרה, בדרך כלל משתמשים בעבר פשוט.',
      },
      deep:
        '• `used to` + פועל בסיס: הרגל (`I used to cycle to work`) או מצב (`I used to live in Haifa`) בעבר — עם המשמעות שהיום זה כבר לא כך.\n' +
        '• בשלילה ובשאלה נכנס `did`, ואחריו צורת בסיס — `use`, בלי d: `I didn\'t use to…`, `Did you use to…?`. בלי `did` תמיד `used`. (הכתיב `didn\'t used to` מופיע לפעמים בכתיבה לא רשמית, אבל ברוב המקורות הוא נחשב שגוי.)\n' +
        '• שלילה טבעית נוספת: `I never used to…` — כאן אין `did`, ולכן `used`.\n' +
        '• גם עבר פשוט מתאים להרגל או למצב שהסתיימו: `I lived in Haifa`. כשמציינים משך (`for five years`) או מספר פעמים — בדרך כלל עבר פשוט, לא `used to`.\n' +
        '• זהירות מבלבול: `be used to` (רגיל ל…) ו-`get used to` (מתרגל ל…) הם מבנים אחרים. שם `to` היא מילת יחס, ואחריה בא ing או שם עצם.',
      pitfalls: [
        '`I use to live…` — בלי `did` הצורה היא `used`.',
        '`I used to living…` — אחרי `used to` (הרגל בעבר) בא פועל בסיס.',
        '`I didn\'t used to…` — אחרי `did` בא `use`, בלי d.',
      ],
    },
    {
      unit: 'S11.would',
      title: '`would` — כך היה קורה שוב ושוב',
      short:
        '`would` + פועל בסיס מתאר פעולה שחזרה שוב ושוב בעבר: `Every summer we would visit my grandmother`. למצב (לגור, להכיר, לאהוב) `would` לא מתאים — שם `used to`.',
      chain: ['would', 'V (base)'],
      examples: [
        { en: 'Every summer we would visit my grandmother.', he: 'כל קיץ היינו מבקרים את סבתא שלי.' },
        { en: 'After work, we would sit in the café on the corner.', he: 'אחרי העבודה היינו יושבים בבית הקפה שבפינה.' },
        {
          en: 'When the system crashed, we would call the same technician.',
          he: 'כשהמערכת הייתה קורסת, היינו מתקשרים לאותו טכנאי.',
        },
      ],
      contrast: {
        a: { en: 'I used to live in Haifa.', he: 'פעם גרתי בחיפה.' },
        b: { en: 'I would live in Haifa if I could.', he: 'הייתי גר בחיפה אילו יכולתי.' },
        note: 'עם פועל של מצב, `would` נשמע כמו תנאי — "הייתי גר…". מצב בעבר מתארים עם `used to` (או בעבר פשוט). להרגל של פעולה — `would` ו-`used to` מתאימים שניהם.',
      },
      deep:
        '• `would` להרגל = "כך היה קורה": `On Fridays we would visit the market`. בעברית זה מקביל ל"היינו מבקרים".\n' +
        '• רק לפעולות שחזרו. מצבים — `live`, `know`, `have` (במובן "יש לי"), `like`, `believe` — לא "חוזרים", הם פשוט נמשכים. לכן `I would live in Haifa` לא נשמע כהרגל אלא כתנאי. כאן רק `used to`: `I used to live in Haifa`.\n' +
        '• `used to` מתאים לשניהם — פעולה ומצב. בסיפור מתחילים לעתים קרובות ב-`used to` וממשיכים ב-`would`: `We used to spend the summer by the sea. We would swim every morning…`\n' +
        '• `would` צריך הקשר של עבר (`every summer`, `when I was…`, `at my old job`). בלי הקשר כזה המשפט עלול להישמע כמו תנאי.\n' +
        '• גם עבר פשוט מתאים לפעולה שחזרה: `Every summer we visited my grandmother`.\n' +
        '• אחרי `would` תמיד פועל בסיס — גם בסיפור על העבר: `we would visit`, לא `we would visited`.',
      pitfalls: [
        '`We would visited` — אחרי `would` בא פועל בסיס: `we would visit`.',
        '`I would live in Haifa` (כהרגל) — `live` הוא מצב: `I used to live in Haifa`.',
        '`would` בלי הקשר של עבר עלול להישמע כמו תנאי.',
      ],
    },
    {
      unit: 'S11.be_used_to',
      title: '`be used to` — רגיל ל…',
      short:
        '`be used to` + שם עצם או פועל עם ing פירושו "רגיל ל…": `I\'m used to the noise`, `I\'m used to working late`. ה-`to` כאן היא מילת יחס, ולכן אחריה לא בא פועל בסיס.',
      chain: ['am / is / are / was', 'used to', 'V-ing / noun'],
      examples: [
        { en: "I'm used to working late.", he: 'אני רגיל לעבוד עד מאוחר.' },
        { en: "I'm used to the noise.", he: 'אני רגיל לרעש.' },
        { en: "She isn't used to the cold yet.", he: 'היא עדיין לא רגילה לקור.' },
      ],
      contrast: {
        a: { en: 'I used to work late.', he: 'פעם עבדתי עד מאוחר — היום כבר לא.' },
        b: { en: "I'm used to working late.", he: 'אני רגיל לעבוד עד מאוחר.' },
        note: 'אותן מילים, משמעות אחרת. בלי `be` — הרגל שנגמר, ואחריו פועל בסיס. עם `be` — "רגיל ל…", ואחריו ing או שם עצם.',
      },
      deep:
        '• `be used to` = זה מוכר לי, זה כבר לא מוזר או קשה. `used` כאן מתפקד כמו תואר ("רגיל").\n' +
        '• `to` כאן היא מילת יחס (כמו ב-`I look forward to the meeting`), ולכן אחריה שם עצם (`the noise`) או פועל עם ing (`working`) — לא פועל בסיס: לא `I\'m used to work late`.\n' +
        '• `be` משתנה לפי הזמן והנושא: `I\'m used to…`, `She wasn\'t used to…`, `Are you used to…?`.\n' +
        '• `used to` בלי `be` הוא מבנה אחר לגמרי: הרגל בעבר שנגמר, ואחריו פועל בסיס: `I used to work late`.\n' +
        '• לתהליך ההתרגלות — `get used to`: `I\'m getting used to it`.',
      pitfalls: [
        '`I\'m used to work late` — אחרי `be used to` בא ing: `I\'m used to working late`.',
        '`I used to working late` — בלי `be` זה מבנה ההרגל שנגמר, ואחריו פועל בסיס.',
        '`I\'m use to it` — הכתיב הוא `used`, גם כשבדיבור ה-d כמעט לא נשמעת.',
      ],
    },
    {
      unit: 'S11.get_used_to',
      title: '`get used to` — מתרגל ל…',
      short:
        '`get used to` + שם עצם או ing מתאר את התהליך: משהו חדש נהיה בהדרגה מוכר. `I\'m getting used to working from home`, `You\'ll get used to it`.',
      chain: ['get / got / getting', 'used to', 'V-ing / noun'],
      examples: [
        { en: "I'm getting used to working from home.", he: 'אני מתרגל לעבוד מהבית.' },
        { en: "I can't get used to the new system.", he: 'אני לא מצליח להתרגל למערכת החדשה.' },
        { en: "You'll get used to it.", he: 'תתרגל לזה.' },
      ],
      contrast: {
        a: { en: "I'm used to the new system.", he: 'אני רגיל למערכת החדשה — היא כבר מוכרת.' },
        b: { en: "I'm getting used to the new system.", he: 'אני מתרגל למערכת החדשה — עדיין בתהליך.' },
        note: '`be used to` — המצב: כבר רגיל. `get used to` — התהליך: נהיה רגיל. אחרי שניהם בא שם עצם או ing.',
      },
      deep:
        '• `get` כאן = "נהיה": `get used to` = נהיה רגיל. לכן הוא מתאר תהליך: `I\'m getting used to it` (קורה עכשיו, בהדרגה), `I got used to it quickly` (התהליך הסתיים), `You\'ll get used to it` (עוד יקרה).\n' +
        '• גם כאן `to` היא מילת יחס: אחריה שם עצם או ing — `get used to waking up early`, לא `get used to wake up`.\n' +
        '• `I can\'t get used to…` — לא מצליח להתרגל, למרות הזמן שעבר.\n' +
        '• ב-present perfect שומעים `I\'ve gotten used to it` (אמריקאית) וגם `I\'ve got used to it` (בריטית). שתי הצורות תקינות.\n' +
        '• `be used to` מתאר את המצב שבסוף התהליך: `Now I\'m used to it`.',
      pitfalls: [
        '`get used to wake up` — אחרי `get used to` בא ing: `get used to waking up`.',
        '`I\'m used to it` אומר שכבר התרגלת; `I\'m getting used to it` — שאתה עדיין בתהליך.',
        '`get use to` — הכתיב הוא `used`.',
      ],
    },
  ],
  examples: {
    'S11.used_to': [
      { en: 'He used to play the guitar in a band.', he: 'פעם הוא ניגן בגיטרה בלהקה.' },
      { en: "I didn't use to check my email on weekends.", he: 'פעם לא בדקתי מיילים בסופי שבוע.' },
      { en: 'Did you use to live near here?', he: 'פעם גרת כאן בסביבה?' },
    ],
    'S11.would': [
      { en: 'When it rained, we would stay inside and play cards.', he: 'כשירד גשם, היינו נשארים בבית ומשחקים קלפים.' },
      { en: 'On long trips, we would stop at the same gas station.', he: 'בנסיעות ארוכות היינו עוצרים באותה תחנת דלק.' },
      {
        en: 'My first manager would always answer emails within an hour.',
        he: 'המנהלת הראשונה שלי תמיד הייתה עונה למיילים תוך שעה.',
      },
    ],
    'S11.be_used_to': [
      { en: 'Are you used to working with two screens?', he: 'אתה רגיל לעבוד עם שני מסכים?' },
      { en: "We're used to a lot of noise in this office.", he: 'אנחנו רגילים להרבה רעש במשרד הזה.' },
      { en: "He wasn't used to such long meetings.", he: 'הוא לא היה רגיל לפגישות כל כך ארוכות.' },
    ],
    'S11.get_used_to': [
      { en: 'It took me a month to get used to the new keyboard.', he: 'לקח לי חודש להתרגל למקלדת החדשה.' },
      {
        en: 'Have you gotten used to the new office?',
        he: 'כבר התרגלת למשרד החדש?',
        note: 'באנגלית בריטית: `Have you got used to…?` — שתי הצורות תקינות.',
      },
      { en: "I'm slowly getting used to cooking every day.", he: 'אני לאט לאט מתרגל לבשל כל יום.' },
    ],
  },
  items: [
    // ---------------------------------------------------------------- used to
    {
      id: 'S11-U-01',
      v: 1,
      skill: 'S11',
      unit: 'S11.used_to',
      sub: 'negative',
      type: 'assemble',
      role: 'practice',
      stage: 1,
      ctx: 'daily.food',
      fam: 'S11.used-to-coffee-negative',
      goal: 'לומר שפעם לא אהבת קפה',
      instr: 'בנה את המשפט באנגלית. לא חייבים להשתמש בכל המילים.',
      promptHe: 'פעם לא אהבתי קפה.',
      sitHe: 'היום אתה שותה קפה כל בוקר. חבר מופתע לשמוע שפעם לא אהבת אותו.',
      target: 'שלילה של `used to`',
      scaffold: ["didn't", 'use to', 'V (base)'],
      hint: 'בשלילה נכנס `didn\'t`. מה קורה ל-`used` אחריו?',
      explain:
        'בשלילה נכנס `didn\'t`, ואחריו צורת בסיס — `use`, בלי d: `I didn\'t use to like coffee`. אפשר גם `I never used to like coffee`.',
      deep: 'זה אותו כלל כמו `I didn\'t like` (ולא `didn\'t liked`): אחרי `did` בא בסיס. ב-`never used to` אין `did`, ולכן `used` נשאר עם d. הכתיב `didn\'t used to` מופיע לפעמים בכתיבה לא רשמית, אבל ברוב המקורות הוא נחשב שגוי.',
      tokens: [
        { id: 't1', t: 'I' },
        { id: 't2', t: "didn't" },
        { id: 't3', t: 'use' },
        { id: 't4', t: 'used' },
        { id: 't5', t: 'to' },
        { id: 't6', t: 'like' },
        { id: 't7', t: 'liked' },
        { id: 't8', t: 'coffee' },
        { id: 't9', t: 'never' },
      ],
      accept: [
        { a: "I didn't use to like coffee", o: 'correct_target' },
        {
          a: 'I never used to like coffee',
          o: 'valid_alternative',
          note: 'גם נכון וטבעי מאוד. כאן אין `did`, ולכן `used` עם d.',
        },
        {
          a: "I didn't like coffee",
          o: 'target_not_used',
          note: 'תקין — עבר פשוט. התרגיל ביקש את השלילה של `used to`, שמדגישה שזה היה פעם ושהיום זה השתנה.',
        },
        {
          a: 'I never liked coffee',
          o: 'target_not_used',
          note: 'תקין — עבר פשוט. התרגיל ביקש את השלילה של `used to`, שמדגישה שזה היה פעם ושהיום זה השתנה.',
        },
      ],
      wrong: [
        {
          a: 'I used to like coffee',
          as: 'meaning_mismatch',
          err: 'affirmative_for_negative',
          fb: 'המשפט תקין, אבל הפוך: פירושו שפעם כן אהבת קפה. השלילה: `I didn\'t use to like coffee`.',
        },
      ],
      rules: [
        {
          has: ["didn't used"],
          as: 'form_error',
          err: 'did_used',
          fb: 'אחרי `didn\'t` בא פועל בסיס — `use`, בלי d: `I didn\'t use to like coffee`. (`didn\'t used to` מופיע לפעמים בכתיבה לא רשמית, אבל ברוב המקורות נחשב שגוי.)',
        },
        {
          has: ["didn't", 'never'],
          as: 'form_error',
          err: 'double_negative',
          fb: 'שלילה אחת מספיקה: `I didn\'t use to like coffee` או `I never used to like coffee`.',
        },
        {
          has: ['to liked'],
          as: 'form_error',
          err: 'used_to_past',
          fb: 'אחרי `use to` / `used to` בא פועל בסיס: `like`, לא `liked`.',
        },
        {
          has: ["didn't liked"],
          as: 'form_error',
          err: 'did_past',
          fb: 'אחרי `didn\'t` בא פועל בסיס: `I didn\'t like…` — ובמבנה של "פעם": `I didn\'t use to like coffee`.',
        },
        {
          has: ['never use to'],
          as: 'form_error',
          err: 'use_without_did',
          fb: 'בלי `did` הצורה היא `used to` (עם d): `I never used to like coffee`. `use to` בלי d בא רק אחרי `did` / `didn\'t`.',
        },
        {
          has: ['use to'],
          lacks: ["didn't"],
          as: 'form_error',
          err: 'use_without_did',
          fb: 'בלי `did` הצורה היא `used to` (עם d) — וכאן חסרה גם השלילה: `I didn\'t use to like coffee` או `I never used to like coffee`.',
        },
        {
          has: ['liked'],
          lacks: ["didn't", 'never'],
          as: 'meaning_mismatch',
          err: 'affirmative_for_negative',
          fb: '`I liked coffee` אומר שאהבת קפה — ההפך. השלילה: `I didn\'t use to like coffee`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S11-U-02',
      v: 1,
      skill: 'S11',
      unit: 'S11.used_to',
      sub: 'question',
      type: 'assemble',
      role: 'practice',
      stage: 1,
      ctx: 'work.job',
      fam: 'S11.used-to-downtown-question',
      goal: 'לשאול עמיתה אם פעם עבדה במרכז העיר',
      instr: 'בנה את השאלה באנגלית. לא חייבים להשתמש בכל המילים.',
      promptHe: 'פעם היית עובדת במרכז העיר?',
      sitHe: 'עמיתה חדשה מכירה כל בית קפה במרכז העיר. אתה חושד שפעם היא עבדה שם.',
      target: 'שאלה עם `did` + `use to`',
      scaffold: ['Did', 'you', 'use to', 'V (base)'],
      hint: 'בשאלה `did` בא לפני `you`. מה קורה ל-`used` אחרי `did`?',
      explain: 'בשאלה נכנס `did`, ואחריו צורת בסיס — `use`, בלי d: `Did you use to work downtown?`',
      deep: 'השאלה בנויה כמו כל שאלה בעבר: `Did you work…?` ← `Did you use to work…?`. אחרי `did` תמיד בסיס — `use` ולא `used`, בדיוק כמו `Did you invite…?` ולא `Did you invited…?`.',
      tokens: [
        { id: 't1', t: 'did' },
        { id: 't2', t: 'you' },
        { id: 't3', t: 'use' },
        { id: 't4', t: 'used' },
        { id: 't5', t: 'to' },
        { id: 't6', t: 'work' },
        { id: 't7', t: 'worked' },
        { id: 't8', t: 'downtown' },
      ],
      accept: [
        { a: 'Did you use to work downtown', o: 'correct_target' },
        {
          a: 'Did you work downtown',
          o: 'target_not_used',
          note: 'תקין — שאלה בעבר פשוט. התרגיל ביקש את השאלה עם `use to`, שמדגישה שזה היה המצב פעם.',
        },
        {
          a: 'You used to work downtown',
          o: 'target_not_used',
          note: 'בדיבור זו יכולה להיות שאלה, בהטעמה עולה. התרגיל ביקש את מבנה השאלה המלא: `Did you use to…?`',
        },
        {
          a: 'You worked downtown',
          o: 'target_not_used',
          note: 'בדיבור זו יכולה להיות שאלה, בהטעמה עולה. התרגיל ביקש את מבנה השאלה המלא: `Did you use to…?`',
        },
      ],
      rules: [
        {
          has: ['did you used'],
          as: 'form_error',
          err: 'did_used',
          fb: 'אחרי `did` בא פועל בסיס — `use`, בלי d: `Did you use to work downtown?` (`Did you used to` מופיע לפעמים בכתיבה לא רשמית, אבל ברוב המקורות נחשב שגוי.)',
        },
        {
          has: ['did you worked'],
          as: 'form_error',
          err: 'did_past',
          fb: 'אחרי `did` בא פועל בסיס: `Did you work…?` — ובמבנה של "פעם": `Did you use to work downtown?`',
        },
        {
          has: ['to worked'],
          as: 'form_error',
          err: 'used_to_past',
          fb: 'אחרי `use to` / `used to` בא פועל בסיס: `work`, לא `worked`.',
        },
        {
          has: ['use to'],
          lacks: ['did'],
          as: 'form_error',
          err: 'use_without_did',
          fb: 'בלי `did` הצורה היא `used to`. בשאלה: `Did you use to work downtown?`',
        },
        {
          has: ['use work'],
          as: 'form_error',
          err: 'use_to_missing_to',
          fb: 'חסר `to`: `Did you use to work downtown?`',
        },
        {
          has: ['used work'],
          as: 'form_error',
          err: 'use_to_missing_to',
          fb: 'חסר `to`: `used to work`. בשאלה: `Did you use to work downtown?`',
        },
      ],
      end: '?',
    },
    {
      id: 'S11-U-03',
      v: 2,
      skill: 'S11',
      unit: 'S11.used_to',
      sub: 'affirmative',
      type: 'correct',
      role: 'practice',
      stage: 2,
      ctx: 'daily.travel',
      fam: 'S11.used-to-bus-work',
      goal: 'לספר על הרגל שהיה לעמית ונגמר',
      instr: INSTR_CORRECT,
      sitHe: 'במשך שנים עמית שלך נסע לעבודה באוטובוס. מאז שעבר דירה הוא מגיע ברגל. אתה מספר על זה למישהו.',
      hint: 'בלי `did` — איך נכתב `used to`?',
      explain: 'בלי `did` הצורה היא `used to`: `He used to take the bus to work`. `use to` בלי d בא רק אחרי `did`.',
      deep: 'בדיבור ה-d של `used to` כמעט לא נשמעת, ולכן קל לכתוב `use to`. הכלל: `used to` במשפט חיובי; `did … use to` בשלילה ובשאלה. ו-`He is used to taking the bus` הוא מבנה אחר — "הוא רגיל לנסוע באוטובוס" (היום).',
      source: [
        { id: 's1', t: 'he' },
        { id: 's2', t: 'use', why: 'בלי `did` הצורה היא `used to` (עם d).', err: 'use_without_did' },
        { id: 's3', t: 'to' },
        { id: 's4', t: 'take' },
        { id: 's5', t: 'the bus' },
        { id: 's6', t: 'to work' },
      ],
      tokens: [
        { id: 't1', t: 'used' },
        {
          id: 't2',
          t: 'is',
          why: '`is` לא מתאים כאן: מדובר בהרגל שנגמר — `He used to take the bus`. (`is used to` + ing פירושו "רגיל ל…" — היום.)',
          err: 'be_used_to_for_past_habit',
        },
        {
          id: 't3',
          t: 'taking',
          why: 'אחרי `used to` (הרגל בעבר) בא פועל בסיס: `take`. ing בא רק אחרי `be used to` — "רגיל ל…".',
          err: 'used_to_ing',
        },
      ],
      accept: [{ a: 'He used to take the bus to work', o: 'correct_target' }],
      wrong: [
        {
          a: 'He use to take the bus to work',
          as: 'form_error',
          err: 'use_without_did',
          fb: 'בלי `did` הצורה היא `used to`: `He used to take the bus to work`. `use to` בלי d בא רק אחרי `did`: `Did he use to…?`',
        },
        {
          a: 'He is used to taking the bus to work',
          as: 'meaning_mismatch',
          err: 'be_used_to_for_past_habit',
          fb: 'המשפט תקין, אבל פירושו שהוא רגיל לנסוע באוטובוס — היום. הוא כבר לא נוסע כך: `He used to take the bus to work`.',
        },
      ],
      rules: [
        {
          has: ['is used to take'],
          as: 'form_error',
          err: 'be_used_to_base',
          fb: 'אחרי `is used to` בא ing — אבל `is used to` פירושו "רגיל ל…". כאן הרגל שנגמר: `He used to take the bus to work`.',
        },
        {
          has: ['is use'],
          as: 'form_error',
          err: 'use_form',
          fb: '`is use to` אינו מבנה תקין. הרגל שנגמר: `He used to take the bus to work`.',
        },
        {
          has: ['used to taking'],
          lacks: ['is'],
          as: 'form_error',
          err: 'used_to_ing',
          fb: 'אחרי `used to` (הרגל בעבר) בא פועל בסיס: `used to take`. `used to taking` בא רק אחרי `be` — ושם המשמעות היא "רגיל ל…".',
        },
        {
          has: ['is taking'],
          as: 'meaning_mismatch',
          err: 'progressive_for_past_habit',
          fb: 'המשפט תקין, אבל `He is taking the bus…` מתאר מה שקורה עכשיו. הוא כבר לא נוסע כך — הרגל שנגמר: `He used to take the bus to work`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S11-U-04',
      v: 1,
      skill: 'S11',
      unit: 'S11.used_to',
      sub: 'contrast',
      type: 'discriminate',
      role: 'practice',
      stage: 3,
      ctx: 'daily.home',
      fam: 'S11.used-to-near-sea',
      goal: 'לספר איפה גרת פעם',
      instr: 'בחר את כל המשפטים שנכונים ומתאימים לסיטואציה.',
      sitHe: 'במשך שנים גרת ליד הים. לפני שנתיים עברת לדירה במרכז העיר. חבר חדש שואל איפה גרת קודם.',
      hint: 'מצב שהסתיים. מה ההבדל בין `used to` לבין `be used to`?',
      explain: 'מצב שהסתיים: `I used to live…` או עבר פשוט. `I\'m used to living…` = רגיל (היום), ו-`I use to` שגוי.',
      deep: '`used to` ועבר פשוט מתארים שניהם משהו שהסתיים; `used to` מדגיש שזה היה המצב הקבוע אז. `I\'m used to living near the sea` נשמע כמעט אותו דבר, אבל פירושו "אני רגיל לגור ליד הים" — משהו שנכון עכשיו.',
      diff: '`I used to live…` — פעם, והיום כבר לא. `I\'m used to living…` — אני רגיל (היום).',
      multi: true,
      options: [
        { id: 'a', en: 'I used to live near the sea.', v: 'fits', why: 'מצב שנמשך בעבר והסתיים: `used to live`. מתאים.' },
        {
          id: 'b',
          en: 'I lived near the sea for years.',
          v: 'fits',
          why: 'גם עבר פשוט מתאים למצב שהסתיים — `for years` אומר כמה זמן זה נמשך.',
        },
        {
          id: 'c',
          en: "I'm used to living near the sea.",
          v: 'other_meaning',
          why: 'המשפט תקין, אבל פירושו "אני רגיל לגור ליד הים" — היום. אתה כבר לא גר שם.',
          err: 'be_used_to_for_past_habit',
        },
        {
          id: 'd',
          en: 'I use to live near the sea.',
          v: 'ungrammatical',
          why: 'בלי `did` הצורה היא `used to`: `I used to live near the sea`.',
          err: 'use_without_did',
        },
      ],
    },
    {
      id: 'S11-U-05',
      v: 1,
      skill: 'S11',
      unit: 'S11.used_to',
      sub: 'negative',
      type: 'correct',
      role: 'practice',
      stage: 3,
      ctx: 'work.meeting',
      fam: 'S11.didnt-use-to-meetings',
      goal: 'לספר על הבדל בין הצוות הקודם לצוות החדש',
      instr: INSTR_CORRECT,
      sitHe: 'בצוות הקודם שלך לא היו ישיבות בוקר. בצוות החדש יש ישיבה כל בוקר, ואתה מספר לחבר על ההבדל.',
      hint: 'אחרי `didn\'t` — `use` או `used`?',
      explain: 'המשפט תקין: אחרי `didn\'t` בא פועל בסיס — `use`, בלי d. `used` בא רק כשאין `did`: `We used to…`.',
      deep: 'זה אותו כלל כמו `We didn\'t have` (ולא `didn\'t had`): `did` כבר נושא את העבר, והפועל שאחריו חוזר לבסיס. לכן `didn\'t use to`. הכתיב `didn\'t used to` מופיע לפעמים בכתיבה לא רשמית, אבל ברוב המקורות הוא נחשב שגוי.',
      source: [
        { id: 's1', t: 'we' },
        { id: 's2', t: "didn't" },
        { id: 's3', t: 'use' },
        { id: 's4', t: 'to' },
        { id: 's5', t: 'have' },
        { id: 's6', t: 'morning meetings' },
      ],
      tokens: [
        {
          id: 't1',
          t: 'used',
          why: 'אחרי `didn\'t` בא פועל בסיס — `use`, בלי d. המשפט המקורי היה תקין.',
          err: 'did_used',
        },
        {
          id: 't2',
          t: 'had',
          why: 'אחרי `didn\'t` ואחרי `use to` בא פועל בסיס: `have`, לא `had`.',
          err: 'did_past',
        },
      ],
      accept: [
        { a: "We didn't use to have morning meetings", o: 'correct_target' },
        {
          a: "We didn't have morning meetings",
          o: 'valid_alternative',
          note: 'גם נכון — עבר פשוט. אבל המשפט המקורי היה תקין: אחרי `didn\'t` בא `use` בלי d.',
        },
      ],
      rules: [
        {
          has: ["didn't used"],
          as: 'form_error',
          err: 'did_used',
          fb: 'המשפט המקורי היה תקין: אחרי `didn\'t` בא פועל בסיס — `use`, בלי d. (`didn\'t used to` מופיע לפעמים בכתיבה לא רשמית, אבל ברוב המקורות נחשב שגוי.)',
        },
        {
          has: ['to had'],
          as: 'form_error',
          err: 'used_to_past',
          fb: 'אחרי `use to` בא פועל בסיס: `have`, לא `had`. המשפט המקורי היה תקין.',
        },
        {
          has: ["didn't had"],
          as: 'form_error',
          err: 'did_past',
          fb: 'אחרי `didn\'t` בא פועל בסיס: `didn\'t have`.',
        },
        {
          has: ['used to have'],
          lacks: ["didn't"],
          as: 'meaning_mismatch',
          err: 'affirmative_for_negative',
          fb: 'המשפט תקין, אבל הפוך: פירושו שפעם כן היו ישיבות בוקר. המשפט המקורי היה נכון: `We didn\'t use to have morning meetings`.',
        },
        {
          has: ['had'],
          lacks: ["didn't"],
          as: 'meaning_mismatch',
          err: 'affirmative_for_negative',
          fb: '`We had morning meetings` אומר שכן היו ישיבות — ההפך. המשפט המקורי היה נכון: `We didn\'t use to have morning meetings`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S11-U-C1',
      v: 2,
      skill: 'S11',
      unit: 'S11.used_to',
      sub: 'affirmative',
      type: 'assemble',
      role: 'check',
      stage: 2,
      ctx: 'work.software',
      fam: 'S11.used-to-print-reports',
      goal: 'לספר לעמית חדש על הרגל שהיה במשרד',
      instr: 'קרא את הסיטואציה ובנה משפט אחד באנגלית. לא חייבים להשתמש בכל המילים.',
      sitEn:
        'Five years ago, everyone in your office printed every report on paper. Today everything is digital. A new colleague asks how things were before. Tell him.',
      trHe: 'לפני חמש שנים כולם במשרד שלך הדפיסו כל דוח על נייר. היום הכול דיגיטלי. עמית חדש שואל איך היה פעם. ספר לו.',
      hint: 'הרגל שהיה ונגמר.',
      explain: 'הרגל שהיה ונגמר: `We used to print every report`. אחרי `used to` — פועל בסיס.',
      tokens: [
        { id: 't1', t: 'we' },
        { id: 't2', t: 'used' },
        { id: 't3', t: 'to' },
        { id: 't4', t: 'print' },
        { id: 't5', t: 'every report' },
        { id: 't6', t: 'use', why: 'בלי `did` הצורה היא `used to` (עם d).', err: 'use_without_did' },
        {
          id: 't7',
          t: 'printing',
          why: 'אחרי `used to` (הרגל בעבר) בא פועל בסיס: `print`, לא `printing`.',
          err: 'used_to_ing',
        },
        {
          id: 't8',
          t: 'are',
          why: '`are` לא מתאים כאן: ההרגל כבר נגמר — `We used to print…`. (`are used to` פירושו "רגילים ל…" — היום.)',
          err: 'be_used_to_for_past_habit',
        },
      ],
      accept: [{ a: 'We used to print every report', o: 'correct_target' }],
      wrong: [
        {
          a: 'We are used to printing every report',
          as: 'meaning_mismatch',
          err: 'be_used_to_for_past_habit',
          fb: 'המשפט תקין, אבל פירושו שאתם רגילים להדפיס כל דוח — היום. ההרגל נגמר: `We used to print every report`.',
        },
      ],
      rules: [
        {
          has: ['are used to print'],
          as: 'form_error',
          err: 'be_used_to_base',
          fb: 'אחרי `are used to` בא ing — אבל `are used to` פירושו "רגילים ל…". כאן הרגל שנגמר: `We used to print every report`.',
        },
        {
          has: ['used to printing'],
          lacks: ['are'],
          as: 'form_error',
          err: 'used_to_ing',
          fb: 'אחרי `used to` (הרגל בעבר) בא פועל בסיס: `used to print`.',
        },
        {
          has: ['print'],
          lacks: ['used', 'use'],
          as: 'meaning_mismatch',
          err: 'present_for_past_habit',
          fb: '`We print…` מתאר את מה שקורה היום. ההרגל נגמר: `We used to print every report`.',
        },
        {
          has: ['are printing'],
          as: 'meaning_mismatch',
          err: 'progressive_for_past_habit',
          fb: 'המשפט תקין, אבל `We are printing…` מתאר מה שקורה עכשיו. ההרגל נגמר: `We used to print every report`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S11-U-06',
      v: 1,
      skill: 'S11',
      unit: 'S11.used_to',
      sub: 'affirmative',
      type: 'assemble',
      role: 'practice',
      stage: 1,
      ctx: 'daily.family',
      fam: 'S11.used-to-guitar',
      goal: 'לספר שפעם ניגנת בגיטרה כל יום',
      instr: 'בנה את המשפט באנגלית. לא חייבים להשתמש בכל המילים.',
      promptHe: 'פעם הייתי מנגן בגיטרה כל יום.',
      sitHe: 'חבר רואה גיטרה בפינת החדר ושואל אם אתה מנגן. אתה מסביר שפעם ניגנת כל יום, אבל כבר שנים שלא נגעת בה.',
      target: 'הרגל בעבר עם `used to`',
      scaffold: ['used to', 'V (base)'],
      hint: 'הרגל שהיה ונגמר. אחרי `used to` בא פועל בסיס.',
      explain: 'הרגל מהעבר שהסתיים: `I used to play the guitar every day`. אחרי `used to` בא פועל בצורת בסיס.',
      deep: 'במשפט חיובי ללא `did`, כותבים `used` עם d: `used to play`. אחרי `used to` (הרגל בעבר) לא מוסיפים ing.',
      tokens: [
        { id: 't1', t: 'I' },
        { id: 't2', t: 'used' },
        { id: 't3', t: 'to' },
        { id: 't4', t: 'play' },
        { id: 't5', t: 'the guitar' },
        { id: 't6', t: 'every day' },
        { id: 't7', t: 'use', why: 'בלי `did` הצורה היא `used to` (עם d).', err: 'use_without_did' },
        {
          id: 't8',
          t: 'playing',
          why: 'אחרי `used to` (הרגל בעבר) בא פועל בסיס: `play`, לא `playing`.',
          err: 'used_to_ing',
        },
        { id: 't9', t: 'played' },
      ],
      accept: [
        { a: 'I used to play the guitar every day', o: 'correct_target' },
        { a: 'Every day I used to play the guitar', o: 'correct_target' },
        {
          a: 'I played the guitar every day',
          o: 'target_not_used',
          note: 'תקין — עבר פשוט. התרגיל ביקש להשתמש ב-`used to` כדי להדגיש שההרגל הסתיים.',
        },
      ],
      rules: [
        {
          has: ['to played'],
          as: 'form_error',
          err: 'used_to_past',
          fb: 'אחרי `used to` בא פועל בסיס: `play`, לא `played`.',
        },
        {
          has: ['used to playing'],
          as: 'form_error',
          err: 'used_to_ing',
          fb: 'אחרי `used to` להרגל בעבר בא פועל בסיס: `used to play`, לא `playing`.',
        },
        {
          has: ['use to'],
          as: 'form_error',
          err: 'use_without_did',
          fb: 'בלי `did` הצורה היא `used to` (עם d): `I used to play the guitar every day`.',
        },
        {
          has: ['play the guitar every day'],
          lacks: ['used', 'use'],
          as: 'meaning_mismatch',
          err: 'present_for_past_habit',
          fb: '`I play…` מתאר הרגל בהווה. אתה כבר לא מנגן: `I used to play the guitar every day`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S11-U-C2',
      v: 1,
      skill: 'S11',
      unit: 'S11.used_to',
      sub: 'question',
      type: 'assemble',
      role: 'check',
      stage: 2,
      ctx: 'work.job',
      fam: 'S11.used-to-travel-job',
      goal: 'לשאול עמית אם פעם הוא נהג לטוס הרבה במסגרת העבודה',
      instr: 'קרא את הסיטואציה ובנה את השאלה באנגלית. לא חייבים להשתמש בכל המילים.',
      sitEn:
        'A colleague knows every airport lounge and international flight routine. Ask him if he used to travel a lot for work.',
      trHe: 'עמית בצוות מכיר בעל פה כל טרקלין בשדות תעופה וכל נוהל טיסה. שאל אותו אם פעם הוא נהג לטוס הרבה לצרכי עבודה.',
      target: 'שאלה עם `did` + `use to`',
      hint: 'בשאלה בעבר נכנס `did`. מה קורה ל-`used` אחרי `did`?',
      explain: 'בשאלה עם `did` הפועל חוזר לצורת בסיס: `Did you use to travel a lot for work?` — `use` בלי d.',
      deep: 'בדיוק כמו `Did you see` ולא `Did you saw`, השאלה לוקחת `did` + בסיס: `Did you use to…`.',
      tokens: [
        { id: 't1', t: 'did' },
        { id: 't2', t: 'you' },
        { id: 't3', t: 'use' },
        { id: 't4', t: 'to' },
        { id: 't5', t: 'travel' },
        { id: 't6', t: 'a lot for work' },
        {
          id: 't7',
          t: 'used',
          why: 'אחרי `did` בא פועל בסיס — `use`, בלי d: `Did you use to travel…?`',
          err: 'did_used',
        },
        {
          id: 't8',
          t: 'traveled',
          why: 'אחרי `did` ואחרי `use to` בא פועל בסיס: `travel`, לא `traveled`.',
          err: 'did_past',
        },
      ],
      accept: [
        { a: 'Did you use to travel a lot for work', o: 'correct_target' },
        {
          a: 'Did you travel a lot for work',
          o: 'target_not_used',
          note: 'תקין — שאלה בעבר פשוט. התרגיל ביקש לשאול עם `use to` כדי להדגיש שמדובר בהרגל מהעבר.',
        },
      ],
      rules: [
        {
          has: ['did you used'],
          as: 'form_error',
          err: 'did_used',
          fb: 'אחרי `did` בא פועל בסיס: `use`, בלי d: `Did you use to travel a lot for work?`',
        },
        {
          has: ['did you traveled'],
          as: 'form_error',
          err: 'did_past',
          fb: 'אחרי `did` בא פועל בסיס: `Did you travel…?` או `Did you use to travel…?`',
        },
        {
          has: ['to traveled'],
          as: 'form_error',
          err: 'used_to_past',
          fb: 'אחרי `to` בא פועל בסיס: `travel`, לא `traveled`.',
        },
        {
          has: ['use to'],
          lacks: ['did'],
          as: 'form_error',
          err: 'use_without_did',
          fb: 'בשאלה בעבר נדרש `did`: `Did you use to travel a lot for work?`',
        },
      ],
      end: '?',
    },
    // ---------------------------------------------------------------- would
    {
      id: 'S11-W-01',
      v: 1,
      skill: 'S11',
      unit: 'S11.would',
      sub: 'affirmative',
      type: 'correct',
      role: 'practice',
      stage: 1,
      ctx: 'daily.past',
      fam: 'S11.would-flea-market',
      goal: 'לספר על הרגל קבוע מהעבר',
      instr: INSTR_CORRECT,
      sitHe: 'אתה מספר לחבר על השנים שגרת ליד יפו: בכל יום שישי הלכתם לשוק הפשפשים.',
      target: '`would` + פועל (הרגל בעבר)',
      scaffold: ['would', 'V (base)'],
      hint: 'מה בא אחרי `would` — גם כשהסיפור בעבר?',
      explain: 'אחרי `would` בא פועל בסיס: `we would visit`. העבר כבר מסומן ב-`would` — כמו `will visit` בעתיד.',
      deep: 'זו הטעות `We would visited`. `would` להרגל בעבר עובד כמו כל מודאלי: `would` + בסיס. בעברית "היינו מבקרים" — העבר נמצא ב"היינו", והפועל עצמו לא משתנה. גם עבר פשוט מתאים כאן: `On Fridays, we visited the flea market`.',
      source: [
        { id: 's1', t: 'on Fridays' },
        { id: 's2', t: 'we' },
        { id: 's3', t: 'would' },
        { id: 's4', t: 'visited' },
        { id: 's5', t: 'the flea market' },
      ],
      tokens: [
        { id: 't1', t: 'visit' },
        { id: 't2', t: 'to', why: 'אחרי `would` בא פועל בסיס ישירות, בלי `to`: `would visit`.', err: 'modal_to' },
      ],
      accept: [
        { a: 'On Fridays, we would visit the flea market', o: 'correct_target' },
        { a: 'We would visit the flea market on Fridays', o: 'correct_target' },
        {
          a: 'On Fridays, we visited the flea market',
          o: 'target_not_used',
          note: 'תקין — עבר פשוט מתאים גם להרגל בעבר. התרגיל ביקש לשמור על `would` ולתקן את הפועל שאחריו.',
        },
        {
          a: 'We visited the flea market on Fridays',
          o: 'target_not_used',
          note: 'תקין — עבר פשוט מתאים גם להרגל בעבר. התרגיל ביקש לשמור על `would` ולתקן את הפועל שאחריו.',
        },
      ],
      wrong: [
        {
          a: 'On Fridays we would visited the flea market',
          as: 'form_error',
          err: 'modal_past',
          fb: 'אחרי `would` בא פועל בסיס — גם כשמספרים על העבר: `we would visit`. העבר כבר מסומן ב-`would`.',
        },
      ],
      rules: [
        {
          has: ['would visited'],
          as: 'form_error',
          err: 'modal_past',
          fb: 'אחרי `would` בא פועל בסיס: `would visit`, לא `would visited`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S11-W-02',
      v: 1,
      skill: 'S11',
      unit: 'S11.would',
      sub: 'affirmative',
      type: 'assemble',
      role: 'practice',
      stage: 2,
      ctx: 'work.job',
      fam: 'S11.would-thursday-lunch',
      goal: 'לספר לעמית חדש על מסורת מהעבודה הראשונה שלך',
      instr: 'קרא את הסיטואציה והשלם את המשפט באנגלית. לא חייבים להשתמש בכל המילים.',
      sitEn:
        'At your first job there was a tradition: every Thursday, everyone ate lunch together in the office kitchen. Tell a new colleague about it.',
      trHe: 'בעבודה הראשונה שלך הייתה מסורת: בכל יום חמישי כולם אכלו יחד ארוחת צהריים במטבח המשרדי. ספר על זה לעמית חדש.',
      target: '`would` + פועל (הרגל בעבר)',
      hint: 'פעולה שחזרה כל שבוע בעבר.',
      explain: 'פעולה שחזרה בעבר: `we would eat lunch together every Thursday`. אחרי `would` — פועל בסיס.',
      deep: '`At my first job` כבר קובע שמדובר בעבר, ולכן `would` נשמע כאן כהרגל ולא כתנאי. גם `we used to eat…` וגם `we ate…` נכונים; `would` מתאים במיוחד כשמתארים "איך זה היה" בסיפור.',
      lead: 'At my first job,',
      tokens: [
        { id: 't1', t: 'we' },
        { id: 't2', t: 'would' },
        { id: 't3', t: 'eat' },
        { id: 't4', t: 'lunch together' },
        { id: 't5', t: 'every Thursday' },
        { id: 't6', t: 'ate' },
        { id: 't7', t: 'eating', why: 'אחרי `would` בא פועל בסיס: `eat`, לא `eating`.', err: 'modal_ing' },
      ],
      accept: [
        { a: 'we would eat lunch together every Thursday', o: 'correct_target' },
        { a: 'every Thursday we would eat lunch together', o: 'correct_target' },
        {
          a: 'we ate lunch together every Thursday',
          o: 'target_not_used',
          note: 'תקין — עבר פשוט מתאים גם לפעולה שחזרה. התרגיל ביקש את `would`.',
        },
        {
          a: 'every Thursday we ate lunch together',
          o: 'target_not_used',
          note: 'תקין — עבר פשוט מתאים גם לפעולה שחזרה. התרגיל ביקש את `would`.',
        },
      ],
      rules: [
        {
          has: ['would ate'],
          as: 'form_error',
          err: 'modal_past',
          fb: 'אחרי `would` בא פועל בסיס: `we would eat`. (בלי `would` — `we ate`.)',
        },
        {
          has: ['eat'],
          lacks: ['would'],
          as: 'meaning_mismatch',
          err: 'present_for_past_habit',
          fb: '`we eat…` מתאר מה שקורה היום. זה היה בעבודה הקודמת: `we would eat lunch together every Thursday`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S11-W-03',
      v: 1,
      skill: 'S11',
      unit: 'S11.would',
      sub: 'state_vs_action',
      type: 'discriminate',
      role: 'practice',
      stage: 3,
      ctx: 'daily.home',
      fam: 'S11.would-first-apartment',
      goal: 'לספר על הדירה הראשונה שלך',
      instr: 'בחר את כל המשפטים שנכונים ומתאימים לסיפור.',
      sitHe: 'אתה מספר על הדירה הראשונה שלך: היא הייתה קטנה מאוד, ובכל ערב השכן מלמעלה ניגן בפסנתר.',
      hint: 'אילו פעלים מתארים פעולה שחזרה, ואילו — מצב שנמשך?',
      explain: '`would` מתאר פעולה שחזרה (`would play`), לא מצב (`live`). למצב — `used to`.',
      deep: 'למה? `would` להרגל אומר "זה מה שהיה קורה שוב ושוב". מצב — לגור, להכיר, לאהוב, להיות בעל — לא "קורה שוב ושוב"; הוא פשוט נמשך. לכן `I would live there` לא נשמע כהרגל אלא כתנאי: "הייתי גר שם (אילו…)". `used to` מתאים לשניהם: `I used to live there` וגם `my neighbor used to play the piano`.',
      diff: '`would` — רק פעולה שחזרה. `used to` — פעולה שחזרה וגם מצב.',
      multi: true,
      options: [
        {
          id: 'a',
          en: 'I used to live in a tiny apartment.',
          v: 'fits',
          why: 'מצב שנמשך בעבר והסתיים: `used to live`. נכון.',
        },
        {
          id: 'b',
          en: 'I would live in a tiny apartment.',
          v: 'other_meaning',
          why: '`would` להרגל מתאים לפעולות שחזרו, לא למצב כמו `live`. המשפט נשמע כמו תנאי: "הייתי גר (אילו…)".',
          err: 'would_state',
        },
        {
          id: 'c',
          en: 'Every evening, my neighbor would play the piano.',
          v: 'fits',
          why: 'פעולה שחזרה שוב ושוב בעבר: `would play`. נכון.',
        },
        {
          id: 'd',
          en: 'Every evening, my neighbor would played the piano.',
          v: 'ungrammatical',
          why: 'אחרי `would` בא פועל בסיס: `would play`.',
          err: 'modal_past',
        },
      ],
    },
    {
      id: 'S11-W-04',
      v: 2,
      skill: 'S11',
      unit: 'S11.would',
      sub: 'affirmative',
      type: 'transform',
      role: 'practice',
      stage: 2,
      ctx: 'daily.health',
      fam: 'S11.would-run-beach',
      goal: 'לספר על שגרת אימונים מהעבר',
      instr: 'החלף את `used to` ב-`would`.',
      sitHe: 'אתה מספר על השנה שבה התאמנת לקראת מרתון: כל בוקר רצת לאורך החוף.',
      target: '`would` + פועל בסיס',
      fromLabel: '`used to`',
      toLabel: '`would`',
      hint: '`would` מחליף את `used to` כולו. מה נשאר מהפועל?',
      explain: 'לפעולה שחזרה, `would` יכול להחליף את `used to`: `Every morning, I would run along the beach`. אחרי `would` — פועל בסיס.',
      deep: 'ההחלפה עובדת כי `run` היא פעולה שחזרה כל בוקר. עם מצב (`live`, `know`) היא לא עובדת: `I used to live near the beach`, ולא `I would live…`. שים לב שנשאר רק `would` — בלי `used` ובלי `to`.',
      source: [
        { id: 's1', t: 'every morning' },
        { id: 's2', t: 'I' },
        { id: 's3', t: 'used', why: 'בגרסה עם `would` אין `used to`: `would` מחליף אותו.', err: 'would_used_to' },
        { id: 's4', t: 'to', why: 'אחרי `would` אין `to`; ה-`to` שייך ל-`used to`, ש-`would` מחליף.', err: 'modal_to' },
        { id: 's5', t: 'run' },
        { id: 's6', t: 'along the beach' },
      ],
      sourceEnd: '.',
      tokens: [
        { id: 't1', t: 'would' },
        { id: 't2', t: 'ran' },
        { id: 't3', t: 'running', why: 'אחרי `would` (וגם אחרי `used to`) בא פועל בסיס: `run`.', err: 'modal_ing' },
      ],
      accept: [
        { a: 'Every morning, I would run along the beach', o: 'correct_target' },
        { a: 'I would run along the beach every morning', o: 'correct_target' },
        {
          a: 'Every morning, I ran along the beach',
          o: 'target_not_used',
          note: 'תקין — עבר פשוט. התבקשת להשתמש ב-`would`.',
        },
        {
          a: 'I ran along the beach every morning',
          o: 'target_not_used',
          note: 'תקין — עבר פשוט. התבקשת להשתמש ב-`would`.',
        },
      ],
      wrong: [
        {
          a: 'Every morning I used to run along the beach',
          as: 'target_not_used',
          err: 'not_transformed',
          fb: 'המשפט תקין — `used to` מתאים כאן. התבקשת להחליף אותו ב-`would`, שמתאים גם הוא לפעולה שחזרה.',
        },
        {
          a: 'I used to run along the beach every morning',
          as: 'target_not_used',
          err: 'not_transformed',
          fb: 'המשפט תקין — `used to` מתאים כאן. התבקשת להחליף אותו ב-`would`, שמתאים גם הוא לפעולה שחזרה.',
        },
      ],
      rules: [
        {
          has: ['would', 'used'],
          as: 'form_error',
          err: 'would_used_to',
          fb: '`would` מחליף את `used to` — הם לא באים יחד: `I would run along the beach`.',
        },
        {
          has: ['would to'],
          as: 'form_error',
          err: 'modal_to',
          fb: 'אחרי `would` אין `to`: `I would run…`. ה-`to` שייך ל-`used to`, שהוחלף.',
        },
        {
          has: ['would ran'],
          as: 'form_error',
          err: 'modal_past',
          fb: 'אחרי `would` בא פועל בסיס: `would run`, לא `would ran`.',
        },
        {
          has: ['to ran'],
          as: 'form_error',
          err: 'used_to_past',
          fb: 'אחרי `used to` בא פועל בסיס: `used to run` — ובגרסה החדשה: `would run`.',
        },
        {
          has: ['I run'],
          as: 'meaning_mismatch',
          err: 'present_for_past_habit',
          fb: '`I run…` מתאר הרגל של היום. זה היה בשנה ההיא: `Every morning, I would run along the beach`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S11-W-C1',
      v: 1,
      skill: 'S11',
      unit: 'S11.would',
      sub: 'state_vs_action',
      type: 'correct',
      role: 'check',
      stage: 3,
      ctx: 'work.job',
      fam: 'S11.would-know-everyone',
      goal: 'לספר שפעם הכרת את כולם במשרד הקודם',
      instr: INSTR_CORRECT,
      sitHe: 'אתה מספר לעמית חדש על המשרד הקודם: הוא היה קטן, והכרת בו את כולם. בבניין החדש זה כבר לא כך.',
      hint: 'האם `know` היא פעולה שחוזרת — או מצב?',
      explain:
        '`know` הוא מצב, ו-`would` להרגל מתאים רק לפעולות. מצב בעבר: `I used to know everyone in the old office` (או `I knew…`).',
      source: [
        { id: 's1', t: 'I' },
        {
          id: 's2',
          t: 'would',
          why: '`would` להרגל מתאים לפעולות שחזרו, לא למצב כמו `know`. מצב בעבר: `used to know`.',
          err: 'would_state',
        },
        { id: 's3', t: 'know' },
        { id: 's4', t: 'everyone' },
        { id: 's5', t: 'in the old office' },
      ],
      tokens: [
        { id: 't1', t: 'used' },
        { id: 't2', t: 'to' },
        { id: 't3', t: 'knew' },
      ],
      accept: [
        { a: 'I used to know everyone in the old office', o: 'correct_target' },
        { a: 'In the old office, I used to know everyone', o: 'correct_target' },
        {
          a: 'I knew everyone in the old office',
          o: 'valid_alternative',
          note: 'גם נכון: עבר פשוט מתאים למצב בעבר. `used to` מדגיש שהיום זה כבר לא כך.',
        },
        {
          a: 'In the old office, I knew everyone',
          o: 'valid_alternative',
          note: 'גם נכון: עבר פשוט מתאים למצב בעבר. `used to` מדגיש שהיום זה כבר לא כך.',
        },
      ],
      wrong: [
        {
          a: 'I would know everyone in the old office',
          as: 'meaning_mismatch',
          err: 'would_state',
          fb: '`know` הוא מצב, לא פעולה שחוזרת — ו-`would` להרגל מתאים רק לפעולות. כך המשפט נשמע כמו תנאי ("הייתי מכיר…"). מצב בעבר: `I used to know everyone in the old office`.',
        },
      ],
      rules: [
        {
          has: ['would', 'used'],
          as: 'form_error',
          err: 'would_used_to',
          fb: '`would` ו-`used to` לא באים יחד. למצב בעבר: `I used to know everyone…`.',
        },
        {
          has: ['would knew'],
          as: 'form_error',
          err: 'modal_past',
          fb: 'אחרי `would` בא פועל בסיס — אבל כאן `would` בכלל לא מתאים, כי `know` הוא מצב: `I used to know…` או `I knew…`.',
        },
        {
          has: ['to knew'],
          as: 'form_error',
          err: 'used_to_past',
          fb: 'אחרי `used to` בא פועל בסיס: `used to know`.',
        },
        {
          has: ['would to'],
          as: 'form_error',
          err: 'modal_to',
          fb: 'אחרי `would` אין `to` — ובכל מקרה `would` לא מתאים למצב כמו `know`: `I used to know…`.',
        },
        {
          has: ['would know'],
          as: 'meaning_mismatch',
          err: 'would_state',
          fb: '`know` הוא מצב, ו-`would` להרגל מתאים רק לפעולות. מצב בעבר: `I used to know everyone in the old office`.',
        },
        {
          has: ['used know'],
          as: 'form_error',
          err: 'used_missing_to',
          fb: 'ב-`used to` ה-`to` נשאר: `I used to know…`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S11-W-05',
      v: 1,
      skill: 'S11',
      unit: 'S11.would',
      sub: 'affirmative',
      type: 'assemble',
      role: 'practice',
      stage: 2,
      ctx: 'daily.past',
      fam: 'S11.would-coffee-balcony',
      goal: 'לספר על שגרת בוקר נעימה שהייתה לך בעבר',
      instr: 'קרא את הסיטואציה והשלם את המשפט באנגלית. לא חייבים להשתמש בכל המילים.',
      sitEn:
        'In your previous apartment you had a quiet balcony. Every summer morning, you drank coffee there. Tell a friend about that routine.',
      trHe: 'בדירה הקודמת שלך הייתה מרפסת שקטה. בכל בוקר בקיץ היית שותה שם קפה. ספר לחבר על ההרגל הזה.',
      target: '`would` + פועל (הרגל בעבר)',
      hint: 'פעולה שחזרה באופן קבוע בעבר.',
      explain: 'פעולה שחזרה בעבר: `I would drink coffee on the balcony`. אחרי `would` בא פועל בסיס.',
      deep: 'הביטוי הפותח כבר מבהיר שמדובר בעבר, ולכן `would` מתאר הרגל נוסטלגי ("הייתי שותה קפה"). אחרי `would` תמיד פועל בסיס.',
      lead: 'Every summer morning,',
      tokens: [
        { id: 't1', t: 'I' },
        { id: 't2', t: 'would' },
        { id: 't3', t: 'drink' },
        { id: 't4', t: 'coffee on the balcony' },
        { id: 't5', t: 'drank' },
        {
          id: 't6',
          t: 'drinking',
          why: 'אחרי `would` בא פועל בסיס: `drink`, לא `drinking`.',
          err: 'modal_ing',
        },
      ],
      accept: [
        { a: 'I would drink coffee on the balcony', o: 'correct_target' },
        {
          a: 'I drank coffee on the balcony',
          o: 'target_not_used',
          note: 'תקין — עבר פשוט מתאים גם להרגל בעבר. התרגיל ביקש לתרגל את `would`.',
        },
      ],
      rules: [
        {
          has: ['would drank'],
          as: 'form_error',
          err: 'modal_past',
          fb: 'אחרי `would` בא פועל בסיס: `would drink`, לא `would drank`.',
        },
        {
          has: ['I drink'],
          as: 'meaning_mismatch',
          err: 'present_for_past_habit',
          fb: '`I drink…` מתאר מה שאתה עושה בהווה. בדירה הקודמת: `I would drink coffee on the balcony`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S11-W-C2',
      v: 1,
      skill: 'S11',
      unit: 'S11.would',
      sub: 'state_vs_action',
      type: 'discriminate',
      role: 'check',
      stage: 3,
      ctx: 'work.job',
      fam: 'S11.would-stay-late-pizza',
      goal: 'לתאר מה היה קורה כשהיה לחץ בעבודה הקודמת',
      instr: 'בחר את כל המשפטים שנכונים ומתאימים לסיטואציה.',
      sitHe: 'אתה מספר על תקופת עומס בעבודה הקודמת: בכל פעם שהתקרב מועד הגשה, הצוות היה נשאר עד מאוחר ומזמין פיצה.',
      hint: 'אילו פעלים מתארים פעולה חוזרת (action) ואילו מתארים מצב קבוע (state)?',
      explain:
        'פעולה שחזרה בעבר מתוארת ב-`would` או ב-`used to`: `the team would stay late`. פועל של מצב כמו `have` לא מתאים ל-`would` לתאר הרגל.',
      deep: '`would` מתאר רק פעולות שחזרו שוב ושוב (`stay`, `order`). מצבים נמשכים (`have a large room`, `be quiet`) דורשים `used to`.',
      diff: '`would` — פעולה שחזרה. `used to` — פעולה שחזרה וגם מצב.',
      multi: true,
      options: [
        {
          id: 'a',
          en: 'Before big deadlines, the team would stay late and order food.',
          v: 'fits',
          why: 'פעולה שחזרה שוב ושוב בעבר: `would stay` ו-`order`. נכון.',
        },
        {
          id: 'b',
          en: 'Before big deadlines, the team used to stay late and order food.',
          v: 'fits',
          why: '`used to` מתאים גם הוא להרגל של פעולה שחזרה בעבר. נכון.',
        },
        {
          id: 'c',
          en: 'Before big deadlines, the team would stayed late.',
          v: 'ungrammatical',
          why: 'אחרי `would` בא פועל בסיס: `would stay`, לא `would stayed`.',
          err: 'modal_past',
        },
        {
          id: 'd',
          en: 'Before big deadlines, the team would have a smaller office.',
          v: 'other_meaning',
          why: '`have an office` הוא מצב מתמשך (state), לא פעולה שחוזרת. עם `would` זה נשמע כמו תנאי ("היה להם משרד קטן יותר אילו..."). למצב בעבר משתמשים ב-`used to have`.',
          err: 'would_state',
        },
      ],
    },
    // ---------------------------------------------------------------- be used to
    {
      id: 'S11-B-01',
      v: 1,
      skill: 'S11',
      unit: 'S11.be_used_to',
      sub: 'affirmative',
      type: 'correct',
      role: 'practice',
      stage: 1,
      ctx: 'work.meeting',
      fam: 'S11.be-used-to-speaking',
      goal: 'לומר שעמיתה רגילה לדבר מול קהל',
      instr: INSTR_CORRECT,
      sitHe: 'עמיתה שלך מציגה בכנסים כבר שנים. מישהו שואל אם היא לחוצה לפני הרצאה. אתה אומר שלא — זה מוכר לה.',
      scaffold: ['is', 'used to', 'V-ing / noun'],
      hint: 'אחרי `be used to` — איזו צורה של הפועל?',
      explain:
        'אחרי `be used to` בא ing (או שם עצם): `She is used to speaking in front of large audiences`. ה-`to` כאן היא מילת יחס.',
      deep: 'בעברית "רגילה לדבר" — שם פועל, ולכן מתחשק לכתוב `to speak`. אבל ב-`be used to` ה-`to` היא מילת יחס, כמו ב-`used to the noise`, ואחריה בא שם עצם או ing. `She used to speak…` (בלי `is`) הוא מבנה אחר: פעם, והיום כבר לא.',
      source: [
        { id: 's1', t: 'she' },
        { id: 's2', t: 'is' },
        { id: 's3', t: 'used' },
        { id: 's4', t: 'to' },
        {
          id: 's5',
          t: 'speak',
          why: 'אחרי `be used to` בא ing (`speaking`) או שם עצם — לא פועל בסיס.',
          err: 'be_used_to_base',
        },
        { id: 's6', t: 'in front of large audiences' },
      ],
      tokens: [
        { id: 't1', t: 'speaking' },
        {
          id: 't2',
          t: 'use',
          why: 'הכתיב הוא `used` (עם d), גם כשבדיבור ה-d כמעט לא נשמעת.',
          err: 'use_spelling',
        },
      ],
      accept: [{ a: 'She is used to speaking in front of large audiences', o: 'correct_target' }],
      wrong: [
        {
          a: 'She is used to speak in front of large audiences',
          as: 'form_error',
          err: 'be_used_to_base',
          fb: 'אחרי `be used to` בא ing (או שם עצם): `She is used to speaking…`. ה-`to` כאן היא מילת יחס, לא חלק מפועל.',
        },
        {
          a: 'She used to speak in front of large audiences',
          as: 'meaning_mismatch',
          err: 'used_to_for_accustomed',
          fb: 'המשפט תקין, אבל פירושו שפעם היא הרצתה והיום כבר לא. היא עדיין מרצה ורגילה לזה: `She is used to speaking…`.',
        },
      ],
      rules: [
        {
          has: ['used to speaking'],
          lacks: ['is'],
          as: 'form_error',
          err: 'missing_be',
          fb: 'חסר `is`: "רגילה ל…" = `is used to` + ing: `She is used to speaking…`.',
        },
        {
          has: ['is speaking'],
          as: 'meaning_mismatch',
          err: 'progressive_for_accustomed',
          fb: '`She is speaking…` מתאר מה שקורה עכשיו. "רגילה ל…": `She is used to speaking in front of large audiences`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S11-B-02',
      v: 2,
      skill: 'S11',
      unit: 'S11.be_used_to',
      sub: 'affirmative',
      type: 'assemble',
      role: 'practice',
      stage: 1,
      ctx: 'daily.travel',
      fam: 'S11.be-used-to-long-drives',
      goal: 'לומר שנסיעות ארוכות לא מפריעות לך',
      instr: 'בנה את המשפט באנגלית. לא חייבים להשתמש בכל המילים.',
      promptHe: 'אני רגיל לנסיעות ארוכות.',
      sitHe: 'חבר שואל אם שלוש שעות נהיגה לאילת לא מעייפות אותך. אתה נוהג הרבה, וזה מוכר לך.',
      scaffold: ['am', 'used to', 'V-ing / noun'],
      hint: 'אחרי `am used to` בא שם עצם — או פועל עם ing.',
      explain: 'רגיל ל…: `am used to` + שם עצם (`long drives`) או ing (`driving long distances`). פועל בסיס לא בא כאן.',
      tokens: [
        { id: 't1', t: 'I' },
        { id: 't2', t: 'am' },
        { id: 't3', t: 'used' },
        { id: 't4', t: 'to' },
        { id: 't5', t: 'long drives' },
        { id: 't6', t: 'driving' },
        { id: 't7', t: 'long distances' },
        {
          id: 't8',
          t: 'drive',
          why: 'אחרי `be used to` בא ing (`driving`) או שם עצם — לא פועל בסיס.',
          err: 'be_used_to_base',
        },
        {
          id: 't9',
          t: 'use',
          why: 'הכתיב הוא `used` (עם d), גם כשבדיבור ה-d כמעט לא נשמעת.',
          err: 'use_spelling',
        },
      ],
      accept: [
        { a: 'I am used to long drives', o: 'correct_target' },
        { a: 'I am used to driving long distances', o: 'correct_target' },
        { a: 'I am used to long distances', o: 'correct_target' },
      ],
      rules: [
        {
          has: ['used to drive'],
          lacks: ['am'],
          as: 'meaning_mismatch',
          err: 'used_to_for_accustomed',
          fb: 'המשפט תקין, אבל פירושו שפעם נהגת למרחקים ארוכים והיום כבר לא. "רגיל ל…": `I am used to…`.',
        },
        {
          has: ['used to'],
          lacks: ['am'],
          as: 'form_error',
          err: 'missing_be',
          fb: 'חסר `am`: "רגיל ל…" = `am used to` + שם עצם או ing. (`I used to` בלי `am` פירושו הרגל שנגמר, ואחריו פועל בסיס.)',
        },
        {
          has: ['I drive long distances'],
          as: 'meaning_mismatch',
          err: 'lost_accustomed',
          fb: 'המשפט תקין, אבל הוא רק אומר שאתה נוהג למרחקים ארוכים. צריך לומר שזה מוכר לך: `I am used to long drives`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S11-B-03',
      v: 1,
      skill: 'S11',
      unit: 'S11.be_used_to',
      sub: 'contrast',
      type: 'discriminate',
      role: 'practice',
      stage: 3,
      ctx: 'work.project',
      fam: 'S11.be-used-to-deadlines',
      goal: 'להסביר למה מועד הגשה קרוב לא מלחיץ אותך',
      instr: 'בחר את המשפט שנכון ומתאים לסיטואציה.',
      sitHe: 'אתה עובד כבר שנים בפרויקטים עם לוחות זמנים לחוצים. עמית חדש מופתע שאתה רגוע יום לפני ההגשה.',
      hint: 'אתה כבר רגיל — לא "פעם", ולא "בתהליך".',
      explain: 'רגיל ל…: `I\'m used to tight deadlines`. `I used to…` = פעם, והיום לא; `getting used to` = עדיין בתהליך.',
      deep: 'שלושה מבנים דומים: `I used to have tight deadlines` — פעם היו, היום לא. `I\'m getting used to tight deadlines` — אני מתרגל, עוד לא לגמרי. `I\'m used to tight deadlines` — זה כבר מוכר לי. ואחרי `be used to` לא בא פועל בסיס: `used to working`, לא `used to work`.',
      multi: false,
      options: [
        {
          id: 'a',
          en: "I'm used to tight deadlines.",
          v: 'fits',
          why: '`be used to` + שם עצם: זה מוכר לך, ולכן אתה רגוע. מתאים.',
        },
        {
          id: 'b',
          en: 'I used to have tight deadlines.',
          v: 'other_meaning',
          why: 'המשפט תקין, אבל פירושו שפעם היו לך מועדים לחוצים, והיום כבר לא.',
          err: 'used_to_for_accustomed',
        },
        {
          id: 'c',
          en: "I'm used to work under pressure.",
          v: 'ungrammatical',
          why: 'אחרי `be used to` בא ing או שם עצם: `I\'m used to working under pressure`.',
          err: 'be_used_to_base',
        },
        {
          id: 'd',
          en: "I'm getting used to tight deadlines.",
          v: 'other_meaning',
          why: 'המשפט תקין, אבל `getting used to` אומר שאתה עדיין בתהליך ההתרגלות — ואתה כבר רגיל.',
          err: 'get_for_be',
        },
      ],
    },
    {
      id: 'S11-B-04',
      v: 1,
      skill: 'S11',
      unit: 'S11.be_used_to',
      sub: 'question',
      type: 'assemble',
      role: 'practice',
      stage: 2,
      ctx: 'work.schedule',
      fam: 'S11.be-used-to-morning-shift',
      goal: 'לשאול עמיתה אם משמרת הבוקר כבר מוכרת לה',
      instr: 'קרא את הסיטואציה ובנה שאלה אחת באנגלית. לא חייבים להשתמש בכל המילים.',
      sitEn:
        'Two months ago, your colleague moved from the evening shift to the morning shift. Ask her if the new shift feels normal to her now.',
      trHe: 'לפני חודשיים העמיתה שלך עברה ממשמרת ערב למשמרת בוקר. שאל אותה אם המשמרת החדשה כבר מרגישה לה רגילה.',
      hint: 'השאלה נבנית עם `be`, שעובר לפני `you`.',
      explain: 'שאלה עם `be used to`: `Are you used to the morning shift yet?` — `are` לפני `you`, בלי `do`.',
      deep: '`be used to` מתנהג כמו כל משפט עם `be`: בשאלה `are` עובר לפני הנושא, ואין צורך ב-`do`. `yet` בסוף השאלה פירושו "כבר". לשאלה על התהליך אפשר גם `Are you getting used to the morning shift?`',
      tokens: [
        { id: 't1', t: 'are' },
        { id: 't2', t: 'you' },
        { id: 't3', t: 'used' },
        { id: 't4', t: 'to' },
        { id: 't5', t: 'the morning shift' },
        { id: 't6', t: 'yet' },
        { id: 't7', t: 'do', why: 'השאלה נבנית עם `be`, לא עם `do`: `Are you used to…?`', err: 'do_with_be' },
        { id: 't8', t: 'use', why: 'הכתיב הוא `used` (עם d): `Are you used to…?`', err: 'use_spelling' },
      ],
      accept: [
        { a: 'Are you used to the morning shift yet', o: 'correct_target' },
        { a: 'Are you used to the morning shift', o: 'correct_target' },
      ],
      rules: [
        {
          order: ['you', 'are'],
          has: ['yet'],
          as: 'form_error',
          err: 'no_inversion',
          fb: 'בשאלה `are` בא לפני `you`: `Are you used to the morning shift yet?`',
        },
      ],
      end: '?',
    },
    {
      id: 'S11-B-05',
      v: 2,
      skill: 'S11',
      unit: 'S11.be_used_to',
      sub: 'affirmative',
      type: 'correct',
      role: 'practice',
      stage: 3,
      ctx: 'work.municipality',
      fam: 'S11.be-used-to-same-questions',
      goal: 'להסביר לעמית חדש למה הפקידות בדלפק רגועות',
      instr: INSTR_CORRECT,
      sitHe: 'בדלפק הקבלה בעירייה עונים כל יום על אותן שאלות. עמית חדש מתפלא שהפקידות לא מתעצבנות, ואתה מסביר לו.',
      hint: 'אחרי `be used to` — פועל בסיס, או ing?',
      explain:
        'המשפט תקין: אחרי `be used to` בא ing (או שם עצם) — `They are used to answering…`. פועל בסיס בא רק אחרי `used to` בלי `be`, בהרגל שנגמר.',
      deep: 'שני מבנים שנראים כמעט אותו דבר: `They used to answer` — פעם ענו, והיום כבר לא (פועל בסיס). `They are used to answering` — הן רגילות לענות (ing, כי `to` כאן היא מילת יחס). כאן מדובר במה שנכון היום, ולכן `are used to answering`.',
      source: [
        { id: 's1', t: 'they' },
        { id: 's2', t: 'are' },
        { id: 's3', t: 'used' },
        { id: 's4', t: 'to' },
        { id: 's5', t: 'answering' },
        { id: 's6', t: 'the same questions' },
        { id: 's7', t: 'every day' },
      ],
      tokens: [
        {
          id: 't1',
          t: 'answer',
          why: 'אחרי `be used to` בא ing (`answering`) או שם עצם — לא פועל בסיס. המשפט המקורי היה תקין.',
          err: 'be_used_to_base',
        },
      ],
      accept: [
        { a: 'They are used to answering the same questions every day', o: 'correct_target' },
        {
          a: 'They are used to the same questions every day',
          o: 'valid_alternative',
          note: 'גם נכון: אחרי `be used to` יכול לבוא גם שם עצם (`the same questions`). אבל המשפט המקורי היה תקין כמו שהוא.',
        },
      ],
      rules: [
        {
          has: ['used to answer'],
          lacks: ['are'],
          as: 'meaning_mismatch',
          err: 'used_to_for_accustomed',
          fb: 'המשפט תקין, אבל פירושו שפעם הן ענו על השאלות האלה והיום כבר לא. המשפט המקורי היה נכון: `They are used to answering…`.',
        },
        {
          has: ['are used to answer'],
          as: 'form_error',
          err: 'be_used_to_base',
          fb: 'המשפט המקורי היה תקין: אחרי `be used to` בא ing — `answering`. ה-`to` כאן היא מילת יחס.',
        },
        {
          has: ['used to answering'],
          lacks: ['are'],
          as: 'form_error',
          err: 'missing_be',
          fb: 'חסר `are`: "רגילות ל…" = `are used to` + ing. המשפט המקורי היה תקין.',
        },
        {
          has: ['they answer'],
          as: 'meaning_mismatch',
          err: 'lost_accustomed',
          fb: 'המשפט תקין, אבל הוא רק מתאר מה הן עושות. המשפט המקורי אמר את מה שצריך — שהן רגילות לזה: `They are used to answering…`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S11-B-C1',
      v: 2,
      skill: 'S11',
      unit: 'S11.be_used_to',
      sub: 'negative',
      type: 'assemble',
      role: 'check',
      stage: 2,
      ctx: 'daily.food',
      fam: 'S11.be-used-to-early-dinner',
      goal: 'לומר למארחים שארוחת ערב מוקדמת מוזרה לך',
      instr: 'קרא את הסיטואציה ובנה משפט אחד באנגלית. לא חייבים להשתמש בכל המילים.',
      sitEn:
        'You are staying with friends abroad. They always have dinner at five in the afternoon. At home you eat at eight or nine. Tell them how it feels to you.',
      trHe: 'אתה מתארח אצל חברים בחו"ל. הם תמיד אוכלים ארוחת ערב בחמש אחר הצהריים; בבית אתה אוכל בשמונה או בתשע. ספר להם איך זה מרגיש לך.',
      hint: 'זה לא מוכר לך. איך שוללים "רגיל ל…"?',
      explain: 'לא רגיל ל…: `I am not used to eating dinner so early`. שוללים את `be`, ואחרי `used to` בא ing או שם עצם.',
      tokens: [
        { id: 't1', t: 'I' },
        { id: 't2', t: 'am' },
        { id: 't3', t: 'not' },
        { id: 't4', t: 'used' },
        { id: 't5', t: 'to' },
        { id: 't6', t: 'eating' },
        { id: 't7', t: 'dinner' },
        { id: 't8', t: 'so early' },
        {
          id: 't9',
          t: 'eat',
          why: 'אחרי `be used to` בא ing (`eating`) או שם עצם — לא פועל בסיס.',
          err: 'be_used_to_base',
        },
        {
          id: 't10',
          t: "didn't",
          why: 'את "לא רגיל ל…" שוללים דרך `be`: `I am not used to…`. `didn\'t use to` הוא השלילה של הרגל בעבר — משמעות אחרת.',
          err: 'didnt_use_to_for_accustomed',
        },
        { id: 't11', t: 'use', why: 'הכתיב הוא `used` (עם d): `I am not used to…`.', err: 'use_spelling' },
      ],
      accept: [
        { a: 'I am not used to eating dinner so early', o: 'correct_target' },
        { a: 'I am not used to eating so early', o: 'correct_target' },
        { a: 'I am not used to dinner so early', o: 'correct_target' },
      ],
      wrong: [
        {
          a: "I didn't use to eat dinner so early",
          as: 'meaning_mismatch',
          err: 'didnt_use_to_for_accustomed',
          fb: 'המשפט תקין, אבל פירושו שבעבר לא היה לך הרגל כזה. אתה רוצה לומר שזה מוזר לך עכשיו: `I am not used to eating dinner so early`.',
        },
      ],
      rules: [
        {
          has: ["didn't use to eat"],
          as: 'meaning_mismatch',
          err: 'didnt_use_to_for_accustomed',
          fb: 'המשפט תקין, אבל פירושו שבעבר לא היה לך הרגל כזה. אתה רוצה לומר שזה מוזר לך עכשיו: `I am not used to eating dinner so early`.',
        },
        {
          has: ['not used to'],
          lacks: ['am'],
          as: 'form_error',
          err: 'missing_be',
          fb: 'חסר `am`: `I am not used to…`.',
        },
        {
          has: ['am used to'],
          lacks: ['not'],
          as: 'meaning_mismatch',
          err: 'affirmative_for_negative',
          fb: 'המשפט אומר שאתה כן רגיל — ההפך. `I am not used to eating dinner so early`.',
        },
      ],
      end: '.',
    },
    // ---------------------------------------------------------------- get used to
    {
      id: 'S11-G-01',
      v: 2,
      skill: 'S11',
      unit: 'S11.get_used_to',
      sub: 'progressive',
      type: 'assemble',
      role: 'practice',
      stage: 1,
      ctx: 'daily.travel',
      fam: 'S11.get-used-to-train',
      goal: 'לומר שאתה מתרגל לנסוע ברכבת לעבודה',
      instr: 'בנה את המשפט באנגלית. לא חייבים להשתמש בכל המילים.',
      promptHe: 'אני מתרגל לנסוע ברכבת לעבודה.',
      sitHe: 'לפני חודש מכרת את הרכב, ועכשיו אתה נוסע לעבודה ברכבת. זה עדיין חדש לך.',
      scaffold: ['am', 'getting', 'used to', 'V-ing / noun'],
      hint: 'תהליך שקורה עכשיו: `am getting used to`, ואחריו ing.',
      explain: 'תהליך של התרגלות, עכשיו: `I am getting used to taking the train to work`. אחרי `used to` כאן בא ing.',
      deep: '`get used to` = נהיה רגיל. בצורה המתמשכת (`am getting`) הוא מתאר תהליך שקורה עכשיו, בהדרגה. `I am used to…` היה אומר שהתהליך כבר הסתיים — אתה כבר רגיל.',
      tokens: [
        { id: 't1', t: 'I' },
        { id: 't2', t: 'am' },
        { id: 't3', t: 'getting' },
        { id: 't4', t: 'used' },
        { id: 't5', t: 'to' },
        { id: 't6', t: 'taking' },
        { id: 't7', t: 'the train to work' },
        { id: 't8', t: 'take', why: 'אחרי `get used to` בא ing: `taking`, לא `take`.', err: 'get_used_to_base' },
        { id: 't9', t: 'use', why: 'הכתיב הוא `used`: `getting used to`.', err: 'use_spelling' },
      ],
      accept: [
        { a: 'I am getting used to taking the train to work', o: 'correct_target' },
        { a: 'I am getting used to the train to work', o: 'correct_target' },
      ],
      wrong: [
        {
          a: 'I am used to taking the train to work',
          as: 'meaning_mismatch',
          err: 'be_for_get',
          fb: 'המשפט תקין, אבל פירושו שאתה כבר רגיל. זה עדיין חדש לך: `I am getting used to taking the train to work`.',
        },
      ],
      rules: [
        {
          has: ['used to take'],
          lacks: ['am'],
          as: 'meaning_mismatch',
          err: 'used_to_for_process',
          fb: 'המשפט תקין, אבל פירושו שפעם נסעת ברכבת והיום כבר לא. מתרגל: `I am getting used to taking the train to work`.',
        },
        {
          has: ['getting used to'],
          lacks: ['am'],
          as: 'form_error',
          err: 'missing_be',
          fb: 'חסר `am`: `I am getting used to…`.',
        },
        {
          has: ['used to taking'],
          lacks: ['am'],
          as: 'form_error',
          err: 'missing_be',
          fb: 'חסרים `am getting`: `I am getting used to taking the train to work`.',
        },
        {
          has: ['am taking'],
          as: 'meaning_mismatch',
          err: 'progressive_for_process',
          fb: '`I am taking the train` מתאר מה אתה עושה, לא את ההתרגלות: `I am getting used to taking the train to work`.',
        },
        {
          has: ['am used to'],
          lacks: ['take'],
          as: 'meaning_mismatch',
          err: 'be_for_get',
          fb: 'המשפט תקין, אבל פירושו שאתה כבר רגיל. זה עדיין חדש לך: `I am getting used to taking the train to work`.',
        },
        {
          has: ['I take'],
          as: 'meaning_mismatch',
          err: 'present_for_process',
          fb: '`I take the train to work` רק מתאר מה אתה עושה, לא את ההתרגלות: `I am getting used to taking the train to work`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S11-G-02',
      v: 2,
      skill: 'S11',
      unit: 'S11.get_used_to',
      sub: 'future',
      type: 'correct',
      role: 'practice',
      stage: 1,
      ctx: 'work.clinic',
      fam: 'S11.get-used-to-waking-early',
      goal: 'להרגיע עובד חדש שיתרגל לקום מוקדם',
      instr: INSTR_CORRECT,
      sitHe: 'עובד חדש במרפאה מתחיל במשמרת בוקר ומתלונן שקשה לו לקום בחמש וחצי. אתה מרגיע אותו.',
      scaffold: ['will', 'get', 'used to', 'V-ing / noun'],
      hint: 'אחרי `get used to` — איזו צורה של הפועל?',
      explain: 'אחרי `get used to` בא ing (או שם עצם): `You will get used to waking up early`. ה-`to` כאן היא מילת יחס.',
      deep: 'אותו כלל כמו ב-`be used to`: `to` כאן היא מילת יחס, ולכן `waking up`, לא `wake up`. `will` נשאר עם בסיס — `will get` — כי `get` הוא הפועל שבא אחרי המודאלי.',
      source: [
        { id: 's1', t: 'you' },
        { id: 's2', t: 'will' },
        { id: 's3', t: 'get' },
        { id: 's4', t: 'used' },
        { id: 's5', t: 'to' },
        {
          id: 's6',
          t: 'wake up',
          why: 'אחרי `get used to` בא ing: `waking up`, לא `wake up`.',
          err: 'get_used_to_base',
        },
        { id: 's7', t: 'early' },
      ],
      tokens: [
        { id: 't1', t: 'waking up' },
        { id: 't2', t: 'use', why: 'הכתיב הוא `used`: `get used to`.', err: 'use_spelling' },
      ],
      accept: [
        { a: 'You will get used to waking up early', o: 'correct_target' },
        {
          a: 'You get used to waking up early',
          o: 'valid_alternative',
          note: 'גם נכון: הווה פשוט כללי — "מתרגלים לזה". `You will get used to…` מדגיש שזה יקרה גם לו.',
        },
      ],
      wrong: [
        {
          a: 'You will get used to wake up early',
          as: 'form_error',
          err: 'get_used_to_base',
          fb: 'אחרי `get used to` בא ing (או שם עצם): `You will get used to waking up early`. ה-`to` כאן היא מילת יחס.',
        },
      ],
      rules: [
        {
          has: ['wake up'],
          lacks: ['used'],
          as: 'meaning_mismatch',
          err: 'prediction_for_reassurance',
          fb: '`You will wake up early` הוא רק תחזית. כדי להרגיע — שזה יהפוך לרגיל: `You will get used to waking up early`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S11-G-03',
      v: 1,
      skill: 'S11',
      unit: 'S11.get_used_to',
      sub: 'past',
      type: 'assemble',
      role: 'practice',
      stage: 2,
      ctx: 'work.software',
      fam: 'S11.got-used-to-system',
      goal: 'לספר שהתרגלת מהר למערכת החדשה',
      instr: 'קרא את הסיטואציה ובנה משפט אחד באנגלית. לא חייבים להשתמש בכל המילים.',
      sitEn:
        'Last month your office switched to a new booking system. The first days were confusing, but after a week it felt normal. A colleague from another branch asks how it went. Tell her.',
      trHe: 'בחודש שעבר המשרד שלכם עבר למערכת זימונים חדשה. הימים הראשונים היו מבלבלים, אבל אחרי שבוע זה כבר הרגיש רגיל. עמיתה מסניף אחר שואלת איך היה. ספר לה.',
      hint: 'התהליך כבר הסתיים — בעבר.',
      explain: 'תהליך שהסתיים: `I got used to the new system quickly`. `got` הוא העבר של `get`.',
      deep: '`get used to` בעבר: `I got used to it`. עכשיו, בסוף התהליך, אפשר גם לומר `I\'m used to it now`. ב-present perfect שומעים `I\'ve gotten used to it` (אמריקאית) וגם `I\'ve got used to it` (בריטית) — שתי הצורות תקינות.',
      tokens: [
        { id: 't1', t: 'I' },
        { id: 't2', t: 'got' },
        { id: 't3', t: 'used' },
        { id: 't4', t: 'to' },
        { id: 't5', t: 'the new system' },
        { id: 't6', t: 'quickly' },
        { id: 't7', t: 'use', why: 'הכתיב הוא `used`: `got used to`.', err: 'use_spelling' },
        {
          id: 't8',
          t: 'getting',
          why: '`getting` מתאר תהליך שעדיין נמשך (ודורש `am` לפניו). כאן התהליך כבר הסתיים: `I got used to…`.',
          err: 'getting_for_finished',
        },
      ],
      accept: [
        { a: 'I got used to the new system quickly', o: 'correct_target' },
        { a: 'I quickly got used to the new system', o: 'correct_target' },
        { a: 'I got used to the new system', o: 'correct_target' },
      ],
      rules: [
        {
          has: ['used to'],
          lacks: ['got', 'getting'],
          as: 'form_error',
          err: 'missing_get',
          fb: 'חסר `got`: התרגלתי = `I got used to…`. (`I used to` + פועל בסיס הוא הרגל בעבר — מבנה אחר.)',
        },
      ],
      end: '.',
    },
    {
      id: 'S11-G-04',
      v: 1,
      skill: 'S11',
      unit: 'S11.get_used_to',
      sub: 'contrast',
      type: 'transform',
      role: 'practice',
      stage: 3,
      ctx: 'work.schedule',
      fam: 'S11.getting-used-to-schedule',
      goal: 'לתאר התרגלות שעדיין נמשכת',
      instr: 'שנה את המשפט כך שיתאר תהליך שעדיין נמשך.',
      sitHe: 'לפני שבועיים עברתם ללוח משמרות חדש. זה עדיין לא לגמרי טבעי לך, אבל כל שבוע קל יותר.',
      target: 'תהליך: `am getting used to`',
      fromLabel: 'מצב: רגיל ל…',
      toLabel: 'תהליך: מתרגל ל…',
      hint: 'תהליך שקורה עכשיו — איזו צורה של `get`?',
      explain: 'תהליך שעדיין נמשך: `I am getting used to the new schedule`. `am used to` = כבר רגיל; `got used to` = התהליך הסתיים.',
      deep: 'שלוש נקודות על אותו ציר: `I am getting used to it` — בתהליך; `I got used to it` — התהליך הסתיים; `I am used to it` — המצב שבסוף. כאן, אחרי שבועיים ועם כל שבוע קל יותר, מתאים התהליך.',
      diff: '`am used to` — כבר רגיל (מצב). `am getting used to` — מתרגל (תהליך).',
      source: [
        { id: 's1', t: 'I' },
        { id: 's2', t: 'am' },
        { id: 's3', t: 'used' },
        { id: 's4', t: 'to' },
        { id: 's5', t: 'the new schedule' },
      ],
      sourceEnd: '.',
      tokens: [
        { id: 't1', t: 'getting' },
        {
          id: 't2',
          t: 'get',
          why: 'לתהליך שקורה עכשיו צריך את הצורה המתמשכת: `am getting used to`.',
          err: 'get_form',
        },
        {
          id: 't3',
          t: 'got',
          why: '`got used to` אומר שהתהליך כבר הסתיים. כאן הוא עדיין נמשך: `am getting used to`.',
          err: 'got_for_getting',
          as: 'meaning_mismatch',
        },
      ],
      accept: [{ a: 'I am getting used to the new schedule', o: 'correct_target' }],
      wrong: [
        {
          a: 'I am used to the new schedule',
          as: 'target_not_used',
          err: 'not_transformed',
          fb: 'המשפט תקין — אבל הוא אומר שכבר התרגלת. התבקשת לתאר תהליך שעדיין נמשך: `I am getting used to the new schedule`.',
        },
        {
          a: 'I got used to the new schedule',
          as: 'meaning_mismatch',
          err: 'got_for_getting',
          fb: 'המשפט תקין, אבל `got used to` אומר שהתהליך כבר הסתיים. הוא עדיין נמשך: `I am getting used to the new schedule`.',
        },
      ],
      rules: [
        {
          has: ['am get'],
          as: 'form_error',
          err: 'be_get_base',
          fb: 'אחרי `am` בא `getting`: `I am getting used to…`.',
        },
        {
          has: ['am got'],
          as: 'form_error',
          err: 'be_got',
          fb: '`am got` אינו מבנה תקין כאן. תהליך שנמשך: `I am getting used to…`.',
        },
        {
          has: ['getting used'],
          lacks: ['am'],
          as: 'form_error',
          err: 'missing_be',
          fb: 'חסר `am`: `I am getting used to…`.',
        },
        {
          has: ['I get used'],
          as: 'meaning_mismatch',
          err: 'simple_for_process',
          fb: '`I get used to…` בהווה פשוט מתאר הרגל כללי. להתרגלות שקורית עכשיו: `I am getting used to the new schedule`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S11-G-C1',
      v: 2,
      skill: 'S11',
      unit: 'S11.get_used_to',
      sub: 'future',
      type: 'assemble',
      role: 'check',
      stage: 2,
      ctx: 'daily.home',
      fam: 'S11.get-used-to-rain',
      goal: 'להרגיע חברה שעברה לעיר גשומה',
      instr: 'קרא את הסיטואציה ובנה משפט אחד באנגלית. לא חייבים להשתמש בכל המילים.',
      sitEn:
        'Your friend just moved from Tel Aviv to a city where it rains almost every day. She finds the weather hard. Reassure her: after a while, it will feel normal.',
      trHe: 'חברה שלך עברה עכשיו מתל אביב לעיר שבה יורד גשם כמעט כל יום. קשה לה עם מזג האוויר. הרגע אותה: אחרי זמן מה זה ירגיש לה רגיל.',
      hint: 'בעתיד זה יהפוך למוכר.',
      explain: 'תהליך שעוד יקרה: `You will get used to the rain`. אחרי `will` — `get`, ואחרי `used to` — שם עצם או ing.',
      tokens: [
        { id: 't1', t: 'you' },
        { id: 't2', t: 'will' },
        { id: 't3', t: 'get' },
        { id: 't4', t: 'used' },
        { id: 't5', t: 'to' },
        { id: 't6', t: 'the rain' },
        { id: 't7', t: 'soon' },
        { id: 't8', t: 'use', why: 'הכתיב הוא `used`: `get used to`.', err: 'use_spelling' },
        {
          id: 't9',
          t: 'getting',
          why: '`getting` לא מתאים כאן: אחרי `will` בא פועל בסיס — `You will get used to the rain`.',
          err: 'modal_ing',
        },
      ],
      accept: [
        { a: 'You will get used to the rain', o: 'correct_target' },
        { a: 'You will soon get used to the rain', o: 'correct_target' },
        { a: 'You will get used to the rain soon', o: 'correct_target' },
        { a: 'Soon, you will get used to the rain', o: 'correct_target' },
        {
          a: 'You get used to the rain',
          o: 'valid_alternative',
          note: 'גם נכון: הווה פשוט כללי — "מתרגלים לזה". `You will get used to…` מדגיש שזה יקרה גם לה.',
        },
        {
          a: 'You soon get used to the rain',
          o: 'valid_alternative',
          note: 'גם נכון: הווה פשוט כללי — "מתרגלים לזה מהר". `You will get used to…` מדגיש שזה יקרה גם לה.',
        },
      ],
      rules: [
        {
          has: ['used to'],
          lacks: ['get', 'getting'],
          as: 'form_error',
          err: 'missing_get',
          fb: 'חסר `get`: להתרגל = `get used to`. `You will get used to the rain`.',
        },
      ],
      end: '.',
    },
    // ---------------------------------------------------------------- dialogues
    {
      id: 'S11-B-D1',
      v: 2,
      skill: 'S11',
      unit: 'S11.be_used_to',
      sub: 'dialogue',
      type: 'dialogue',
      role: 'practice',
      stage: 2,
      ctx: 'work.job',
      fam: 'S11.dialogue-early-start',
      goal: 'להסביר לעמית חדש למה אתה מגיע מוקדם',
      instr: 'ענה לדן בכל תור.',
      partnerName: 'Dan',
      setupHe: 'דן, עמית חדש, שם לב שאתה תמיד מגיע ראשון למשרד, כבר בשבע וחצי.',
      hint: 'בתור הראשון — מה היה קורה כל יום בעבודה הקודמת (`would`). בתור השני — מה מוכר לך היום (`be used to`).',
      explain: 'הרגל בעבר: `we would start at seven every day`. רגיל ל…: `I am used to getting up early`.',
      turns: [
        {
          partner: {
            en: "You're always the first one here. How do you do it?",
            he: 'אתה תמיד הראשון כאן. איך אתה עושה את זה?',
          },
          unit: 'S11.would',
          sub: 'affirmative',
          instr: 'ספר לו שבעבודה הקודמת שלך התחלתם לעבוד כל יום בשבע.',
          target: '`would` + פועל (הרגל בעבר)',
          hint: 'פעולה שחזרה כל יום בעבר: `would` + פועל בסיס.',
          explain: 'הרגל בעבר: `At my old job, we would start at seven every day`. אחרי `would` — פועל בסיס.',
          build: {
            lead: 'At my old job,',
            tokens: [
              { id: 't1', t: 'we' },
              { id: 't2', t: 'would' },
              { id: 't3', t: 'start' },
              { id: 't4', t: 'at seven' },
              { id: 't5', t: 'every day' },
              { id: 't6', t: 'used' },
              { id: 't7', t: 'to' },
              {
                id: 't8',
                t: 'starting',
                why: 'אחרי `would` — וגם אחרי `used to` — בא פועל בסיס: `start`.',
                err: 'modal_ing',
              },
            ],
            accept: [
              { a: 'we would start at seven every day', o: 'correct_target' },
              { a: 'every day we would start at seven', o: 'correct_target' },
              {
                a: 'we used to start at seven every day',
                o: 'target_not_used',
                note: 'נכון לגמרי — `used to` מתאים לכל הרגל בעבר. כאן התבקשת לתרגל את `would`.',
              },
              {
                a: 'every day we used to start at seven',
                o: 'target_not_used',
                note: 'נכון לגמרי — `used to` מתאים לכל הרגל בעבר. כאן התבקשת לתרגל את `would`.',
              },
              { a: 'we would start every day at seven', o: 'correct_target' },
              {
                a: 'we used to start every day at seven',
                o: 'target_not_used',
                note: 'נכון לגמרי — `used to` מתאים לכל הרגל בעבר. כאן התבקשת לתרגל את `would`.',
              },
            ],
            rules: [
              {
                has: ['would to'],
                as: 'form_error',
                err: 'modal_to',
                fb: 'אחרי `would` אין `to`: `we would start…`.',
              },
              {
                has: ['would', 'used'],
                as: 'form_error',
                err: 'would_used_to',
                fb: '`would` ו-`used to` לא באים יחד — בוחרים אחד: `we would start…` או `we used to start…`.',
              },
              {
                has: ['used start'],
                as: 'form_error',
                err: 'used_missing_to',
                fb: 'ב-`used to` ה-`to` נשאר: `we used to start…`.',
              },
            ],
            end: '.',
          },
        },
        {
          partner: {
            en: "Wow. Isn't it hard for you to get up so early?",
            he: 'וואו. לא קשה לך לקום כל כך מוקדם?',
          },
          sub: 'affirmative',
          instr: 'ענה שלא — אתה רגיל לקום מוקדם.',
          hint: 'רגיל ל… = `am used to` + ing או שם עצם.',
          explain: 'רגיל למשהו: `I am used to getting up early`. אחרי `be used to` בא ing — או שם עצם, כמו `it`.',
          build: {
            tokens: [
              { id: 't1', t: 'I' },
              { id: 't2', t: 'am' },
              { id: 't3', t: 'used' },
              { id: 't4', t: 'to' },
              { id: 't5', t: 'getting up' },
              { id: 't6', t: 'early' },
              { id: 't7', t: 'it' },
              {
                id: 't8',
                t: 'get up',
                why: 'אחרי `be used to` בא ing (`getting up`) או שם עצם — לא פועל בסיס.',
                err: 'be_used_to_base',
              },
              { id: 't9', t: 'use', why: 'הכתיב הוא `used` (עם d).', err: 'use_spelling' },
            ],
            accept: [
              { a: 'I am used to getting up early', o: 'correct_target' },
              { a: 'I am used to it', o: 'correct_target' },
            ],
            rules: [
              {
                has: ['used to get up'],
                lacks: ['am'],
                as: 'meaning_mismatch',
                err: 'used_to_for_accustomed',
                fb: 'המשפט תקין, אבל פירושו שפעם קמת מוקדם והיום כבר לא. רגיל ל…: `I am used to getting up early`.',
              },
              {
                has: ['used to'],
                lacks: ['am'],
                as: 'form_error',
                err: 'missing_be',
                fb: 'חסר `am`: "רגיל ל…" = `am used to` + ing או שם עצם.',
              },
              {
                has: ['I get up'],
                as: 'meaning_mismatch',
                err: 'lost_accustomed',
                fb: 'המשפט תקין, אבל הוא רק מתאר מה אתה עושה. דן שאל אם זה קשה לך — ענה שאתה רגיל: `I am used to getting up early`.',
              },
            ],
            end: '.',
          },
        },
      ],
      closing: {
        en: 'Lucky you. I need three alarms just to get out of bed.',
        he: 'יופי לך. אני צריך שלושה שעונים מעוררים רק כדי לצאת מהמיטה.',
      },
    },
    {
      id: 'S11-G-D1',
      v: 2,
      skill: 'S11',
      unit: 'S11.get_used_to',
      sub: 'dialogue',
      type: 'dialogue',
      role: 'practice',
      stage: 2,
      ctx: 'daily.home',
      fam: 'S11.dialogue-village',
      goal: 'לספר לחברה ותיקה על החיים אחרי המעבר',
      instr: 'ענה לתמר בכל תור.',
      partnerName: 'Tamar',
      setupHe: 'לפני חודשיים עברת מהעיר הגדולה לכפר קטן בצפון. תמר, חברה ותיקה, מתקשרת לשאול מה שלומך.',
      hint: 'בתור הראשון — הרגל שהיה ונגמר (`used to`). בתור השני — התרגלות שעדיין נמשכת (`getting used to`).',
      explain: 'הרגל שנגמר: `I used to eat out every weekend`. תהליך שנמשך: `I am still getting used to the quiet`.',
      turns: [
        {
          partner: {
            en: 'So how is village life? Do you still eat out every weekend?',
            he: 'נו, איך החיים בכפר? אתה עדיין יוצא לאכול בחוץ כל סוף שבוע?',
          },
          unit: 'S11.used_to',
          sub: 'affirmative',
          instr: 'ענה שכבר לא — זה היה ההרגל שלך בעיר.',
          hint: 'הרגל שהיה ונגמר: `used to` + פועל בסיס.',
          explain: 'הרגל שנגמר: `I used to eat out every weekend`. אחרי `used to` — פועל בסיס.',
          build: {
            lead: 'Not anymore.',
            tokens: [
              { id: 't1', t: 'I' },
              { id: 't2', t: 'used' },
              { id: 't3', t: 'to' },
              { id: 't4', t: 'eat out' },
              { id: 't5', t: 'every weekend' },
              { id: 't6', t: 'use', why: 'בלי `did` הצורה היא `used to` (עם d).', err: 'use_without_did' },
              {
                id: 't7',
                t: 'eating out',
                why: 'אחרי `used to` (הרגל בעבר) בא פועל בסיס: `eat out`.',
                err: 'used_to_ing',
              },
              {
                id: 't8',
                t: 'am',
                why: '`am used to` פירושו "רגיל ל…" — היום. כאן הרגל שנגמר: `I used to eat out…`.',
                err: 'be_used_to_for_past_habit',
              },
            ],
            accept: [{ a: 'I used to eat out every weekend', o: 'correct_target' }],
            rules: [
              {
                has: ['am used to eating out'],
                as: 'meaning_mismatch',
                err: 'be_used_to_for_past_habit',
                fb: 'המשפט תקין, אבל פירושו שאתה רגיל לאכול בחוץ — היום. ההרגל נגמר: `I used to eat out every weekend`.',
              },
              {
                has: ['am used to eat out'],
                as: 'form_error',
                err: 'be_used_to_base',
                fb: 'אחרי `am used to` בא ing — אבל כאן בכלל צריך הרגל שנגמר: `I used to eat out every weekend`.',
              },
              {
                has: ['eat out'],
                lacks: ['used', 'use'],
                as: 'meaning_mismatch',
                err: 'present_for_past_habit',
                fb: 'זה מתאר מה שאתה עושה היום — אבל כבר לא. הרגל שנגמר: `I used to eat out every weekend`.',
              },
              {
                has: ['am eating out'],
                as: 'meaning_mismatch',
                err: 'progressive_for_past_habit',
                fb: 'המשפט תקין, אבל `I am eating out…` מתאר מה שקורה עכשיו — וזה בדיוק מה שכבר לא קורה. הרגל שנגמר: `I used to eat out every weekend`.',
              },
            ],
            end: '.',
          },
        },
        {
          partner: {
            en: 'I knew it. And what about the quiet? No traffic at all?',
            he: 'ידעתי. ומה עם השקט? בלי תנועה בכלל?',
          },
          sub: 'progressive',
          instr: 'ספר לה שזה עדיין קצת מוזר לך — אתה עדיין מתרגל לשקט.',
          hint: 'תהליך שעדיין נמשך: `am` + `getting used to` + שם עצם.',
          explain: 'תהליך שנמשך: `I am still getting used to the quiet`. אחרי `used to` כאן בא שם עצם (או ing).',
          build: {
            tokens: [
              { id: 't1', t: 'I' },
              { id: 't2', t: 'am' },
              { id: 't3', t: 'still' },
              { id: 't4', t: 'getting' },
              { id: 't5', t: 'used' },
              { id: 't6', t: 'to' },
              { id: 't7', t: 'the quiet' },
              {
                id: 't8',
                t: 'get',
                why: 'לתהליך שקורה עכשיו צריך את הצורה המתמשכת: `am getting used to`.',
                err: 'get_form',
              },
              { id: 't9', t: 'use', why: 'הכתיב הוא `used`: `getting used to`.', err: 'use_spelling' },
            ],
            accept: [
              { a: 'I am still getting used to the quiet', o: 'correct_target' },
              { a: 'I am getting used to the quiet', o: 'correct_target' },
            ],
            rules: [
              {
                has: ['used to'],
                lacks: ['am'],
                as: 'form_error',
                err: 'missing_be',
                fb: 'חסר `am`: `I am still getting used to the quiet`.',
              },
              {
                has: ['used to the quiet'],
                lacks: ['getting', 'get'],
                as: 'meaning_mismatch',
                err: 'be_for_get',
                fb: 'המשפט הזה אומר שאתה כבר רגיל. אתה עדיין בתהליך: `I am still getting used to the quiet`.',
              },
            ],
            end: '.',
          },
        },
      ],
      closing: {
        en: "Give it a few more weeks. Soon you won't be able to sleep in the city.",
        he: 'תן לזה עוד כמה שבועות. בקרוב לא תצליח לישון בעיר.',
      },
    },
  ],
};
