import type { SkillPack } from '../schema';

/**
 * S12 ACTIVE_PASSIVE — who performs the action vs what receives it, in the present perfect:
 * `has approved` (active) / `has been approved` (passive) / `has been approving` (active continuous).
 * New unit: it opens with an explicit bridge from `have been working`.
 */

const CHAIN = ['has / have', 'been', 'V3'];

export const S12: SkillPack = {
  skill: 'S12',
  lessons: [
    {
      unit: 'S12',
      title: 'מי אישר, ומה אושר: `has approved` / `has been approved`',
      short:
        '`The manager has approved the change` — מי שעשה את הפעולה (המנהל) בא ראשון. `The change has been approved` — מה שקיבל את הפעולה (השינוי) בא ראשון, והמבנה הוא `has / have` + `been` + V3.',
      chain: CHAIN,
      examples: [
        { en: 'The manager has approved the change.', he: 'המנהל אישר את השינוי.', note: 'פעיל — מי עשה את הפעולה.' },
        {
          en: 'The change has been approved (by the manager).',
          he: 'השינוי אושר (על ידי המנהל).',
          note: 'סביל — מה קיבל את הפעולה.',
        },
        {
          en: 'The manager has been approving requests all morning.',
          he: 'המנהל מאשר בקשות כל הבוקר.',
          note: 'פעיל מתמשך — הוא עושה את הפעולה, וזה נמשך.',
        },
      ],
      contrast: {
        a: { en: 'The change has been approved.', he: 'השינוי אושר — הוא קיבל את הפעולה.' },
        b: {
          en: 'The manager has been approving requests all morning.',
          he: 'המנהל מאשר בקשות כל הבוקר — הוא עושה את הפעולה.',
        },
        note: 'אותן מילים, `has been`, ומה שבא אחריהן נקבע לפי המשמעות: V3 כשהנושא קיבל את הפעולה (סביל), ing כשהנושא עושה אותה לאורך זמן (פעיל מתמשך).',
      },
      deep:
        '• גשר: נתקלת ב-`The change has been approved` באמצע תרגול של `have been working`, בלי הסבר. זה לא אותו מבנה: `has been working` — מישהו עובד (פעיל, מתמשך); `has been approved` — משהו אושר (סביל).\n' +
        '• פעיל: הנושא הוא מי שעושה — `The manager has approved the change`. סביל: הנושא הוא מה שקיבל את הפעולה — `The change has been approved`. המושא של המשפט הפעיל הופך לנושא של הסביל.\n' +
        '• הסביל נבנה מ-`be` + V3. ב-present perfect ה-`be` הופך ל-`been`: `has / have` + `been` + V3. `has` או `have` לפי הנושא החדש: `The change has…`, `The documents have…`.\n' +
        '• `by` + מי שעשה — רק כשזה מוסיף מידע: `The change has been approved by the manager`. כשלא יודעים מי עשה, או שזה לא חשוב, משמיטים אותו.\n' +
        '• אחרי `been` לא תמיד בא ing, וגם לא תמיד V3 — המשמעות מחליטה. הנושא עושה את הפעולה לאורך זמן: `been approving`. הנושא קיבל את הפעולה: `been approved`.\n' +
        '• עם זמן שהסתיים (`yesterday`) גם הסביל בעבר פשוט: `The change was approved yesterday`.',
      pitfalls: [
        '`The change has approved` — בלי `been` המשפט אומר שהשינוי אישר משהו.',
        '`The change has been approve` — אחרי `been` בסביל בא V3: `approved`.',
        '`The manager has been approved the change` — המנהל עושה את הפעולה: `has approved` (או `has been approving`).',
      ],
    },
  ],
  examples: {
    S12: [
      { en: 'The contract has been signed by both sides.', he: 'החוזה נחתם על ידי שני הצדדים.' },
      { en: 'Has the meeting been moved to Thursday?', he: 'הפגישה הועברה ליום חמישי?' },
      { en: 'The files have not been uploaded yet.', he: 'הקבצים עוד לא הועלו.' },
      {
        en: 'She has been answering calls all day.',
        he: 'היא עונה לשיחות כל היום.',
        note: 'פעיל מתמשך — היא עושה את הפעולה.',
      },
    ],
  },
  items: [
    {
      id: 'S12-01',
      v: 2,
      skill: 'S12',
      unit: 'S12',
      sub: 'passive_transform',
      type: 'transform',
      role: 'practice',
      stage: 1,
      ctx: 'work.project',
      fam: 'S12.budget-maya',
      goal: 'להפוך משפט פעיל לסביל: מה אושר',
      instr: 'הפוך את המשפט לסביל שמתחיל ב-`the new budget`.',
      sitHe: 'מאיה אישרה את התקציב החדש. עכשיו אתה רוצה לשים במרכז את התקציב — לא את מאיה.',
      target: 'סביל: `has / have` + `been` + V3',
      scaffold: CHAIN,
      fromLabel: 'פעיל — מי עשה',
      toLabel: 'סביל — מה קיבל את הפעולה',
      hint: 'הנושא החדש: `the new budget`. אחריו `has` ← `been` ← `approved`. את מאיה אפשר להוסיף עם `by`, או להשמיט.',
      explain:
        'בסביל מה שקיבל את הפעולה בא ראשון: `The new budget has been approved (by Maya)`. אחרי `been` בא כאן V3, כי התקציב לא עושה את הפעולה.',
      deep: 'המושא של המשפט הפעיל (`the new budget`) הופך לנושא. `has` נשאר (הנושא ביחיד), נוסף `been`, והפועל נשאר V3: `approved`. `by Maya` הוא תוספת — מוסיפים אותו כשחשוב לומר מי אישר.',
      source: [
        { id: 's1', t: 'Maya' },
        { id: 's2', t: 'has' },
        { id: 's3', t: 'approved' },
        { id: 's4', t: 'the new budget' },
      ],
      sourceEnd: '.',
      tokens: [
        { id: 't1', t: 'been' },
        { id: 't2', t: 'by' },
        {
          id: 't3',
          t: 'being',
          why: '`being` לא בא אחרי `has`. ב-present perfect: `has been` + V3.',
          err: 'being_for_been',
        },
        {
          id: 't4',
          t: 'have',
          why: '`the new budget` ו-`Maya` ביחיד, ולכן `has`, לא `have`.',
          err: 'have_agreement',
        },
        {
          id: 't5',
          t: 'approving',
          why: '`been approving` מתאר מישהו שעושה את הפעולה ועדיין באמצע. כאן התקציב כבר אושר, והוא מה שקיבל את הפעולה: `has been approved`.',
          err: 'ing_for_passive',
          as: 'meaning_mismatch',
        },
      ],
      accept: [
        { a: 'The new budget has been approved by Maya', o: 'correct_target' },
        { a: 'The new budget has been approved', o: 'correct_target' },
      ],
      wrong: [
        {
          a: 'Maya has approved the new budget',
          as: 'target_not_used',
          err: 'not_transformed',
          fb: 'המשפט הפעיל תקין, אבל התבקשת להפוך אותו לסביל: `The new budget has been approved (by Maya)`.',
        },
      ],
      rules: [
        {
          has: ['the new budget has approved'],
          as: 'form_error',
          err: 'passive_missing_been',
          fb: 'בלי `been` המשפט אומר שהתקציב אישר משהו. בסביל: `The new budget has been approved`.',
        },
        {
          has: ['Maya has been approved the new budget'],
          as: 'form_error',
          err: 'agent_as_passive_subject',
          fb: 'מאיה היא מי שאישרה, ולכן היא לא הנושא של `has been approved` — ואחרי `has been approved` לא בא מושא כמו `the new budget`. הסביל מתחיל במה שאושר: `The new budget has been approved by Maya`.',
        },
        {
          has: ['Maya has been approved'],
          as: 'meaning_mismatch',
          err: 'agent_as_passive_subject',
          fb: 'המשפט תקין, אבל `Maya has been approved` אומר שמאיה עצמה אושרה (למשל לתפקיד). היא זו שאישרה. הסביל מתחיל במה שאושר: `The new budget has been approved by Maya`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S12-02',
      v: 1,
      skill: 'S12',
      unit: 'S12',
      sub: 'passive_affirmative',
      type: 'assemble',
      role: 'practice',
      stage: 1,
      ctx: 'work.report',
      fam: 'S12.documents-signed',
      goal: 'לומר שהמסמכים כבר נחתמו',
      instr: 'בנה את המשפט באנגלית. לא חייבים להשתמש בכל המילים.',
      promptHe: 'המסמכים כבר נחתמו.',
      sitHe: 'המסמכים חתומים ומוכנים לשליחה. לא חשוב מי חתם עליהם.',
      scaffold: CHAIN,
      hint: '`the documents` ברבים, ולכן `have`. אחריו `been` ו-V3. `already` נכנס אחרי `have`.',
      explain:
        'המסמכים קיבלו את הפעולה, ומי שחתם לא חשוב: `The documents have already been signed`. ברבים — `have`.',
      deep: 'מסמכים לא חותמים — חותמים עליהם, ולכן סביל: `have been signed`. `already` בא בדרך כלל בין `have` ל-`been`. בעברית "נחתמו" הוא עבר, אבל כשהחשוב הוא המצב עכשיו (המסמכים חתומים ומוכנים), באנגלית משתמשים ב-present perfect.',
      tokens: [
        { id: 't1', t: 'the documents' },
        { id: 't2', t: 'have' },
        { id: 't3', t: 'already' },
        { id: 't4', t: 'been' },
        { id: 't5', t: 'signed' },
        { id: 't6', t: 'has', why: '`the documents` ברבים, ולכן `have`, לא `has`.', err: 'have_agreement' },
        {
          id: 't7',
          t: 'signing',
          why: '`been signing` אומר שמישהו חותם (פעיל, מתמשך). המסמכים לא חותמים — חותמים עליהם: `been signed`.',
          err: 'ing_for_passive',
          as: 'meaning_mismatch',
        },
        { id: 't8', t: 'sign', why: '`sign` היא צורת הבסיס. אחרי `been` בסביל בא V3: `signed`.', err: 'base_for_v3' },
      ],
      accept: [
        { a: 'The documents have already been signed', o: 'correct_target' },
        {
          a: 'The documents have been signed',
          o: 'valid_alternative',
          note: 'נכון גם בלי `already`. המילה מוסיפה את ה"כבר" שבמשפט.',
        },
        {
          a: 'The documents have been signed already',
          o: 'valid_alternative',
          note: 'גם נכון: `already` בסוף המשפט — מדובר יותר.',
        },
      ],
      rules: [
        {
          has: ['signed'],
          lacks: ['been'],
          as: 'form_error',
          err: 'passive_missing_been',
          fb: 'בלי `been` המשפט אומר שהמסמכים חתמו על משהו. בסביל: `have been signed`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S12-03',
      v: 2,
      skill: 'S12',
      unit: 'S12',
      sub: 'passive_no_agent',
      type: 'transform',
      role: 'practice',
      stage: 1,
      ctx: 'work.email',
      fam: 'S12.invitations-sent',
      goal: 'לומר שההזמנות נשלחו, בלי לציין מי שלח',
      instr: 'הפוך לסביל שמתחיל ב-`the invitations`. מי ששלח לא ידוע — אין צורך להזכיר אותו.',
      sitHe: 'ההזמנות לכנס כבר נשלחו. אתה לא יודע מי שלח אותן.',
      target: 'סביל: `have` + `been` + V3',
      scaffold: CHAIN,
      fromLabel: 'פעיל',
      toLabel: 'סביל',
      hint: '`the invitations` ברבים, ולכן `have`. את `someone` משמיטים.',
      explain: 'כשלא יודעים מי עשה, הסביל פשוט משמיט אותו: `The invitations have been sent`. הנושא החדש ברבים, ולכן `have`.',
      deep: 'בפעיל חייבים נושא, ולכן אומרים `someone`. בסביל אין בו צורך: `The invitations have been sent`. `by someone` כמעט אף פעם לא נאמר — הוא לא מוסיף מידע. שים לב גם ש-`has` הופך ל-`have`: הנושא החדש ברבים.',
      source: [
        {
          id: 's1',
          t: 'someone',
          why: '`someone` לא נחוץ בסביל: כשלא יודעים מי עשה את הפעולה, פשוט משמיטים אותו.',
          err: 'agent_kept',
        },
        { id: 's2', t: 'has', why: '`the invitations` ברבים, ולכן `have`, לא `has`.', err: 'have_agreement' },
        { id: 's3', t: 'sent' },
        { id: 's4', t: 'the invitations' },
      ],
      sourceEnd: '.',
      tokens: [
        { id: 't1', t: 'have' },
        { id: 't2', t: 'been' },
        { id: 't3', t: 'send', why: '`send` היא צורת הבסיס. אחרי `been` בסביל בא V3: `sent`.', err: 'base_for_v3' },
        { id: 't4', t: 'being', why: '`being` לא בא אחרי `have`. ב-present perfect: `have been` + V3.', err: 'being_for_been' },
      ],
      accept: [{ a: 'The invitations have been sent', o: 'correct_target' }],
      wrong: [
        {
          a: 'Someone has sent the invitations',
          as: 'target_not_used',
          err: 'not_transformed',
          fb: 'המשפט הפעיל תקין, אבל התבקשת להפוך אותו לסביל: `The invitations have been sent`.',
        },
      ],
      rules: [
        {
          starts: 'someone has been',
          as: 'meaning_mismatch',
          err: 'agent_as_passive_subject',
          fb: 'כש-`someone` הוא הנושא של `has been sent`, המשפט אומר שמישהו נשלח, או שמישהו קיבל את ההזמנות. הסביל מתחיל במה שנשלח: `The invitations have been sent`.',
        },
        {
          has: ['the invitations have sent'],
          as: 'form_error',
          err: 'passive_missing_been',
          fb: 'בלי `been` המשפט אומר שההזמנות שלחו משהו. בסביל: `The invitations have been sent`.',
        },
        {
          has: ['the invitations has'],
          as: 'form_error',
          err: 'have_agreement',
          fb: '`the invitations` ברבים: `The invitations have been sent`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S12-04',
      v: 1,
      skill: 'S12',
      unit: 'S12',
      sub: 'passive_affirmative',
      type: 'assemble',
      role: 'practice',
      stage: 1,
      ctx: 'work.schedule',
      fam: 'S12.appointment-rescheduled',
      goal: 'להודיע שתור נקבע מחדש',
      instr: 'בנה את המשפט באנגלית. לא חייבים להשתמש בכל המילים.',
      promptHe: 'התור שלך נקבע מחדש ליום שלישי.',
      sitHe: 'אתה עונה לטלפון במשרד ומודיע למי שמתקשר שהתור שלו הועבר ליום שלישי. לא חשוב מי שינה אותו.',
      scaffold: CHAIN,
      hint: 'התור קיבל את הפעולה, ולכן הוא הנושא: `has` ← `been` ← V3.',
      explain: 'התור לא קבע כלום — קבעו אותו מחדש: `Your appointment has been rescheduled for Tuesday`.',
      deep: 'המבנה זהה לכל סביל ב-present perfect: `has / have` + `been` + V3. בהודעות על שינויים (`has been rescheduled`, `has been canceled`, `has been moved`) הסביל נפוץ מאוד, כי מה שחשוב הוא מה השתנה — לא מי שינה.',
      tokens: [
        { id: 't1', t: 'your appointment' },
        { id: 't2', t: 'has' },
        { id: 't3', t: 'been' },
        { id: 't4', t: 'rescheduled' },
        { id: 't5', t: 'for Tuesday' },
        { id: 't6', t: 'have', why: '`your appointment` ביחיד, ולכן `has`, לא `have`.', err: 'have_agreement' },
        {
          id: 't7',
          t: 'rescheduling',
          why: '`been rescheduling` אומר שהתור עצמו קובע משהו מחדש (פעיל, מתמשך). התור קיבל את הפעולה: `has been rescheduled`.',
          err: 'ing_for_passive',
          as: 'meaning_mismatch',
        },
        { id: 't8', t: 'being', why: '`being` לא בא אחרי `has`. ב-present perfect: `has been` + V3.', err: 'being_for_been' },
      ],
      accept: [{ a: 'Your appointment has been rescheduled for Tuesday', o: 'correct_target' }],
      rules: [
        {
          has: ['rescheduled'],
          lacks: ['been'],
          as: 'form_error',
          err: 'passive_missing_been',
          fb: 'בלי `been` המשפט אומר שהתור קבע משהו מחדש. בסביל: `has been rescheduled`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S12-05',
      v: 1,
      skill: 'S12',
      unit: 'S12',
      sub: 'passive_affirmative',
      type: 'assemble',
      role: 'practice',
      stage: 2,
      ctx: 'work.software',
      fam: 'S12.system-updated',
      goal: 'להודיע למשתמשים שהמערכת עודכנה',
      instr: 'בנה משפט אחד באנגלית להודעה.',
      sitHe: 'אחרי שבוע של תקלות, המערכת עודכנה סוף סוף ועובדת כמו שצריך. אתה כותב הודעה קצרה לכל המשתמשים. מי עדכן — לא חשוב.',
      hint: 'מה קיבל את הפעולה? זה הנושא.',
      explain:
        'המערכת קיבלה את הפעולה, ומי שעדכן לא חשוב: `The system has finally been updated`. אחרי `been` בא V3, כי המערכת לא מעדכנת.',
      deep: '`finally` נכנס בדרך כלל בין `has` ל-`been`, כמו `already`. אם היית מציין מתי זה קרה (`last night`), היית עובר לעבר פשוט: `The system was updated last night`.',
      tokens: [
        { id: 't1', t: 'the system' },
        { id: 't2', t: 'has' },
        { id: 't3', t: 'finally' },
        { id: 't4', t: 'been' },
        { id: 't5', t: 'updated' },
        {
          id: 't6',
          t: 'updating',
          why: '`been updating` מתאר פעולה שנמשכת — כאילו המערכת עדיין באמצע עדכון. העדכון הסתיים, והמערכת קיבלה אותו: `has been updated`.',
          err: 'ing_for_passive',
          as: 'meaning_mismatch',
        },
        { id: 't7', t: 'have', why: '`the system` ביחיד, ולכן `has`, לא `have`.', err: 'have_agreement' },
      ],
      accept: [
        { a: 'The system has finally been updated', o: 'correct_target' },
        { a: 'The system has been updated', o: 'correct_target' },
        {
          a: 'Finally, the system has been updated',
          o: 'valid_alternative',
          note: 'גם נכון: `finally` בתחילת המשפט.',
        },
      ],
      end: '.',
    },
    {
      id: 'S12-06',
      v: 1,
      skill: 'S12',
      unit: 'S12',
      sub: 'contrast',
      type: 'discriminate',
      role: 'practice',
      stage: 3,
      ctx: 'work.job',
      fam: 'S12.approving-requests',
      goal: 'לתאר מנהלת שעדיין באמצע אישור בקשות',
      instr: 'בחר את המשפט שמתאר את המצב.',
      sitHe: 'מתשע בבוקר המנהלת עוברת על בקשות החופשה ומאשרת אותן אחת אחת. עכשיו אחת-עשרה, והיא עדיין באמצע.',
      hint: 'מי עושה את הפעולה — המנהלת או הבקשות? והאם זה עדיין נמשך?',
      explain:
        'המנהלת עושה את הפעולה, והיא עדיין נמשכת: `The manager has been approving requests since nine`. `been approved` היה אומר שמשהו קיבל את הפעולה.',
      deep: 'שלושה מבנים עם `has been` / `have been`, ושלוש משמעויות: `has been approving` — היא מאשרת לאורך זמן (פעיל, מתמשך). `have been approved` — הבקשות אושרו (סביל). `has been approved requests` — ערבוב שאינו תקין: בסביל הנושא הוא מה שאושר, ואחרי `has been approved` לא בא מושא.',
      multi: false,
      options: [
        {
          id: 'a',
          en: 'The manager has been approving requests since nine.',
          v: 'fits',
          why: 'המנהלת עושה את הפעולה, והיא נמשכת מתשע עד עכשיו: `has been` + ing.',
        },
        {
          id: 'b',
          en: 'The manager has been approved requests since nine.',
          v: 'ungrammatical',
          why: '`has been approved` הוא סביל — הנושא מקבל את הפעולה. המנהלת עושה את הפעולה, ואחרי `has been approved` לא בא מושא כמו `requests`.',
          err: 'passive_for_active',
        },
        {
          id: 'c',
          en: 'All the requests have been approved.',
          v: 'other_meaning',
          why: 'משפט תקין, אבל הוא אומר שכל הבקשות כבר אושרו — והיא עדיין באמצע.',
          err: 'passive_result_for_ongoing',
        },
        {
          id: 'd',
          en: 'The requests have been approving since nine.',
          v: 'other_meaning',
          why: 'המבנה אומר שהבקשות הן שמאשרות משהו. בקשות מקבלות את הפעולה — הן לא עושות אותה.',
          err: 'ing_for_passive',
        },
      ],
    },
    {
      id: 'S12-07',
      v: 1,
      skill: 'S12',
      unit: 'S12',
      sub: 'passive_agent',
      type: 'assemble',
      role: 'practice',
      stage: 2,
      ctx: 'work.municipality',
      fam: 'S12.permit-issued',
      goal: 'לספר שההיתר הונפק',
      instr: 'בנה משפט אחד באנגלית. לא חייבים להשתמש בכל המילים.',
      sitHe: 'הגשת לעירייה בקשה להיתר לסגירת מרפסת. היום הודיעו לך שההיתר מוכן. ספר לשכן שגם הוא מחכה להיתר.',
      hint: 'ההיתר קיבל את הפעולה. `by` + מי שעשה — רק אם רוצים להוסיף.',
      explain: 'ההיתר קיבל את הפעולה: `The permit has been issued`. אפשר להוסיף `by the municipality`, אבל זה לא חובה.',
      deep: 'כשכולם יודעים מי מנפיק היתרים, `by the municipality` לא מוסיף הרבה — ולכן בדרך כלל משמיטים אותו. שתי הגרסאות נכונות. אם רוצים לשים במרכז את מי שעשה, אפשר גם משפט פעיל: `The municipality has issued the permit`.',
      tokens: [
        { id: 't1', t: 'the permit' },
        { id: 't2', t: 'has' },
        { id: 't3', t: 'been' },
        { id: 't4', t: 'issued' },
        { id: 't5', t: 'by the municipality' },
        {
          id: 't6',
          t: 'issuing',
          why: '`been issuing` מתאר מישהו שמנפיק משהו לאורך זמן (פעיל, מתמשך). ההיתר קיבל את הפעולה: `has been issued`.',
          err: 'ing_for_passive',
          as: 'meaning_mismatch',
        },
        { id: 't7', t: 'have', why: '`the permit` ביחיד, ולכן `has`, לא `have`.', err: 'have_agreement' },
      ],
      accept: [
        { a: 'The permit has been issued', o: 'correct_target' },
        { a: 'The permit has been issued by the municipality', o: 'correct_target' },
      ],
      rules: [
        {
          has: ['issued'],
          lacks: ['been'],
          as: 'form_error',
          err: 'passive_missing_been',
          fb: 'בלי `been` המשפט לא אומר שההיתר קיבל את הפעולה. בסביל: `The permit has been issued`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S12-08',
      v: 1,
      skill: 'S12',
      unit: 'S12',
      sub: 'passive_affirmative',
      type: 'correct',
      role: 'practice',
      stage: 2,
      ctx: 'work.report',
      fam: 'S12.report-reviewed',
      goal: 'לומר שהדוח נבדק על ידי שני מנהלים',
      instr: 'אם יש טעות — גע במילה או ברווח ובחר תיקון. אם המשפט תקין, בחר "אין צורך בתיקון".',
      sitHe: 'שני מנהלים קראו את הדוח ואישרו את התוכן שלו. עכשיו הוא מוכן להפצה.',
      hint: 'מי עשה את הבדיקה, ומה קיבל אותה? איזה מבנה מתאים כשהנושא הוא `the report`?',
      explain:
        'הדוח קיבל את הפעולה, ולכן סביל: `The report has been reviewed by two managers`. בלי `been` זה נשמע כאילו הדוח בדק משהו.',
      deep: '`has reviewed` הוא פעיל: הנושא עשה את הבדיקה (`Two managers have reviewed the report`). כשהנושא הוא הדוח, צריך את החוליה `been`: `has been reviewed`. כאן `by two managers` מוסיף מידע, ולכן טבעי להשאיר אותו.',
      source: [
        { id: 's1', t: 'the report' },
        { id: 's2', t: 'has' },
        { id: 's3', t: 'reviewed' },
        { id: 's4', t: 'by two managers' },
      ],
      tokens: [
        { id: 't1', t: 'been' },
        { id: 't2', t: 'being', why: '`being` לא בא אחרי `has`. ב-present perfect: `has been` + V3.', err: 'being_for_been' },
        { id: 't3', t: 'have', why: '`the report` ביחיד, ולכן `has`, לא `have`.', err: 'have_agreement' },
      ],
      accept: [
        { a: 'The report has been reviewed by two managers', o: 'correct_target' },
        {
          a: 'The report has been reviewed',
          o: 'valid_alternative',
          note: 'גם נכון, בלי `by`. כאן `by two managers` מוסיף מידע, ולכן כדאי להשאיר אותו.',
        },
      ],
      wrong: [
        {
          a: 'The report has reviewed by two managers',
          as: 'form_error',
          err: 'passive_missing_been',
          fb: 'בלי `been`, `has reviewed` הוא פעיל — כאילו הדוח בדק משהו. הדוח קיבל את הפעולה: `The report has been reviewed by two managers`.',
        },
      ],
      rules: [
        {
          has: ['has reviewed'],
          as: 'form_error',
          err: 'passive_missing_been',
          fb: 'בין `has` ל-`reviewed` חסר `been`: `has been reviewed`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S12-09',
      v: 1,
      skill: 'S12',
      unit: 'S12',
      sub: 'active_continuous',
      type: 'correct',
      role: 'practice',
      stage: 3,
      ctx: 'work.project',
      fam: 'S12.dan-reviewing',
      goal: 'לתאר עמית שעדיין באמצע בדיקת החוזים',
      instr: 'אם יש טעות — גע במילה או ברווח ובחר תיקון. אם המשפט תקין, בחר "אין צורך בתיקון".',
      sitHe: 'דן התחיל לעבור על החוזים בשמונה. עכשיו אחת-עשרה, והוא עדיין עובר עליהם.',
      hint: 'מי עושה את הפעולה — דן או החוזים? והאם זה עדיין נמשך?',
      explain:
        'המשפט נכון כמו שהוא: דן עושה את הפעולה והיא עדיין נמשכת, ולכן `has been reviewing`. אחרי `been` בא כאן ing — לא V3.',
      deep: 'כאן קל להתבלבל: `has been` מופיע גם בסביל (`The contracts have been reviewed` — החוזים נבדקו). אבל הנושא הוא דן, והוא זה שבודק, ולכן פעיל מתמשך: `Dan has been reviewing the contracts all morning`.',
      source: [
        { id: 's1', t: 'Dan' },
        { id: 's2', t: 'has' },
        { id: 's3', t: 'been' },
        { id: 's4', t: 'reviewing' },
        { id: 's5', t: 'the contracts' },
        { id: 's6', t: 'all morning' },
      ],
      tokens: [
        { id: 't1', t: 'reviewed' },
        { id: 't2', t: 'have', why: '`Dan` ביחיד, ולכן `has`, לא `have`.', err: 'have_agreement' },
      ],
      accept: [
        { a: 'Dan has been reviewing the contracts all morning', o: 'correct_target' },
        {
          a: 'Dan has reviewed the contracts all morning',
          o: 'valid_alternative',
          note: 'אפשרי, אבל `has reviewed the contracts` נשמע כאילו הבדיקה כבר הסתיימה. כשהוא עדיין באמצע, `has been reviewing` מדויק יותר — והמשפט המקורי היה נכון.',
        },
      ],
      rules: [
        {
          has: ['been reviewed'],
          as: 'form_error',
          err: 'passive_for_active',
          fb: '`has been reviewed` הוא סביל — כאילו דן הוא מי שנבדק. דן עושה את הפעולה והיא עדיין נמשכת: `has been reviewing`. המשפט המקורי היה נכון.',
        },
        {
          has: ['has reviewing'],
          as: 'form_error',
          err: 'missing_been',
          fb: 'בין `has` ל-`reviewing` חסר `been`. המשפט המקורי היה נכון: `Dan has been reviewing the contracts all morning`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S12-10',
      v: 2,
      skill: 'S12',
      unit: 'S12',
      sub: 'passive_negative',
      type: 'assemble',
      role: 'practice',
      stage: 2,
      ctx: 'work.email',
      fam: 'S12.reminders-not-sent',
      goal: 'לומר שמיילי התזכורת עוד לא נשלחו',
      instr: 'קרא את הסיטואציה ובנה משפט אחד באנגלית.',
      sitEn: "Your manager asks about the reminder emails for tomorrow's training. Nobody has sent them yet. Answer her.",
      trHe: 'המנהלת שואלת על מיילי התזכורת להדרכה של מחר. אף אחד עוד לא שלח אותם. ענה לה.',
      hint: 'המיילים הם מה שלא קיבל את הפעולה. בשלילה — איפה נכנס `not` בשרשרת?',
      explain:
        'בשלילה `not` בא אחרי `have`: `The reminder emails have not been sent yet`. המיילים הם מה שנשלח (או לא נשלח), ולכן `been` + V3.',
      deep: 'בשלילה הסדר הוא `have` ← `not` ← `been` ← V3. בדיבור מקצרים: `haven\'t been sent`. `yet` בא בסוף, או — בסגנון רשמי יותר — בין `not` ל-`been`: `have not yet been sent`.',
      tokens: [
        { id: 't1', t: 'the reminder emails' },
        { id: 't2', t: 'have' },
        { id: 't3', t: 'not' },
        { id: 't4', t: 'been' },
        { id: 't5', t: 'sent' },
        { id: 't6', t: 'yet' },
        { id: 't7', t: 'has', why: '`the reminder emails` ברבים, ולכן `have`, לא `has`.', err: 'have_agreement' },
        {
          id: 't8',
          t: 'sending',
          why: '`been sending` אומר שמישהו שולח (פעיל, מתמשך). המיילים הם מה שנשלח: `been sent`.',
          err: 'ing_for_passive',
          as: 'meaning_mismatch',
        },
        {
          id: 't9',
          t: 'already',
          why: '`already` אומר שזה כבר קרה — אבל אף אחד עוד לא שלח אותם. בשלילה: `not … yet`.',
          err: 'already_for_yet',
          as: 'meaning_mismatch',
        },
      ],
      accept: [
        { a: 'The reminder emails have not been sent yet', o: 'correct_target' },
        { a: 'The reminder emails have not yet been sent', o: 'valid_alternative', note: 'גם נכון, בסגנון רשמי יותר.' },
        { a: 'The reminder emails have not been sent', o: 'valid_alternative', note: 'גם נכון, בלי `yet`. `yet` מוסיף "עדיין / עד עכשיו".' },
      ],
      rules: [
        {
          has: ['sent'],
          lacks: ['been'],
          as: 'form_error',
          err: 'passive_missing_been',
          fb: 'בלי `been` המשפט אומר שהמיילים לא שלחו משהו. בסביל: `have not been sent`.',
        },
        {
          has: ['not have'],
          as: 'form_error',
          err: 'word_order',
          fb: '`not` בא אחרי `have`: `The reminder emails have not been sent yet`.',
        },
        {
          has: ['been not'],
          as: 'form_error',
          err: 'word_order',
          fb: '`not` בא מיד אחרי `have`, לפני `been`: `have not been sent`.',
        },
        {
          has: ['been sent'],
          lacks: ['not', 'has'],
          as: 'meaning_mismatch',
          err: 'affirmative_for_negative',
          fb: 'המשפט אומר שהמיילים כבר נשלחו — אבל אף אחד עוד לא שלח אותם. בשלילה: `The reminder emails have not been sent yet`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S12-11',
      v: 1,
      skill: 'S12',
      unit: 'S12',
      sub: 'contrast_past',
      type: 'assemble',
      role: 'practice',
      stage: 3,
      ctx: 'work.meeting',
      fam: 'S12.change-yesterday',
      goal: 'לומר מתי השינוי אושר',
      instr: 'בנה משפט אחד באנגלית. לא חייבים להשתמש בכל המילים.',
      sitHe: 'יום רביעי. בישיבה של אתמול אישרו את השינוי בנוהל. עמית שואל מתי זה אושר.',
      target: 'לענות מתי — עם `yesterday`',
      hint: 'יש כאן זמן שהסתיים. מה זה עושה ל-`has been`?',
      explain:
        'עם `yesterday` — זמן שהסתיים — גם הסביל בעבר פשוט: `The change was approved yesterday`. `has been approved` מתאים רק בלי זמן מוגמר.',
      deep: 'אותו כלל כמו ב-`I sent the report yesterday`: present perfect לא הולך עם זמן שהסתיים — גם לא בסביל. `The change has been approved` (בלי זמן) מתאר את המצב עכשיו; `The change was approved yesterday` אומר מתי. הסביל בעבר פשוט: `was / were` + V3.',
      tokens: [
        { id: 't1', t: 'the change' },
        { id: 't2', t: 'was' },
        { id: 't3', t: 'approved' },
        { id: 't4', t: 'yesterday' },
        { id: 't5', t: 'has' },
        { id: 't6', t: 'been' },
        { id: 't7', t: 'were', why: '`the change` ביחיד, ולכן `was`, לא `were`.', err: 'be_agreement' },
      ],
      accept: [
        { a: 'The change was approved yesterday', o: 'correct_target' },
        { a: 'Yesterday the change was approved', o: 'valid_alternative', note: 'גם נכון: `yesterday` בתחילת המשפט.' },
        {
          a: 'The change has been approved',
          o: 'target_not_used',
          note: 'תקין — המצב עכשיו, בלי זמן. אבל העמית שאל מתי, ועם `yesterday` צריך עבר פשוט: `The change was approved yesterday`.',
        },
        { a: 'The change was approved', o: 'target_not_used', note: 'תקין, אבל חסר מתי: `yesterday`.' },
      ],
      wrong: [
        {
          a: 'The change has been approved yesterday',
          as: 'form_error',
          err: 'perfect_with_finished_time',
          fb: '`yesterday` הוא זמן שהסתיים, ולכן גם בסביל עבר פשוט: `The change was approved yesterday` — בדיוק כמו `I sent the report yesterday`.',
        },
      ],
      rules: [
        {
          has: ['has', 'yesterday'],
          as: 'form_error',
          err: 'perfect_with_finished_time',
          fb: 'עם `yesterday` אין `has`. הסביל בעבר פשוט: `The change was approved yesterday`.',
        },
        {
          has: ['was been'],
          as: 'form_error',
          err: 'was_been',
          fb: '`was` ו-`been` לא באים כאן יחד. הסביל בעבר פשוט: `was approved`.',
        },
        {
          has: ['approved'],
          lacks: ['was', 'been'],
          as: 'form_error',
          err: 'passive_missing_be',
          fb: 'בלי `was` (או `been`) המשפט אומר שהשינוי אישר משהו. השינוי קיבל את הפעולה: `The change was approved yesterday`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S12-D1',
      v: 1,
      skill: 'S12',
      unit: 'S12',
      sub: 'dialogue',
      type: 'dialogue',
      role: 'practice',
      stage: 2,
      ctx: 'work.software',
      fam: 'S12.dialogue-new-version',
      goal: 'לעדכן את המנהלת: מה כבר נבדק, ומי עדיין עובד',
      instr: 'ענה לנועה בכל תור.',
      partnerName: 'Noa',
      setupHe: 'נועה, מנהלת הצוות, שואלת מה המצב עם הגרסה החדשה של אפליקציית הזימונים.',
      hint: 'בתור הראשון — מה קיבל את הפעולה (סביל). בתור השני — מי עושה פעולה שעדיין נמשכת.',
      explain: 'הגרסה קיבלה את הפעולה: `It has been tested`. רון עושה את הפעולה, והיא נמשכת: `He has been fixing bugs all morning`.',
      turns: [
        {
          partner: { en: 'Is the new version of the app ready?', he: 'הגרסה החדשה של האפליקציה מוכנה?' },
          sub: 'passive_affirmative',
          instr: 'ענה שכן — היא כבר נבדקה (לא חשוב מי בדק).',
          hint: 'הגרסה קיבלה את הפעולה: `has` ← `been` ← V3.',
          explain: 'הגרסה לא בודקת — בודקים אותה: `Yes, it has been tested`.',
          build: {
            tokens: [
              { id: 't1', t: 'yes' },
              { id: 't2', t: 'it' },
              { id: 't3', t: 'has' },
              { id: 't4', t: 'already' },
              { id: 't5', t: 'been' },
              { id: 't6', t: 'tested' },
              {
                id: 't7',
                t: 'testing',
                why: '`been testing` אומר שהגרסה עצמה בודקת משהו (פעיל, מתמשך). הגרסה היא מה שנבדק: `has been tested`.',
                err: 'ing_for_passive',
                as: 'meaning_mismatch',
              },
              { id: 't8', t: 'have', why: '`it` ביחיד, ולכן `has`, לא `have`.', err: 'have_agreement' },
            ],
            accept: [
              { a: 'Yes, it has been tested', o: 'correct_target' },
              { a: 'Yes, it has already been tested', o: 'correct_target' },
              { a: 'It has been tested', o: 'valid_alternative', note: 'גם נכון, גם בלי `yes`.' },
              { a: 'It has already been tested', o: 'valid_alternative', note: 'גם נכון, גם בלי `yes`.' },
            ],
            rules: [
              {
                has: ['tested'],
                lacks: ['been'],
                as: 'form_error',
                err: 'passive_missing_been',
                fb: 'בלי `been` המשפט אומר שהגרסה בדקה משהו. בסביל: `it has been tested`.',
              },
            ],
            end: '.',
          },
        },
        {
          partner: { en: "Great. And where's Ron? I haven't seen him today.", he: 'מצוין. ואיפה רון? לא ראיתי אותו היום.' },
          sub: 'active_continuous',
          instr: 'ספר לה שרון מתקן באגים כל הבוקר — הוא עדיין באמצע.',
          target: 'פעולה שנמשכת עד עכשיו: `has been` + V-ing',
          hint: 'עכשיו הנושא הוא רון, והוא זה שעושה את הפעולה — כבר כל הבוקר.',
          explain: 'רון עושה את הפעולה, והיא נמשכת עד עכשיו: `He has been fixing bugs all morning`. אחרי `been` בא כאן ing.',
          build: {
            tokens: [
              { id: 't1', t: 'he' },
              { id: 't2', t: 'has' },
              { id: 't3', t: 'been' },
              { id: 't4', t: 'fixing' },
              { id: 't5', t: 'bugs' },
              { id: 't6', t: 'all morning' },
              { id: 't7', t: 'fixed' },
              { id: 't8', t: 'have', why: 'עם `he` משתמשים ב-`has`, לא ב-`have`.', err: 'have_agreement' },
            ],
            accept: [
              { a: 'He has been fixing bugs all morning', o: 'correct_target' },
              {
                a: 'He has fixed bugs all morning',
                o: 'target_not_used',
                note: 'תקין — מתאר באגים שכבר תוקנו במהלך הבוקר. כדי להדגיש שהוא עדיין באמצע: `has been fixing`.',
              },
            ],
            rules: [
              {
                has: ['been fixed'],
                as: 'form_error',
                err: 'passive_for_active',
                fb: '`has been fixed` הוא סביל — כאילו רון תוקן. רון עושה את הפעולה: `He has been fixing bugs all morning`.',
              },
              {
                has: ['has fixing'],
                as: 'form_error',
                err: 'missing_been',
                fb: 'בין `has` ל-`fixing` חסר `been`: `has been fixing`.',
              },
            ],
            end: '.',
          },
        },
      ],
      closing: {
        en: 'Good. Please tell him the release has been moved to Thursday.',
        he: 'טוב. תגיד לו בבקשה שההשקה הועברה ליום חמישי.',
      },
    },
    {
      id: 'S12-C1',
      v: 1,
      skill: 'S12',
      unit: 'S12',
      sub: 'passive_affirmative',
      type: 'assemble',
      role: 'check',
      stage: 2,
      ctx: 'daily.travel',
      fam: 'S12.booking-confirmed',
      goal: 'לספר שההזמנה במלון אושרה',
      instr: 'בנה משפט אחד באנגלית. לא חייבים להשתמש בכל המילים.',
      sitHe: 'הזמנתם חדר במלון לטיול. עכשיו הגיע מייל מהמלון: ההזמנה אושרה. ספר לחבר שנוסע איתך.',
      hint: 'ההזמנה קיבלה את הפעולה — היא הנושא.',
      explain: 'ההזמנה קיבלה את הפעולה: `Our hotel booking has been confirmed`. `just` מוסיף שזה קרה ממש עכשיו.',
      tokens: [
        { id: 't1', t: 'our hotel booking' },
        { id: 't2', t: 'has' },
        { id: 't3', t: 'just' },
        { id: 't4', t: 'been' },
        { id: 't5', t: 'confirmed' },
        {
          id: 't6',
          t: 'confirming',
          why: '`been confirming` אומר שההזמנה עצמה מאשרת משהו (פעיל, מתמשך). ההזמנה היא מה שאושר: `has been confirmed`.',
          err: 'ing_for_passive',
          as: 'meaning_mismatch',
        },
        { id: 't7', t: 'have', why: '`our hotel booking` ביחיד, ולכן `has`, לא `have`.', err: 'have_agreement' },
        { id: 't8', t: 'being', why: '`being` לא בא אחרי `has`. ב-present perfect: `has been` + V3.', err: 'being_for_been' },
      ],
      accept: [
        { a: 'Our hotel booking has just been confirmed', o: 'correct_target' },
        { a: 'Our hotel booking has been confirmed', o: 'correct_target' },
      ],
      rules: [
        {
          has: ['confirmed'],
          lacks: ['been'],
          as: 'form_error',
          err: 'passive_missing_been',
          fb: 'בלי `been` המשפט אומר שההזמנה אישרה משהו. בסביל: `has been confirmed`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S12-C2',
      v: 1,
      skill: 'S12',
      unit: 'S12',
      sub: 'contrast',
      type: 'assemble',
      role: 'check',
      stage: 3,
      ctx: 'daily.home',
      fam: 'S12.elevator-fixing',
      goal: 'להסביר לשכן למה המעלית עדיין לא עובדת',
      instr: 'קרא את הסיטואציה ובנה משפט אחד באנגלית. לא חייבים להשתמש בכל המילים.',
      sitEn:
        "A technician started working on your building's elevator at eight. It's eleven now, and he is still working on it. A neighbor asks why the elevator isn't working yet.",
      trHe: 'טכנאי התחיל לעבוד על המעלית בבניין שלכם בשמונה. עכשיו אחת-עשרה, והוא עדיין עובד עליה. שכן שואל למה המעלית עוד לא עובדת.',
      hint: 'מי עושה את הפעולה, והאם היא כבר הסתיימה?',
      explain:
        'הטכנאי עושה את הפעולה, והיא עדיין נמשכת: `The technician has been fixing the elevator since eight`. `has been fixed` היה אומר שהמעלית כבר תוקנה.',
      tokens: [
        { id: 't1', t: 'the technician' },
        { id: 't2', t: 'has' },
        { id: 't3', t: 'been' },
        { id: 't4', t: 'fixing' },
        { id: 't5', t: 'the elevator' },
        { id: 't6', t: 'since eight' },
        {
          id: 't7',
          t: 'fixed',
          why: '`fixed` אומר שהתיקון הסתיים (או, אחרי `been`, שמשהו תוקן — סביל). הטכנאי עדיין באמצע: `has been fixing`.',
          err: 'v3_for_ongoing',
          as: 'meaning_mismatch',
        },
        { id: 't8', t: 'have', why: '`the technician` ו-`the elevator` ביחיד, ולכן `has`, לא `have`.', err: 'have_agreement' },
      ],
      accept: [{ a: 'The technician has been fixing the elevator since eight', o: 'correct_target' }],
      rules: [
        {
          has: ['elevator has been fixed'],
          as: 'meaning_mismatch',
          err: 'passive_result_for_ongoing',
          fb: 'המשפט תקין, אבל הוא אומר שהמעלית כבר תוקנה — והיא עדיין לא עובדת. הטכנאי עושה את הפעולה והוא עדיין באמצע: `The technician has been fixing the elevator since eight`.',
        },
        {
          has: ['technician has been fixed'],
          as: 'form_error',
          err: 'passive_for_active',
          fb: '`has been fixed` הוא סביל — כאילו הטכנאי תוקן. הטכנאי עושה את הפעולה: `has been fixing`.',
        },
        {
          has: ['elevator has been fixing'],
          as: 'meaning_mismatch',
          err: 'ing_for_passive',
          fb: 'המבנה אומר שהמעלית מתקנת משהו. המעלית מקבלת את הפעולה, והטכנאי עושה אותה: `The technician has been fixing the elevator since eight`.',
        },
        {
          has: ['has fixed'],
          as: 'meaning_mismatch',
          err: 'v3_for_ongoing',
          fb: 'המשפט אומר שהתיקון כבר הסתיים — אבל הטכנאי עדיין באמצע: `has been fixing`.',
        },
        {
          has: ['has fixing'],
          as: 'form_error',
          err: 'missing_been',
          fb: 'בין `has` ל-`fixing` חסר `been`: `has been fixing`.',
        },
      ],
      end: '.',
    },
    {
      id: 'S12-C3',
      v: 1,
      skill: 'S12',
      unit: 'S12',
      sub: 'passive_agent',
      type: 'discriminate',
      role: 'check',
      stage: 3,
      ctx: 'work.clinic',
      fam: 'S12.opening-hours',
      goal: 'לנסח הודעה על שעות פתיחה שאושרו',
      instr: 'בחר את כל המשפטים שמתאימים להודעה.',
      sitHe: 'הנהלת המרפאה אישרה את שעות הפתיחה החדשות. אתה כותב על זה הודעה קצרה ללוח המודעות של הצוות.',
      hint: 'מה קיבל את הפעולה? ו-`by` — חובה או רשות?',
      explain:
        'השעות קיבלו את הפעולה, ולכן `have been approved`. `by the management` אפשרי אבל לא חובה — שני המשפטים מתאימים.',
      multi: true,
      options: [
        {
          id: 'a',
          en: 'The new opening hours have been approved.',
          v: 'fits',
          why: 'סביל תקין: השעות קיבלו את הפעולה, ולא חייבים לומר מי אישר.',
        },
        {
          id: 'b',
          en: 'The new opening hours have been approved by the management.',
          v: 'fits',
          why: '`by the management` מוסיף מי אישר. זה לא חובה, אבל נכון.',
        },
        {
          id: 'c',
          en: 'The new opening hours have approved.',
          v: 'ungrammatical',
          why: 'חסר `been`. `have approved` בלי `been` הוא פעיל — מתאים כשהנושא הוא מי שאישר (`The clinic manager has approved the new hours`). כאן השעות קיבלו את הפעולה: `have been approved`.',
          err: 'passive_missing_been',
        },
        {
          id: 'd',
          en: 'The new opening hours has been approved.',
          v: 'ungrammatical',
          why: '`hours` ברבים, ולכן `have been approved`, לא `has`.',
          err: 'have_agreement',
        },
      ],
    },
  ],
};
