/** Hebrew names for error types, shown on the progress screen. Unknown types fall back to a generic label. */
const ERROR_LABELS: Record<string, string> = {
  missing_be: 'השמטת am / is / are',
  be_agreement: 'am / is / are לא מתאים לנושא',
  be_base: 'am / is / are + פועל בלי ing',
  missing_been: 'השמטת been',
  been_v3: 'been + V3 במקום been + ing',
  being_for_been: 'being במקום been',
  present_for_duration: 'הווה במקום have been למשך עד עכשיו',
  past_for_duration: 'עבר פשוט במקום משך עד עכשיו',
  v3_for_ongoing: 'צורה שמסמנת סיום לפעולה שעוד נמשכת',
  have_agreement: 'have / has לא מתאים לנושא',
  have_without_been: 'have בלי been לפני ing',
  have_base: 'have + פועל בסיס במקום V3',
  double_aux: 'שני פעלי עזר יחד',
  since_period: 'since לפני פרק זמן',
  for_point: 'for לפני נקודת זמן',
  perfect_with_finished_time: 'have + זמן עבר מוגמר',
  base_for_past: 'צורת בסיס במקום עבר',
  missing_time: 'חסר ציון זמן',
  did_v2: 'did + צורת עבר',
  do_with_perfect: 'do במקום have',
  no_inversion: 'סדר מילים בשאלה ישירה',
  inversion_in_indirect: 'היפוך בתוך שאלה עקיפה',
  do_in_indirect: 'do / does בתוך שאלה עקיפה',
  agreement_s: 'חסר s בפועל',
  not_transformed: 'המשפט לא הומר',
  simple_for_now: 'הווה פשוט למה שקורה עכשיו',
  wrong_aux: 'פועל עזר לא מתאים',
  word_order: 'סדר מילים',
  modal_to: 'to מיותר אחרי מודאל',
  modal_v2: 'מודאל + צורת עבר',
  modal_s: 'מודאל + s',
  missed_valid_option: 'לא זוהתה אפשרות תקינה',
  missing_duration: 'חסר כמה זמן',
  perfect_for_finished: 'have + זמן עבר מוגמר',
  did_for_ongoing: 'did למשהו שעדיין נמשך',
  stative_continuous: 'פועל מצב עם ing',
  stative_progressive: 'פועל מצב עם ing',
  stative_ing: 'פועל מצב עם ing',
  from_for_since: 'from במקום for / since',
  aux_order: 'סדר פעלי העזר בשאלה',
  past_for_ongoing: 'עבר פשוט למשהו שעדיין נמשך',
  do_with_ing: 'do לפני פועל עם ing',
  since_clause_tense: 'זמן הפועל אחרי since',
  be_v3: 'am / is / are + V3',
  ago_with_perfect: 'ago עם have',
  yes_no_question: 'מבנה שאלת כן/לא',
  present_for_now: 'הווה במקום משהו שנמשך עד לפני רגע',
  no_how_long: 'חסר How long',
  missing_since: 'חסר since',
  missing_did: 'חסר did',
  for_ago: 'for במקום ago',
  duration_twice: 'משך הזמן פעמיים',
  duration_kept: 'משך הזמן לא הוסר',
  did_with_perfect: 'did עם have',
  did_ing: 'did + פועל עם ing',
  been_base: 'been + פועל בסיס',
  since_for_ago: 'since במקום ago',
  period_kept: 'פרק הזמן לא הוסר',
  past_event: 'אירוע בעבר',
  passive_for_active: 'סביל במקום פעיל',
  not_position: 'מיקום not',
  joined_for: 'joined + for',
  have_v2: 'have + צורת עבר (V2)',
  for_kept: 'for לא הוסר',
  for_for_ago: 'for במקום ago',
  do_v3: 'do / did + V3',
  base_form: 'צורת בסיס',
  base_for_v3: 'צורת בסיס במקום V3',
  base_after_have: 'have + צורת בסיס',
  missing_have: 'השמטת have / has',
  missing_do: 'חסר do / does / did',
  missing_modal: 'חסר פועל עזר מודאלי',
  missing_verb: 'חסר פועל',
  missing_main_verb: 'חסר הפועל העיקרי',
  missing_if: 'חסר if / whether',
  missing_get: 'חסר get',
  did_v3: 'did + V3',
  did_past: 'did + צורת עבר',
  did_used: 'did + used to',
  did_v_s: 'did + פועל עם s',
  does_v2: 'does + צורת עבר',
  does_v_s: 'does + פועל עם s',
  does_ing: 'does + פועל עם ing',
  does_for_past: 'does במקום did',
  do_does_agreement: 'do / does לא מתאים לנושא',
  do_with_be: 'do עם be',
  did_in_subject_q: 'did בשאלה על הנושא',
  base_in_subject_q: 'צורת בסיס בשאלה על הנושא',
  object_for_subject: 'שאלה על המושא במקום על הנושא',
  subject_for_object: 'שאלה על הנושא במקום על המושא',
  object_q_v2: 'שאלה על המושא + צורת עבר',
  modal_ing: 'מודאל + פועל עם ing',
  modal_past: 'מודאל + צורת עבר',
  modal_v_s: 'מודאל + פועל עם s',
  double_modal: 'שני מודאלים יחד',
  have_to_missing_to: 'have to בלי to',
  need_to_missing_to: 'need to בלי to',
  ought_missing_to: 'ought to בלי to',
  able_missing_to: 'able to בלי to',
  mustnt_for_no_need: "mustn't במקום don't have to",
  dont_have_to_for_prohibition: "don't have to במקום mustn't",
  used_to_ing: 'used to + פועל עם ing',
  be_used_to_base: 'be used to + צורת בסיס',
  get_used_to_base: 'get used to + צורת בסיס',
  used_to_for_accustomed: 'used to במקום be used to',
  would_state: 'would למצב (ולא לפעולה חוזרת)',
  use_to_missing_to: 'use to בלי to',
  used_missing_to: 'used בלי to',
  passive_missing_been: 'סביל בלי been',
  passive_missing_be: 'סביל בלי be',
  ing_for_passive: 'ing במקום סביל',
  ing_for_v3: 'ing במקום V3',
  agent_as_passive_subject: 'מבצע הפעולה כנושא של סביל',
  been_for_gone: 'been במקום gone',
  been_gone: 'been / gone',
  already_for_yet: 'already במקום yet',
  yet_affirmative: 'yet במשפט חיובי',
  ever_in_statement: 'ever במשפט חיובי',
  ever_position: 'מיקום ever',
  present_for_past: 'הווה במקום עבר',
  past_for_present: 'עבר במקום הווה',
  that_for_if: 'that במקום if / whether',
  not_indirect: 'שאלה ישירה במקום עקיפה',
  declarative_question: 'שאלה בלי היפוך',
  question_for_statement: 'שאלה במקום משפט',
  double_negative: 'שלילה כפולה',
  wrong_period: 'זמן לא מתאים',
  meaning: 'משמעות לא מתאימה',
  form: 'צורה לא תקינה',
};

/** The Hebrew name of an error type, or null when none was written for it. */
export function errorLabel(code: string): string | null {
  return ERROR_LABELS[code] ?? null;
}

export function registerErrorLabels(extra: Record<string, string>): void {
  Object.assign(ERROR_LABELS, extra);
}
