import type { Item } from './schema';

/**
 * Four short calibration tasks, woven into learning (feedback and an explanation follow each
 * attempt). They only adjust the starting priorities; they never produce a level score.
 */
export const CALIBRATION: Item[] = [
  {
    id: 'CAL-1',
    v: 1,
    skill: 'S01',
    unit: 'S01',
    sub: 'affirmative',
    type: 'assemble',
    role: 'calibration',
    stage: 2,
    ctx: 'work.meeting',
    fam: 'CAL.presenting',
    goal: 'לתאר מה קורה בפגישה ממש עכשיו',
    instr: 'בנה את המשפט באנגלית.',
    promptHe: 'היא מציגה את התוכנית עכשיו.',
    hint: 'פעולה שקורה ברגע זה: `is` + פועל עם ing.',
    explain: 'מה שקורה עכשיו נבנה מ-`am / is / are` + פועל עם ing: `She is presenting the plan now`.',
    deep: 'בעברית אין מילה שמקבילה ל-`is` במשפט הזה, ולכן קל להשמיט אותה. באנגלית המבנה המתמשך תמיד צריך את שני החלקים: `is` וגם `presenting`.',
    tokens: [
      { id: 't1', t: 'she' },
      { id: 't2', t: 'is' },
      { id: 't3', t: 'presenting' },
      { id: 't4', t: 'the plan' },
      { id: 't5', t: 'now' },
      { id: 't6', t: 'are', why: 'עם `she` משתמשים ב-`is`, לא ב-`are`.', err: 'be_agreement' },
      {
        id: 't7',
        t: 'presents',
        why: '`presents` מתאר הרגל או לוח זמנים קבוע. למה שקורה ממש עכשיו: `is presenting`.',
        err: 'simple_for_now',
        as: 'meaning_mismatch',
      },
      { id: 't8', t: 'has', why: '`has` לא מתאים כאן: לפעולה שקורה עכשיו צריך `is` + פועל עם ing.', err: 'wrong_aux' },
    ],
    accept: [
      { a: 'She is presenting the plan now', o: 'correct_target' },
      { a: 'She is now presenting the plan', o: 'valid_alternative', note: 'גם נכון: `now` יכול לבוא גם אחרי `is`.' },
      { a: 'Now she is presenting the plan', o: 'valid_alternative', note: 'גם נכון: `now` בתחילת המשפט.' },
    ],
    rules: [
      {
        has: ['she presenting'],
        lacks: ['is'],
        as: 'form_error',
        err: 'missing_be',
        fb: 'חסר `is`: לפני פועל עם ing צריך `am / is / are`. כאן: `She is presenting`.',
      },
    ],
    end: '.',
  },
  {
    id: 'CAL-2',
    v: 1,
    skill: 'S03',
    unit: 'S03',
    sub: 'affirmative',
    type: 'assemble',
    role: 'calibration',
    stage: 2,
    ctx: 'work.email',
    fam: 'CAL.waiting-answer',
    goal: 'לומר כמה זמן אתם כבר מחכים לתשובה',
    instr: 'בנה את המשפט באנגלית.',
    promptHe: 'אנחנו מחכים לתשובה כבר שבוע.',
    hint: 'התחלנו לחכות לפני שבוע ועדיין מחכים: `have` + `been` + פועל עם ing.',
    explain: 'מחכים כבר שבוע = התחלנו בעבר ועדיין מחכים: `We have been waiting for an answer for a week`.',
    deep: 'בעברית אומרים "אנחנו מחכים" בהווה גם כשמציינים משך. באנגלית, ברגע שמוסיפים כמה זמן זה נמשך עד עכשיו, עוברים ל-`have been waiting`. לפרק זמן (`a week`) משתמשים ב-`for`.',
    tokens: [
      { id: 't1', t: 'we' },
      { id: 't2', t: 'have' },
      { id: 't3', t: 'been' },
      { id: 't4', t: 'waiting' },
      { id: 't5', t: 'for an answer' },
      { id: 't6', t: 'for a week' },
      {
        id: 't7',
        t: 'are',
        why: '`are waiting` מתאר רק את מה שקורה עכשיו. כדי לומר כמה זמן זה נמשך עד עכשיו צריך `have been waiting`.',
        err: 'present_for_duration',
      },
      {
        id: 't8',
        t: 'since a week',
        why: '`since` בא לפני נקודת התחלה (`since Monday`). לפרק זמן כמו שבוע: `for a week`.',
        err: 'since_period',
      },
      { id: 't9', t: 'has', why: 'עם `we` משתמשים ב-`have`, לא ב-`has`.', err: 'have_agreement' },
    ],
    accept: [
      { a: 'We have been waiting for an answer for a week', o: 'correct_target' },
      { a: 'We have been waiting for a week for an answer', o: 'valid_alternative', note: 'גם הסדר הזה תקין.' },
    ],
    wrong: [
      {
        a: 'We are waiting for an answer for a week',
        as: 'meaning_mismatch',
        err: 'present_for_duration',
        fb: 'בעברית "אנחנו מחכים כבר שבוע" — בהווה. באנגלית `We are waiting … for a week` לא אומר "כבר שבוע". למשך עד עכשיו: `We have been waiting for an answer for a week`.',
      },
    ],
    rules: [
      {
        has: ['have waiting'],
        lacks: ['been'],
        as: 'form_error',
        err: 'missing_been',
        fb: 'בין `have` ל-`waiting` חסרה המילה `been`: `have been waiting`.',
      },
    ],
    end: '.',
  },
  {
    id: 'CAL-3',
    v: 2,
    skill: 'S06',
    unit: 'S06',
    sub: 'finished_time',
    type: 'correct',
    role: 'calibration',
    stage: 2,
    ctx: 'work.report',
    fam: 'CAL.finished-report',
    goal: 'לומר מתי סיימת את הדוח',
    instr: 'אם יש טעות — גע במילה או ברווח ובחר תיקון. אם המשפט תקין, בחר "אין צורך בתיקון".',
    hint: '`last night` הוא זמן שהסתיים.',
    explain: 'עם זמן עבר שהסתיים, כמו `last night`, משתמשים בעבר פשוט: `I finished the report last night`.',
    deep: 'present perfect (`have finished`) מחבר את העבר להווה בלי לציין מתי בדיוק. ברגע שמציינים זמן מוגמר (`yesterday`, `last night`, `in 2020`) — עבר פשוט, גם אם לתוצאה יש חשיבות עכשיו.',
    source: [
      { id: 's1', t: 'I' },
      {
        id: 's2',
        t: 'have',
        why: 'עם `last night` — זמן שהסתיים — לא משתמשים ב-`have`. עבר פשוט: `I finished`.',
        err: 'perfect_with_finished_time',
      },
      { id: 's3', t: 'finished' },
      { id: 's4', t: 'the report' },
      { id: 's5', t: 'last night' },
    ],
    tokens: [
      {
        id: 't1',
        t: 'finish',
        why: '`finish` היא צורת הבסיס. לעבר: `finished`.',
        err: 'base_for_past',
      },
      { id: 't2', t: 'was' },
      {
        id: 't3',
        t: 'has',
        why: 'עם `I` לא אומרים `has`, וממילא עם `last night` צריך עבר פשוט: `I finished`.',
        err: 'have_agreement',
      },
    ],
    accept: [
      { a: 'I finished the report last night', o: 'correct_target' },
      {
        a: 'The report was finished last night',
        o: 'valid_alternative',
        note: 'גם נכון — משפט סביל בעבר פשוט ("הדוח הושלם אתמול בלילה"). כשאתה זה שסיים, טבעי יותר: `I finished the report last night`.',
      },
    ],
    wrong: [
      {
        a: 'I have finished the report last night',
        as: 'form_error',
        err: 'perfect_with_finished_time',
        fb: '`last night` הוא זמן שהסתיים, לכן עבר פשוט: `I finished the report last night`. `have finished` מתאים רק בלי ציון זמן מוגמר.',
      },
    ],
    rules: [
      {
        has: ['was finished the report'],
        as: 'form_error',
        err: 'wrong_aux',
        fb: '`was` + V3 הוא סביל ("הדוח הושלם"), ואחריו לא בא מושא. כדי לספר מה עשית: `I finished the report last night`.',
      },
    ],
    end: '.',
  },
  {
    id: 'CAL-4',
    v: 2,
    skill: 'S08',
    unit: 'S08',
    sub: 'wh_indirect',
    type: 'transform',
    role: 'calibration',
    stage: 2,
    ctx: 'work.schedule',
    fam: 'CAL.take-effect',
    goal: 'לשאול בנימוס מתי מתחיל לוח הזמנים החדש',
    instr: 'הפוך את השאלה הישירה לשאלה עקיפה שמתחילה ב-`Could you tell me`.',
    target: 'שאלה עקיפה שמתחילה ב-`Could you tell me`',
    fromLabel: 'שאלה ישירה',
    toLabel: 'שאלה עקיפה',
    hint: 'אחרי `Could you tell me when` הסדר הוא כמו במשפט רגיל, בלי `does`.',
    explain: 'בשאלה עקיפה החלק הפנימי בנוי כמו משפט רגיל: `when the new schedule takes effect`, בלי `does`.',
    deep: 'בשאלה ישירה `does` בא לפני הנושא: `When does it take effect?`. בתוך שאלה עקיפה אין היפוך ואין `does`, ולכן הפועל מקבל s כרגיל: `…when it takes effect`. גם `will take effect` תקין כשמדברים על העתיד.',
    source: [
      { id: 's1', t: 'when' },
      {
        id: 's2',
        t: 'does',
        why: 'בתוך שאלה עקיפה אין `does`: `Could you tell me when the new schedule takes effect?`',
        err: 'do_in_indirect',
      },
      { id: 's3', t: 'the new schedule' },
      { id: 's4', t: 'take' },
      { id: 's5', t: 'effect' },
    ],
    sourceEnd: '?',
    tokens: [
      { id: 't1', t: 'could you tell me' },
      { id: 't2', t: 'takes' },
      { id: 't3', t: 'will' },
    ],
    accept: [
      { a: 'Could you tell me when the new schedule takes effect', o: 'correct_target' },
      {
        a: 'Could you tell me when the new schedule will take effect',
        o: 'valid_alternative',
        note: 'גם נכון: `will take effect` מתאים כשמדברים על העתיד.',
      },
    ],
    wrong: [
      {
        a: 'When does the new schedule take effect',
        as: 'target_not_used',
        err: 'not_transformed',
        fb: 'זו שאלה ישירה תקינה, אבל התבקשת להפוך אותה לשאלה עקיפה שמתחילה ב-`Could you tell me`.',
      },
    ],
    rules: [
      {
        has: ['the new schedule does take'],
        as: 'meaning_mismatch',
        err: 'emphatic_do',
        fb: 'המשפט תקין דקדוקית, אבל `does take` בסדר רגיל הוא צורה של הדגשה, כמו בניגוד למשהו שנאמר קודם. בשאלה עקיפה רגילה אין צורך ב-`does`: `when the new schedule takes effect`.',
      },
      {
        has: ['when will the new schedule'],
        as: 'form_error',
        err: 'inversion_in_indirect',
        fb: 'בתוך שאלה עקיפה אין היפוך: `will` בא אחרי הנושא, כמו במשפט רגיל — `when the new schedule will take effect`.',
      },
      {
        order: ['could you tell me', 'does'],
        as: 'form_error',
        err: 'inversion_in_indirect',
        fb: 'בתוך שאלה עקיפה אין `does` והסדר הוא כמו במשפט רגיל: `when the new schedule takes effect`.',
      },
      {
        has: ['could you tell me', 'schedule take'],
        as: 'form_error',
        err: 'agreement_s',
        fb: 'בלי `does` הפועל מקבל s, כמו במשפט רגיל: `the new schedule takes effect`.',
      },
      {
        has: ['will takes'],
        as: 'form_error',
        err: 'will_s',
        fb: 'אחרי `will` בא פועל בסיס, בלי s: `when the new schedule will take effect`.',
      },
    ],
    end: '?',
  },
];
